<?php
namespace ETG\DynamicFilterSEOBridge\SEO;
use ETG\DynamicFilterSEOBridge\Config\Configuration;
final class ContentReadiness {
	private $config;public function __construct(Configuration $config){$this->config=$config;}
	public function evaluate(array $context):array{$profileContent=(array)($context['profile']['content']??array());$required=array_key_exists('required',$profileContent)?(bool)$profileContent['required']:(bool)$this->config->get('require_content_readiness',true);$requireMeta=array_key_exists('require_meta_description',$profileContent)?(bool)$profileContent['require_meta_description']:(bool)$this->config->get('require_meta_description',true);$depth=max(0,count((array)($context['filters']??array())));$minChars=array_key_exists('min_chars',$profileContent)?(int)$profileContent['min_chars']:(int)$this->config->get('min_content_chars',250);$depthChars=(array)($profileContent['min_chars_by_depth']??array());if($depth>0&&isset($depthChars[(string)$depth])){$minChars=max(0,(int)$depthChars[(string)$depth]);}$minSegments=0;$depthSegments=(array)($profileContent['min_unique_segments_by_depth']??array());if($depth>0&&isset($depthSegments[(string)$depth])){$minSegments=max(0,(int)$depthSegments[(string)$depth]);}
		$combo=(array)($context['combo']??array());$title=trim((string)($combo['title']??''));$meta=trim((string)($combo['meta_description']??''));$segments=array();foreach((array)($context['terms']??array()) as $term){if(!is_array($term)){continue;}foreach(array('short_description','description') as $field){$text=trim((string)($term[$field]??''));if(''===$text){continue;}$plainSegment=function_exists('wp_strip_all_tags')?wp_strip_all_tags($text):strip_tags($text);$plainSegment=preg_replace('/\s+/u',' ',trim((string)$plainSegment));if(is_string($plainSegment)&&''!==$plainSegment){$segments[]=$plainSegment;}}}$segments=array_values(array_unique($segments));if(!$segments&&!empty($combo['intro'])){$fallback=function_exists('wp_strip_all_tags')?wp_strip_all_tags((string)$combo['intro']):strip_tags((string)$combo['intro']);$fallback=preg_replace('/\s+/u',' ',trim((string)$fallback));if(is_string($fallback)&&''!==$fallback){$segments[]=$fallback;}}
		$plain=implode(' ',$segments);$chars=function_exists('mb_strlen')?mb_strlen($plain):strlen($plain);$reasons=array();if(''===$title){$reasons[]='missing_title';}if($requireMeta&&''===$meta){$reasons[]='missing_meta_description';}if($chars<$minChars){$reasons[]='insufficient_unique_copy';}if(count($segments)<$minSegments){$reasons[]='insufficient_unique_sections';}$baseReady=!$required||empty($reasons);$filteredReady=$baseReady;if(function_exists('apply_filters')){$filteredReady=(bool)apply_filters('etg_filter_seo_content_ready',$baseReady,$reasons,$context);}$ready=$baseReady&&$filteredReady;return array('contract'=>'etg.dfsb.content-readiness.v4','required'=>$required,'ready'=>$ready,'base_ready'=>$baseReady,'override_applied'=>$filteredReady!==$baseReady,'override_direction'=>$filteredReady!==$baseReady?($filteredReady?'attempted_promote_blocked':'veto'):'none','reasons'=>$reasons,'filter_depth'=>$depth,'content_chars'=>$chars,'unique_segments'=>count($segments),'minimum_chars'=>$minChars,'minimum_unique_segments'=>$minSegments,'require_meta_description'=>$requireMeta);}
}
