<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class MAD4B_SCP_BitFlows_Adapter extends MAD4B_SCP_Adapter_Base {
	public function id() { return 'bitflows'; }
	public function label() { return 'Bit Flows'; }
	public function is_available() { return class_exists( 'BitApps\\Pi\\Model\\Flow' ); }
	public function ability_names() { return array( 'read' => array( 'bitflows/status', 'bitflows/list-flows', 'bitflows/get-flow', 'bitflows/get-executions' ), 'content' => array(), 'admin' => array( 'bitflows/run-flow' ) ); }
	protected function detect_plugin_version() { if ( defined( 'BITPI_VERSION' ) ) return BITPI_VERSION; if ( defined( 'BIT_PI_VERSION' ) ) return BIT_PI_VERSION; return ''; }
	public function register_abilities() {
		$this->add_ability( 'bitflows/status', 'Get Bit Flows Status', 'status', array( 'MAD4B_SCP_Policy', 'can_read' ) );
		$this->add_ability( 'bitflows/list-flows', 'List Bit Flows', 'list_flows', array( 'MAD4B_SCP_Policy', 'can_read' ), $this->schema( array( 'limit' => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 50 ) ) ) );
		$flow_schema = $this->schema( array( 'flow_id' => array( 'type' => 'integer', 'minimum' => 1 ) ), array( 'flow_id' ) );
		$this->add_ability( 'bitflows/get-flow', 'Get Bit Flow', 'get_flow', array( 'MAD4B_SCP_Policy', 'can_read' ), $flow_schema );
		$this->add_ability( 'bitflows/get-executions', 'Get Bit Flow Executions', 'get_executions', array( 'MAD4B_SCP_Policy', 'can_read' ), $this->schema( array( 'flow_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'limit' => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 20 ) ), array( 'flow_id' ) ) );
		$this->add_ability( 'bitflows/run-flow', 'Run Bit Flow', 'run_flow', array( $this, 'can_run_flow' ), $this->schema( array( 'flow_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'trigger_data' => array( 'type' => 'object', 'default' => array() ), 'reason' => array( 'type' => 'string', 'minLength' => 3, 'maxLength' => 500 ) ), array( 'flow_id', 'reason' ) ), 'admin', false, false, false );
	}
	public function status() { $status = parent::status(); $status['contracts'] = array( 'flow_model' => class_exists( 'BitApps\\Pi\\Model\\Flow' ), 'flow_executor' => class_exists( 'BitApps\\Pi\\src\\Flow\\FlowExecutor' ), 'flow_history' => class_exists( 'BitApps\\Pi\\Model\\FlowHistory' ) ); return $status; }
	public function can_run_flow( $input = null ) { return current_user_can( 'manage_options' ) && (bool) apply_filters( 'mad4b_scp_bitflows_run_permission', true, $input, get_current_user_id() ); }
	public function list_flows( $input ) { if ( ! $this->is_available() ) return $this->unavailable_error(); $limit = isset( $input['limit'] ) ? max( 1, min( 100, absint( $input['limit'] ) ) ) : 50; $class = 'BitApps\\Pi\\Model\\Flow'; try { $flows = $class::select( array( 'id', 'title', 'run_count', 'is_active', 'trigger_type', 'listener_type' ) )->desc()->take( $limit )->get(); return array( 'flows' => $this->normalize( $flows ), 'count' => is_countable( $flows ) ? count( $flows ) : 0 ); } catch ( Throwable $e ) { return new WP_Error( 'mad4b_bitflows_list_failed', $e->getMessage() ); } }
	public function get_flow( $input ) { if ( ! $this->is_available() ) return $this->unavailable_error(); $class = 'BitApps\\Pi\\Model\\Flow'; try { $flow = $class::select( array( 'id', 'title', 'run_count', 'is_active', 'trigger_type', 'listener_type', 'is_hook_capture', 'settings', 'map' ) )->findOne( array( 'id' => absint( $input['flow_id'] ) ) ); if ( ! $flow ) return new WP_Error( 'mad4b_bitflows_flow_missing', 'Flow not found.' ); return array( 'flow' => $this->normalize( $flow ) ); } catch ( Throwable $e ) { return new WP_Error( 'mad4b_bitflows_get_failed', $e->getMessage() ); } }
	public function get_executions( $input ) { if ( ! class_exists( 'BitApps\\Pi\\Model\\FlowHistory' ) ) return new WP_Error( 'mad4b_bitflows_history_unavailable', 'Bit Flows history contract is unavailable.' ); $class = 'BitApps\\Pi\\Model\\FlowHistory'; $limit = isset( $input['limit'] ) ? max( 1, min( 100, absint( $input['limit'] ) ) ) : 20; try { $items = $class::where( 'flow_id', absint( $input['flow_id'] ) )->desc()->take( $limit )->select( array( 'id', 'flow_id', 'parent_history_id', 'status', 'created_at', 'updated_at' ) )->get(); return array( 'flow_id' => absint( $input['flow_id'] ), 'executions' => $this->normalize( $items ), 'count' => is_countable( $items ) ? count( $items ) : 0 ); } catch ( Throwable $e ) { return new WP_Error( 'mad4b_bitflows_history_failed', $e->getMessage() ); } }
	public function run_flow( $input ) { if ( ! $this->is_available() || ! class_exists( 'BitApps\\Pi\\src\\Flow\\FlowExecutor' ) ) return $this->unavailable_error(); $flow_class = 'BitApps\\Pi\\Model\\Flow'; $executor = 'BitApps\\Pi\\src\\Flow\\FlowExecutor'; $id = absint( $input['flow_id'] ); try { $flow = $flow_class::select( array( 'id', 'title', 'map', 'settings', 'listener_type', 'is_hook_capture', 'is_active' ) )->findOne( array( 'id' => $id ) ); if ( ! $flow ) return new WP_Error( 'mad4b_bitflows_flow_missing', 'Flow not found.' ); if ( 1 !== (int) $flow->is_active ) return new WP_Error( 'mad4b_bitflows_flow_inactive', 'Inactive flows cannot be run through the control plane.' ); $trigger_data = isset( $input['trigger_data'] ) && is_array( $input['trigger_data'] ) ? $input['trigger_data'] : array(); MAD4B_SCP_Audit::record( 'bitflows/run-flow', array( 'flow_id' => $id, 'reason' => sanitize_text_field( $input['reason'] ), 'trigger_keys' => array_keys( $trigger_data ) ), 'attempt' ); $result = $executor::execute( $flow, $trigger_data ); if ( false === $result ) return new WP_Error( 'mad4b_bitflows_execution_rejected', 'Bit Flows executor rejected the run.' ); MAD4B_SCP_Audit::record( 'bitflows/run-flow', array( 'flow_id' => $id, 'queued' => true ) ); return array( 'flow_id' => $id, 'queued' => true, 'executor_result' => (bool) $result ); } catch ( Throwable $e ) { return new WP_Error( 'mad4b_bitflows_execution_failed', $e->getMessage() ); } }
}
