<?php

if ( ! defined( 'ABSPATH' ) ) { exit; }

final class MAD4B_SCP_JetEngine_Adapter extends MAD4B_SCP_Adapter_Base {
	public function id() { return 'jetengine'; }
	public function label() { return 'JetEngine'; }
	public function is_available() { return function_exists( 'jet_engine' ) || class_exists( 'Jet_Engine' ); }
	public function ability_names() { return array( 'read' => array( 'jetengine/status', 'jetengine/get-post-meta', 'jetengine/list-post-meta', 'jetengine/get-cpt-definition' ), 'content' => array( 'jetengine/update-post-meta' ), 'admin' => array() ); }
	protected function detect_plugin_version() { return defined( 'JET_ENGINE_VERSION' ) ? JET_ENGINE_VERSION : ''; }
	public function register_abilities() {
		$this->add_ability( 'jetengine/status', 'Get JetEngine Status', 'status', array( 'MAD4B_SCP_Policy', 'can_read' ) );
		$this->add_ability( 'jetengine/get-post-meta', 'Get JetEngine Post Meta', 'get_post_meta_value', array( $this, 'can_read_post' ), $this->schema( array( 'post_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'field' => array( 'type' => 'string', 'minLength' => 1, 'maxLength' => 191 ) ), array( 'post_id', 'field' ) ) );
		$this->add_ability( 'jetengine/list-post-meta', 'List JetEngine Post Meta', 'list_post_meta', array( $this, 'can_read_post' ), $this->schema( array( 'post_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'prefix' => array( 'type' => 'string', 'maxLength' => 100, 'default' => '' ) ), array( 'post_id' ) ) );
		$this->add_ability( 'jetengine/get-cpt-definition', 'Get JetEngine CPT Definition', 'get_cpt_definition', array( 'MAD4B_SCP_Policy', 'can_read' ), $this->schema( array( 'post_type' => array( 'type' => 'string', 'minLength' => 1, 'maxLength' => 20 ) ), array( 'post_type' ) ) );
		$this->add_ability( 'jetengine/update-post-meta', 'Update JetEngine Post Meta', 'update_post_meta_value', array( $this, 'can_edit_post' ), $this->schema( array( 'post_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'field' => array( 'type' => 'string', 'minLength' => 1, 'maxLength' => 191 ), 'value' => $this->json_value_schema(), 'expected_sha256' => array( 'type' => 'string', 'minLength' => 64, 'maxLength' => 64 ), 'allow_create' => array( 'type' => 'boolean', 'default' => false ) ), array( 'post_id', 'field', 'value' ) ), 'content', false, false, true );
	}
	public function can_read_post( $input ) { $id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0; return $id > 0 && current_user_can( 'read_post', $id ); }
	public function can_edit_post( $input ) { $id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0; return $id > 0 && current_user_can( 'edit_post', $id ); }
	public function status() { $status = parent::status(); $status['contracts'] = array( 'jet_engine_function' => function_exists( 'jet_engine' ), 'jet_engine_class' => class_exists( 'Jet_Engine' ) ); return $status; }
	public function get_post_meta_value( $input ) { if ( ! $this->is_available() ) return $this->unavailable_error(); $field = sanitize_key( $input['field'] ); if ( '' === $field ) return new WP_Error( 'mad4b_jetengine_invalid_field', 'Invalid meta field.' ); $id = absint( $input['post_id'] ); $value = get_post_meta( $id, $field, true ); return array( 'post_id' => $id, 'field' => $field, 'value' => $value, 'sha256' => $this->hash_value( $value ), 'exists' => metadata_exists( 'post', $id, $field ) ); }
	public function list_post_meta( $input ) { if ( ! $this->is_available() ) return $this->unavailable_error(); $id = absint( $input['post_id'] ); $all = get_post_meta( $id ); $prefix = isset( $input['prefix'] ) ? (string) $input['prefix'] : ''; $items = array(); foreach ( $all as $key => $values ) { if ( 0 === strpos( $key, '_' ) ) continue; if ( '' !== $prefix && 0 !== strpos( $key, $prefix ) ) continue; $value = count( $values ) === 1 ? maybe_unserialize( $values[0] ) : array_map( 'maybe_unserialize', $values ); $items[] = array( 'field' => $key, 'value' => $value, 'sha256' => $this->hash_value( $value ) ); if ( count( $items ) >= 300 ) break; } return array( 'post_id' => $id, 'meta' => $items, 'count' => count( $items ) ); }
	public function get_cpt_definition( $input ) { if ( ! $this->is_available() ) return $this->unavailable_error(); $post_type = sanitize_key( $input['post_type'] ); $object = get_post_type_object( $post_type ); if ( ! $object ) return new WP_Error( 'mad4b_jetengine_cpt_missing', 'Post type is not registered.' ); return array( 'post_type' => $post_type, 'label' => $object->label, 'public' => (bool) $object->public, 'hierarchical' => (bool) $object->hierarchical, 'show_in_rest' => (bool) $object->show_in_rest, 'taxonomies' => get_object_taxonomies( $post_type ), 'supports' => get_all_post_type_supports( $post_type ) ); }
	public function update_post_meta_value( $input ) { if ( ! $this->is_available() ) return $this->unavailable_error(); $id = absint( $input['post_id'] ); $field = sanitize_key( $input['field'] ); if ( '' === $field ) return new WP_Error( 'mad4b_jetengine_invalid_field', 'Invalid meta field.' ); if ( 0 === strpos( $field, '_' ) && ! apply_filters( 'mad4b_scp_allow_protected_meta_write', false, 'jetengine', $field, $id ) ) return new WP_Error( 'mad4b_jetengine_protected_meta', 'Protected meta writes are denied by default.' ); $exists = metadata_exists( 'post', $id, $field ); $current = get_post_meta( $id, $field, true ); $hash = $this->hash_value( $current ); if ( $exists ) { $expected = isset( $input['expected_sha256'] ) ? strtolower( trim( $input['expected_sha256'] ) ) : ''; if ( '' === $expected || ! hash_equals( $hash, $expected ) ) return new WP_Error( 'mad4b_jetengine_stale_meta', 'Current meta SHA-256 is required.', array( 'current_sha256' => $hash ) ); } elseif ( empty( $input['allow_create'] ) ) return new WP_Error( 'mad4b_jetengine_create_denied', 'Set allow_create=true to create a new meta field.' ); $result = update_post_meta( $id, $field, $input['value'] ); if ( false === $result && $current !== $input['value'] ) return new WP_Error( 'mad4b_jetengine_update_failed', 'Unable to update meta.' ); $new = get_post_meta( $id, $field, true ); MAD4B_SCP_Audit::record( 'jetengine/update-post-meta', array( 'post_id' => $id, 'field' => $field, 'sha256' => $this->hash_value( $new ) ) ); return array( 'post_id' => $id, 'field' => $field, 'updated' => true, 'value' => $new, 'sha256' => $this->hash_value( $new ) ); }
}
