<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class MAD4B_SCP_JetSmartFilters_Adapter extends MAD4B_SCP_Adapter_Base {
	public function id() { return 'jetsmartfilters'; }
	public function label() { return 'JetSmartFilters'; }
	public function is_available() { return class_exists( 'Jet_Smart_Filters' ) || function_exists( 'jet_smart_filters' ) || null !== $this->filter_post_type(); }
	public function ability_names() { return array( 'read' => array( 'jetsmartfilters/status', 'jetsmartfilters/list-filters', 'jetsmartfilters/get-filter', 'jetsmartfilters/get-query-binding' ), 'content' => array(), 'admin' => array( 'jetsmartfilters/update-filter-meta' ) ); }
	protected function detect_plugin_version() { return defined( 'JET_SMART_FILTERS_VERSION' ) ? JET_SMART_FILTERS_VERSION : ''; }
	public function register_abilities() {
		$this->add_ability( 'jetsmartfilters/status', 'Get JetSmartFilters Status', 'status', array( 'MAD4B_SCP_Policy', 'can_read' ) );
		$this->add_ability( 'jetsmartfilters/list-filters', 'List JetSmartFilters Filters', 'list_filters', array( 'MAD4B_SCP_Policy', 'can_read' ), $this->schema( array( 'limit' => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 50 ) ) ) );
		$filter_schema = $this->schema( array( 'filter_id' => array( 'type' => 'integer', 'minimum' => 1 ) ), array( 'filter_id' ) );
		$this->add_ability( 'jetsmartfilters/get-filter', 'Get JetSmartFilters Filter', 'get_filter', array( $this, 'can_read_filter' ), $filter_schema );
		$this->add_ability( 'jetsmartfilters/get-query-binding', 'Get JetSmartFilters Query Binding', 'get_query_binding', array( $this, 'can_read_filter' ), $filter_schema );
		$this->add_ability( 'jetsmartfilters/update-filter-meta', 'Update JetSmartFilters Filter Meta', 'update_filter_meta', array( 'MAD4B_SCP_Policy', 'can_admin' ), $this->schema( array( 'filter_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'meta_key' => array( 'type' => 'string', 'minLength' => 1, 'maxLength' => 191 ), 'value' => array(), 'expected_sha256' => array( 'type' => 'string', 'minLength' => 64, 'maxLength' => 64 ) ), array( 'filter_id', 'meta_key', 'value', 'expected_sha256' ) ), 'admin', false, false, true );
	}
	public function status() { $status = parent::status(); $status['filter_post_type'] = $this->filter_post_type(); return $status; }
	public function can_read_filter( $input ) { $id = isset( $input['filter_id'] ) ? absint( $input['filter_id'] ) : 0; return $id > 0 && current_user_can( 'read_post', $id ); }
	public function list_filters( $input ) { $post_type = $this->filter_post_type(); if ( ! $post_type ) return $this->unavailable_error(); $limit = isset( $input['limit'] ) ? max( 1, min( 100, absint( $input['limit'] ) ) ) : 50; $posts = get_posts( array( 'post_type' => $post_type, 'post_status' => array( 'publish', 'draft', 'private' ), 'posts_per_page' => $limit, 'orderby' => 'ID', 'order' => 'DESC' ) ); $items = array(); foreach ( $posts as $post ) $items[] = array( 'id' => $post->ID, 'title' => $post->post_title, 'status' => $post->post_status, 'modified_gmt' => $post->post_modified_gmt ); return array( 'post_type' => $post_type, 'filters' => $items, 'count' => count( $items ) ); }
	public function get_filter( $input ) { $post_type = $this->filter_post_type(); $post = get_post( absint( $input['filter_id'] ) ); if ( ! $post_type || ! $post || $post->post_type !== $post_type ) return new WP_Error( 'mad4b_jetsmartfilters_filter_missing', 'Filter not found.' ); $meta = get_post_meta( $post->ID ); $items = array(); foreach ( $meta as $key => $values ) { if ( '_edit_lock' === $key || '_edit_last' === $key || 0 === strpos( $key, '_wp_' ) ) continue; $value = count( $values ) === 1 ? maybe_unserialize( $values[0] ) : array_map( 'maybe_unserialize', $values ); $items[ $key ] = array( 'value' => $value, 'sha256' => $this->hash_value( $value ) ); } return array( 'filter' => array( 'id' => $post->ID, 'title' => $post->post_title, 'status' => $post->post_status, 'meta' => $items ) ); }
	public function get_query_binding( $input ) { $data = $this->get_filter( $input ); if ( is_wp_error( $data ) ) return $data; $bindings = array(); foreach ( $data['filter']['meta'] as $key => $item ) { $haystack = strtolower( $key . ' ' . wp_json_encode( $item['value'] ) ); if ( false !== strpos( $haystack, 'query' ) || false !== strpos( $haystack, 'provider' ) || false !== strpos( $haystack, 'listing' ) ) $bindings[ $key ] = $item; } return array( 'filter_id' => absint( $input['filter_id'] ), 'bindings' => $bindings, 'count' => count( $bindings ) ); }
	public function update_filter_meta( $input ) { $post_type = $this->filter_post_type(); $id = absint( $input['filter_id'] ); $post = get_post( $id ); if ( ! $post_type || ! $post || $post->post_type !== $post_type ) return new WP_Error( 'mad4b_jetsmartfilters_filter_missing', 'Filter not found.' ); $key = sanitize_key( $input['meta_key'] ); if ( '' === $key || '_edit_lock' === $key || '_edit_last' === $key || 0 === strpos( $key, '_wp_' ) ) return new WP_Error( 'mad4b_jetsmartfilters_meta_denied', 'This meta key cannot be changed.' ); if ( ! metadata_exists( 'post', $id, $key ) ) return new WP_Error( 'mad4b_jetsmartfilters_meta_missing', 'Meta key does not already exist. This ability does not create arbitrary filter internals.' ); $current = get_post_meta( $id, $key, true ); $hash = $this->hash_value( $current ); if ( ! hash_equals( $hash, strtolower( trim( $input['expected_sha256'] ) ) ) ) return new WP_Error( 'mad4b_jetsmartfilters_stale_meta', 'Filter meta SHA-256 no longer matches.', array( 'current_sha256' => $hash ) ); $result = update_post_meta( $id, $key, $input['value'] ); if ( false === $result && $current !== $input['value'] ) return new WP_Error( 'mad4b_jetsmartfilters_update_failed', 'Unable to update filter meta.' ); $new = get_post_meta( $id, $key, true ); MAD4B_SCP_Audit::record( 'jetsmartfilters/update-filter-meta', array( 'filter_id' => $id, 'meta_key' => $key, 'sha256' => $this->hash_value( $new ) ) ); return array( 'filter_id' => $id, 'meta_key' => $key, 'updated' => true, 'sha256' => $this->hash_value( $new ) ); }
	private function filter_post_type() { foreach ( array( 'jet-smart-filters', 'jet-smart-filter' ) as $post_type ) if ( post_type_exists( $post_type ) ) return $post_type; return null; }
}
