<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class MAD4B_SCP_WooCommerce_Adapter extends MAD4B_SCP_Adapter_Base {
	public function id() { return 'woocommerce'; }
	public function label() { return 'WooCommerce'; }
	public function is_available() { return function_exists( 'wc_get_product' ); }
	public function ability_names() { return array( 'read' => array( 'woocommerce/status', 'woocommerce/get-product' ), 'content' => array( 'woocommerce/update-product' ), 'admin' => array() ); }
	protected function detect_plugin_version() { return defined( 'WC_VERSION' ) ? WC_VERSION : ''; }
	public function register_abilities() { $this->add_ability( 'woocommerce/status', 'Get WooCommerce Status', 'status', array( 'MAD4B_SCP_Policy', 'can_read' ) ); $schema = $this->schema( array( 'product_id' => array( 'type' => 'integer', 'minimum' => 1 ) ), array( 'product_id' ) ); $this->add_ability( 'woocommerce/get-product', 'Get WooCommerce Product', 'get_product', array( $this, 'can_read_product' ), $schema ); $this->add_ability( 'woocommerce/update-product', 'Update WooCommerce Product', 'update_product', array( $this, 'can_edit_product' ), $this->schema( array( 'product_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'fields' => array( 'type' => 'object' ) ), array( 'product_id', 'fields' ) ), 'content', false, false, true ); }
	public function can_read_product( $input ) { $id = isset( $input['product_id'] ) ? absint( $input['product_id'] ) : 0; return $id > 0 && current_user_can( 'read_post', $id ); }
	public function can_edit_product( $input ) { $id = isset( $input['product_id'] ) ? absint( $input['product_id'] ) : 0; return $id > 0 && current_user_can( 'edit_post', $id ); }
	public function get_product( $input ) { if ( ! $this->is_available() ) return $this->unavailable_error(); $product = wc_get_product( absint( $input['product_id'] ) ); if ( ! $product ) return new WP_Error( 'mad4b_wc_product_missing', 'Product not found.' ); return array( 'product' => array( 'id' => $product->get_id(), 'type' => $product->get_type(), 'name' => $product->get_name(), 'status' => $product->get_status(), 'sku' => $product->get_sku(), 'regular_price' => $product->get_regular_price(), 'sale_price' => $product->get_sale_price(), 'stock_status' => $product->get_stock_status(), 'featured' => $product->get_featured(), 'permalink' => $product->get_permalink() ) ); }
	public function update_product( $input ) { if ( ! $this->is_available() ) return $this->unavailable_error(); $product = wc_get_product( absint( $input['product_id'] ) ); if ( ! $product ) return new WP_Error( 'mad4b_wc_product_missing', 'Product not found.' ); $allowed = array( 'name', 'status', 'sku', 'regular_price', 'sale_price', 'stock_status', 'featured' ); foreach ( $input['fields'] as $field => $value ) { if ( ! in_array( $field, $allowed, true ) ) return new WP_Error( 'mad4b_wc_field_denied', 'Unsupported product field: ' . sanitize_key( $field ) ); $method = 'set_' . $field; if ( ! is_callable( array( $product, $method ) ) ) return new WP_Error( 'mad4b_wc_setter_missing', 'WooCommerce setter is unavailable for: ' . sanitize_key( $field ) ); if ( 'featured' === $field ) $value = (bool) $value; else $value = sanitize_text_field( $value ); $product->$method( $value ); } $saved = $product->save(); MAD4B_SCP_Audit::record( 'woocommerce/update-product', array( 'product_id' => $product->get_id(), 'fields' => array_keys( $input['fields'] ) ) ); return array( 'product_id' => $saved, 'updated' => true ); }
}
