<?php
namespace ETG\DynamicFilterSEOBridge\Admin;

require_once dirname( __DIR__ ) . '/Identifiers/QueryId.php';

use ETG\DynamicFilterSEOBridge\Config\Configuration;
use ETG\DynamicFilterSEOBridge\Config\ProfileRegistry;
use ETG\DynamicFilterSEOBridge\Diagnostics\PublicationEvidenceBundle;
use ETG\DynamicFilterSEOBridge\Identifiers\QueryId;
use ETG\DynamicFilterSEOBridge\SEO\PublicationRegistry;

final class PublicationPage {
	private $config; private $profiles; private $publication; private $evidence;
	public function __construct(Configuration $config,ProfileRegistry $profiles,PublicationRegistry $publication,PublicationEvidenceBundle $evidence){$this->config=$config;$this->profiles=$profiles;$this->publication=$publication;$this->evidence=$evidence;}
	public function register():void{add_action('admin_menu',array($this,'menu'));add_action('admin_post_etg_dfsb_export_publication_preview',array($this,'export'));add_action('admin_post_etg_dfsb_export_publication_evidence',array($this,'exportEvidence'));add_action('admin_post_etg_dfsb_save_structured_profile',array($this,'saveStructuredProfile'));}
	public function menu():void{add_options_page('ETG SEO Publication','ETG SEO Publication','manage_options','etg-filter-seo-publication',array($this,'render'));}
	public function render():void{
		if(!current_user_can('manage_options')){return;}
		$tabs=array('overview'=>'Overview','candidates'=>'Candidates','profiles'=>'Profile Manager','elementor'=>'Elementor Content','sitemap'=>'Sitemap & Discovery','evidence'=>'Evidence Bundle');
		$tab=isset($_GET['tab'])?sanitize_key((string)wp_unslash($_GET['tab'])):'overview';if(!isset($tabs[$tab])){$tab='overview';}
		$summary=('candidates'===$tab&&isset($_GET['etg_build_publication_preview']))?$this->publication->publicationSummary(50):null;
		$bundle=('evidence'===$tab&&isset($_GET['etg_build_evidence_bundle']))?$this->evidence->collect(50):null;
		$notice=isset($_GET['etg_notice'])?sanitize_key((string)wp_unslash($_GET['etg_notice'])):'';
		echo '<div class="wrap etg-publication-admin"><h1>ETG SEO Publication</h1>';$this->styles();
		if($notice){printf('<div class="notice %s inline"><p>%s</p></div>',0===strpos($notice,'saved')?'notice-success':'notice-error',esc_html($this->noticeText($notice)));}
		echo '<div class="etg-pub-grid">';$this->statusCard('Global bridge',$this->config->enabled()?'ON':'OFF','Master authority switch. Structured Profile Manager writes are blocked while Global bridge is ON.',$this->config->enabled()?'danger':'safe');$this->statusCard('Profiles',(string)count($this->profiles->all()),'Profiles may remain disabled during dark validation; evidence resolution never grants live authority.');$this->statusCard('Publication model','READ-ONLY PREVIEW','Preview separates candidate metadata/schema from emitted state and performs no activation.','readonly');$this->statusCard('Rollout cap',(string)$this->config->get('publication_max_urls',100).' URLs','Global live publication ceiling; Alpha9 hard-caps at 500 and defaults to 100.');echo '</div>';
		echo '<nav class="nav-tab-wrapper" aria-label="ETG SEO Publication sections">';foreach($tabs as $slug=>$label){$url=add_query_arg(array('page'=>'etg-filter-seo-publication','tab'=>$slug),admin_url('options-general.php'));printf('<a class="nav-tab %s" href="%s">%s</a>',$tab===$slug?'nav-tab-active':'',esc_url($url),esc_html($label));}echo '</nav>';
		if('candidates'===$tab){$this->renderCandidates($summary);}elseif('profiles'===$tab){$this->renderProfiles();}elseif('elementor'===$tab){$this->renderElementor();}elseif('sitemap'===$tab){$this->renderSitemap();}elseif('evidence'===$tab){$this->renderEvidence($bundle);}else{$this->renderOverview();}echo '</div>';
	}
	private function statusCard(string $label,string $value,string $tip,string $kind=''):void{echo '<div class="etg-pub-card"><strong>'.esc_html($label).'</strong><br/><span class="etg-pub-badge '.esc_attr($kind?'etg-pub-'.$kind:'').'">'.esc_html($value).'</span>';$this->tip($tip);echo '</div>';}
	private function renderOverview():void{echo '<div class="etg-pub-card"><h2>Publication governance contract</h2><p>Indexing requires exact profile/route/taxonomy authority, approved language-bound combinations, translated Terms, authoritative result count, provider observation evidence, result-count parity evidence, content readiness and Elementor verification.</p><p>Disabled profiles may be inspected in dark validation, but live Rank Math metadata still requires real provider/query observation.</p></div><div class="etg-pub-card"><h2>Safe sequence</h2><ol><li>Global OFF + profiles disabled.</li><li>Runtime Inventory and reconciliation.</li><li>Enter reviewed route/taxonomy-set/combination authority.</li><li>Dark-render Elementor server-side content and attach evidence.</li><li>Attach provider/query and count-parity evidence.</li><li>Run Candidate Preview and Evidence Bundle.</li><li>Only then make a separate activation decision.</li></ol></div>';}
	private function renderCandidates($summary):void{
		echo '<div class="etg-pub-card"><h2>Publication Candidate Preview <span class="etg-pub-badge etg-pub-readonly">READ-ONLY</span></h2><div class="etg-pub-actions"><form method="get"><input type="hidden" name="page" value="etg-filter-seo-publication"/><input type="hidden" name="tab" value="candidates"/><input type="hidden" name="etg_build_publication_preview" value="1"/><button class="button button-secondary">Build Publication Preview</button>';$this->tip('Evaluates at most 50 approved combinations in memory and writes nothing.');echo '</form><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="etg_dfsb_export_publication_preview"/>';wp_nonce_field('etg_dfsb_export_publication_preview');echo '<button class="button button-secondary">Download Preview JSON</button>';$this->tip('Exports candidate/emitted separation, exclusions, cache and performance evidence.');echo '</form></div></div>';
		if(!is_array($summary)){return;}printf('<div class="etg-pub-card"><strong>Candidates:</strong> %d &nbsp; <strong>Would index:</strong> %d &nbsp; <strong>Ready if Global ON:</strong> %d &nbsp; <strong>Live included:</strong> %d<pre class="etg-pub-code">%s</pre></div>',(int)$summary['candidate_count'],(int)$summary['would_index_count'],(int)$summary['publication_ready_if_global_on_count'],(int)$summary['sitemap_included_count'],esc_html(wp_json_encode($summary['exclusion_reasons'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)));
		echo '<table class="etg-pub-table"><thead><tr><th>URL / Signature</th><th>Candidate metadata</th><th>Emitted if eligible</th><th>Evidence</th><th>Count</th><th>Sitemap</th><th>Exclusions</th></tr></thead><tbody>';foreach((array)$summary['candidates'] as $row){echo '<tr><td><code>'.esc_html((string)$row['signature']).'</code><br/><small>'.esc_html((string)$row['url']).'</small></td><td>'.esc_html((string)($row['metadata_candidate']['title']??'')).'<br/><small>schema candidate: '.(empty($row['schema_candidate'])?'NO':'YES').'</small></td><td>'.(empty($row['metadata_emitted_if_global_on'])?'BLOCKED':'ELIGIBLE').'<br/><small>schema emitted: '.(empty($row['schema_emitted'])?'NO':'YES').'</small></td><td>Provider '.(!empty($row['provider_observation_verified'])?'VERIFIED':'MISSING').'<br/>Elementor '.(!empty($row['elementor_content_verified'])?'VERIFIED':'MISSING').'<br/>Parity '.(!empty($row['result_count_parity_verified'])?'VERIFIED':'MISSING').'</td><td>'.(is_numeric($row['result_count'])?esc_html((string)$row['result_count']):'N/A').'</td><td>'.(!empty($row['sitemap_included'])?'INCLUDED':(!empty($row['publication_ready_if_global_on'])?'READY IF GLOBAL ON':'EXCLUDED')).'</td><td>'.esc_html(implode(', ',(array)$row['exclusion_reasons'])).'</td></tr>';}echo '</tbody></table>';
	}
	private function renderProfiles():void{
		$globalOn=$this->config->enabled();echo '<div class="etg-pub-card"><h2>Structured Profile Manager</h2><p>Safe daily-editing surface. Raw <code>profiles_json</code> remains Advanced authority. <strong>'.($globalOn?'WRITE LOCKED':'WRITES ALLOWED WHILE GLOBAL OFF').'</strong></p></div>';
		foreach($this->profiles->all() as $id=>$profile){$pub=(array)($profile['publication']??array());$routes=array_values((array)($profile['routes']??array()));$route=count($routes)===1?(array)$routes[0]:array();echo '<form class="etg-pub-card etg-profile-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="etg_dfsb_save_structured_profile"/><input type="hidden" name="profile_id" value="'.esc_attr((string)$id).'"/>';wp_nonce_field('etg_dfsb_save_structured_profile:'.$id);echo '<h2>'.esc_html((string)$id).'</h2><table class="form-table">';
			$this->checkRow('Profile enabled','profile_enabled',!empty($profile['enabled']),'Controls live profile eligibility. Keep OFF during dark validation.');
			$this->checkRow('Require provider observation','require_provider_observation_for_index',!empty($profile['require_provider_observation_for_index']),'When ON, live indexing hard-denies if JetSmartFilters provider/query was not observed.');
			$this->textRow('Exact route provider','route_provider',(string)($route['provider']??''),'Exact JetSmartFilters provider. Multiple-route profiles must be edited in Advanced JSON.',count($routes)>1);
			$this->textRow('Exact Query Builder ID','route_query_id',(string)($route['query_id']??''),'Exact case-sensitive Query ID paired with the provider. Query IDs are identifiers, not WordPress slugs.',count($routes)>1);
			$this->textareaRow('Allowed taxonomy sets','allowed_taxonomy_sets',implode("\n",(array)($profile['allowed_taxonomy_sets']??array())),'Structural allowlist of exact taxonomy shapes; discovery never grants authority.',4);
			$this->textareaRow('Approved combinations','indexable_combinations',implode("\n",(array)($profile['indexable_combinations']??array())),'Exact profile + language + term signatures only. No wildcard or Cartesian generation.',7);
			$this->evidenceRow('Provider observation evidence','provider_observation_verified','provider_observation_evidence_id',!empty($pub['provider_observation_verified']),(string)($pub['provider_observation_evidence_id']??''),'Confirms representative live requests exposed the expected provider/query. Evidence ID is required.');
			$this->checkRow('Elementor dark render','elementor_render_when_global_off',!empty($pub['elementor_render_when_global_off']),'Allows server-side ETG shortcode content while Global OFF; does not enable SEO publication.');
			$this->evidenceRow('Elementor content evidence','elementor_content_verified','elementor_verification_evidence_id',!empty($pub['elementor_content_verified']),(string)($pub['elementor_verification_evidence_id']??''),'Confirms H1/intro/Term sections exist server-side. Evidence ID is required.');
			$this->checkRow('Require result-count parity','require_result_count_parity_for_publication',!empty($pub['require_result_count_parity_for_publication']),'Requires frontend = request adapter = background probe before sitemap publication.');
			$this->evidenceRow('Result-count parity evidence','result_count_parity_verified','result_count_parity_evidence_id',!empty($pub['result_count_parity_verified']),(string)($pub['result_count_parity_evidence_id']??''),'Recorded parity proof. A mismatch must remain blocked.');
			$this->checkRow('Sitemap publication','sitemap',!empty($pub['sitemap']),'Allows this profile to publish only after all gates pass and Global is ON.');
			echo '<tr><th>Bounded limits ';$this->tip('Caps expensive preview/publication work. Preview max 100; publication max 500, recommended 100 or less.');echo '</th><td>Preview <input type="number" min="1" max="100" name="max_preview_urls" value="'.esc_attr((string)($pub['max_preview_urls']??50)).'"/> &nbsp; Publication <input type="number" min="1" max="500" name="max_publication_urls" value="'.esc_attr((string)($pub['max_publication_urls']??100)).'"/></td></tr></table><p><button class="button button-primary" '.($globalOn?'disabled':'').'>Save Structured Profile</button> ';$this->tip('Persists only this profile while Global OFF. Verified flags require non-empty evidence IDs.');echo '</p></form>';}
	}
	private function checkRow(string $label,string $name,bool $checked,string $tip):void{echo '<tr><th>'.esc_html($label).' ';$this->tip($tip);echo '</th><td><label><input type="checkbox" name="'.esc_attr($name).'" value="1" '.checked($checked,true,false).'/> Enabled</label></td></tr>';}
	private function textRow(string $label,string $name,string $value,string $tip,bool $disabled=false):void{echo '<tr><th>'.esc_html($label).' ';$this->tip($tip);echo '</th><td><input class="regular-text code" name="'.esc_attr($name).'" value="'.esc_attr($value).'" '.($disabled?'disabled':'').'/></td></tr>';}
	private function textareaRow(string $label,string $name,string $value,string $tip,int $rows):void{echo '<tr><th>'.esc_html($label).' ';$this->tip($tip);echo '</th><td><textarea class="large-text code" rows="'.$rows.'" name="'.esc_attr($name).'">'.esc_textarea($value).'</textarea></td></tr>';}
	private function evidenceRow(string $label,string $flag,string $idName,bool $verified,string $id,string $tip):void{echo '<tr><th>'.esc_html($label).' ';$this->tip($tip);echo '</th><td><label><input type="checkbox" name="'.esc_attr($flag).'" value="1" '.checked($verified,true,false).'/> Verified</label> <input class="regular-text code" name="'.esc_attr($idName).'" value="'.esc_attr($id).'" placeholder="evidence:sha256-or-ticket"/></td></tr>';}
	private function renderElementor():void{
		echo '<div class="etg-pub-card"><h2>Elementor Theme Builder support</h2><p>Use server-rendered ETG shortcodes in the archive template. Verification requires an evidence reference, not a bare checkbox.</p><pre class="etg-pub-code">[etg_filter_h1]\n[etg_filter_intro]\n[etg_filter_sections]\n[etg_filter_gallery mode="priority" limit="8"]\n[etg_filter_term_section role="location" field="description" heading="1"]</pre></div>';
		echo '<div class="etg-pub-card"><h2>Safe dark presentation</h2><p>With Global bridge OFF, enable <code>elementor_render_when_global_off</code> only for read-only server-side visual/source validation of governed Term content. This does not activate Rank Math metadata, robots index authority, hreflang publication, or the live ETG sitemap.</p></div>';
	}
	private function renderSitemap():void{echo '<div class="etg-pub-card"><h2>Rank Math dynamic sitemap</h2><p><code>etg-filter-seo</code> returns no URLs while Global OFF. Alpha9 adds bounded rollout, persistent candidate cache, provider evidence and count-parity gates.</p><p><strong>Expected:</strong> <code>'.esc_html(home_url('/etg-filter-seo-sitemap.xml')).'</code></p><p><strong>Clean canonical URLs remain deferred</strong> until rewrite/collision/WPML evidence exists.</p></div>';}
	private function renderEvidence($bundle):void{echo '<div class="etg-pub-card"><h2>Runtime Evidence Bundle <span class="etg-pub-badge etg-pub-readonly">READ-ONLY</span></h2><div class="etg-pub-actions"><form method="get"><input type="hidden" name="page" value="etg-filter-seo-publication"/><input type="hidden" name="tab" value="evidence"/><input type="hidden" name="etg_build_evidence_bundle" value="1"/><button class="button button-secondary">Build Evidence Bundle</button>';$this->tip('Collects readiness, Runtime Inventory, profile evidence refs and bounded preview; no mutation.');echo '</form><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="etg_dfsb_export_publication_evidence"/>';wp_nonce_field('etg_dfsb_export_publication_evidence');echo '<button class="button button-secondary">Download Evidence JSON</button>';$this->tip('Downloads the same non-authorizing bundle for audit and hashing.');echo '</form></div></div>';if(is_array($bundle)){echo '<div class="etg-pub-card"><strong>Evidence complete:</strong> '.(!empty($bundle['evidence_complete'])?'YES':'NO').' &nbsp; <strong>Activation authorized:</strong> NO<pre class="etg-pub-code">'.esc_html(wp_json_encode(array('activation_blockers'=>$bundle['activation_blockers'],'required_external_evidence'=>$bundle['required_external_evidence'],'profile_evidence'=>$bundle['profile_evidence']),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)).'</pre></div>';}}
	public function export():void{if(!current_user_can('manage_options')){wp_die('Forbidden','Forbidden',array('response'=>403));}check_admin_referer('etg_dfsb_export_publication_preview');$this->jsonDownload('etg-dfsb-publication-preview.json',$this->publication->publicationSummary(100));}
	public function exportEvidence():void{if(!current_user_can('manage_options')){wp_die('Forbidden','Forbidden',array('response'=>403));}check_admin_referer('etg_dfsb_export_publication_evidence');$this->jsonDownload('etg-dfsb-publication-evidence.json',$this->evidence->collect(100));}
	public function saveStructuredProfile():void{
		if(!current_user_can('manage_options')){wp_die('Forbidden','Forbidden',array('response'=>403));}$profileId=isset($_POST['profile_id'])?sanitize_key((string)wp_unslash($_POST['profile_id'])):'';check_admin_referer('etg_dfsb_save_structured_profile:'.$profileId);if($this->config->enabled()){$this->redirectNotice('write_blocked_global_on');}if(''===$profileId){$this->redirectNotice('profile_not_found');}
		$settings=$this->config->all();$raw=json_decode((string)($settings['profiles_json']??''),true);if(!is_array($raw)){$this->redirectNotice('profile_registry_invalid');}$index=null;foreach($raw as $i=>$candidate){if(is_array($candidate)&&sanitize_key((string)($candidate['id']??''))===$profileId){$index=$i;break;}}if(null===$index){$this->redirectNotice('profile_not_found');}$profile=(array)$raw[$index];$pub=is_array($profile['publication']??null)?$profile['publication']:array();$routes=array_values((array)($profile['routes']??array()));
		$profile['enabled']=isset($_POST['profile_enabled']);$profile['require_provider_observation_for_index']=isset($_POST['require_provider_observation_for_index']);if(count($routes)<=1){$provider=isset($_POST['route_provider'])?sanitize_key((string)wp_unslash($_POST['route_provider'])):'';$queryId=isset($_POST['route_query_id'])?QueryId::normalize(wp_unslash((string)$_POST['route_query_id'])):'';if($provider&&$queryId){$route=array('provider'=>$provider,'query_id'=>$queryId,'provider_query_id'=>$queryId);$existing=count($routes)===1?(array)$routes[0]:array();$queryBuilderId=QueryId::normalize($existing['query_builder_query_id']??'');if(''!==$queryBuilderId){$route['query_builder_query_id']=$queryBuilderId;}$profile['routes']=array($route);$profile['providers']=array($provider);$profile['query_ids']=array($queryId);}}
		$profile['allowed_taxonomy_sets']=$this->taxonomySetLines($_POST['allowed_taxonomy_sets']??'');$profile['indexable_combinations']=$this->textLines($_POST['indexable_combinations']??'',500);
		$pub['sitemap']=isset($_POST['sitemap']);$pub['elementor_render_when_global_off']=isset($_POST['elementor_render_when_global_off']);$pub['elementor_content_verified']=isset($_POST['elementor_content_verified']);$pub['elementor_verification_evidence_id']=$this->evidenceId($_POST['elementor_verification_evidence_id']??'');$pub['provider_observation_verified']=isset($_POST['provider_observation_verified']);$pub['provider_observation_evidence_id']=$this->evidenceId($_POST['provider_observation_evidence_id']??'');$pub['require_result_count_parity_for_publication']=isset($_POST['require_result_count_parity_for_publication']);$pub['result_count_parity_verified']=isset($_POST['result_count_parity_verified']);$pub['result_count_parity_evidence_id']=$this->evidenceId($_POST['result_count_parity_evidence_id']??'');$pub['max_preview_urls']=$this->boundedInt($_POST['max_preview_urls']??50,1,100);$pub['max_publication_urls']=$this->boundedInt($_POST['max_publication_urls']??100,1,500);
		if($pub['elementor_content_verified']&&''===$pub['elementor_verification_evidence_id']){$this->redirectNotice('elementor_evidence_required');}if($pub['provider_observation_verified']&&''===$pub['provider_observation_evidence_id']){$this->redirectNotice('provider_evidence_required');}if($pub['result_count_parity_verified']&&''===$pub['result_count_parity_evidence_id']){$this->redirectNotice('count_parity_evidence_required');}
		$profile['publication']=$pub;$raw[$index]=$profile;$settings['profiles_json']=wp_json_encode($raw,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);update_option(Configuration::OPTION_NAME,$this->config->sanitize($settings),false);$this->redirectNotice('saved_profile');
	}
	private function jsonDownload(string $filename,array $payload):void{if(function_exists('nocache_headers')){nocache_headers();}header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename="'.$filename.'"');echo wp_json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
	private function taxonomySetLines($value):array{$out=array();foreach($this->textLines($value,100) as $line){$parts=preg_split('/[+;,]+/',$line);$parts=array_values(array_unique(array_filter(array_map('sanitize_key',(array)$parts),'strlen')));sort($parts,SORT_STRING);if($parts){$out[]=implode('+',$parts);}}return array_values(array_unique($out));}
	private function textLines($value,int $limit):array{$value=is_string($value)?wp_unslash($value):'';$lines=preg_split('/[\r\n]+/',$value);$out=array();foreach((array)$lines as $line){$line=trim((string)$line);if(''===$line){continue;}$line=function_exists('sanitize_text_field')?sanitize_text_field($line):strip_tags($line);if(''!==$line){$out[]=$line;}if(count($out)>=$limit){break;}}return array_values(array_unique($out));}
	private function evidenceId($value):string{$value=is_string($value)?wp_unslash($value):'';$value=trim($value);if(strlen($value)>160){$value=substr($value,0,160);}$value=preg_replace('/[^A-Za-z0-9:_\-.]/','',$value);return is_string($value)?$value:'';}
	private function boundedInt($value,int $min,int $max):int{$value=is_numeric($value)?(int)$value:$min;return max($min,min($max,$value));}
	private function redirectNotice(string $notice):void{$url=add_query_arg(array('page'=>'etg-filter-seo-publication','tab'=>'profiles','etg_notice'=>$notice),admin_url('options-general.php'));wp_safe_redirect($url);exit;}
	private function noticeText(string $notice):string{$map=array('saved_profile'=>'Structured profile saved while Global bridge is OFF.','write_blocked_global_on'=>'Profile write blocked: turn Global bridge OFF before changing structured authority.','profile_not_found'=>'Profile not found.','profile_registry_invalid'=>'Profile registry is invalid; no write was performed.','elementor_evidence_required'=>'Elementor verification requires a non-empty evidence ID.','provider_evidence_required'=>'Provider observation verification requires a non-empty evidence ID.','count_parity_evidence_required'=>'Result-count parity verification requires a non-empty evidence ID.');return (string)($map[$notice]??$notice);}
	private function styles():void{echo '<style>.etg-publication-admin .nav-tab-wrapper{margin-bottom:20px}.etg-pub-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;max-width:1200px}.etg-pub-card{background:#fff;border:1px solid #dcdcde;border-radius:6px;padding:16px;margin:0 0 16px;max-width:1400px}.etg-pub-badge{display:inline-block;padding:3px 8px;border-radius:12px;font-size:11px;font-weight:700}.etg-pub-safe{background:#d7f3df;color:#0b5d24}.etg-pub-danger{background:#fbeaea;color:#8a1515}.etg-pub-readonly{background:#e8f0fe;color:#174ea6}.etg-pub-tip{display:inline-flex;width:18px;height:18px;align-items:center;justify-content:center;border-radius:50%;background:#2271b1;color:#fff;font-weight:700;font-size:12px;cursor:help;margin-left:5px}.etg-pub-table{border-collapse:collapse;width:100%;max-width:1500px;background:#fff}.etg-pub-table th,.etg-pub-table td{border:1px solid #dcdcde;padding:8px;vertical-align:top;text-align:left}.etg-pub-code{background:#f6f7f7;padding:12px;overflow:auto;max-width:1350px}.etg-pub-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.etg-profile-form textarea{max-width:900px}</style>';}
	private function tip(string $text):void{printf('<span class="etg-pub-tip" tabindex="0" title="%1$s" aria-label="%1$s">?</span>',esc_attr($text));}
}
