<?php
namespace ETG\DynamicFilterSEOBridge\Admin;

use ETG\DynamicFilterSEOBridge\Config\Configuration;
use ETG\DynamicFilterSEOBridge\Config\ProfileRegistry;
use ETG\DynamicFilterSEOBridge\Diagnostics\PublicationEvidenceBundle;
use ETG\DynamicFilterSEOBridge\Diagnostics\LiveRuntimeProbe;
use ETG\DynamicFilterSEOBridge\SEO\PublicationRegistry;

final class PublicationPage {
    private $config; private $profiles; private $publication; private $evidence; private $probe;
    public function __construct(Configuration $config,ProfileRegistry $profiles,PublicationRegistry $publication,PublicationEvidenceBundle $evidence,LiveRuntimeProbe $probe=null){$this->config=$config;$this->profiles=$profiles;$this->publication=$publication;$this->evidence=$evidence;$this->probe=$probe;}
    public function register():void{
        add_action('admin_menu',array($this,'menu'));
        add_action('admin_post_etg_dfsb_export_publication_preview',array($this,'export'));
        add_action('admin_post_etg_dfsb_export_publication_evidence',array($this,'exportEvidence'));
        add_action('admin_post_etg_dfsb_save_structured_profile',array($this,'saveStructuredProfile'));
        add_action('admin_post_etg_dfsb_save_publication_limits',array($this,'savePublicationLimits'));
    }
    public function menu():void{add_options_page('ETG SEO Publication','ETG SEO Publication','manage_options','etg-filter-seo-publication',array($this,'render'));}
    public function render():void{
        if(!current_user_can('manage_options')){return;}
        $tabs=array('overview'=>'Overview','candidates'=>'Candidates','profiles'=>'Profile Manager','elementor'=>'Elementor Content','sitemap'=>'Sitemap & Discovery','runtime'=>'Live Runtime Probe','evidence'=>'Evidence Bundle');
        $tab=isset($_GET['tab'])?sanitize_key((string)wp_unslash($_GET['tab'])):'overview';if(!isset($tabs[$tab])){$tab='overview';}
        $notice=isset($_GET['etg_notice'])?sanitize_key((string)wp_unslash($_GET['etg_notice'])):'';
        echo '<div class="wrap"><h1>ETG SEO Publication</h1>';
        if($notice){echo '<div class="notice '.(0===strpos($notice,'saved')||0===strpos($notice,'probe_')?'notice-success':'notice-error').' inline"><p>'.esc_html($this->noticeText($notice)).'</p></div>';}
        echo '<p><strong>Global bridge:</strong> '.($this->config->enabled()?'ON — WRITE LOCKED':'OFF — dark validation only').' &nbsp; <strong>Profiles:</strong> '.count($this->profiles->all()).' &nbsp; <strong>Rollout cap:</strong> '.(int)$this->config->get('publication_max_urls',10).' URLs</p>';
        echo '<nav class="nav-tab-wrapper">';foreach($tabs as $slug=>$label){$url=add_query_arg(array('page'=>'etg-filter-seo-publication','tab'=>$slug),admin_url('options-general.php'));echo '<a class="nav-tab '.($tab===$slug?'nav-tab-active':'').'" href="'.esc_url($url).'">'.esc_html($label).'</a>';}echo '</nav><div style="margin-top:20px">';
        if('candidates'===$tab){$this->renderCandidates();}elseif('profiles'===$tab){$this->renderProfiles();}elseif('elementor'===$tab){$this->renderElementor();}elseif('sitemap'===$tab){$this->renderSitemap();}elseif('runtime'===$tab){$this->renderRuntime();}elseif('evidence'===$tab){$this->renderEvidence();}else{$this->renderOverview();}echo '</div></div>';
    }
    private function renderOverview():void{echo '<div class="card" style="max-width:1100px"><h2>Publication governance contract</h2><p>Indexing requires exact route/taxonomy authority, language-bound approved combinations, translated Terms, authoritative count, current provider evidence, count-parity evidence, content readiness and server-side Elementor verification.</p><p>Disabled profiles can be inspected in dark validation. No preview, probe or evidence bundle authorizes Production activation.</p></div>';}
    private function renderCandidates():void{
        $summary=isset($_GET['etg_build_publication_preview'])?$this->publication->publicationSummary(50):null;
        echo '<div class="card" style="max-width:1200px"><h2>Publication Candidate Preview — READ-ONLY</h2><form method="get"><input type="hidden" name="page" value="etg-filter-seo-publication"/><input type="hidden" name="tab" value="candidates"/><input type="hidden" name="etg_build_publication_preview" value="1"/><button class="button">Build Publication Preview</button></form><form style="margin-top:8px" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="etg_dfsb_export_publication_preview"/>';wp_nonce_field('etg_dfsb_export_publication_preview');echo '<button class="button">Download Preview JSON</button></form>';
        if(is_array($summary)){echo '<p><strong>Candidates:</strong> '.(int)$summary['candidate_count'].' &nbsp; <strong>Would index:</strong> '.(int)$summary['would_index_count'].' &nbsp; <strong>Ready if Global ON:</strong> '.(int)$summary['publication_ready_if_global_on_count'].' &nbsp; <strong>Live included:</strong> '.(int)$summary['sitemap_included_count'].'</p><pre style="white-space:pre-wrap">'.esc_html(wp_json_encode(array('exclusions'=>$summary['exclusion_reasons'],'performance'=>$summary['performance'],'cache'=>$summary['cache'],'limits'=>$summary['limits']),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)).'</pre>';}
        echo '</div>';
    }
    private function renderProfiles():void{
        $locked=$this->config->enabled();echo '<div class="card" style="max-width:1200px"><h2>Structured Profile Manager</h2><p><strong>'.($locked?'WRITE LOCKED':'WRITES ALLOWED WHILE GLOBAL OFF').'</strong>. Raw <code>profiles_json</code> remains Advanced authority. Evidence is SHA256-only and fingerprint-bound.</p></div>';
        foreach($this->profiles->all() as $id=>$profile){$pub=(array)($profile['publication']??array());$routes=array_values((array)($profile['routes']??array()));$route=1===count($routes)?(array)$routes[0]:array();echo '<form class="card" style="max-width:1200px" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="etg_dfsb_save_structured_profile"/><input type="hidden" name="profile_id" value="'.esc_attr((string)$id).'"/>';wp_nonce_field('etg_dfsb_save_structured_profile:'.$id);echo '<h2>'.esc_html((string)$id).'</h2><p>Authority fingerprint: <code>'.esc_html((string)($profile['authority_fingerprint']??'')).'</code></p><table class="form-table">';
            $this->checkRow('Profile enabled','profile_enabled',!empty($profile['enabled']));$this->checkRow('Require provider observation','require_provider_observation_for_index',!empty($profile['require_provider_observation_for_index']));$this->textRow('Exact route provider','route_provider',(string)($route['provider']??''),count($routes)>1);$this->textRow('Exact Query Builder ID','route_query_id',(string)($route['query_id']??''),count($routes)>1);$this->areaRow('Allowed taxonomy sets','allowed_taxonomy_sets',implode("\n",(array)($profile['allowed_taxonomy_sets']??array())));$this->areaRow('Approved combinations','indexable_combinations',implode("\n",(array)($profile['indexable_combinations']??array())));
            $this->checkRow('Sitemap publication','sitemap',!empty($pub['sitemap']));$this->checkRow('Elementor dark render','elementor_render_when_global_off',!empty($pub['elementor_render_when_global_off']));$this->evidenceRow('Elementor content evidence','elementor_content_verified','elementor_verification_evidence_id',!empty($pub['elementor_evidence_current']),(string)($pub['elementor_verification_evidence_id']??''));$this->evidenceRow('Provider observation evidence','provider_observation_verified','provider_observation_evidence_id',!empty($pub['provider_observation_evidence_current']),(string)($pub['provider_observation_evidence_id']??''));$this->checkRow('Require count parity','require_result_count_parity_for_publication',!empty($pub['require_result_count_parity_for_publication']));$this->evidenceRow('Result-count parity evidence','result_count_parity_verified','result_count_parity_evidence_id',!empty($pub['result_count_parity_evidence_current']),(string)($pub['result_count_parity_evidence_id']??''));
            echo '<tr><th>Bounded limits</th><td>Preview <input type="number" min="1" max="100" name="max_preview_urls" value="'.esc_attr((string)($pub['max_preview_urls']??25)).'"/> &nbsp; Publication <input type="number" min="1" max="500" name="max_publication_urls" value="'.esc_attr((string)($pub['max_publication_urls']??10)).'"/></td></tr></table><p><button class="button button-primary" '.($locked?'disabled':'').'>Save Structured Profile</button></p></form>';}
    }
    private function renderElementor():void{echo '<div class="card" style="max-width:1000px"><h2>Elementor Theme Builder</h2><p>Use server-rendered ETG context from the same resolved Terms used by metadata. Dark presentation may run while Global OFF without granting index authority.</p><pre>[etg_filter_h1]\n[etg_filter_intro]\n[etg_filter_sections]\n[etg_filter_gallery mode="priority" limit="8"]\n[etg_filter_term_section role="location" field="description" heading="1"]</pre><p>Acceptance requires View Source evidence and an immutable <code>sha256:&lt;64hex&gt;</code> reference bound to the current profile fingerprint.</p></div>';}
    private function renderSitemap():void{$max=(int)$this->config->get('publication_max_urls',10);$budget=(int)$this->config->get('publication_candidate_evaluation_budget',50);$ttl=(int)$this->config->get('publication_cache_ttl',21600);echo '<div class="card" style="max-width:1000px"><h2>Rank Math dynamic sitemap</h2><p><code>etg-filter-seo</code> must remain empty while Global OFF. Recommended rollout: <strong>10 → 25 → 50 → 100</strong>.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="etg_dfsb_save_publication_limits"/>';wp_nonce_field('etg_dfsb_save_publication_limits');echo '<p>Live cap <input type="number" min="1" max="500" name="publication_max_urls" value="'.esc_attr((string)$max).'"/> &nbsp; Evaluation budget <input type="number" min="1" max="500" name="publication_candidate_evaluation_budget" value="'.esc_attr((string)$budget).'"/> &nbsp; Cache TTL <input type="number" min="300" max="86400" name="publication_cache_ttl" value="'.esc_attr((string)$ttl).'"/></p><button class="button button-primary" '.($this->config->enabled()?'disabled':'').'>Save bounded rollout controls</button></form></div>';}
    private function renderRuntime():void{echo '<div class="card" style="max-width:1100px"><h2>Live Runtime Probe — NON-AUTHORIZING</h2>';if(!$this->probe){echo '<p>Probe service unavailable.</p></div>';return;}$status=$this->probe->status();echo '<p>Armed: <strong>'.(!empty($status['armed'])?'YES':'NO').'</strong> &nbsp; Samples: '.(int)$status['sample_count'].' &nbsp; Remaining: '.(int)$status['seconds_remaining'].'s</p><p>This probe observes provider/query timing, authoritative count timing, WPML/Unicode state, query/memory cost and server HTML SHA256 only. It never activates SEO authority.</p><pre style="max-height:500px;overflow:auto">'.esc_html(wp_json_encode(array_slice(array_reverse($this->probe->samples()),0,20),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)).'</pre></div>';}
    private function renderEvidence():void{$bundle=isset($_GET['etg_build_evidence_bundle'])?$this->evidence->collect(50):null;echo '<div class="card" style="max-width:1200px"><h2>Runtime Evidence Bundle — READ-ONLY</h2><form method="get"><input type="hidden" name="page" value="etg-filter-seo-publication"/><input type="hidden" name="tab" value="evidence"/><input type="hidden" name="etg_build_evidence_bundle" value="1"/><button class="button">Build Evidence Bundle</button></form><form style="margin-top:8px" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="etg_dfsb_export_publication_evidence"/>';wp_nonce_field('etg_dfsb_export_publication_evidence');echo '<button class="button">Download Evidence JSON</button></form>';if(is_array($bundle)){echo '<pre style="max-height:600px;overflow:auto">'.esc_html(wp_json_encode($bundle,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)).'</pre>';}echo '</div>';}
    public function export():void{$this->requireAdmin('etg_dfsb_export_publication_preview');$this->download('etg-dfsb-publication-preview.json',$this->publication->publicationSummary(100));}
    public function exportEvidence():void{$this->requireAdmin('etg_dfsb_export_publication_evidence');$this->download('etg-dfsb-publication-evidence.json',$this->evidence->collect(100));}
    public function savePublicationLimits():void{$this->requireAdmin('etg_dfsb_save_publication_limits');if($this->config->enabled()){$this->redirect('write_blocked_global_on','sitemap');}$settings=$this->config->all();$max=$this->int($_POST['publication_max_urls']??10,1,500);$budget=$this->int($_POST['publication_candidate_evaluation_budget']??50,1,500);$settings['publication_max_urls']=$max;$settings['publication_candidate_evaluation_budget']=max($max,$budget);$settings['publication_cache_ttl']=$this->int($_POST['publication_cache_ttl']??21600,300,86400);update_option(Configuration::OPTION_NAME,$this->config->sanitize($settings),false);$this->redirect('saved_publication_limits','sitemap');}
    public function saveStructuredProfile():void{
        if(!current_user_can('manage_options')){wp_die('Forbidden','Forbidden',array('response'=>403));}$id=isset($_POST['profile_id'])?sanitize_key((string)wp_unslash($_POST['profile_id'])):'';check_admin_referer('etg_dfsb_save_structured_profile:'.$id);if($this->config->enabled()){$this->redirect('write_blocked_global_on');}
        $settings=$this->config->all();$raw=json_decode((string)($settings['profiles_json']??''),true);if(!is_array($raw)){$this->redirect('profile_registry_invalid');}$idx=null;foreach($raw as $i=>$row){if(is_array($row)&&sanitize_key((string)($row['id']??''))===$id){$idx=$i;break;}}if(null===$idx){$this->redirect('profile_not_found');}
        $profile=(array)$raw[$idx];$before=$this->profiles->get($id);$beforePub=(array)($before['publication']??array());$oldFingerprint=$this->profiles->fingerprintForRawProfile($profile);$pub=is_array($profile['publication']??null)?$profile['publication']:array();$routes=array_values((array)($profile['routes']??array()));
        $profile['enabled']=isset($_POST['profile_enabled']);$profile['require_provider_observation_for_index']=isset($_POST['require_provider_observation_for_index']);if(count($routes)<=1){$provider=sanitize_key((string)wp_unslash($_POST['route_provider']??''));$query=sanitize_key((string)wp_unslash($_POST['route_query_id']??''));if($provider&&$query){$profile['routes']=array(array('provider'=>$provider,'query_id'=>$query));$profile['providers']=array($provider);$profile['query_ids']=array($query);}}
        $profile['allowed_taxonomy_sets']=$this->taxonomyLines($_POST['allowed_taxonomy_sets']??'');$profile['indexable_combinations']=$this->lines($_POST['indexable_combinations']??'',500);
        $pub['sitemap']=isset($_POST['sitemap']);$pub['elementor_render_when_global_off']=isset($_POST['elementor_render_when_global_off']);$pub['elementor_content_verified']=isset($_POST['elementor_content_verified']);$pub['elementor_verification_evidence_id']=$this->evidenceId($_POST['elementor_verification_evidence_id']??'');$pub['provider_observation_verified']=isset($_POST['provider_observation_verified']);$pub['provider_observation_evidence_id']=$this->evidenceId($_POST['provider_observation_evidence_id']??'');$pub['require_result_count_parity_for_publication']=isset($_POST['require_result_count_parity_for_publication']);$pub['result_count_parity_verified']=isset($_POST['result_count_parity_verified']);$pub['result_count_parity_evidence_id']=$this->evidenceId($_POST['result_count_parity_evidence_id']??'');$pub['max_preview_urls']=$this->int($_POST['max_preview_urls']??25,1,100);$pub['max_publication_urls']=$this->int($_POST['max_publication_urls']??10,1,500);
        foreach(array(array('elementor_content_verified','elementor_verification_evidence_id','elementor_evidence_current'),array('provider_observation_verified','provider_observation_evidence_id','provider_observation_evidence_current'),array('result_count_parity_verified','result_count_parity_evidence_id','result_count_parity_evidence_current')) as $e){list($flag,$key,$current)=$e;if(!empty($pub[$flag])&&!$this->validEvidence((string)$pub[$key])){$this->redirect($key.'_required');}$oldId=(string)($beforePub[$key]??'');if(!empty($pub[$flag])&&!empty($beforePub[$flag])&&empty($beforePub[$current])&&$oldId!==''&&hash_equals($oldId,(string)$pub[$key])){$this->redirect('stale_evidence_must_change');}}
        $profile['publication']=$pub;$newFingerprint=$this->profiles->fingerprintForRawProfile($profile);$changed=!hash_equals($oldFingerprint,$newFingerprint);foreach(array(array('elementor_content_verified','elementor_verification_evidence_id','elementor_verification_authority_fingerprint'),array('provider_observation_verified','provider_observation_evidence_id','provider_observation_authority_fingerprint'),array('result_count_parity_verified','result_count_parity_evidence_id','result_count_parity_authority_fingerprint')) as $b){list($flag,$key,$fp)=$b;if($changed){$profile['publication'][$flag]=false;$profile['publication'][$fp]='';}elseif(!empty($profile['publication'][$flag])&&$this->validEvidence((string)$profile['publication'][$key])){$profile['publication'][$fp]=$newFingerprint;}else{$profile['publication'][$fp]='';}}
        $raw[$idx]=$profile;$settings['profiles_json']=wp_json_encode($raw,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);update_option(Configuration::OPTION_NAME,$this->config->sanitize($settings),false);$this->redirect($changed?'saved_profile_evidence_invalidated':'saved_profile');
    }
    private function requireAdmin(string $nonce):void{if(!current_user_can('manage_options')){wp_die('Forbidden','Forbidden',array('response'=>403));}check_admin_referer($nonce);}
    private function download(string $name,array $payload):void{if(function_exists('nocache_headers')){nocache_headers();}header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename="'.$name.'"');echo wp_json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
    private function checkRow(string $label,string $name,bool $checked):void{echo '<tr><th>'.esc_html($label).'</th><td><label><input type="checkbox" name="'.esc_attr($name).'" value="1" '.checked($checked,true,false).'/> Enabled</label></td></tr>';}
    private function textRow(string $label,string $name,string $value,bool $disabled=false):void{echo '<tr><th>'.esc_html($label).'</th><td><input class="regular-text code" name="'.esc_attr($name).'" value="'.esc_attr($value).'" '.($disabled?'disabled':'').'/></td></tr>';}
    private function areaRow(string $label,string $name,string $value):void{echo '<tr><th>'.esc_html($label).'</th><td><textarea class="large-text code" rows="5" name="'.esc_attr($name).'">'.esc_textarea($value).'</textarea></td></tr>';}
    private function evidenceRow(string $label,string $flag,string $idKey,bool $current,string $id):void{echo '<tr><th>'.esc_html($label).'</th><td><label><input type="checkbox" name="'.esc_attr($flag).'" value="1" '.checked($current,true,false).'/> Verified/current</label> <input class="regular-text code" name="'.esc_attr($idKey).'" value="'.esc_attr($id).'" placeholder="sha256:&lt;64hex&gt;"/></td></tr>';}
    private function lines($value,int $limit):array{$out=array();foreach(preg_split('/[\r\n]+/',(string)wp_unslash($value)) as $line){$line=trim((string)$line);if($line===''){continue;}$out[]=sanitize_text_field($line);if(count($out)>=$limit){break;}}return array_values(array_unique($out));}
    private function taxonomyLines($value):array{$out=array();foreach($this->lines($value,100) as $line){$parts=array_values(array_unique(array_filter(array_map('sanitize_key',preg_split('/[+;,]+/',$line)))));sort($parts,SORT_STRING);if($parts){$out[]=implode('+',$parts);}}return array_values(array_unique($out));}
    private function evidenceId($value):string{$v=preg_replace('/[^A-Za-z0-9:_\-.]/','',trim((string)wp_unslash($value)));return is_string($v)?substr($v,0,160):'';}
    private function validEvidence(string $id):bool{return (bool)preg_match('/^sha256:[a-fA-F0-9]{64}$/',$id);}
    private function int($value,int $min,int $max):int{return max($min,min($max,is_numeric($value)?(int)$value:$min));}
    private function redirect(string $notice,string $tab='profiles'):void{$url=add_query_arg(array('page'=>'etg-filter-seo-publication','tab'=>$tab,'etg_notice'=>$notice),admin_url('options-general.php'));wp_safe_redirect($url);exit;}
    private function noticeText(string $notice):string{$map=array('saved_profile'=>'Structured profile saved while Global bridge is OFF.','saved_profile_evidence_invalidated'=>'Authority changed; old verification was cleared and must be re-evidenced.','saved_publication_limits'=>'Bounded publication limits saved.','write_blocked_global_on'=>'Write blocked while Global bridge is ON.','profile_not_found'=>'Profile not found.','profile_registry_invalid'=>'Profile registry invalid; no write was performed.','stale_evidence_must_change'=>'Stale evidence cannot be rebound with the same SHA256 reference.','elementor_verification_evidence_id_required'=>'Elementor verification needs sha256:<64hex>.','provider_observation_evidence_id_required'=>'Provider verification needs sha256:<64hex>.','result_count_parity_evidence_id_required'=>'Count-parity verification needs sha256:<64hex>.');return (string)($map[$notice]??$notice);}
}
