<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class MAD4B_SCP_Execution_Receipt {
	const CONTRACT='mad4b.execution-receipt.v1';
	const SIGNATURE_STATE='crypto_profile_required';
	public static function build(array $claim,$result,array $terminal){
		if(empty($terminal['receipt_sha256'])||empty($terminal['receipt_id']))return new WP_Error('mad4b_execution_receipt_terminal_missing','Unified execution receipt requires a durable terminal receipt.');
		$stages=array(
			'preparation'=>self::stage(!empty($claim['context_receipt_sha256'])||!empty($claim['commit_guard_snapshot']['material_sha256']),!empty($claim['context_receipt_sha256'])?(string)$claim['context_receipt_sha256']:(isset($claim['commit_guard_snapshot']['material_sha256'])?(string)$claim['commit_guard_snapshot']['material_sha256']:''),'preparation_or_commit_guard'),
			'capability_descriptor'=>self::stage(!empty($claim['capability_descriptor_sha256']),isset($claim['capability_descriptor_sha256'])?(string)$claim['capability_descriptor_sha256']:'','capability_descriptor'),
			'policy_decision'=>self::stage(!empty($claim['policy_decision_sha256']),isset($claim['policy_decision_sha256'])?(string)$claim['policy_decision_sha256']:'','policy_decision'),
			'approval'=>!empty($claim['approval_required'])?self::stage(!empty($claim['approval_ticket_id']),isset($claim['approval_ticket_id'])?hash('sha256',(string)$claim['approval_ticket_id']):'','approval_ticket'):self::na('approval_not_required'),
			'idempotency_claim'=>self::optional($claim,array('idempotency_key','idempotency_claim_sha256'),'idempotency_not_required'),
			'operation_journal'=>self::optional($claim,array('operation_id','operation_key'),'operation_journal_not_required'),
			'provider_evidence'=>self::stage(true,isset($terminal['terminal_material_sha256'])?(string)$terminal['terminal_material_sha256']:(string)$terminal['receipt_sha256'],'terminal_material'),
			'readback_reconciliation'=>self::readback($claim,$result),
			'terminal_outcome'=>self::stage(true,(string)$terminal['receipt_sha256'],'terminal_receipt'),
		);
		foreach(array('preparation','capability_descriptor','policy_decision','provider_evidence','terminal_outcome') as $r)if('PASS'!==$stages[$r]['status'])return new WP_Error('mad4b_execution_receipt_required_stage_missing','Terminal success cannot be represented with a missing required execution stage.',array('stage'=>$r,'terminal_success'=>false));
		if(!empty($claim['approval_required'])&&'PASS'!==$stages['approval']['status'])return new WP_Error('mad4b_execution_receipt_approval_missing','Terminal success requires the exact approval stage.');
		$x=array('contract'=>self::CONTRACT,'receipt_version'=>1,'ability'=>isset($claim['ability'])?(string)$claim['ability']:'','provider_id'=>isset($claim['provider'])?sanitize_key((string)$claim['provider']):'core','request_id'=>isset($claim['request_id'])?substr((string)$claim['request_id'],0,100):'','target_fingerprint'=>isset($claim['target_fingerprint'])?(string)$claim['target_fingerprint']:'','resource_set_sha256'=>isset($claim['resource_set_sha256'])?(string)$claim['resource_set_sha256']:'','approval_impact_binding_sha256'=>isset($claim['approval_impact_binding_sha256'])?(string)$claim['approval_impact_binding_sha256']:'','stages'=>$stages,'terminal_receipt_id'=>(string)$terminal['receipt_id'],'terminal_receipt_sha256'=>(string)$terminal['receipt_sha256'],'signature_state'=>self::SIGNATURE_STATE,'signature_profile'=>'','signature'=>'','authorizing'=>false);
		$x['receipt_sha256']=self::digest($x);if(''===$x['receipt_sha256'])return new WP_Error('mad4b_execution_receipt_encode_failed','Unified execution receipt could not be canonically encoded.');$x['receipt_id']='execution-receipt:v1:'.$x['receipt_sha256'];return$x;
	}
	public static function verify(array $r){if(self::CONTRACT!==(isset($r['contract'])?(string)$r['contract']:''))return new WP_Error('mad4b_execution_receipt_contract_invalid','Execution receipt contract is invalid.');$e=isset($r['receipt_sha256'])?strtolower((string)$r['receipt_sha256']):'';$m=$r;unset($m['receipt_sha256'],$m['receipt_id']);$a=self::digest($m);if(1!==preg_match('/^[a-f0-9]{64}$/D',$e)||!hash_equals($e,$a))return new WP_Error('mad4b_execution_receipt_integrity_invalid','Execution receipt integrity verification failed.');foreach(array('preparation','capability_descriptor','policy_decision','provider_evidence','terminal_outcome') as $s)if(empty($r['stages'][$s])||'PASS'!==(string)$r['stages'][$s]['status'])return new WP_Error('mad4b_execution_receipt_required_stage_missing','Execution receipt is missing a required successful stage.',array('stage'=>$s));return array('contract'=>'mad4b.execution-receipt-verification.v1','valid'=>true,'receipt_sha256'=>$e,'signature_state'=>isset($r['signature_state'])?(string)$r['signature_state']:'','authorizing'=>false);}
	public static function export(array $r){$v=self::verify($r);return is_wp_error($v)?$v:array('contract'=>'mad4b.execution-receipt-export.v1','receipt'=>$r,'verification'=>$v,'authorizing'=>false);}
	private static function stage($ok,$sha,$type){return array('status'=>$ok?'PASS':'MISSING','evidence_type'=>$type,'evidence_sha256'=>(string)$sha,'reason_code'=>$ok?'evidence_present':'required_evidence_missing');}
	private static function na($r){return array('status'=>'NOT_REQUIRED','evidence_type'=>'none','evidence_sha256'=>'','reason_code'=>$r);}
	private static function optional(array $c,array $ks,$reason){foreach($ks as $k)if(!empty($c[$k]))return self::stage(true,preg_match('/^[a-f0-9]{64}$/D',strtolower((string)$c[$k]))?strtolower((string)$c[$k]):hash('sha256',(string)$c[$k]),$k);return self::na($reason);}
	private static function readback(array $c,$r){$x=array();foreach(array('postcondition_recovery','postcondition_observation','reconciliation_ref') as $k)if(!empty($c[$k]))$x[$k]=$c[$k];if(is_array($r))foreach(array('postcondition','readback','reconciliation_ref') as $k)if(!empty($r[$k]))$x[$k]=$r[$k];return empty($x)?self::na('no_reconciliation_required_for_terminal_success_path'):self::stage(true,self::digest($x),'readback_or_reconciliation');}
	private static function digest($v){$v=self::canon($v);$j=function_exists('wp_json_encode')?wp_json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);return is_string($j)?hash('sha256',$j):'';}
	private static function canon($v){if(!is_array($v))return$v;$k=array_keys($v);$l=empty($v)||$k===range(0,count($v)-1);if($l)return array_map(array(__CLASS__,'canon'),$v);ksort($v,SORT_STRING);foreach($v as $kk=>$vv)$v[$kk]=self::canon($vv);return$v;}
}
