<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class MAD4B_SCP_Semantic_Intent_Router {
	const CONTRACT='mad4b.semantic-intent-routing.v1';
	public static function boot(){if(function_exists('add_action'))add_action('wp_abilities_api_init',array(__CLASS__,'register_ability'),34);}
	public static function register_ability(){if(!function_exists('wp_register_ability')||(function_exists('wp_has_ability')&&wp_has_ability('mad4b/semantic-intent-route')))return;wp_register_ability('mad4b/semantic-intent-route',array('label'=>'Semantic Intent Route','description'=>'Non-authorizing semantic intent routing across certified provider capabilities.','category'=>'mad4b-read','execute_callback'=>array(__CLASS__,'route'),'permission_callback'=>array('MAD4B_SCP_Policy','can_read'),'input_schema'=>array('type'=>'object','properties'=>array('intent'=>array('type'=>'string','maxLength'=>96),'target_kind'=>array('type'=>'string','maxLength'=>64),'required_traits'=>array('type'=>'object','additionalProperties'=>true),'preferred_provider'=>array('type'=>'string','maxLength'=>64),'release_ring'=>array('type'=>'string','maxLength'=>32),'require_certified'=>array('type'=>'boolean')),'required'=>array('intent'),'additionalProperties'=>false),'output_schema'=>array('type'=>'object','additionalProperties'=>true),'meta'=>array('mcp'=>array('public'=>false,'type'=>'tool','surface'=>'read'),'annotations'=>array('readonly'=>true,'destructive'=>false,'idempotent'=>true))));}
	public static function route($input=array()){
		$input=is_array($input)?$input:array();$intent=strtolower(trim(isset($input['intent'])?(string)$input['intent']:''));$intent=preg_replace('/[^a-z0-9._-]/','',$intent);if(''===$intent)return new WP_Error('mad4b_semantic_intent_required','Semantic intent is required.');
		$target=sanitize_key(isset($input['target_kind'])?(string)$input['target_kind']:'');$required=isset($input['required_traits'])&&is_array($input['required_traits'])?$input['required_traits']:array();$preferred=sanitize_key(isset($input['preferred_provider'])?(string)$input['preferred_provider']:'');$ring=sanitize_key(isset($input['release_ring'])?(string)$input['release_ring']:'');$cert=!array_key_exists('require_certified',$input)||!empty($input['require_certified']);
		if(!class_exists('MAD4B_SCP_Operation_Registry'))return new WP_Error('mad4b_semantic_operation_registry_unavailable','Operation Registry is unavailable.');$st=MAD4B_SCP_Operation_Registry::status();if(is_wp_error($st))return$st;$matches=array();
		foreach(isset($st['operations'])&&is_array($st['operations'])?$st['operations']:array() as $row){if(!is_array($row))continue;$id=isset($row['id'])?strtolower((string)$row['id']):'';$kind=isset($row['target_kind'])?sanitize_key((string)$row['target_kind']):'';$supports=isset($row['supports'])&&is_array($row['supports'])?array_map('sanitize_key',$row['supports']):array();if($id!==$intent&&!in_array(sanitize_key($intent),$supports,true))continue;if(''!==$target&&''!==$kind&&$target!==$kind)continue;$matches[]=$row;}
		$idx=self::index();$candidates=array();
		foreach($matches as $row){$executor=isset($row['executor'])?(string)$row['executor']:'';$pairs='exact_executor_from_plan'===$executor?array():($idx[$executor]??array());if(empty($pairs)){$candidates[]=array('operation_id'=>(string)$row['id'],'planner'=>(string)$row['planner'],'executor'=>$executor,'provider_id'=>'','capability_id'=>'','eligible'=>false,'confidence'=>0.25,'reason_code'=>'exact_capability_resolution_deferred_or_unmapped','human_review_required'=>true,'evidence_refs'=>array(),'authorizing'=>false);continue;}foreach($pairs as $pair){$res=class_exists('MAD4B_SCP_Capability_Traits')?MAD4B_SCP_Capability_Traits::resolve(array('capability_id'=>$pair['capability_id'],'required_traits'=>$required,'release_ring'=>$ring,'require_certified'=>$cert,'preferred_provider'=>''!==$preferred?$preferred:$pair['provider_id'])):array('eligible'=>array());$ok=false;$ev=array();if(is_array($res))foreach(isset($res['eligible'])&&is_array($res['eligible'])?$res['eligible']:array() as $er){if((string)$er['provider_id']===(string)$pair['provider_id']){$ok=true;$ev[]=array('profile_fingerprint'=>(string)$er['profile_fingerprint'],'certification_fingerprint'=>(string)$er['certification_fingerprint'],'descriptor_generation_sha256'=>isset($er['descriptor_generation_sha256'])?(string)$er['descriptor_generation_sha256']:'');break;}}$candidates[]=array('operation_id'=>(string)$row['id'],'planner'=>(string)$row['planner'],'executor'=>$executor,'provider_id'=>$pair['provider_id'],'capability_id'=>$pair['capability_id'],'eligible'=>$ok,'confidence'=>$ok?0.95:0.0,'reason_code'=>$ok?'semantic_traits_and_certification_match':'semantic_traits_or_certification_rejected','human_review_required'=>!$ok,'evidence_refs'=>$ev,'authorizing'=>false);}}
		$eligible=array_values(array_filter($candidates,static function($r){return!empty($r['eligible']);}));$selected=1===count($eligible)?$eligible[0]:array();$amb=count($eligible)>1;
		return array('contract'=>self::CONTRACT,'intent'=>$intent,'target_kind'=>$target,'required_traits'=>$required,'candidates'=>$candidates,'eligible_count'=>count($eligible),'selected'=>$selected,'ambiguous'=>$amb,'human_review_required'=>$amb||empty($selected),'confidence'=>!empty($selected)?(float)$selected['confidence']:0.0,'mutation_performed'=>false,'authority_created'=>false,'authorizing'=>false,'next_action'=>!empty($selected)?'execute_exact_planner_then_revalidate_authority':'human_review_or_exact_operation_required');
	}
	private static function index(){ $p=defined('MAD4B_SCP_DIR')?MAD4B_SCP_DIR.'config/provider-capability-contracts.json':'';if(''===$p||!is_readable($p))return array();$d=json_decode((string)file_get_contents($p),true);$o=array();foreach(isset($d['providers'])&&is_array($d['providers'])?$d['providers']:array() as $prov=>$pr)foreach(isset($pr['capabilities'])&&is_array($pr['capabilities'])?$pr['capabilities']:array() as $cid=>$cap)foreach(isset($cap['abilities'])&&is_array($cap['abilities'])?$cap['abilities']:array() as $a){$a=(string)$a;if(''!==$a)$o[$a][]=array('provider_id'=>sanitize_key((string)$prov),'capability_id'=>(string)$cid);}return$o;}
}
MAD4B_SCP_Semantic_Intent_Router::boot();
