<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class MAD4B_SCP_Operating_Model {
	const CONTRACT = 'mad4b.operating-model-contracts.v1';
	const PLAN_CONTRACT = 'mad4b.operation-plan.v1';
	const COMPILER_CONTRACT = 'mad4b.workflow-compiler.v1';
	const CONFIG = 'config/operating-model-contracts.json';
	const MAX_CANONICAL_BYTES = 262144;
	const MAX_OPERATIONS = 100;
	const MAX_BINDINGS = 500;
	const MAX_EVIDENCE_NODES = 128;
	private static $config = null;

	public static function boot() {
		add_action( 'wp_abilities_api_categories_init', array( __CLASS__, 'register_category' ), 24 );
		add_action( 'wp_abilities_api_init', array( __CLASS__, 'register_abilities' ), 33 );
	}
	public static function register_category() {
		if ( function_exists( 'wp_register_ability_category' ) ) wp_register_ability_category( 'mad4b-operating-model', array( 'label' => 'MAD4B Operating Model', 'description' => 'Read-only desired-state, planning, evidence, invariant and workflow compilation primitives.' ) );
	}
	public static function register_abilities() {
		if ( ! function_exists( 'wp_register_ability' ) ) return;
		self::register_read( 'mad4b/operating-model-status', 'Operating Model Status', array( __CLASS__, 'status' ) );
		self::register_read( 'mad4b/semantic-identity-map', 'Resolve Semantic Identity Map', array( __CLASS__, 'semantic_identity_map' ), self::semantic_identity_schema() );
		self::register_read( 'mad4b/site-feature-bundle-validate', 'Validate Site Feature Bundle', array( __CLASS__, 'site_feature_bundle_validate' ), self::bundle_schema() );
		self::register_read( 'mad4b/state-diff', 'Compute Desired/Observed State Diff', array( __CLASS__, 'state_diff' ), self::state_diff_schema() );
		self::register_read( 'mad4b/operation-plan', 'Build Immutable Operation Plan', array( __CLASS__, 'operation_plan' ), self::operation_plan_schema() );
		self::register_read( 'mad4b/evidence-invalidation-plan', 'Plan Evidence Dependency Invalidation', array( __CLASS__, 'evidence_invalidation_plan' ), self::evidence_schema() );
		self::register_read( 'mad4b/invariant-evaluate', 'Evaluate Operating Model Invariants', array( __CLASS__, 'invariant_evaluate' ), self::facts_schema() );
		self::register_read( 'mad4b/candidate-state', 'Resolve Candidate State Machine', array( __CLASS__, 'candidate_state' ), self::facts_schema() );
		self::register_read( 'mad4b/workflow-compile', 'Compile Provider-neutral Workflow DAG', array( __CLASS__, 'workflow_compile' ), self::workflow_schema() );
	}
	private static function register_read( $name, $label, $callback, $input_schema = null ) {
		if ( function_exists( 'wp_has_ability' ) && wp_has_ability( $name ) ) return;
		$args = array(
			'label'=>$label,'description'=>$label . '. Deterministic, read-only and non-authorizing.','category'=>'mad4b-operating-model','execute_callback'=>$callback,'permission_callback'=>array('MAD4B_SCP_Policy','can_read'),
			'output_schema'=>array('type'=>'object','additionalProperties'=>true),
			'meta'=>array('public'=>false,'show_in_rest'=>false,'mcp'=>array('public'=>false,'type'=>'tool','surface'=>'read'),'annotations'=>array('readonly'=>true,'destructive'=>false,'idempotent'=>true)),
		);
		if ( is_array( $input_schema ) ) $args['input_schema']=$input_schema;
		wp_register_ability( $name, $args );
	}
	public static function status() {
		$c=self::config(); if(is_wp_error($c)) return $c;
		return array('contract'=>self::CONTRACT,'config_sha256'=>self::stable_digest($c),'site_neutral'=>true,'semantic_identity'=>$c['semantic_identity'],'ownership_model'=>$c['ownership_model'],'state_model'=>$c['state_model'],'operation_plan'=>$c['operation_plan'],'evidence_graph'=>array('contract'=>$c['evidence_graph']['contract'],'node_count'=>count($c['evidence_graph']['nodes'])),'candidate_state_machine'=>$c['candidate_state_machine'],'workflow_compiler'=>$c['workflow_compiler'],'workflow_provider_bridge'=>$c['workflow_provider_bridge'],'mutation_performed'=>false,'authority_created'=>false,'production_authority_created'=>false);
	}
	public static function semantic_identity_map( $input=array() ) {
		$bindings=is_array($input)&&isset($input['bindings'])&&is_array($input['bindings'])?array_slice($input['bindings'],0,self::MAX_BINDINGS):array(); $map=array();$dup=array();$invalid=array();
		foreach($bindings as $i=>$b){if(!is_array($b)){$invalid[]=(int)$i;continue;}$role=isset($b['role'])?strtolower(trim((string)$b['role'])):'';$provider=isset($b['provider'])?sanitize_key((string)$b['provider']):'';$type=isset($b['target_type'])?sanitize_key((string)$b['target_type']):'';$pid=isset($b['physical_id'])?trim((string)$b['physical_id']):'';if(!preg_match('/^[a-z0-9][a-z0-9._-]{0,127}$/',$role)||''===$provider||''===$type||''===$pid||strlen($pid)>191){$invalid[]=(int)$i;continue;}if(isset($map[$role])){$dup[]=$role;continue;}$map[$role]=array('role'=>$role,'provider'=>$provider,'target_type'=>$type,'physical_id'=>$pid);}
		ksort($map,SORT_STRING);$dup=array_values(array_unique($dup));sort($dup,SORT_STRING);
		return array('contract'=>'mad4b.semantic-identity-map.v1','bindings'=>$map,'binding_count'=>count($map),'duplicate_roles'=>$dup,'invalid_indexes'=>array_values(array_unique($invalid)),'valid'=>empty($dup)&&empty($invalid)&&count($bindings)===count($map),'map_sha256'=>self::stable_digest($map),'physical_identity_usage'=>'optimistic_locking_only','non_authorizing'=>true,'mutation_performed'=>false);
	}
	public static function site_feature_bundle_validate($input=array()){
		$bundle=is_array($input)&&isset($input['bundle'])&&is_array($input['bundle'])?$input['bundle']:array();$c=self::config();if(is_wp_error($c))return $c;$bounded=self::bounded_canonical($bundle);if(is_wp_error($bounded))return $bounded;$allowed=array_values((array)$c['site_feature_bundle']['allowed_sections']);$unknown=array_values(array_diff(array_keys($bundle),$allowed));sort($unknown,SORT_STRING);
		return array('contract'=>'mad4b.site-feature-bundle-validation.v1','bundle_contract'=>$c['site_feature_bundle']['contract'],'valid'=>empty($unknown),'unknown_sections'=>$unknown,'sections'=>array_values(array_intersect($allowed,array_keys($bundle))),'bundle_sha256'=>self::stable_digest($bounded),'configuration_only'=>true,'non_authorizing'=>true,'mutation_performed'=>false);
	}
	public static function state_diff($input=array()){
		$d=is_array($input)&&isset($input['desired'])&&is_array($input['desired'])?$input['desired']:array();$o=is_array($input)&&isset($input['observed'])&&is_array($input['observed'])?$input['observed']:array();$d=self::bounded_canonical($d);if(is_wp_error($d))return $d;$o=self::bounded_canonical($o);if(is_wp_error($o))return $o;$changes=array();self::diff_values($d,$o,'',$changes);
		return array('contract'=>'mad4b.desired-observed-diff.v1','desired_state_sha256'=>self::stable_digest($d),'observed_state_sha256'=>self::stable_digest($o),'change_count'=>count($changes),'converged'=>empty($changes),'changes'=>array_slice($changes,0,1000),'non_authorizing'=>true,'mutation_performed'=>false);
	}
	public static function operation_plan($input=array()){
		$input=is_array($input)?$input:array();$c=self::config();if(is_wp_error($c))return $c;$d=isset($input['desired_state'])&&is_array($input['desired_state'])?self::bounded_canonical($input['desired_state']):array();if(is_wp_error($d))return $d;$o=isset($input['observed_state'])&&is_array($input['observed_state'])?self::bounded_canonical($input['observed_state']):array();if(is_wp_error($o))return $o;$raw=isset($input['operations'])&&is_array($input['operations'])?array_slice($input['operations'],0,self::MAX_OPERATIONS):array();$ops=array();$seen=array();$targets=array();$providers=array();$reversible=array();$destructive=array();
		foreach($raw as $i=>$r){$op=self::normalize_operation($r,$i);if(is_wp_error($op))return $op;if(isset($seen[$op['id']]))return new WP_Error('mad4b_operation_plan_duplicate_step','Operation plan contains a duplicate operation id.');$seen[$op['id']]=true;$ops[]=$op;$targets[]=$op['target'];$providers[]=$op['provider'];if($op['reversible'])$reversible[]=$op['id'];if($op['destructive'])$destructive[]=$op['id'];}
		$valid=self::validate_dependencies($ops);if(is_wp_error($valid))return $valid;$diff=array();self::diff_values($d,$o,'',$diff);$deps=isset($input['evidence_dependencies'])&&is_array($input['evidence_dependencies'])?self::clean_ids($input['evidence_dependencies'],self::MAX_EVIDENCE_NODES):array();$providers=array_values(array_unique(array_filter($providers)));sort($providers,SORT_STRING);$targets=array_values(array_unique(array_filter($targets)));sort($targets,SORT_STRING);
		$plan=array('contract'=>self::PLAN_CONTRACT,'site_uuid'=>isset($input['site_uuid'])?strtolower(trim((string)$input['site_uuid'])):'','environment'=>isset($input['environment'])?sanitize_key((string)$input['environment']):'','candidate_sha'=>isset($input['candidate_sha'])?strtolower(trim((string)$input['candidate_sha'])):'','build_fingerprint'=>isset($input['build_fingerprint'])?strtolower(trim((string)$input['build_fingerprint'])):'','desired_state_digest'=>self::stable_digest($d),'observed_state_digest'=>self::stable_digest($o),'drift_count'=>count($diff),'operations'=>$ops,'operation_count'=>count($ops),'affected_objects'=>$targets,'provider_bindings'=>$providers,'reversible_operations'=>$reversible,'destructive_operations'=>$destructive,'cross_provider'=>count($providers)>1,'evidence_dependencies'=>$deps,'approval_binding'=>$c['operation_plan']['approval_binding'],'non_authorizing'=>true,'mutation_performed'=>false,'authority_created'=>false);$plan['plan_sha256']=self::stable_digest($plan);return $plan;
	}
	public static function evidence_invalidation_plan($input=array()){
		$c=self::config();if(is_wp_error($c))return $c;$nodes=(array)$c['evidence_graph']['nodes'];$changed=self::clean_ids(is_array($input)&&isset($input['changed'])&&is_array($input['changed'])?$input['changed']:array(),self::MAX_EVIDENCE_NODES);$unknown=array_values(array_diff($changed,array_keys($nodes)));sort($unknown,SORT_STRING);$valid=array_values(array_intersect($changed,array_keys($nodes)));$reverse=array();foreach($nodes as $n=>$deps)foreach((array)$deps as $dep)$reverse[$dep][]=$n;$q=$valid;$inv=array_fill_keys($valid,true);while($q){$cur=array_shift($q);foreach((array)($reverse[$cur]??array())as$dependent){if(isset($inv[$dependent]))continue;$inv[$dependent]=true;$q[]=$dependent;}}$result=array_keys($inv);sort($result,SORT_STRING);
		return array('contract'=>'mad4b.evidence-invalidation-plan.v1','graph_contract'=>$c['evidence_graph']['contract'],'changed'=>$valid,'unknown_nodes'=>$unknown,'invalidate'=>$result,'invalidation_count'=>count($result),'non_authorizing'=>true,'mutation_performed'=>false);
	}
	public static function invariant_evaluate($input=array()){
		$facts=is_array($input)&&isset($input['facts'])&&is_array($input['facts'])?$input['facts']:array();$c=self::config();if(is_wp_error($c))return $c;$violations=array();$evaluated=array();foreach((array)$c['invariants']as$inv){$id=sanitize_key((string)($inv['id']??''));if(''===$id)continue;$triggered=self::facts_match($facts,(array)($inv['when_all']??array()));$passed=!$triggered||self::facts_match($facts,(array)($inv['require_all']??array()));$evaluated[]=array('id'=>$id,'triggered'=>$triggered,'passed'=>$passed);if(!$passed)$violations[]=$id;}return array('contract'=>'mad4b.invariant-evaluation.v1','valid'=>empty($violations),'violations'=>$violations,'evaluated'=>$evaluated,'facts_sha256'=>self::stable_digest(self::canonicalize($facts)),'non_authorizing'=>true,'mutation_performed'=>false);
	}
	public static function candidate_state($input=array()){
		$facts=is_array($input)&&isset($input['facts'])&&is_array($input['facts'])?$input['facts']:array();$c=self::config();if(is_wp_error($c))return $c;$m=$c['candidate_state_machine'];$current='UNBOUND';$next='';$blockers=array();foreach((array)$m['transitions']as$t){if($current!==(string)$t['from'])continue;$missing=array();foreach((array)$t['requires']as$fact)if(true!==($facts[$fact]??false))$missing[]=(string)$fact;if($missing){$next=(string)$t['to'];$blockers=$missing;break;}$current=(string)$t['to'];}return array('contract'=>$m['contract'],'state'=>$current,'next_state'=>$next,'blockers'=>$blockers,'write_runtime_dependency_is_not_bootstrap_precondition'=>true,'non_authorizing'=>true,'mutation_performed'=>false);
	}
	public static function workflow_compile($input=array()){
		$input=is_array($input)?$input:array();$c=self::config();if(is_wp_error($c))return $c;$id=isset($input['workflow_id'])?sanitize_key((string)$input['workflow_id']):'';if(''===$id)return new WP_Error('mad4b_workflow_compile_id_required','workflow_id is required.');$raw=isset($input['steps'])&&is_array($input['steps'])?array_slice($input['steps'],0,self::MAX_OPERATIONS):array();$steps=array();$seen=array();$mechanics=array_values((array)$c['workflow_compiler']['provider_mechanics']);foreach($raw as$i=>$r){$step=self::normalize_operation($r,$i);if(is_wp_error($step))return $step;if(isset($seen[$step['id']]))return new WP_Error('mad4b_workflow_compile_duplicate_step','Workflow contains a duplicate step id.');$seen[$step['id']]=true;$uses=in_array($step['mechanic'],$mechanics,true);$step['executor']=$uses?'workflow_provider':'mad4b_direct';$step['workflow_provider_authority']=false;$step['mutation_executor']=$step['mutation']?'mad4b_capability':'none';$steps[]=$step;}$valid=self::validate_dependencies($steps);if(is_wp_error($valid))return $valid;$order=self::topological_order($steps);if(is_wp_error($order))return $order;$result=array('contract'=>self::COMPILER_CONTRACT,'workflow_id'=>$id,'steps'=>$steps,'execution_order'=>$order,'source_of_truth'=>$c['workflow_compiler']['source_of_truth'],'mutation_executor'=>$c['workflow_compiler']['mutation_executor'],'workflow_provider_role'=>$c['workflow_compiler']['workflow_provider_role'],'non_authorizing'=>true,'mutation_performed'=>false,'authority_created'=>false);$result['workflow_sha256']=self::stable_digest($result);return $result;
	}
	private static function normalize_operation($raw,$index){if(!is_array($raw))return new WP_Error('mad4b_operation_plan_step_invalid','Every operation must be an object.');$id=isset($raw['id'])?sanitize_key((string)$raw['id']):'step-'.((int)$index+1);$cap=isset($raw['capability'])?trim((string)$raw['capability']):'';$provider=isset($raw['provider'])?sanitize_key((string)$raw['provider']):'';$target=isset($raw['target'])?trim((string)$raw['target']):'';$mechanic=isset($raw['mechanic'])?sanitize_key((string)$raw['mechanic']):'direct';if(''===$id||''===$cap||strlen($cap)>160||''===$provider||''===$target||strlen($target)>191)return new WP_Error('mad4b_operation_plan_step_identity_invalid','Operation id, capability, provider and target are required.');$deps=self::clean_ids(isset($raw['depends_on'])&&is_array($raw['depends_on'])?$raw['depends_on']:array(),self::MAX_OPERATIONS);$expected=isset($raw['expected_state_sha256'])?strtolower(trim((string)$raw['expected_state_sha256'])):'';if(''!==$expected&&!preg_match('/^[a-f0-9]{64}$/',$expected))return new WP_Error('mad4b_operation_plan_expected_state_invalid','expected_state_sha256 must be an exact SHA-256 digest.');return array('id'=>$id,'capability'=>$cap,'provider'=>$provider,'target'=>$target,'depends_on'=>$deps,'reversible'=>true===($raw['reversible']??false),'destructive'=>true===($raw['destructive']??false),'mutation'=>true===($raw['mutation']??false),'mechanic'=>$mechanic,'expected_state_sha256'=>$expected);}
	private static function validate_dependencies(array$steps){$ids=array();foreach($steps as$s)$ids[$s['id']]=true;foreach($steps as$s)foreach($s['depends_on']as$dep)if(!isset($ids[$dep]))return new WP_Error('mad4b_operation_plan_dependency_missing','Operation dependency references an unknown step.',array('step'=>$s['id'],'dependency'=>$dep));$order=self::topological_order($steps);return is_wp_error($order)?$order:true;}
	private static function topological_order(array$steps){$ind=array();$edges=array();foreach($steps as$s){$ind[$s['id']]=0;$edges[$s['id']]=array();}foreach($steps as$s)foreach($s['depends_on']as$dep){$edges[$dep][]=$s['id'];$ind[$s['id']]++;}$q=array();foreach($ind as$id=>$degree)if(0===$degree)$q[]=$id;sort($q,SORT_STRING);$order=array();while($q){$id=array_shift($q);$order[]=$id;foreach($edges[$id]as$next){$ind[$next]--;if(0===$ind[$next]){$q[]=$next;sort($q,SORT_STRING);}}}return count($order)===count($steps)?$order:new WP_Error('mad4b_workflow_compile_cycle','Workflow dependencies contain a cycle.');}
	private static function diff_values($d,$o,$path,array&$changes){if(is_array($d)&&is_array($o)){$keys=array_values(array_unique(array_merge(array_keys($d),array_keys($o))));usort($keys,static function($a,$b){return strcmp((string)$a,(string)$b);});foreach($keys as$key){$next=''===$path?(string)$key:$path.'.'.(string)$key;$hd=array_key_exists($key,$d);$ho=array_key_exists($key,$o);if(!$hd||!$ho){$changes[]=array('path'=>$next,'change'=>$hd?'missing_observed':'unexpected_observed','desired_sha256'=>$hd?self::stable_digest($d[$key]):'','observed_sha256'=>$ho?self::stable_digest($o[$key]):'');continue;}self::diff_values($d[$key],$o[$key],$next,$changes);}return;}if(self::stable_digest($d)!==self::stable_digest($o))$changes[]=array('path'=>$path,'change'=>'value_mismatch','desired_sha256'=>self::stable_digest($d),'observed_sha256'=>self::stable_digest($o));}
	private static function facts_match(array$facts,array$required){foreach($required as$k=>$v)if(!array_key_exists($k,$facts)||$facts[$k]!==$v)return false;return true;}
	private static function clean_ids(array$items,$limit){$r=array();foreach(array_slice($items,0,(int)$limit)as$item){$id=sanitize_key((string)$item);if(''!==$id)$r[]=$id;}$r=array_values(array_unique($r));sort($r,SORT_STRING);return$r;}
	private static function bounded_canonical($v){$c=self::canonicalize($v);$j=wp_json_encode($c,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);if(!is_string($j))return new WP_Error('mad4b_operating_model_encode_failed','Operating-model value could not be encoded.');if(strlen($j)>self::MAX_CANONICAL_BYTES)return new WP_Error('mad4b_operating_model_value_too_large','Operating-model value exceeds the bounded canonical size.');return$c;}
	private static function stable_digest($v){$c=self::canonicalize($v);$j=function_exists('wp_json_encode')?wp_json_encode($c,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):json_encode($c,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);return is_string($j)?hash('sha256',$j):'';}
	private static function canonicalize($v){if(!is_array($v))return$v;$list=empty($v)||array_keys($v)===range(0,count($v)-1);if($list){$o=array();foreach($v as$item)$o[]=self::canonicalize($item);return$o;}ksort($v,SORT_STRING);foreach($v as$k=>$item)$v[$k]=self::canonicalize($item);return$v;}
	private static function config(){if(is_array(self::$config))return self::$config;$path=MAD4B_SCP_DIR.self::CONFIG;if(!is_readable($path))return new WP_Error('mad4b_operating_model_config_missing','Operating-model contract configuration is unavailable.');$raw=file_get_contents($path);$c=false===$raw?null:json_decode($raw,true);if(!is_array($c)||self::CONTRACT!==(string)($c['contract']??'')||true!==($c['site_neutral']??false))return new WP_Error('mad4b_operating_model_config_invalid','Operating-model contract configuration is invalid.');self::$config=$c;return self::$config;}
	private static function semantic_identity_schema(){return array('type'=>'object','properties'=>array('bindings'=>array('type'=>'array','maxItems'=>self::MAX_BINDINGS,'items'=>array('type'=>'object','additionalProperties'=>true))),'required'=>array('bindings'),'additionalProperties'=>false);}
	private static function bundle_schema(){return array('type'=>'object','properties'=>array('bundle'=>array('type'=>'object','additionalProperties'=>true)),'required'=>array('bundle'),'additionalProperties'=>false);}
	private static function state_diff_schema(){return array('type'=>'object','properties'=>array('desired'=>array('type'=>'object','additionalProperties'=>true),'observed'=>array('type'=>'object','additionalProperties'=>true)),'required'=>array('desired','observed'),'additionalProperties'=>false);}
	private static function operation_plan_schema(){return array('type'=>'object','properties'=>array('site_uuid'=>array('type'=>'string','maxLength'=>64),'environment'=>array('type'=>'string','enum'=>array('local','development','staging','production')),'candidate_sha'=>array('type'=>'string','maxLength'=>40),'build_fingerprint'=>array('type'=>'string','maxLength'=>64),'desired_state'=>array('type'=>'object','additionalProperties'=>true),'observed_state'=>array('type'=>'object','additionalProperties'=>true),'operations'=>array('type'=>'array','maxItems'=>self::MAX_OPERATIONS,'items'=>array('type'=>'object','additionalProperties'=>true)),'evidence_dependencies'=>array('type'=>'array','maxItems'=>self::MAX_EVIDENCE_NODES,'items'=>array('type'=>'string','maxLength'=>128))),'required'=>array('environment','desired_state','observed_state','operations'),'additionalProperties'=>false);}
	private static function evidence_schema(){return array('type'=>'object','properties'=>array('changed'=>array('type'=>'array','maxItems'=>self::MAX_EVIDENCE_NODES,'items'=>array('type'=>'string','maxLength'=>128))),'required'=>array('changed'),'additionalProperties'=>false);}
	private static function facts_schema(){return array('type'=>'object','properties'=>array('facts'=>array('type'=>'object','additionalProperties'=>array('type'=>'boolean'))),'required'=>array('facts'),'additionalProperties'=>false);}
	private static function workflow_schema(){return array('type'=>'object','properties'=>array('workflow_id'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'steps'=>array('type'=>'array','maxItems'=>self::MAX_OPERATIONS,'items'=>array('type'=>'object','additionalProperties'=>true))),'required'=>array('workflow_id','steps'),'additionalProperties'=>false);}
}
