<?php
/** Typed inert forms compiled exclusively from current native contracts. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class MAD4B_SCP_CSO_Forms {
	const PURPOSE = 'mad4b.cso01.form.v1';
	const TTL = 900;
	const MAX_FIELDS = 128;
	const MAX_DEPTH = 4;
	const MAX_ITEMS = 128;
	const MAX_TEXT = 4096;

	public static function schema( $name, $target = array() ) {
		if ( ! MAD4B_SCP_CSO_Scope::enabled( 'forms' ) ) return self::deny( 'disabled' );
		if ( ! is_string( $name ) || ! class_exists( 'MAD4B_SCP_Canonicalization' ) || ! self::map( $target ) ) return self::deny( 'invalid_form' );
		$canonical = MAD4B_SCP_Canonicalization::ability_name( $name ); if ( is_wp_error( $canonical ) || $canonical !== $name ) return self::deny( 'invalid_form' );
		$scope = MAD4B_SCP_CSO_Scope::current(); if ( is_wp_error( $scope ) ) return $scope;
		$d = MAD4B_SCP_CSO_Registry::describe( $name, $target ); if ( is_wp_error( $d ) ) return $d;
		$fields = self::compile( $d ); if ( is_wp_error( $fields ) ) return $fields;
		$valid = self::check( $d, $target, true ); if ( is_wp_error( $valid ) ) return $valid;
		if ( ! self::target_safe( $target, $d['input_schema'], $d, '' ) || true !== MAD4B_SCP_CSO_Scope::safe_data( $target ) ) return self::deny( 'unsafe_target' );
		try { $id = bin2hex( random_bytes( 16 ) ); } catch ( Throwable $e ) { return self::deny( 'unavailable' ); }
		$fingerprint = self::fingerprint( $d ); if ( is_wp_error( $fingerprint ) ) return $fingerprint;
		$material = array( 'form_id' => $id, 'ability_name' => $name, 'target' => $target, 'scope' => $scope, 'descriptor_sha256' => $fingerprint, 'expires_at' => self::now() + self::TTL );
		$sealed = MAD4B_SCP_CSO_Scope::seal( $material, self::PURPOSE ); if ( is_wp_error( $sealed ) ) return $sealed;
		foreach ( $fields as &$field ) $field['locked'] = array_key_exists( $field['field_id'], $target ); unset( $field );
		return array( 'contract' => 'mad4b.cso01.form-descriptor.v1', 'status' => 'PROPOSED', 'form_id' => $id, 'site_uuid' => $scope['site_uuid'], 'environment' => $scope['environment'], 'source_sha' => $scope['source_sha'], 'schema_digest' => $d['schema_sha256'], 'adapter_digest' => $d['adapter_sha256'], 'expires_at' => gmdate( 'c', $material['expires_at'] ), 'locale' => $scope['locale'], 'fields' => $fields, 'sealed_form' => $sealed, 'non_authorizing' => true, 'execution_allowed' => false );
	}

	/** Internal services reconstruct the descriptor. A client never supplies a trusted schema. */
	public static function inspect( $sealed ) {
		if ( ! MAD4B_SCP_CSO_Scope::enabled( 'forms' ) ) return self::deny( 'disabled' );
		if ( ! is_array( $sealed ) ) return self::deny( 'invalid_form' );
		$m = MAD4B_SCP_CSO_Scope::unseal( $sealed, self::PURPOSE ); if ( is_wp_error( $m ) ) return $m;
		if ( ! is_array( $m ) || array_diff( array_keys( $m ), array( 'form_id','ability_name','target','scope','descriptor_sha256','expires_at' ) ) || ! isset( $m['form_id'],$m['ability_name'],$m['target'],$m['scope'],$m['descriptor_sha256'],$m['expires_at'] ) || ! is_int( $m['expires_at'] ) || self::now() >= $m['expires_at'] || $m['expires_at'] > self::now() + self::TTL || ! self::map( $m['target'] ) ) return self::deny( 'stale_form' );
		$current = MAD4B_SCP_CSO_Scope::assert_current( $m['scope'] ); if ( is_wp_error( $current ) || false === $current ) return self::deny( 'stale_form' );
		$d = MAD4B_SCP_CSO_Registry::describe( $m['ability_name'], $m['target'] ); if ( is_wp_error( $d ) ) return $d;
		$fields = self::compile( $d ); if ( is_wp_error( $fields ) ) return $fields;
		$fingerprint = self::fingerprint( $d ); if ( is_wp_error( $fingerprint ) || ! is_string( $m['descriptor_sha256'] ) || ! hash_equals( $m['descriptor_sha256'], $fingerprint ) ) return self::deny( 'stale_form' );
		$valid = self::check( $d, $m['target'], true ); if ( is_wp_error( $valid ) ) return self::deny( 'stale_form' );
		return array( 'form_id' => $m['form_id'], 'ability_name' => $m['ability_name'], 'target' => $m['target'], 'scope' => $m['scope'], 'expires_at' => $m['expires_at'], 'schema_sha256' => $d['schema_sha256'], 'descriptor_sha256' => $m['descriptor_sha256'], 'descriptor' => $d, 'fields' => $fields, 'sealed_form' => $sealed, 'non_authorizing' => true, 'execution_allowed' => false );
	}
	public static function validate( $form, $values ) { return self::validate_values( $form, $values, false ); }
	public static function validate_draft( $form, $values ) { return self::validate_values( $form, $values, true ); }
	private static function validate_values( $sealed, $values, $partial ) {
		$f = self::inspect( $sealed ); if ( is_wp_error( $f ) ) return $f;
		if ( ! self::map( $values ) ) return self::deny( 'invalid_values' );
		foreach ( $f['target'] as $key => $value ) if ( array_key_exists( $key, $values ) ) return self::deny( 'target_conflict' );
		$input = array_merge( $f['target'], $values ); $valid = self::check( $f['descriptor'], $input, $partial ); if ( is_wp_error( $valid ) ) return $valid;
		if ( true !== MAD4B_SCP_CSO_Scope::safe_data( $input ) ) return self::deny( 'unsafe_values' );
		$r = array( 'status' => $partial ? 'DRAFT_VALIDATED' : 'VALIDATED', 'form_id' => $f['form_id'], 'ability_name' => $f['ability_name'], 'target' => $f['target'], 'values' => $values, 'input' => $input, 'scope' => $f['scope'], 'schema_sha256' => $f['schema_sha256'], 'descriptor_sha256' => $f['descriptor_sha256'], 'expires_at' => $f['expires_at'], 'non_authorizing' => true, 'execution_allowed' => false );
		$r['validated_form'] = MAD4B_SCP_CSO_Scope::seal( $r, 'mad4b.cso01.validated-form.v1' ); return is_wp_error( $r['validated_form'] ) ? $r['validated_form'] : $r;
	}

	public static function suggest( $sealed, $field, $query = '', $offset = 0 ) {
		$f = self::inspect( $sealed ); if ( is_wp_error( $f ) ) return $f;
		if ( ! is_string( $field ) || ! isset( $f['descriptor']['input_schema']['properties'][ $field ] ) || ! is_string( $query ) || strlen( $query ) > 512 || ! self::length( $query,128 ) || ! is_int( $offset ) || $offset < 0 || $offset > 1000 ) return self::deny( 'invalid_suggestion' );
		$s = $f['descriptor']['input_schema']['properties'][ $field ]; $meta = self::metadata( $f['descriptor'],$field );
		if ( self::has_secret( $s,$field,$f['descriptor'] ) || ! self::visible( $meta,$f['target'] ) ) return self::deny( 'unsupported_suggestion' );
		$enum = $s['enum'] ?? $s['items']['enum'] ?? null;
		if ( is_array( $enum ) ) { $items = array(); foreach ( $enum as $v ) if ( is_scalar( $v ) && ( '' === $query || false !== stripos( (string)$v,$query ) ) ) $items[] = array( 'value'=>$v,'label'=>self::text( (string)$v,256 ) ); return array( 'status'=>'SUGGESTIONS','items'=>array_slice( $items,$offset,20 ),'next_offset'=>count( $items ) > $offset+20 ? $offset+20 : null,'locale'=>$f['scope']['locale'],'non_authorizing'=>true ); }
		$binding = $meta['suggestion'] ?? null;
		if ( ! is_array( $binding ) || ! isset( $binding['ability_name'],$binding['resource_type'] ) || ! in_array( $binding['resource_type'],array( 'post','term','user','media' ),true ) ) return self::deny( 'unsupported_suggestion' );
		$params = $binding['input'] ?? array(); if ( ! self::map( $params ) ) return self::deny( 'unsupported_suggestion' );
		foreach ( array( 'query'=>$query,'offset'=>$offset,'limit'=>20,'locale'=>$f['scope']['locale'] ) as $key=>$v ) { $k = $binding[ $key.'_key' ] ?? $key; if ( ! is_string( $k ) || ! preg_match( '/^[a-zA-Z][a-zA-Z0-9_-]{0,63}$/D',$k ) ) return self::deny( 'unsupported_suggestion' ); $params[ $k ]=$v; }
		$reader = MAD4B_SCP_CSO_Registry::describe( $binding['ability_name'],$params ); if ( is_wp_error( $reader ) || 'read' !== ( $reader['lane'] ?? null ) || empty( $reader['preparation'] ) ) return self::deny( 'unsupported_suggestion' );
		$reply = MAD4B_SCP_CSO_Registry::read( $binding['ability_name'],$params,$reader['preparation'] );
		if ( is_wp_error( $reply ) || ! is_array( $reply ) || ! array_key_exists( 'result',$reply ) || true !== ( $reply['read_only'] ?? null ) || false !== ( $reply['mutation_performed'] ?? null ) ) return self::deny( 'suggestion_unavailable' );
		$rows=$reply['result']; $path=$binding['items_path']??'items'; if ( ! is_string( $path ) || strlen( $path )>128 || ! preg_match( '/^[a-zA-Z0-9_.]*$/D',$path ) ) return self::deny( 'unsupported_suggestion' );
		foreach ( '' === $path ? array() : explode( '.',$path ) as $key ) { if ( ! is_array( $rows ) || ! array_key_exists( $key,$rows ) ) return self::deny( 'suggestion_unavailable' ); $rows=$rows[ $key ]; }
		if ( ! is_array( $rows ) || array_values( $rows ) !== $rows || count( $rows )>20 ) return self::deny( 'suggestion_unavailable' );
		$vk=$binding['value_key']??'id'; $lk=$binding['label_key']??'label'; $ik=$binding['id_key']??$vk;
		foreach ( array( $vk,$lk,$ik ) as $k ) if ( ! is_string( $k ) || ! preg_match( '/^[a-zA-Z][a-zA-Z0-9_-]{0,63}$/D',$k ) ) return self::deny( 'unsupported_suggestion' );
		$items=array(); foreach ( $rows as $row ) { if ( ! is_array( $row ) || ! isset( $row[ $ik ],$row[ $vk ],$row[ $lk ] ) || ! is_int( $row[ $ik ] ) || $row[ $vk ] !== $row[ $ik ] || ! is_string( $row[ $lk ] ) || ! self::resource( $row[ $ik ],$binding,$f['scope'] ) ) continue; $items[]=array( 'value'=>$row[ $ik ],'label'=>self::text( $row[ $lk ],256 ) ); }
		if ( is_wp_error( self::inspect( $sealed ) ) ) return self::deny( 'stale_form' );
		// Counts and next-page hints must not disclose excluded private objects.
		return array( 'status'=>'SUGGESTIONS','items'=>$items,'next_offset'=>null,'locale'=>$f['scope']['locale'],'non_authorizing'=>true );
	}
	public static function explain( $sealed,$field ) { $f=self::inspect( $sealed ); if ( is_wp_error( $f ) ) return $f; foreach ( $f['fields'] as $row ) if ( is_string( $field ) && $row['field_id']===$field ) return array( 'status'=>'EXPLANATION','field'=>$row,'owner'=>self::text( $f['descriptor']['provider']['id']??'UNKNOWN',128 ),'storage_kind'=>$row['storage_kind']??'UNKNOWN','side_effects'=>$row['side_effects']??array( 'UNKNOWN' ),'next_step'=>'secret_handoff'===$row['field_type'] ? 'Use a separately certified first-party secret handoff. Never paste the value into the conversation.' : 'Review a separately governed plan before saving.','non_authorizing'=>true,'execution_allowed'=>false ); return self::deny( 'unsupported_field' ); }

	private static function compile( $d ) {
		if ( ! is_array( $d ) || ! isset( $d['input_schema'],$d['schema_sha256'],$d['adapter_sha256'] ) || 'object' !== ( $d['input_schema']['type']??null ) || ! isset( $d['input_schema']['properties'] ) ) return self::deny( 'unsupported_schema' );
		if ( self::secret( '',$d['input_schema'],array() ) ) return self::deny( 'secure_handoff_required' );
		$count=0; if ( ! self::bounded( $d['input_schema'],0,$count,'',$d ) ) return self::deny( 'unsupported_schema' );
		$fields=array(); $graph=array(); $required=$d['input_schema']['required']??array();
		foreach ( $d['input_schema']['properties'] as $id=>$s ) {
			$meta=self::metadata( $d,$id ); foreach ( array( 'visible_when','required_when' ) as $key ) if ( isset( $meta[ $key ] ) ) { if ( ! self::condition_valid( $meta[ $key ],array_keys( $d['input_schema']['properties'] ) ) ) return self::deny( 'unsupported_condition' ); $graph[ $id ]=array_merge( $graph[ $id ]??array(),self::refs( $meta[ $key ] ) ); }
			if ( isset( $meta['exclusive_with'] ) ) { if ( ! is_array( $meta['exclusive_with'] ) || count( $meta['exclusive_with'] )>16 ) return self::deny( 'unsupported_condition' ); foreach ( $meta['exclusive_with'] as $other ) if ( ! is_string( $other ) || ! isset( $d['input_schema']['properties'][ $other ] ) || $other===$id ) return self::deny( 'unsupported_condition' ); }
			if ( 'hidden' === ( $meta['visibility']??null ) ) continue;
			$type=self::field_type( $s,$meta ); $secret=self::has_secret( $s,$id,$d ); $ro=$secret || false===$type || ! empty( $s['readOnly'] ) || 'read_only' === ( $meta['visibility']??null ) || 'UNSUPPORTED' === ( $d['storage_status']??null );
			$kind=$secret ? 'secret_handoff' : ( $type ?: 'string' );
			$row=array( 'field_id'=>$id,'name'=>$id,'label'=>self::text( $meta['label']??$s['title']??$id,256 ),'field_type'=>$kind,'type'=>$kind,'value_type'=>$s['type'],'sensitivity'=>self::sensitivity( $d,$id ),'required'=>in_array( $id,$required,true ),'read_only'=>$ro,'readonly'=>$ro,'writable_by_adapter'=>! $ro && ! empty( $d['writable_by_adapter'] ),'control'=>self::control( $kind ),'help'=>self::text( $meta['help']??$s['description']??'Behavior not declared by the registered provider.',2048 ),'constraints'=>array(),'autocomplete'=>! $ro && isset( $meta['suggestion']['ability_name'],$meta['suggestion']['resource_type'] ) && is_string( $meta['suggestion']['ability_name'] ) && in_array( $meta['suggestion']['resource_type'],array( 'post','term','media','user' ),true ) );
			if ( ! $secret ) { foreach ( array( 'minimum','maximum','multipleOf','minLength','maxLength','minItems','maxItems','pattern' ) as $key ) if ( isset( $s[ $key ] ) ) { $row[ $key ]=$s[ $key ]; $row['constraints'][ $key ]=$s[ $key ]; } if ( isset( $s['format'] ) ) { $row['format']=$s['format']; if ( 'date-time'===$s['format'] ) $row['control']='text'; } $enum=$s['enum']??$s['items']['enum']??null; if ( is_array( $enum ) ) { $row['options']=array(); foreach ( $enum as $value ) $row['options'][]=array( 'value'=>$value,'label'=>self::text( (string)$value,256 ) ); } }
			foreach ( array( 'visible_when','required_when','exclusive_with','storage_kind','side_effects' ) as $key ) if ( isset( $meta[ $key ] ) ) $row[ $key ]=$meta[ $key ];
			if ( isset( $meta['visible_when']['field'],$meta['visible_when']['operator'] ) && 'equals'===$meta['visible_when']['operator'] && array_key_exists( 'value',$meta['visible_when'] ) ) $row['visibility']=array( 'field_id'=>$meta['visible_when']['field'],'equals'=>$meta['visible_when']['value'] );
			if ( $secret ) $row['handoff_required']=true; $fields[]=$row;
		}
		$seen=array(); foreach ( array_keys( $graph ) as $id ) if ( ! self::acyclic( $id,$graph,$seen ) ) return self::deny( 'cyclic_condition' ); return $fields;
	}
	private static function fingerprint( $d ) { $m=array(); foreach ( array( 'ability_name','metadata_trusted','schema_sha256','adapter_sha256','capability_binding','lane','writable_by_adapter','storage_status','provider','readback' ) as $key ) $m[ $key ]=$d[ $key ]??null; $m['field_metadata_sha256']=MAD4B_SCP_CSO_Scope::digest( $d['field_metadata']??array() ); if ( is_wp_error( $m['field_metadata_sha256'] ) ) return $m['field_metadata_sha256']; return MAD4B_SCP_CSO_Scope::digest( $m ); }
	private static function check( $d,$input,$partial ) { if ( ! self::map( $input ) || count( $input )>self::MAX_FIELDS ) return self::deny( 'invalid_values' ); if ( $input && 'UNSUPPORTED' === ( $d['storage_status']??null ) ) return self::deny( 'unsupported_storage' ); $r=self::node( $input,$d['input_schema'],'',$d,$input,$partial,0 ); if ( is_wp_error( $r ) ) return $r; if ( ! $partial && function_exists( 'rest_validate_value_from_schema' ) && true!==rest_validate_value_from_schema( $input,$d['input_schema'],'input' ) ) return self::deny( 'invalid_values' ); return true; }
	private static function node( $v,$s,$path,$d,$root,$partial,$depth ) {
		if ( $depth>self::MAX_DEPTH || ! is_array( $s ) || ! isset( $s['type'] ) || ! is_string( $s['type'] ) ) return self::deny( 'unsupported_field' );
		$meta=self::metadata( $d,$path ); $type=$s['type'];
		if ( ''!==$path && ( self::has_secret( $s,$path,$d ) || ! empty( $s['readOnly'] ) || 'read_only' === ( $meta['visibility']??null ) || ! self::visible( $meta,$root ) ) ) return self::deny( 'field_not_available' );
		if ( ''!==$path && false===self::field_type( $s,$meta ) ) return self::deny( 'unsupported_field' );
		if ( 'object'===$type ) {
			if ( ! self::map( $v ) || count( $v )>self::MAX_FIELDS ) return self::deny( 'invalid_values' );
			foreach ( $v as $key=>$child ) { if ( ! array_key_exists( $key,$s['properties'] ) ) return self::deny( 'unknown_field' ); $cp=''===$path ? $key : $path.'.'.$key; $r=self::node( $child,$s['properties'][ $key ],$cp,$d,$root,$partial,$depth+1 ); if ( is_wp_error( $r ) ) return $r; foreach ( self::metadata( $d,$cp )['exclusive_with']??array() as $other ) if ( array_key_exists( $other,$root ) ) return self::deny( 'exclusive_fields' ); }
			if ( ! $partial ) foreach ( $s['properties'] as $key=>$child ) { $cm=self::metadata( $d,''===$path ? $key : $path.'.'.$key ); $needed=in_array( $key,$s['required']??array(),true ) || ( isset( $cm['required_when'] ) && self::condition( $cm['required_when'],$root ) ); if ( $needed && self::visible( $cm,$root ) && ! array_key_exists( $key,$v ) ) return self::deny( 'required_field' ); }
		} elseif ( 'array'===$type ) {
			if ( ! is_array( $v ) || array_values( $v )!==$v || count( $v )>self::MAX_ITEMS || count( $v )<( $s['minItems']??0 ) || count( $v )>( $s['maxItems']??32 ) ) return self::deny( 'invalid_values' ); $seen=array(); foreach ( $v as $child ) { $r=self::node( $child,$s['items'],$path.'.*',$d,$root,$partial,$depth+1 ); if ( is_wp_error( $r ) ) return $r; if ( ! empty( $s['uniqueItems'] ) ) { $key=serialize( $child ); if ( isset( $seen[ $key ] ) ) return self::deny( 'invalid_values' ); $seen[ $key ]=true; } }
		} elseif ( 'string'===$type ) {
			$max=min( self::MAX_TEXT,$s['maxLength']??self::MAX_TEXT ); if ( ! is_string( $v ) || strlen( $v )>4*$max || ! self::length( $v,$max,$s['minLength']??0 ) || false!==strpos( $v,"\0" ) ) return self::deny( 'invalid_values' );
			if ( isset( $s['pattern'] ) && 1!==@preg_match( '/(*LIMIT_MATCH=10000)(*LIMIT_RECURSION=256)'.str_replace( '/','\\/',$s['pattern'] ).'/u',$v ) ) return self::deny( 'invalid_values' ); if ( isset( $s['format'] ) && ! self::format( $v,$s['format'],$meta ) ) return self::deny( 'invalid_values' ); if ( 'rich_text' === ( $meta['field_type']??null ) && ( ! function_exists( 'wp_kses_post' ) || wp_kses_post( $v )!==$v ) ) return self::deny( 'invalid_values' );
		} elseif ( 'integer'===$type || 'number'===$type ) {
			if ( ( 'integer'===$type && ! is_int( $v ) ) || ( 'number'===$type && ! is_int( $v ) && ! is_float( $v ) ) || ! is_finite( (float)$v ) || abs( $v )>9007199254740991 ) return self::deny( 'invalid_values' ); if ( isset( $s['minimum'] ) && ( ! empty( $s['exclusiveMinimum'] ) ? $v<=$s['minimum'] : $v<$s['minimum'] ) ) return self::deny( 'invalid_values' ); if ( isset( $s['maximum'] ) && ( ! empty( $s['exclusiveMaximum'] ) ? $v>=$s['maximum'] : $v>$s['maximum'] ) ) return self::deny( 'invalid_values' ); if ( isset( $s['multipleOf'] ) && abs( $v/$s['multipleOf']-round( $v/$s['multipleOf'] ) )>0.0000001 ) return self::deny( 'invalid_values' );
		} elseif ( 'boolean'===$type ) { if ( ! is_bool( $v ) ) return self::deny( 'invalid_values' ); } else return self::deny( 'unsupported_field' );
		if ( isset( $s['enum'] ) && ! in_array( $v,$s['enum'],true ) ) return self::deny( 'invalid_values' ); if ( isset( $meta['resource_type'] ) ) foreach ( 'array'===$type ? $v : array( $v ) as $id ) if ( ! self::resource( $id,$meta,$d['scope'] ) ) return self::deny( 'invalid_reference' ); return true;
	}
	private static function bounded( $s,$depth,&$count,$path,$d ) {
		if ( ! is_array( $s ) || $depth>self::MAX_DEPTH || ++$count>256 || ! isset( $s['type'] ) || ! is_string( $s['type'] ) ) return false; foreach ( array( 'oneOf','anyOf','allOf','not','$ref','patternProperties','dependencies' ) as $key ) if ( isset( $s[ $key ] ) ) return false;
		if ( self::secret( $path,$s,self::metadata( $d,$path ) ) ) foreach ( array( 'default','enum','examples' ) as $key ) if ( array_key_exists( $key,$s ) ) return false;
		foreach ( array( 'minLength','maxLength','minItems','maxItems' ) as $key ) if ( isset( $s[ $key ] ) && ( ! is_int( $s[ $key ] ) || $s[ $key ]<0 ) ) return false; foreach ( array( 'minimum','maximum','multipleOf' ) as $key ) if ( isset( $s[ $key ] ) && ( ( ! is_int( $s[ $key ] ) && ! is_float( $s[ $key ] ) ) || ! is_finite( (float)$s[ $key ] ) ) ) return false; if ( isset( $s['multipleOf'] ) && $s['multipleOf']<=0 ) return false;
		if ( isset( $s['pattern'] ) && ( ! is_string( $s['pattern'] ) || strlen( $s['pattern'] )>128 ) ) return false; if ( isset( $s['enum'] ) ) { if ( ! is_array( $s['enum'] ) || count( $s['enum'] )>512 ) return false; foreach ( $s['enum'] as $v ) if ( ! is_scalar( $v ) || ( is_string( $v ) && ! self::length( $v,self::MAX_TEXT ) ) ) return false; }
		if ( 'object'===$s['type'] ) { if ( ! isset( $s['properties'] ) || ! self::map( $s['properties'] ) || count( $s['properties'] )>self::MAX_FIELDS || ! is_array( $s['required']??array() ) ) return false; foreach ( $s['required']??array() as $key ) if ( ! is_string( $key ) || ! isset( $s['properties'][ $key ] ) ) return false; foreach ( $s['properties'] as $key=>$child ) if ( ! is_string( $key ) || ! preg_match( '/^[a-zA-Z][a-zA-Z0-9_-]{0,127}$/D',$key ) || ! self::bounded( $child,$depth+1,$count,''===$path ? $key : $path.'.'.$key,$d ) ) return false; } elseif ( 'array'===$s['type'] && ( ! isset( $s['items'] ) || ! self::bounded( $s['items'],$depth+1,$count,$path.'.*',$d ) ) ) return false;
		$meta=self::metadata( $d,$path ); foreach ( array( 'visible_when','required_when' ) as $key ) if ( isset( $meta[ $key ] ) && ! self::condition_valid( $meta[ $key ],array_keys( $d['input_schema']['properties'] ) ) ) return false; return true;
	}
	public static function sensitivity( $d,$path ) { $s=$d['input_schema']; foreach ( explode( '.',$path ) as $key ) $s='*'===$key ? ( $s['items']??array() ) : ( $s['properties'][ $key ]??array() ); $meta=self::metadata( $d,$path ); if ( self::has_secret( $s,$path,$d ) ) return 'SECRET'; foreach ( array( 'REGULATED','PERSONAL','SITE_INTERNAL','PUBLIC' ) as $kind ) if ( $kind === ( $meta['sensitivity']??null ) || $kind === ( $s['x-cso']['sensitivity']??null ) ) return $kind; return 'SITE_INTERNAL'; }
	private static function metadata( $d,$path ) { return ! empty( $d['metadata_trusted'] ) && isset( $d['field_metadata'][ $path ] ) && is_array( $d['field_metadata'][ $path ] ) ? $d['field_metadata'][ $path ] : array(); }
	private static function secret( $path,$s,$meta ) { return 1===preg_match( '/api[_-]?key|password|secret|token|credential/i',$path ) || ! empty( $s['writeOnly'] ) || 'password' === ( $s['format']??null ) || 'SECRET' === ( $meta['sensitivity']??null ) || 'SECRET' === ( $s['x-cso']['sensitivity']??null ); }
	private static function has_secret( $s,$path,$d ) { if ( self::secret( $path,$s,self::metadata( $d,$path ) ) ) return true; foreach ( $s['properties']??array() as $key=>$child ) if ( self::has_secret( $child,''===$path ? $key : $path.'.'.$key,$d ) ) return true; return isset( $s['items'] ) && is_array( $s['items'] ) && self::has_secret( $s['items'],$path.'.*',$d ); }
	private static function visible( $m,$v ) { return 'hidden' !== ( $m['visibility']??null ) && ( ! isset( $m['visible_when'] ) || self::condition( $m['visible_when'],$v ) ); }
	private static function field_type( $s,$m ) { if ( isset( $m['resource_type'] ) ) { if ( ! in_array( $m['resource_type'],array( 'post','term','media','user' ),true ) ) return false; if ( 'array'===$s['type'] && 'integer' === ( $s['items']['type']??null ) ) return 'repeater'; return 'integer'===$s['type'] ? ( 'media'===$m['resource_type'] ? 'media_reference' : 'relation' ) : false; } if ( isset( $s['enum'] ) ) return 'enum'; if ( 'string'===$s['type'] ) { if ( in_array( $s['format']??null,array( 'uri','url' ),true ) ) return ! empty( $m['allowed_hosts'] ) ? 'url' : false; if ( in_array( $s['format']??null,array( 'date','date-time' ),true ) ) return 'date'; if ( isset( $s['format'] ) && ! in_array( $s['format'],array( 'email','password' ),true ) ) return false; return 'rich_text' === ( $m['field_type']??null ) ? 'rich_text' : 'string'; } if ( in_array( $s['type'],array( 'integer','number','boolean' ),true ) ) return $s['type']; if ( 'array'===$s['type'] ) return isset( $s['items']['enum'] ) ? 'multi_enum' : 'repeater'; return 'object'===$s['type'] ? 'repeater' : false; }
	private static function control( $t ) { return array( 'integer'=>'number','number'=>'number','boolean'=>'checkbox','date'=>'date','url'=>'url','enum'=>'select','multi_enum'=>'multiselect','repeater'=>'json','relation'=>'autocomplete','media_reference'=>'autocomplete','secret_handoff'=>'external_handoff','rich_text'=>'textarea' )[ $t ]??'text'; }
	private static function condition_valid( $c,$fields,$depth=0 ) { if ( ! is_array( $c ) || $depth>3 || count( $c )>3 ) return false; foreach ( array( 'all','any' ) as $g ) if ( isset( $c[ $g ] ) ) { if ( 1!==count( $c ) || ! is_array( $c[ $g ] ) || ! $c[ $g ] || count( $c[ $g ] )>16 ) return false; foreach ( $c[ $g ] as $child ) if ( ! self::condition_valid( $child,$fields,$depth+1 ) ) return false; return true; } if ( ! isset( $c['field'],$c['operator'] ) || ! is_string( $c['field'] ) || ! in_array( $c['field'],$fields,true ) || ! in_array( $c['operator'],array( 'equals','not_equals','in','not_in','is_set' ),true ) || array_diff( array_keys( $c ),array( 'field','operator','value' ) ) ) return false; if ( 'is_set'===$c['operator'] ) return 2===count( $c ); if ( ! array_key_exists( 'value',$c ) ) return false; $vals=in_array( $c['operator'],array( 'in','not_in' ),true ) ? $c['value'] : array( $c['value'] ); if ( ! is_array( $vals ) || count( $vals )>32 ) return false; foreach ( $vals as $v ) if ( ( ! is_scalar( $v ) && null!==$v ) || ( is_string( $v ) && ! self::length( $v,128 ) ) ) return false; return true; }
	private static function condition( $c,$v ) { foreach ( array( 'all','any' ) as $g ) if ( isset( $c[ $g ] ) ) { foreach ( $c[ $g ] as $child ) { $ok=self::condition( $child,$v ); if ( 'all'===$g && ! $ok ) return false; if ( 'any'===$g && $ok ) return true; } return 'all'===$g; } $has=array_key_exists( $c['field'],$v ); if ( 'is_set'===$c['operator'] ) return $has; if ( ! $has ) return false; $a=$v[ $c['field'] ]; if ( 'equals'===$c['operator'] ) return $a===$c['value']; if ( 'not_equals'===$c['operator'] ) return $a!==$c['value']; if ( 'in'===$c['operator'] ) return in_array( $a,$c['value'],true ); return 'not_in'===$c['operator'] && ! in_array( $a,$c['value'],true ); }
	private static function refs( $c ) { foreach ( array( 'all','any' ) as $g ) if ( isset( $c[ $g ] ) ) { $refs=array(); foreach ( $c[ $g ] as $child ) $refs=array_merge( $refs,self::refs( $child ) ); return $refs; } return array( $c['field'] ); }
	private static function acyclic( $id,$graph,&$seen ) { if ( isset( $seen[ $id ] ) ) return 2===$seen[ $id ]; $seen[ $id ]=1; foreach ( $graph[ $id ]??array() as $next ) if ( ! self::acyclic( $next,$graph,$seen ) ) return false; $seen[ $id ]=2; return true; }
	private static function target_safe( $v,$s,$d,$path ) { if ( ''!==$path && ! in_array( self::sensitivity( $d,$path ),array( 'PUBLIC','SITE_INTERNAL' ),true ) ) return false; if ( 'object'===$s['type'] ) { foreach ( $v as $key=>$child ) if ( ! self::target_safe( $child,$s['properties'][ $key ],$d,''===$path ? $key : $path.'.'.$key ) ) return false; } elseif ( 'array'===$s['type'] ) { foreach ( $v as $child ) if ( ! self::target_safe( $child,$s['items'],$d,$path.'.*' ) ) return false; } return true; }
	private static function resource( $id,$m,$scope ) { if ( ! is_int( $id ) || $id<1 || ! function_exists( 'current_user_can' ) ) return false; $t=$m['resource_type']??''; if ( 'post'===$t || 'media'===$t ) { if ( ! current_user_can( 'read_post',$id ) || ! function_exists( 'get_post' ) ) return false; $p=get_post( $id ); $pt='media'===$t ? 'attachment' : ( $m['post_type']??null ); if ( ! is_string( $pt ) || ! is_object( $p ) || ( $p->post_type??null )!==$pt ) return false; } elseif ( 'term'===$t ) { if ( ! isset( $m['taxonomy'] ) || ! is_string( $m['taxonomy'] ) || ! function_exists( 'get_taxonomy' ) || ! function_exists( 'get_term' ) ) return false; $tax=get_taxonomy( $m['taxonomy'] ); if ( ! is_object( $tax ) || ! isset( $tax->cap->assign_terms ) || ! current_user_can( $tax->cap->assign_terms ) ) return false; $term=get_term( $id,$m['taxonomy'] ); if ( is_wp_error( $term ) || ! is_object( $term ) || ( $term->taxonomy??null )!==$m['taxonomy'] ) return false; } elseif ( 'user'===$t ) { if ( ! current_user_can( 'list_users' ) || ! current_user_can( 'edit_user',$id ) || ! function_exists( 'get_userdata' ) || ! is_object( get_userdata( $id ) ) ) return false; } else return false; if ( function_exists( 'has_filter' ) && has_filter( 'wpml_element_language_code' ) && function_exists( 'apply_filters' ) && 'user'!==$t ) { $et='term'===$t ? 'tax_'.$m['taxonomy'] : 'post_'.( 'media'===$t ? 'attachment' : $m['post_type'] ); $lang=apply_filters( 'wpml_element_language_code',null,array( 'element_id'=>$id,'element_type'=>$et ) ); if ( ! is_string( $lang ) || $lang!==substr( $scope['locale'],0,2 ) ) return false; } return true; }
	private static function format( $v,$f,$m ) { if ( 'date'===$f ) { $d=DateTimeImmutable::createFromFormat( '!Y-m-d',$v ); return false!==$d && $d->format( 'Y-m-d' )===$v; } if ( 'date-time'===$f ) { if ( ! preg_match( '/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:Z|[+-]\d{2}:\d{2})$/D',$v ) ) return false; try { $d=new DateTimeImmutable( $v ); return $d->format( 'Y-m-d\TH:i:s' )===substr( $v,0,19 ); } catch ( Throwable $e ) { return false; } } if ( 'email'===$f ) return false!==filter_var( $v,FILTER_VALIDATE_EMAIL ); if ( 'uri'===$f || 'url'===$f ) { $u=parse_url( $v ); return false!==filter_var( $v,FILTER_VALIDATE_URL ) && ! preg_match( '/[\x00-\x20\x7f]/',$v ) && is_array( $u ) && 'https' === ( $u['scheme']??null ) && isset( $u['host'] ) && ! isset( $u['user'] ) && ! isset( $u['pass'] ) && ( ! isset( $u['port'] ) || 443===$u['port'] ) && is_array( $m['allowed_hosts']??null ) && in_array( strtolower( $u['host'] ),$m['allowed_hosts'],true ) && false===filter_var( $u['host'],FILTER_VALIDATE_IP ) && false!==strpos( $u['host'],'.' ) && ! preg_match( '/\.(?:local|localhost|internal)$/i',$u['host'] ); } return false; }
	private static function map( $v ) { return is_array( $v ) && ! array_filter( array_keys( $v ),'is_int' ); }
	private static function length( $v,$max,$min=0 ) { $n=preg_match_all( '/./us',$v,$chars ); return false!==$n && $n<=$max && $n>=$min; }
	private static function text( $v,$max ) { if ( ! is_string( $v ) ) return ''; $v=preg_replace( '/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/u','',strip_tags( $v ) ); if ( ! is_string( $v ) || false===preg_match_all( '/./us',$v,$chars ) ) return ''; return implode( '',array_slice( $chars[0],0,$max ) ); }
	private static function now() { return class_exists( 'MAD4B_SCP_Time_Policy' ) ? (int)MAD4B_SCP_Time_Policy::now_epoch() : time(); }
	private static function deny( $reason ) { return MAD4B_SCP_CSO_Scope::error( $reason ); }
}
