<?php

if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Zero-touch, read-only functional-gap evidence and evaluation.
 *
 * Repository evidence is generated by CI from exact packaged provider archives
 * and embedded into the installable Control Plane artifact. Runtime evidence is
 * collected locally without shell, SQL, remote requests, credential reads, or
 * mutations. Evaluation is fail-closed and never grants authority.
 */
final class MAD4B_SCP_Functional_Gap_Evidence {
	const CONTRACT = 'mad4b.functional-gap-zero-touch.v1';
	const RUNTIME_CONTRACT = 'mad4b.runtime-functional-gap-evidence.v2';
	const EVALUATION_CONTRACT = 'mad4b.functional-gap-promotion-evaluation.v2';
	const REPOSITORY_CONTRACT = 'mad4b.functional-gap-contract-evidence.v1';
	const REPOSITORY_FILE = 'config/functional-gap-contract-evidence.generated.json';
	const MAX_TREE_FILES = 12000;
	const MAX_TREE_BYTES = 805306368;

	private static $snapshot = null;

	private static function targets() {
		return array(
			'jetengine' => array( 'jet-engine/' ),
			'jetsmartfilters' => array( 'jet-smart-filters/' ),
			'rank-math' => array( 'seo-by-rank-math/', 'seo-by-rank-math-pro/' ),
			'wp-import-export' => array( 'wp-all-import-pro/', 'wp-all-export-pro/' ),
			'bulk-taxonomy-editor' => array( 'bulk-taxonomy-editor/' ),
			'custom-mega-menu' => array( 'custom-mega-menu/', 'custom-mega-menu-v' ),
			'duplicator' => array( 'duplicator/' ),
			'elementskit' => array( 'elementskit-lite/' ),
			'google-tag-manager' => array( 'duracelltomi-google-tag-manager/' ),
			'heic-support' => array( 'heic-support/' ),
			'hostinger-ai' => array( 'hostinger-ai-assistant/' ),
			'hostinger-onboarding' => array( 'hostinger-easy-onboarding/' ),
			'hostinger-reach' => array( 'hostinger-reach/' ),
			'meta-catalog-feed-mapper' => array( 'meta-catalog-feed-mapper-pro/' ),
			'wordpress-importer' => array( 'wordpress-importer/' ),
			'wpl-client' => array( 'wpl-client/' ),
		);
	}

	private static function normalize_plugin_file( $value ) {
		return strtolower( ltrim( str_replace( '\\', '/', (string) $value ), '/' ) );
	}

	private static function plugin_tree_once( $plugin_file ) {
		$plugin_file = ltrim( str_replace( '\\', '/', (string) $plugin_file ), '/' );
		$dirname = dirname( $plugin_file );
		$root = '.' === $dirname ? WP_PLUGIN_DIR : WP_PLUGIN_DIR . '/' . $dirname;
		if ( ! is_dir( $root ) ) return array( 'file_count' => 0, 'total_bytes' => 0, 'tree_sha256' => '' );

		$rows = array();
		$total = 0;
		try {
			$iterator = new RecursiveIteratorIterator(
				new RecursiveDirectoryIterator( $root, FilesystemIterator::SKIP_DOTS ),
				RecursiveIteratorIterator::LEAVES_ONLY
			);
			foreach ( $iterator as $file ) {
				if ( ! $file->isFile() || $file->isLink() ) continue;
				$path = str_replace( '\\', '/', $file->getPathname() );
				$base = rtrim( str_replace( '\\', '/', $root ), '/' ) . '/';
				$relative = 0 === strpos( $path, $base ) ? substr( $path, strlen( $base ) ) : basename( $path );
				$size = (int) $file->getSize();
				if ( count( $rows ) + 1 > self::MAX_TREE_FILES || $total + $size > self::MAX_TREE_BYTES ) {
					return array( 'file_count'=>count( $rows ), 'total_bytes'=>$total, 'tree_sha256'=>'', 'error'=>'tree_scan_budget_exceeded', 'scan_budget_exceeded'=>true );
				}
				$digest = hash_file( 'sha256', $file->getPathname() );
				if ( false === $digest ) return array( 'file_count'=>count( $rows ), 'total_bytes'=>$total, 'tree_sha256'=>'', 'error'=>'tree_file_hash_failed' );
				$total += $size;
				$rows[] = $relative . "\0" . $size . "\0" . $digest;
			}
		} catch ( Exception $e ) {
			return array( 'file_count' => 0, 'total_bytes' => 0, 'tree_sha256' => '', 'error' => 'tree_scan_failed' );
		}
		sort( $rows, SORT_STRING );
		return array(
			'file_count' => count( $rows ),
			'total_bytes' => $total,
			'tree_sha256' => hash( 'sha256', implode( "\n", $rows ) ),
		);
	}

	private static function plugin_tree( $plugin_file, array $expected_hashes = array() ) {
		$expected = array();
		foreach ( $expected_hashes as $digest ) {
			$digest = strtolower( trim( (string) $digest ) );
			if ( preg_match( '/^[a-f0-9]{64}$/', $digest ) ) $expected[ $digest ] = true;
		}
		$first = self::plugin_tree_once( $plugin_file );
		if ( ! empty( $first['error'] ) ) {
			$first['scan_stable'] = false;
			$first['scan_attempts'] = 1;
			$first['comparison'] = sanitize_key( (string) $first['error'] );
			return $first;
		}
		$first_hash = isset( $first['tree_sha256'] ) ? strtolower( (string) $first['tree_sha256'] ) : '';
		if ( '' !== $first_hash && isset( $expected[ $first_hash ] ) ) {
			$first['scan_stable'] = true;
			$first['scan_attempts'] = 1;
			$first['comparison'] = 'exact_repository_match';
			return $first;
		}
		$second = self::plugin_tree_once( $plugin_file );
		if ( ! empty( $second['error'] ) ) {
			$second['scan_stable'] = false;
			$second['scan_attempts'] = 2;
			$second['first_tree_sha256'] = $first_hash;
			$second['comparison'] = sanitize_key( (string) $second['error'] );
			return $second;
		}
		$second_hash = isset( $second['tree_sha256'] ) ? strtolower( (string) $second['tree_sha256'] ) : '';
		$stable = '' !== $first_hash && '' !== $second_hash && hash_equals( $first_hash, $second_hash )
			&& (int) ( isset( $first['file_count'] ) ? $first['file_count'] : -1 ) === (int) ( isset( $second['file_count'] ) ? $second['file_count'] : -2 )
			&& (int) ( isset( $first['total_bytes'] ) ? $first['total_bytes'] : -1 ) === (int) ( isset( $second['total_bytes'] ) ? $second['total_bytes'] : -2 );
		$second['scan_stable'] = $stable;
		$second['scan_attempts'] = 2;
		$second['first_tree_sha256'] = $first_hash;
		$second['comparison'] = $stable ? ( isset( $expected[ $second_hash ] ) ? 'exact_repository_match' : 'stable_runtime_drift' ) : 'runtime_tree_changed_during_scan';
		if ( ! $stable ) $second['error'] = 'runtime_tree_unstable';
		return $second;
	}

	private static function repository_tree_hashes( array $repository, $family ) {
		$out = array();
		$family_row = isset( $repository['families'][ $family ] ) && is_array( $repository['families'][ $family ] ) ? $repository['families'][ $family ] : array();
		foreach ( isset( $family_row['artifacts'] ) && is_array( $family_row['artifacts'] ) ? $family_row['artifacts'] : array() as $artifact ) {
			$digest = isset( $artifact['package_tree']['tree_sha256'] ) ? strtolower( trim( (string) $artifact['package_tree']['tree_sha256'] ) ) : '';
			if ( preg_match( '/^[a-f0-9]{64}$/', $digest ) ) $out[ $digest ] = true;
		}
		return array_keys( $out );
	}

	private static function build_provenance() {
		$path = MAD4B_SCP_DIR . 'MAD4B-BUILD-PROVENANCE.json';
		if ( ! is_file( $path ) || ! is_readable( $path ) ) return array( 'valid'=>false, 'blockers'=>array( 'build_provenance_missing' ) );
		$raw = file_get_contents( $path );
		$data = false === $raw ? null : json_decode( $raw, true );
		if ( ! is_array( $data ) || 'mad4b.build-provenance.v1' !== ( isset( $data['contract'] ) ? (string) $data['contract'] : '' ) ) return array( 'valid'=>false, 'blockers'=>array( 'build_provenance_invalid' ) );
		$source = isset( $data['source_commit_sha'] ) ? strtolower( trim( (string) $data['source_commit_sha'] ) ) : '';
		$fingerprint = isset( $data['build_fingerprint'] ) ? strtolower( trim( (string) $data['build_fingerprint'] ) ) : '';
		$manifest = isset( $data['package_manifest_digest'] ) ? strtolower( trim( (string) $data['package_manifest_digest'] ) ) : '';
		$blockers = array();
		if ( ! preg_match( '/^[a-f0-9]{40}$/', $source ) ) $blockers[] = 'build_provenance_source_invalid';
		if ( ! preg_match( '/^[a-f0-9]{64}$/', $fingerprint ) ) $blockers[] = 'build_provenance_fingerprint_invalid';
		if ( ! preg_match( '/^[a-f0-9]{64}$/', $manifest ) ) $blockers[] = 'build_provenance_manifest_invalid';
		$files = array();
		foreach ( isset( $data['package_files'] ) && is_array( $data['package_files'] ) ? $data['package_files'] : array() as $row ) {
			if ( ! is_array( $row ) || empty( $row['path'] ) ) continue;
			$files[ str_replace( '\\', '/', ltrim( (string) $row['path'], '/' ) ) ] = $row;
		}
		return array(
			'valid' => empty( $blockers ),
			'source_commit_sha' => $source,
			'build_fingerprint' => $fingerprint,
			'package_manifest_digest' => $manifest,
			'package_files' => $files,
			'blockers' => $blockers,
		);
	}

	private static function repository_evidence() {
		$path = MAD4B_SCP_DIR . self::REPOSITORY_FILE;
		if ( ! is_file( $path ) || ! is_readable( $path ) ) {
			return array(
				'present' => false,
				'valid' => false,
				'contract' => '',
				'source_commit_sha' => '',
				'families' => array(),
				'blockers' => array( 'repository_evidence_missing' ),
			);
		}
		$raw = file_get_contents( $path );
		$data = false === $raw ? null : json_decode( $raw, true );
		$evidence_sha256 = false === $raw ? '' : hash( 'sha256', $raw );
		$evidence_bytes = false === $raw ? 0 : strlen( $raw );
		if ( ! is_array( $data ) || self::REPOSITORY_CONTRACT !== ( isset( $data['contract'] ) ? (string) $data['contract'] : '' ) ) {
			return array(
				'present' => true,
				'valid' => false,
				'contract' => is_array( $data ) && isset( $data['contract'] ) ? (string) $data['contract'] : '',
				'source_commit_sha' => '',
				'families' => array(),
				'blockers' => array( 'repository_evidence_invalid' ),
			);
		}

		$blockers = array();
		$source = isset( $data['source_commit_sha'] ) ? strtolower( trim( (string) $data['source_commit_sha'] ) ) : '';
		$provenance = self::build_provenance();
		$build_source = ! empty( $provenance['source_commit_sha'] ) ? (string) $provenance['source_commit_sha'] : self::build_source_commit_sha();
		if ( '' === $source || ! preg_match( '/^[a-f0-9]{40}$/', $source ) ) $blockers[] = 'repository_evidence_source_missing';
		if ( empty( $provenance['valid'] ) ) $blockers = array_merge( $blockers, isset( $provenance['blockers'] ) ? (array) $provenance['blockers'] : array( 'build_provenance_invalid' ) );
		if ( '' !== $build_source && '' !== $source && ! hash_equals( $build_source, $source ) ) $blockers[] = 'repository_evidence_build_source_mismatch';
		$provenance_row = isset( $provenance['package_files'][ self::REPOSITORY_FILE ] ) && is_array( $provenance['package_files'][ self::REPOSITORY_FILE ] ) ? $provenance['package_files'][ self::REPOSITORY_FILE ] : null;
		if ( ! is_array( $provenance_row ) ) {
			$blockers[] = 'repository_evidence_not_bound_in_build_provenance';
		} else {
			$expected_sha = isset( $provenance_row['sha256'] ) ? strtolower( trim( (string) $provenance_row['sha256'] ) ) : '';
			$expected_bytes = isset( $provenance_row['bytes'] ) ? (int) $provenance_row['bytes'] : -1;
			if ( ! preg_match( '/^[a-f0-9]{64}$/', $expected_sha ) || ! hash_equals( $expected_sha, $evidence_sha256 ) ) $blockers[] = 'repository_evidence_sha256_mismatch';
			if ( $expected_bytes < 0 || $expected_bytes !== $evidence_bytes ) $blockers[] = 'repository_evidence_bytes_mismatch';
		}
		$blockers = array_values( array_unique( array_filter( array_map( 'sanitize_key', $blockers ) ) ) );

		return array(
			'present' => true,
			'valid' => empty( $blockers ),
			'contract' => (string) $data['contract'],
			'source_commit_sha' => $source,
			'evidence_sha256' => $evidence_sha256,
			'evidence_bytes' => $evidence_bytes,
			'build_fingerprint' => isset( $provenance['build_fingerprint'] ) ? (string) $provenance['build_fingerprint'] : '',
			'package_manifest_digest' => isset( $provenance['package_manifest_digest'] ) ? (string) $provenance['package_manifest_digest'] : '',
			'families' => isset( $data['families'] ) && is_array( $data['families'] ) ? $data['families'] : array(),
			'blockers' => $blockers,
		);
	}

	private static function build_source_commit_sha() {
		$path = MAD4B_SCP_DIR . 'MAD4B-BUILD-PROVENANCE.json';
		if ( ! is_file( $path ) || ! is_readable( $path ) ) return '';
		$raw = file_get_contents( $path );
		$data = false === $raw ? null : json_decode( $raw, true );
		$sha = is_array( $data ) && isset( $data['source_commit_sha'] ) ? strtolower( trim( (string) $data['source_commit_sha'] ) ) : '';
		return preg_match( '/^[a-f0-9]{40}$/', $sha ) ? $sha : '';
	}

	private static function runtime_evidence( array $repository = array() ) {
		if ( ! function_exists( 'get_plugins' ) ) require_once ABSPATH . 'wp-admin/includes/plugin.php';

		$plugin_map = get_plugins();
		$active = (array) get_option( 'active_plugins', array() );
		$network_active = is_multisite() ? array_keys( (array) get_site_option( 'active_sitewide_plugins', array() ) ) : array();
		$active_set = array();
		foreach ( array_merge( $active, $network_active ) as $plugin_file ) $active_set[ self::normalize_plugin_file( $plugin_file ) ] = true;

		$families = array();
		foreach ( self::targets() as $family => $prefixes ) {
			$families[ $family ] = array();
			foreach ( $plugin_map as $plugin_file => $headers ) {
				$normalized = self::normalize_plugin_file( $plugin_file );
				$matched = false;
				foreach ( $prefixes as $prefix ) {
					$prefix = self::normalize_plugin_file( $prefix );
					if ( '' !== $prefix && 0 === strpos( $normalized, $prefix ) ) { $matched = true; break; }
				}
				if ( ! $matched ) continue;
				$is_active = isset( $active_set[ $normalized ] );
				$families[ $family ][] = array(
					'plugin_file' => (string) $plugin_file,
					'name' => isset( $headers['Name'] ) ? sanitize_text_field( (string) $headers['Name'] ) : '',
					'version' => isset( $headers['Version'] ) ? sanitize_text_field( (string) $headers['Version'] ) : '',
					'active' => $is_active,
					'plugin_tree' => $is_active ? self::plugin_tree( $plugin_file, self::repository_tree_hashes( $repository, $family ) ) : array( 'file_count'=>0, 'total_bytes'=>0, 'tree_sha256'=>'', 'scan_stable'=>false, 'scan_attempts'=>0, 'comparison'=>'inactive_not_scanned' ),
				);
			}
			usort( $families[ $family ], static function ( $a, $b ) { return strcmp( $a['plugin_file'], $b['plugin_file'] ); } );
		}

		$routes = array();
		if ( function_exists( 'rest_get_server' ) ) {
			$server = rest_get_server();
			if ( is_object( $server ) && method_exists( $server, 'get_routes' ) ) {
				foreach ( $server->get_routes() as $route => $handlers ) {
					if ( ! preg_match( '#(?:bulk-taxonomy-editor|wpl-client|rank-math|rankmath|gtm|meta|duplicator|elementskit|hostinger)#i', (string) $route ) ) continue;
					$methods = array();
					foreach ( (array) $handlers as $handler ) {
						if ( ! is_array( $handler ) || empty( $handler['methods'] ) ) continue;
						foreach ( (array) $handler['methods'] as $method => $enabled ) {
							if ( is_int( $method ) ) $method = $enabled;
							if ( $enabled ) $methods[] = strtoupper( (string) $method );
						}
					}
					$methods = array_values( array_unique( $methods ) );
					sort( $methods, SORT_STRING );
					$routes[] = array( 'route' => (string) $route, 'methods' => $methods );
				}
			}
		}
		usort( $routes, static function ( $a, $b ) { return strcmp( $a['route'], $b['route'] ); } );

		$ajax = array();
		global $wp_filter;
		foreach ( (array) $wp_filter as $hook => $hook_obj ) {
			if ( 0 !== strpos( (string) $hook, 'wp_ajax_' ) && 0 !== strpos( (string) $hook, 'wp_ajax_nopriv_' ) ) continue;
			if ( ! preg_match( '/(?:bte_|wpl_|gtm|rank_math|duplicator|elementskit|hostinger|meta)/i', (string) $hook ) ) continue;
			$ajax[] = (string) $hook;
		}
		$ajax = array_values( array_unique( $ajax ) );
		sort( $ajax, SORT_STRING );

		$options = array();
		$secret_pattern = '/(?:secret|token|password|passwd|api[_-]?key|license[_-]?key|access[_-]?key|client[_-]?secret)/i';
		$option_candidates = array(
			'bte_api_enabled','bte_api_allowed_roles','bte_api_allowed_post_types',
			'wpl_access_token','wpl_api_key','wpl_serial_verified','wpl_verified_order_number','wpl_verified_order_numbers','wpl_verified_wpl_ids',
			'rank-math-options-general','rank-math-options-titles','rank-math-options-sitemap',
		);
		foreach ( $option_candidates as $key ) {
			$value = get_option( $key, null );
			$row = array( 'exists' => null !== $value );
			if ( preg_match( $secret_pattern, $key ) ) {
				$row['redacted'] = true;
				$row['configured'] = null !== $value && '' !== (string) $value;
			} else {
				$row['redacted'] = false;
				$row['type'] = gettype( $value );
				if ( is_array( $value ) ) $row['item_count'] = count( $value );
				elseif ( is_scalar( $value ) || null === $value ) $row['empty'] = '' === (string) $value;
			}
			$options[ $key ] = $row;
		}

		$cron = array();
		if ( function_exists( '_get_cron_array' ) ) {
			foreach ( (array) _get_cron_array() as $timestamp => $hooks ) {
				foreach ( (array) $hooks as $hook => $events ) {
					if ( ! preg_match( '/(?:wpl|gtm|rank_math|duplicator|elementskit|hostinger|meta_catalog|feed)/i', (string) $hook ) ) continue;
					$cron[] = array( 'hook' => (string) $hook, 'timestamp' => (int) $timestamp, 'event_count' => is_array( $events ) ? count( $events ) : 0 );
				}
			}
		}
		usort( $cron, static function ( $a, $b ) { return strcmp( $a['hook'], $b['hook'] ) ?: ( $a['timestamp'] <=> $b['timestamp'] ); } );

		$constants = array();
		foreach ( array( 'JET_ENGINE_VERSION','JET_SMART_FILTERS_VERSION','RANK_MATH_VERSION','RANK_MATH_PRO_VERSION','PMXI_VERSION','PMXE_VERSION' ) as $name ) {
			$constants[ $name ] = defined( $name ) ? sanitize_text_field( (string) constant( $name ) ) : null;
		}

		return array(
			'contract' => self::RUNTIME_CONTRACT,
			'generated_at' => gmdate( 'c' ),
			'families' => $families,
			'constants' => $constants,
			'rest_routes' => $routes,
			'ajax_hooks' => $ajax,
			'option_presence' => $options,
			'cron_hooks' => $cron,
			'safety' => array(
				'mutation_performed' => false,
				'remote_request_performed' => false,
				'secret_values_returned' => false,
				'raw_sql_performed' => false,
			),
		);
	}

	private static function active_plugins( array $runtime, $family ) {
		$rows = isset( $runtime['families'][ $family ] ) && is_array( $runtime['families'][ $family ] ) ? $runtime['families'][ $family ] : array();
		return array_values( array_filter( $rows, static function ( $row ) { return is_array( $row ) && ! empty( $row['active'] ); } ) );
	}

	private static function runtime_rows_stable( array $rows ) {
		if ( empty( $rows ) ) return false;
		foreach ( $rows as $row ) {
			if ( ! is_array( $row ) || empty( $row['plugin_tree']['scan_stable'] ) ) return false;
		}
		return true;
	}

	private static function plugin_versions( array $runtime, $family ) {
		$versions = array();
		foreach ( self::active_plugins( $runtime, $family ) as $row ) {
			$version = isset( $row['version'] ) ? (string) $row['version'] : '';
			if ( '' !== $version ) $versions[ $version ] = true;
		}
		$versions = array_keys( $versions );
		sort( $versions, SORT_STRING );
		return $versions;
	}

	private static function tree_matches( array $repo_family, array $runtime_rows ) {
		$trees = array();
		foreach ( isset( $repo_family['artifacts'] ) && is_array( $repo_family['artifacts'] ) ? $repo_family['artifacts'] : array() as $artifact ) {
			$digest = isset( $artifact['package_tree']['tree_sha256'] ) ? strtolower( (string) $artifact['package_tree']['tree_sha256'] ) : '';
			if ( ! preg_match( '/^[a-f0-9]{64}$/', $digest ) ) continue;
			$version = '';
			foreach ( isset( $artifact['plugin_headers'] ) && is_array( $artifact['plugin_headers'] ) ? $artifact['plugin_headers'] : array() as $header ) {
				if ( ! empty( $header['version'] ) ) { $version = (string) $header['version']; break; }
			}
			$trees[ $digest ] = array( 'archive' => isset( $artifact['archive'] ) ? (string) $artifact['archive'] : '', 'version' => $version );
		}
		$matches = array();
		foreach ( $runtime_rows as $plugin ) {
			if ( empty( $plugin['plugin_tree']['scan_stable'] ) ) continue;
			$digest = isset( $plugin['plugin_tree']['tree_sha256'] ) ? strtolower( (string) $plugin['plugin_tree']['tree_sha256'] ) : '';
			if ( ! isset( $trees[ $digest ] ) ) continue;
			$matches[] = array(
				'plugin_file' => isset( $plugin['plugin_file'] ) ? (string) $plugin['plugin_file'] : '',
				'version' => isset( $plugin['version'] ) ? (string) $plugin['version'] : '',
				'tree_sha256' => $digest,
				'repository_archive' => $trees[ $digest ]['archive'],
				'repository_version' => $trees[ $digest ]['version'],
			);
		}
		return $matches;
	}

	private static function route_methods( array $runtime ) {
		$out = array();
		foreach ( isset( $runtime['rest_routes'] ) && is_array( $runtime['rest_routes'] ) ? $runtime['rest_routes'] : array() as $row ) {
			if ( ! is_array( $row ) || empty( $row['route'] ) ) continue;
			$out[ (string) $row['route'] ] = isset( $row['methods'] ) && is_array( $row['methods'] ) ? $row['methods'] : array();
		}
		return $out;
	}

	private static function decision( $family, $state, $reason, array $extra = array() ) {
		return array_merge( array( 'family' => $family, 'state' => $state, 'reason' => $reason ), $extra );
	}

	private static function evaluate( array $repository, array $runtime ) {
		$decisions = array();
		$repo_families = isset( $repository['families'] ) && is_array( $repository['families'] ) ? $repository['families'] : array();

		if ( empty( $repository['valid'] ) ) {
			foreach ( array_keys( self::targets() ) as $family ) {
				$decisions[] = self::decision( $family, 'evidence_unavailable', 'repository_evidence_missing_or_stale' );
			}
			return array(
				'contract' => self::EVALUATION_CONTRACT,
				'ready' => false,
				'promotion_authorized' => false,
				'decisions' => $decisions,
				'blockers' => isset( $repository['blockers'] ) ? $repository['blockers'] : array( 'repository_evidence_unavailable' ),
			);
		}

		$routes = self::route_methods( $runtime );

		$family = 'bulk-taxonomy-editor';
		$rows = self::active_plugins( $runtime, $family );
		$matches = self::tree_matches( isset( $repo_families[ $family ] ) ? $repo_families[ $family ] : array(), $rows );
		$required = array( '/bulk-taxonomy-editor/v1/posts', '/bulk-taxonomy-editor/v1/taxonomies', '/bulk-taxonomy-editor/v1/terms' );
		$missing = array();
		foreach ( $required as $route ) if ( ! isset( $routes[ $route ] ) || ! in_array( 'GET', $routes[ $route ], true ) ) $missing[] = $route;
		if ( ! self::runtime_rows_stable( $rows ) ) {
			$decisions[] = self::decision( $family, 'runtime_evidence_unstable', 'runtime_tree_changed_during_scan', array( 'missing_get_routes' => $missing ) );
		} elseif ( ! empty( $rows ) && count( $matches ) === count( $rows ) && empty( $missing ) ) {
			$decisions[] = self::decision( $family, 'read_contract_candidate', 'exact_runtime_tree_and_required_get_routes_verified', array(
				'exact_tree_matches' => $matches,
				'safe_now' => array( 'plugin_status_read','posts_read','taxonomies_read','terms_read' ),
				'blocked' => array( 'post_create_or_update','bulk_taxonomy_write','term_relationship_mutation','taxonomy_delete_or_merge' ),
			) );
		} else {
			$decisions[] = self::decision( $family, 'contract_discovery_required', 'exact_runtime_tree_or_required_get_routes_unverified', array( 'exact_tree_matches' => $matches, 'missing_get_routes' => $missing ) );
		}

		$family = 'wpl-client';
		$rows = self::active_plugins( $runtime, $family );
		$matches = self::tree_matches( isset( $repo_families[ $family ] ) ? $repo_families[ $family ] : array(), $rows );
		$options = isset( $runtime['option_presence'] ) && is_array( $runtime['option_presence'] ) ? $runtime['option_presence'] : array();
		$secret_ok = isset( $options['wpl_access_token']['redacted'], $options['wpl_api_key']['redacted'] ) && true === $options['wpl_access_token']['redacted'] && true === $options['wpl_api_key']['redacted'];
		$status_keys = array( 'wpl_serial_verified','wpl_verified_order_number','wpl_verified_order_numbers','wpl_verified_wpl_ids' );
		$status_model = true;
		foreach ( $status_keys as $key ) if ( ! array_key_exists( $key, $options ) ) $status_model = false;
		if ( ! self::runtime_rows_stable( $rows ) ) {
			$decisions[] = self::decision( $family, 'runtime_evidence_unstable', 'runtime_tree_changed_during_scan', array( 'secret_redaction_verified' => $secret_ok ) );
		} elseif ( ! empty( $rows ) && count( $matches ) === count( $rows ) && $secret_ok && $status_model ) {
			$decisions[] = self::decision( $family, 'redacted_read_contract_candidate', 'exact_runtime_tree_and_secret_redaction_verified', array(
				'exact_tree_matches' => $matches,
				'safe_now' => array( 'plugin_status_read','license_verification_state_read_redacted' ),
				'blocked' => array( 'credential_read','remote_execution','plugin_or_theme_install','plugin_toggle','filesystem_write','external_write' ),
			) );
		} else {
			$decisions[] = self::decision( $family, 'contract_discovery_required', 'exact_runtime_tree_or_redacted_status_model_unverified', array( 'exact_tree_matches' => $matches, 'secret_redaction_verified' => $secret_ok ) );
		}

		foreach ( array( 'custom-mega-menu','google-tag-manager','meta-catalog-feed-mapper','rank-math' ) as $family ) {
			$rows = self::active_plugins( $runtime, $family );
			$matches = self::tree_matches( isset( $repo_families[ $family ] ) ? $repo_families[ $family ] : array(), $rows );
			if ( ! self::runtime_rows_stable( $rows ) ) {
				$state = 'runtime_evidence_unstable';
				$reason = 'runtime_tree_changed_during_scan';
			} else {
				$state = ! empty( $rows ) && count( $matches ) === count( $rows ) ? 'contract_evidence_review' : 'runtime_alignment_required';
				$reason = 'contract_evidence_review' === $state ? 'exact_runtime_tree_verified_but_semantic_contract_not_yet_promoted' : 'live_runtime_tree_does_not_match_repository_evidence';
			}
			$decisions[] = self::decision( $family, $state, $reason, array( 'runtime_versions' => self::plugin_versions( $runtime, $family ), 'exact_tree_matches' => $matches ) );
		}

		foreach ( array( 'duplicator','elementskit','heic-support','hostinger-ai','hostinger-onboarding','hostinger-reach','wordpress-importer' ) as $family ) {
			$rows = self::active_plugins( $runtime, $family );
			$tree_hashes = array();
			$plugin_files = array();
			foreach ( $rows as $row ) {
				$plugin_files[] = isset( $row['plugin_file'] ) ? (string) $row['plugin_file'] : '';
				$tree_hashes[] = isset( $row['plugin_tree']['tree_sha256'] ) ? (string) $row['plugin_tree']['tree_sha256'] : '';
			}
			$state = empty( $rows ) ? 'not_active' : ( self::runtime_rows_stable( $rows ) ? 'runtime_contract_evidence_captured' : 'runtime_evidence_unstable' );
			$reason = 'runtime_evidence_unstable' === $state ? 'runtime_tree_changed_during_scan' : 'runtime_only_provider_requires_semantic_contract_before_specialized_surface';
			$decisions[] = self::decision( $family, $state, $reason, array(
				'runtime_versions' => self::plugin_versions( $runtime, $family ),
				'plugin_files' => $plugin_files,
				'tree_sha256' => $tree_hashes,
			) );
		}

		foreach ( array( 'jetengine','jetsmartfilters' ) as $family ) {
			$decisions[] = self::decision( $family, 'semantic_attestation_required', 'premium_provider_exact_runtime_and_semantic_review_gate_remains_authoritative', array(
				'runtime_versions' => self::plugin_versions( $runtime, $family ),
			) );
		}

		$decisions[] = self::decision( 'wp-import-export', 'runtime_alignment_or_behavioral_recertification_required', 'composite_provider_requires_exact_component_versions_and_behavioral_execution_contract', array(
			'runtime_versions' => self::plugin_versions( $runtime, 'wp-import-export' ),
		) );

		$counts = array();
		foreach ( $decisions as $row ) {
			$state = isset( $row['state'] ) ? (string) $row['state'] : 'unknown';
			$counts[ $state ] = isset( $counts[ $state ] ) ? $counts[ $state ] + 1 : 1;
		}
		ksort( $counts, SORT_STRING );

		return array(
			'contract' => self::EVALUATION_CONTRACT,
			'ready' => true,
			'promotion_authorized' => false,
			'production_mutation' => false,
			'repository_source_commit_sha' => isset( $repository['source_commit_sha'] ) ? $repository['source_commit_sha'] : '',
			'counts' => $counts,
			'decisions' => $decisions,
			'blockers' => array(),
		);
	}

	public static function snapshot() {
		if ( null !== self::$snapshot ) return self::$snapshot;
		$repository = self::repository_evidence();
		$runtime = self::runtime_evidence( $repository );
		$evaluation = self::evaluate( $repository, $runtime );
		self::$snapshot = array(
			'contract' => self::CONTRACT,
			'read_only' => true,
			'authority_created' => false,
			'mutation_performed' => false,
			'remote_request_performed' => false,
			'secret_values_returned' => false,
			'build_source_commit_sha' => self::build_source_commit_sha(),
			'repository_evidence' => array(
				'present' => ! empty( $repository['present'] ),
				'valid' => ! empty( $repository['valid'] ),
				'contract' => isset( $repository['contract'] ) ? $repository['contract'] : '',
				'source_commit_sha' => isset( $repository['source_commit_sha'] ) ? $repository['source_commit_sha'] : '',
				'evidence_sha256' => isset( $repository['evidence_sha256'] ) ? $repository['evidence_sha256'] : '',
				'evidence_bytes' => isset( $repository['evidence_bytes'] ) ? (int) $repository['evidence_bytes'] : 0,
				'build_fingerprint' => isset( $repository['build_fingerprint'] ) ? $repository['build_fingerprint'] : '',
				'package_manifest_digest' => isset( $repository['package_manifest_digest'] ) ? $repository['package_manifest_digest'] : '',
				'family_count' => isset( $repository['families'] ) && is_array( $repository['families'] ) ? count( $repository['families'] ) : 0,
				'blockers' => isset( $repository['blockers'] ) ? $repository['blockers'] : array(),
			),
			'runtime' => $runtime,
			'evaluation' => $evaluation,
		);
		return self::$snapshot;
	}

	public static function decision_map() {
		$snapshot = self::snapshot();
		$evaluation = isset( $snapshot['evaluation'] ) && is_array( $snapshot['evaluation'] ) ? $snapshot['evaluation'] : array();
		$map = array();
		foreach ( isset( $evaluation['decisions'] ) && is_array( $evaluation['decisions'] ) ? $evaluation['decisions'] : array() as $row ) {
			if ( ! is_array( $row ) || empty( $row['family'] ) ) continue;
			$map[ sanitize_key( (string) $row['family'] ) ] = $row;
		}
		ksort( $map, SORT_STRING );
		return $map;
	}

	public static function summary() {
		$snapshot = self::snapshot();
		$evaluation = isset( $snapshot['evaluation'] ) && is_array( $snapshot['evaluation'] ) ? $snapshot['evaluation'] : array();
		$repository = isset( $snapshot['repository_evidence'] ) && is_array( $snapshot['repository_evidence'] ) ? $snapshot['repository_evidence'] : array();
		$counts = isset( $evaluation['counts'] ) && is_array( $evaluation['counts'] ) ? $evaluation['counts'] : array();
		return array(
			'contract' => self::CONTRACT,
			'ready' => ! empty( $evaluation['ready'] ),
			'repository_evidence_valid' => ! empty( $repository['valid'] ),
			'evidence_integrity_bound' => ! empty( $repository['valid'] ) && ! empty( $repository['evidence_sha256'] ) && ! empty( $repository['build_fingerprint'] ) && ! empty( $repository['package_manifest_digest'] ),
			'evidence_sha256' => isset( $repository['evidence_sha256'] ) ? $repository['evidence_sha256'] : '',
			'build_fingerprint' => isset( $repository['build_fingerprint'] ) ? $repository['build_fingerprint'] : '',
			'package_manifest_digest' => isset( $repository['package_manifest_digest'] ) ? $repository['package_manifest_digest'] : '',
			'promotion_authorized' => false,
			'counts' => $counts,
			'unstable_family_count' => isset( $counts['runtime_evidence_unstable'] ) ? (int) $counts['runtime_evidence_unstable'] : 0,
			'blockers' => isset( $evaluation['blockers'] ) ? $evaluation['blockers'] : array(),
		);
	}
}
