<?php

if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Zero-touch, read-only functional-gap evidence and evaluation.
 *
 * Repository evidence is generated by CI from exact packaged provider archives
 * and embedded into the installable Control Plane artifact. Runtime evidence is
 * collected locally without shell, SQL, remote requests, credential reads, or
 * mutations. Evaluation is fail-closed and never grants authority.
 */
final class MAD4B_SCP_Functional_Gap_Evidence {
	const CONTRACT = 'mad4b.functional-gap-zero-touch.v1';
	const RUNTIME_CONTRACT = 'mad4b.runtime-functional-gap-evidence.v2';
	const EVALUATION_CONTRACT = 'mad4b.functional-gap-promotion-evaluation.v2';
	const REPOSITORY_CONTRACT = 'mad4b.functional-gap-contract-evidence.v1';
	const REPOSITORY_FILE = 'config/functional-gap-contract-evidence.generated.json';
	const POLICY_CONTRACT = 'mad4b.functional-gap-policy.v1';
	const POLICY_FILE = 'config/functional-gap-policy.json';
	const MAX_TREE_FILES = 12000;
	const MAX_TREE_BYTES = 805306368;
	const MAX_SNAPSHOT_TREE_FILES = 30000;
	const MAX_SNAPSHOT_TREE_BYTES = 1610612736;
	const MAX_SNAPSHOT_SCAN_SECONDS = 20.0;
	const MAX_PROVENANCE_VERIFY_FILES = 2500;
	const MAX_PROVENANCE_VERIFY_BYTES = 268435456;
	const MAX_PROVENANCE_VERIFY_SECONDS = 8.0;

	private static $snapshot = null;
	private static $snapshot_key = '';
	private static $scan_files = 0;
	private static $scan_bytes = 0;
	private static $scan_started_at = 0.0;

	private static function policy() {
		$path = MAD4B_SCP_DIR . self::POLICY_FILE;
		$raw = is_file( $path ) && is_readable( $path ) ? file_get_contents( $path ) : false;
		$data = false === $raw ? null : json_decode( $raw, true );
		$blockers = array();
		$supported_modes = array( 'bounded_read_routes','redacted_status','exact_tree_review','runtime_only','premium_semantic','composite_behavioral' );
		if ( ! is_array( $data ) || self::POLICY_CONTRACT !== ( isset( $data['contract'] ) ? (string) $data['contract'] : '' ) ) $blockers[] = 'functional_gap_policy_invalid';
		if ( is_array( $data ) ) {
			if ( 'deny' !== ( isset( $data['default_mutation'] ) ? sanitize_key( (string) $data['default_mutation'] ) : '' ) ) $blockers[] = 'functional_gap_policy_mutation_default_not_deny';
			if ( ! array_key_exists( 'promotion_authorized', $data ) || false !== $data['promotion_authorized'] ) $blockers[] = 'functional_gap_policy_promotion_not_false';
			$families = isset( $data['families'] ) && is_array( $data['families'] ) ? $data['families'] : array();
			if ( empty( $families ) ) $blockers[] = 'functional_gap_policy_families_missing';
			$prefix_owners = array();
			foreach ( $families as $family_id => $row ) {
				$family = sanitize_key( (string) $family_id );
				if ( '' === $family || $family !== (string) $family_id || ! is_array( $row ) ) { $blockers[] = 'functional_gap_policy_family_identity_invalid'; continue; }
				$mode = isset( $row['evaluation_mode'] ) ? sanitize_key( (string) $row['evaluation_mode'] ) : '';
				if ( ! in_array( $mode, $supported_modes, true ) ) $blockers[] = 'functional_gap_policy_mode_invalid_' . $family;
				$matches = isset( $row['match'] ) && is_array( $row['match'] ) ? array_values( array_filter( array_map( 'sanitize_text_field', $row['match'] ) ) ) : array();
				$versioned_matches = isset( $row['versioned_match'] ) && is_array( $row['versioned_match'] ) ? array_values( array_filter( array_map( 'sanitize_text_field', $row['versioned_match'] ) ) ) : array();
				if ( empty( $matches ) && empty( $versioned_matches ) ) $blockers[] = 'functional_gap_policy_match_missing_' . $family;
				$identity_prefixes = array();
				foreach ( $matches as $match ) {
					$prefix = self::normalize_plugin_file( $match );
					if ( '' === $prefix ) { $blockers[] = 'functional_gap_policy_match_invalid_' . $family; continue; }
					$identity_prefixes[] = $prefix;
				}
				foreach ( $versioned_matches as $base ) {
					$base = trim( self::normalize_plugin_file( $base ), '/' );
					if ( '' === $base || 1 === preg_match( '/[^a-z0-9._-]/', $base ) ) { $blockers[] = 'functional_gap_policy_versioned_match_invalid_' . $family; continue; }
					$identity_prefixes[] = $base . '-v';
				}
				foreach ( $identity_prefixes as $prefix ) {
					foreach ( $prefix_owners as $known_prefix => $known_family ) {
						if ( $known_family === $family ) continue;
						if ( 0 === strpos( $prefix, $known_prefix ) || 0 === strpos( $known_prefix, $prefix ) ) $blockers[] = 'functional_gap_policy_match_overlap_' . $known_family . '_' . $family;
					}
					$prefix_owners[ $prefix ] = $family;
				}
				$repo_backed = ! empty( $row['repository_evidence'] );
				$artifacts = isset( $row['repository_artifacts'] ) && is_array( $row['repository_artifacts'] ) ? array_values( array_filter( array_map( 'sanitize_text_field', $row['repository_artifacts'] ) ) ) : array();
				if ( $repo_backed && empty( $artifacts ) ) $blockers[] = 'functional_gap_policy_repository_artifacts_missing_' . $family;
				if ( ! $repo_backed && ! empty( $artifacts ) ) $blockers[] = 'functional_gap_policy_runtime_only_artifacts_present_' . $family;
				if ( 'bounded_read_routes' === $mode ) {
					if ( empty( $row['required_get_routes'] ) || ! is_array( $row['required_get_routes'] ) ) $blockers[] = 'functional_gap_policy_required_routes_missing_' . $family;
					if ( empty( $row['safe_now'] ) || ! is_array( $row['safe_now'] ) || empty( $row['blocked'] ) || ! is_array( $row['blocked'] ) ) $blockers[] = 'functional_gap_policy_read_boundary_missing_' . $family;
				}
				if ( 'redacted_status' === $mode ) {
					if ( empty( $row['redacted_secret_option_keys'] ) || ! is_array( $row['redacted_secret_option_keys'] ) ) $blockers[] = 'functional_gap_policy_redaction_keys_missing_' . $family;
					if ( empty( $row['required_status_option_keys'] ) || ! is_array( $row['required_status_option_keys'] ) ) $blockers[] = 'functional_gap_policy_status_keys_missing_' . $family;
					if ( empty( $row['safe_now'] ) || ! is_array( $row['safe_now'] ) || empty( $row['blocked'] ) || ! is_array( $row['blocked'] ) ) $blockers[] = 'functional_gap_policy_redacted_boundary_missing_' . $family;
				}
			}
			$probes = isset( $data['probes'] ) && is_array( $data['probes'] ) ? $data['probes'] : array();
			foreach ( array( 'rest_route_regex','ajax_hook_regex','cron_hook_regex','secret_key_regex' ) as $regex_key ) {
				$value = isset( $probes[ $regex_key ] ) ? trim( (string) $probes[ $regex_key ] ) : '';
				$pattern = '' === $value ? '' : '~' . str_replace( '~', '\\~', $value ) . '~i';
				if ( '' === $pattern || false === @preg_match( $pattern, '' ) ) $blockers[] = 'functional_gap_policy_probe_regex_invalid_' . $regex_key;
			}
			if ( empty( $probes['option_keys'] ) || ! is_array( $probes['option_keys'] ) ) $blockers[] = 'functional_gap_policy_option_probe_set_missing';
			if ( empty( $probes['constants'] ) || ! is_array( $probes['constants'] ) ) $blockers[] = 'functional_gap_policy_constant_probe_set_missing';
		}
		$blockers = array_values( array_unique( array_filter( array_map( 'sanitize_key', $blockers ) ) ) );
		return array(
			'valid' => empty( $blockers ),
			'contract' => is_array( $data ) && isset( $data['contract'] ) ? (string) $data['contract'] : '',
			'sha256' => false === $raw ? '' : hash( 'sha256', $raw ),
			'bytes' => false === $raw ? 0 : strlen( $raw ),
			'data' => is_array( $data ) ? $data : array(),
			'blockers' => $blockers,
		);
	}

	private static function targets() {
		$policy = self::policy();
		$out = array();
		foreach ( isset( $policy['data']['families'] ) && is_array( $policy['data']['families'] ) ? $policy['data']['families'] : array() as $family => $row ) {
			if ( ! is_array( $row ) ) continue;
			$family = sanitize_key( (string) $family );
			if ( '' !== $family ) $out[ $family ] = $row;
		}
		ksort( $out, SORT_STRING );
		return $out;
	}

	private static function plugin_matches_policy_family( $plugin_file, array $rule ) {
		$plugin_file = self::normalize_plugin_file( $plugin_file );
		foreach ( isset( $rule['match'] ) && is_array( $rule['match'] ) ? $rule['match'] : array() as $prefix ) {
			$prefix = self::normalize_plugin_file( $prefix );
			if ( '' !== $prefix && 0 === strpos( $plugin_file, $prefix ) ) return true;
		}
		foreach ( isset( $rule['versioned_match'] ) && is_array( $rule['versioned_match'] ) ? $rule['versioned_match'] : array() as $base ) {
			$base = trim( self::normalize_plugin_file( $base ), '/' );
			if ( '' === $base ) continue;
			if ( 1 === preg_match( '#^' . preg_quote( $base, '#' ) . '-v[0-9]+(?:\\.[0-9]+)*/#', $plugin_file ) ) return true;
		}
		return false;
	}


	private static function normalize_plugin_file( $value ) {
		return strtolower( ltrim( str_replace( '\\', '/', (string) $value ), '/' ) );
	}

	private static function runtime_identity_key() {
		if ( ! function_exists( 'get_plugins' ) ) require_once ABSPATH . 'wp-admin/includes/plugin.php';
		$plugins = get_plugins();
		if ( ! is_array( $plugins ) ) $plugins = array();
		ksort( $plugins, SORT_STRING );
		$active = array();
		foreach ( array_merge( (array) get_option( 'active_plugins', array() ), is_multisite() ? array_keys( (array) get_site_option( 'active_sitewide_plugins', array() ) ) : array() ) as $plugin_file ) {
			$active[ self::normalize_plugin_file( $plugin_file ) ] = true;
		}
		$rows = array();
		$targets = self::targets();
		foreach ( $plugins as $plugin_file => $headers ) {
			$normalized = self::normalize_plugin_file( $plugin_file );
			$matched = false;
			foreach ( $targets as $rule ) {
				if ( is_array( $rule ) && self::plugin_matches_policy_family( $normalized, $rule ) ) { $matched = true; break; }
			}
			if ( ! $matched ) continue;
			$main = WP_PLUGIN_DIR . '/' . ltrim( str_replace( '\\', '/', (string) $plugin_file ), '/' );
			$main_sha = is_file( $main ) ? @hash_file( 'sha256', $main ) : false;
			$rows[] = implode( "\0", array(
				$normalized,
				isset( $headers['Version'] ) ? (string) $headers['Version'] : '',
				isset( $active[ $normalized ] ) ? '1' : '0',
				is_file( $main ) ? (string) @filesize( $main ) : '-1',
				false !== $main_sha ? (string) $main_sha : '',
			) );
		}
		foreach ( array( MAD4B_SCP_DIR . self::REPOSITORY_FILE, MAD4B_SCP_DIR . self::POLICY_FILE, MAD4B_SCP_DIR . 'MAD4B-BUILD-PROVENANCE.json' ) as $path ) {
			$file_sha = is_file( $path ) ? @hash_file( 'sha256', $path ) : false;
			$rows[] = implode( "\0", array(
				basename( $path ),
				is_file( $path ) ? (string) @filesize( $path ) : '-1',
				false !== $file_sha ? (string) $file_sha : '',
			) );
		}
		sort( $rows, SORT_STRING );
		return hash( 'sha256', implode( "\n", $rows ) );
	}

	private static function plugin_tree_once( $plugin_file ) {
		$plugin_file = ltrim( str_replace( '\\', '/', (string) $plugin_file ), '/' );
		$dirname = dirname( $plugin_file );
		$root = '.' === $dirname ? WP_PLUGIN_DIR : WP_PLUGIN_DIR . '/' . $dirname;
		if ( ! is_dir( $root ) ) return array( 'file_count' => 0, 'total_bytes' => 0, 'tree_sha256' => '' );

		$rows = array();
		$total = 0;
		try {
			$iterator = new RecursiveIteratorIterator(
				new RecursiveDirectoryIterator( $root, FilesystemIterator::SKIP_DOTS ),
				RecursiveIteratorIterator::LEAVES_ONLY
			);
			foreach ( $iterator as $file ) {
				if ( $file->isLink() ) return array( 'file_count'=>count( $rows ), 'total_bytes'=>$total, 'tree_sha256'=>'', 'error'=>'tree_symlink_detected' );
				if ( ! $file->isFile() ) continue;
				if ( self::$scan_started_at > 0 && microtime( true ) - self::$scan_started_at > self::MAX_SNAPSHOT_SCAN_SECONDS ) return array( 'file_count'=>count( $rows ), 'total_bytes'=>$total, 'tree_sha256'=>'', 'error'=>'snapshot_scan_time_budget_exceeded', 'scan_budget_exceeded'=>true );
				$path = str_replace( '\\', '/', $file->getPathname() );
				$base = rtrim( str_replace( '\\', '/', $root ), '/' ) . '/';
				$relative = 0 === strpos( $path, $base ) ? substr( $path, strlen( $base ) ) : basename( $path );
				$size = (int) $file->getSize();
				$mtime = (int) $file->getMTime();
				if ( count( $rows ) + 1 > self::MAX_TREE_FILES || $total + $size > self::MAX_TREE_BYTES ) {
					return array( 'file_count'=>count( $rows ), 'total_bytes'=>$total, 'tree_sha256'=>'', 'error'=>'tree_scan_budget_exceeded', 'scan_budget_exceeded'=>true );
				}
				if ( self::$scan_files + 1 > self::MAX_SNAPSHOT_TREE_FILES || self::$scan_bytes + $size > self::MAX_SNAPSHOT_TREE_BYTES ) {
					return array( 'file_count'=>count( $rows ), 'total_bytes'=>$total, 'tree_sha256'=>'', 'error'=>'snapshot_scan_budget_exceeded', 'scan_budget_exceeded'=>true );
				}
				$digest = hash_file( 'sha256', $file->getPathname() );
				if ( false === $digest ) return array( 'file_count'=>count( $rows ), 'total_bytes'=>$total, 'tree_sha256'=>'', 'error'=>'tree_file_hash_failed' );
				clearstatcache( true, $file->getPathname() );
				$after_size = @filesize( $file->getPathname() );
				$after_mtime = @filemtime( $file->getPathname() );
				if ( false === $after_size || false === $after_mtime || (int) $after_size !== $size || (int) $after_mtime !== $mtime ) {
					return array( 'file_count'=>count( $rows ), 'total_bytes'=>$total, 'tree_sha256'=>'', 'error'=>'tree_file_changed_during_hash' );
				}
				++self::$scan_files;
				self::$scan_bytes += $size;
				$total += $size;
				$rows[] = $relative . "\0" . $size . "\0" . $digest;
			}
		} catch ( Exception $e ) {
			return array( 'file_count' => 0, 'total_bytes' => 0, 'tree_sha256' => '', 'error' => 'tree_scan_failed' );
		}
		sort( $rows, SORT_STRING );
		return array(
			'file_count' => count( $rows ),
			'total_bytes' => $total,
			'tree_sha256' => hash( 'sha256', implode( "\n", $rows ) ),
		);
	}

	private static function plugin_tree( $plugin_file, array $expected_hashes = array() ) {
		$expected = array();
		foreach ( $expected_hashes as $digest ) {
			$digest = strtolower( trim( (string) $digest ) );
			if ( preg_match( '/^[a-f0-9]{64}$/', $digest ) ) $expected[ $digest ] = true;
		}
		$first = self::plugin_tree_once( $plugin_file );
		if ( ! empty( $first['error'] ) ) {
			$first['scan_stable'] = false;
			$first['scan_attempts'] = 1;
			$first['comparison'] = sanitize_key( (string) $first['error'] );
			return $first;
		}
		$first_hash = isset( $first['tree_sha256'] ) ? strtolower( (string) $first['tree_sha256'] ) : '';
		if ( '' !== $first_hash && isset( $expected[ $first_hash ] ) ) {
			$first['scan_stable'] = true;
			$first['scan_attempts'] = 1;
			$first['comparison'] = 'exact_repository_match';
			return $first;
		}
		$second = self::plugin_tree_once( $plugin_file );
		if ( ! empty( $second['error'] ) ) {
			$second['scan_stable'] = false;
			$second['scan_attempts'] = 2;
			$second['first_tree_sha256'] = $first_hash;
			$second['comparison'] = sanitize_key( (string) $second['error'] );
			return $second;
		}
		$second_hash = isset( $second['tree_sha256'] ) ? strtolower( (string) $second['tree_sha256'] ) : '';
		$stable = '' !== $first_hash && '' !== $second_hash && hash_equals( $first_hash, $second_hash )
			&& (int) ( isset( $first['file_count'] ) ? $first['file_count'] : -1 ) === (int) ( isset( $second['file_count'] ) ? $second['file_count'] : -2 )
			&& (int) ( isset( $first['total_bytes'] ) ? $first['total_bytes'] : -1 ) === (int) ( isset( $second['total_bytes'] ) ? $second['total_bytes'] : -2 );
		$second['scan_stable'] = $stable;
		$second['scan_attempts'] = 2;
		$second['first_tree_sha256'] = $first_hash;
		$second['comparison'] = $stable ? ( isset( $expected[ $second_hash ] ) ? 'exact_repository_match' : 'stable_runtime_drift' ) : 'runtime_tree_changed_during_scan';
		if ( ! $stable ) $second['error'] = 'runtime_tree_unstable';
		return $second;
	}

	private static function repository_tree_hashes( array $repository, $family ) {
		$out = array();
		$family_row = isset( $repository['families'][ $family ] ) && is_array( $repository['families'][ $family ] ) ? $repository['families'][ $family ] : array();
		foreach ( isset( $family_row['artifacts'] ) && is_array( $family_row['artifacts'] ) ? $family_row['artifacts'] : array() as $artifact ) {
			$digest = isset( $artifact['package_tree']['tree_sha256'] ) ? strtolower( trim( (string) $artifact['package_tree']['tree_sha256'] ) ) : '';
			if ( preg_match( '/^[a-f0-9]{64}$/', $digest ) ) $out[ $digest ] = true;
		}
		return array_keys( $out );
	}

	private static function verify_build_provenance_package( array $data ) {
		$entries = isset( $data['package_files'] ) && is_array( $data['package_files'] ) ? $data['package_files'] : array();
		if ( empty( $entries ) ) return array( 'valid'=>false, 'blockers'=>array( 'build_provenance_package_files_missing' ) );
		$started = microtime( true );
		$canonical = array();
		$declared = array();
		$total_bytes = 0;
		$verified_files = 0;
		$blockers = array();

		foreach ( $entries as $row ) {
			if ( ! is_array( $row ) ) { $blockers[] = 'build_provenance_package_file_row_invalid'; continue; }
			$rel = isset( $row['path'] ) ? str_replace( '\\', '/', ltrim( trim( (string) $row['path'] ), '/' ) ) : '';
			$expected_bytes = isset( $row['bytes'] ) ? (int) $row['bytes'] : -1;
			$expected_sha = isset( $row['sha256'] ) ? strtolower( trim( (string) $row['sha256'] ) ) : '';
			if ( '' === $rel || false !== strpos( $rel, "\0" ) || preg_match( '#(^|/)\.\.?(/|$)#', $rel ) ) { $blockers[] = 'build_provenance_package_path_invalid'; continue; }
			if ( isset( $declared[ $rel ] ) ) { $blockers[] = 'build_provenance_package_path_duplicate'; continue; }
			if ( $expected_bytes < 0 || ! preg_match( '/^[a-f0-9]{64}$/', $expected_sha ) ) { $blockers[] = 'build_provenance_package_file_identity_invalid'; continue; }
			if ( $verified_files + 1 > self::MAX_PROVENANCE_VERIFY_FILES || $total_bytes + $expected_bytes > self::MAX_PROVENANCE_VERIFY_BYTES || microtime( true ) - $started > self::MAX_PROVENANCE_VERIFY_SECONDS ) {
				$blockers[] = 'build_provenance_verification_budget_exceeded';
				break;
			}
			$path = MAD4B_SCP_DIR . $rel;
			if ( ! is_file( $path ) || ! is_readable( $path ) ) { $blockers[] = 'build_provenance_package_file_missing'; continue; }
			$actual_bytes = @filesize( $path );
			$actual_sha = @hash_file( 'sha256', $path );
			if ( false === $actual_bytes || (int) $actual_bytes !== $expected_bytes ) $blockers[] = 'build_provenance_package_file_bytes_mismatch';
			if ( false === $actual_sha || ! hash_equals( $expected_sha, strtolower( (string) $actual_sha ) ) ) $blockers[] = 'build_provenance_package_file_sha256_mismatch';
			$declared[ $rel ] = true;
			++$verified_files;
			$total_bytes += max( 0, $expected_bytes );
			$canonical[] = $rel . "\0" . $expected_bytes . "\0" . $expected_sha . "\n";
		}

		$actual_files = array();
		try {
			$iterator = new RecursiveIteratorIterator(
				new RecursiveDirectoryIterator( MAD4B_SCP_DIR, FilesystemIterator::SKIP_DOTS ),
				RecursiveIteratorIterator::LEAVES_ONLY
			);
			foreach ( $iterator as $file ) {
				if ( $file->isLink() ) { $blockers[] = 'build_provenance_package_symlink_detected'; continue; }
				if ( ! $file->isFile() ) continue;
				$path = str_replace( '\\', '/', $file->getPathname() );
				$base = rtrim( str_replace( '\\', '/', MAD4B_SCP_DIR ), '/' ) . '/';
				$rel = 0 === strpos( $path, $base ) ? substr( $path, strlen( $base ) ) : '';
				if ( '' === $rel || 'MAD4B-BUILD-PROVENANCE.json' === $rel ) continue;
				$actual_files[ $rel ] = true;
				if ( count( $actual_files ) > self::MAX_PROVENANCE_VERIFY_FILES ) { $blockers[] = 'build_provenance_actual_file_budget_exceeded'; break; }
			}
		} catch ( Exception $e ) {
			$blockers[] = 'build_provenance_actual_file_enumeration_failed';
		}
		$missing_from_manifest = array_diff_key( $actual_files, $declared );
		$missing_from_runtime = array_diff_key( $declared, $actual_files );
		if ( ! empty( $missing_from_manifest ) ) $blockers[] = 'build_provenance_untracked_runtime_files';
		if ( ! empty( $missing_from_runtime ) ) $blockers[] = 'build_provenance_declared_files_missing';

		sort( $canonical, SORT_STRING );
		$manifest = hash( 'sha256', implode( '', $canonical ) );
		$declared_manifest = isset( $data['package_manifest_digest'] ) ? strtolower( trim( (string) $data['package_manifest_digest'] ) ) : '';
		if ( ! preg_match( '/^[a-f0-9]{64}$/', $declared_manifest ) || ! hash_equals( $declared_manifest, $manifest ) ) $blockers[] = 'build_provenance_manifest_recompute_mismatch';

		$version = isset( $data['control_plane_version'] ) ? trim( (string) $data['control_plane_version'] ) : '';
		$source = isset( $data['source_commit_sha'] ) ? strtolower( trim( (string) $data['source_commit_sha'] ) ) : '';
		$adapter_version = isset( $data['mcp_adapter_version'] ) ? trim( (string) $data['mcp_adapter_version'] ) : '';
		$adapter_sha = isset( $data['mcp_adapter_sha256'] ) ? strtolower( trim( (string) $data['mcp_adapter_sha256'] ) ) : '';
		$adapter_rel = 'dependencies/mcp-adapter.zip';
		$adapter_row = null;
		foreach ( $entries as $row ) if ( is_array( $row ) && isset( $row['path'] ) && $adapter_rel === str_replace( '\\', '/', ltrim( (string) $row['path'], '/' ) ) ) { $adapter_row = $row; break; }
		if ( ! is_array( $adapter_row ) || ! isset( $adapter_row['sha256'] ) || ! hash_equals( $adapter_sha, strtolower( (string) $adapter_row['sha256'] ) ) ) $blockers[] = 'build_provenance_adapter_sha_mismatch';

		$payload = "mad4b.build-fingerprint.v1\n" . $version . "\n" . $source . "\n" . $manifest . "\n" . $adapter_version . "\n" . $adapter_sha . "\n";
		$fingerprint = hash( 'sha256', $payload );
		$declared_fingerprint = isset( $data['build_fingerprint'] ) ? strtolower( trim( (string) $data['build_fingerprint'] ) ) : '';
		if ( ! preg_match( '/^[a-f0-9]{64}$/', $declared_fingerprint ) || ! hash_equals( $declared_fingerprint, $fingerprint ) ) $blockers[] = 'build_provenance_fingerprint_recompute_mismatch';

		$blockers = array_values( array_unique( array_filter( array_map( 'sanitize_key', $blockers ) ) ) );
		return array(
			'valid' => empty( $blockers ),
			'blockers' => $blockers,
			'verified_file_count' => $verified_files,
			'verified_bytes' => $total_bytes,
			'actual_file_count' => count( $actual_files ),
			'elapsed_ms' => (int) round( ( microtime( true ) - $started ) * 1000 ),
			'recomputed_package_manifest_digest' => $manifest,
			'recomputed_build_fingerprint' => $fingerprint,
			'integrity_level' => empty( $blockers ) ? 'self_consistent_package' : 'failed_closed',
			'external_cryptographic_attestation' => false,
		);
	}

	private static function build_provenance() {
		$path = MAD4B_SCP_DIR . 'MAD4B-BUILD-PROVENANCE.json';
		if ( ! is_file( $path ) || ! is_readable( $path ) ) return array( 'valid'=>false, 'blockers'=>array( 'build_provenance_missing' ) );
		$raw = file_get_contents( $path );
		$data = false === $raw ? null : json_decode( $raw, true );
		if ( ! is_array( $data ) || 'mad4b.build-provenance.v1' !== ( isset( $data['contract'] ) ? (string) $data['contract'] : '' ) ) return array( 'valid'=>false, 'blockers'=>array( 'build_provenance_invalid' ) );
		$source = isset( $data['source_commit_sha'] ) ? strtolower( trim( (string) $data['source_commit_sha'] ) ) : '';
		$fingerprint = isset( $data['build_fingerprint'] ) ? strtolower( trim( (string) $data['build_fingerprint'] ) ) : '';
		$manifest = isset( $data['package_manifest_digest'] ) ? strtolower( trim( (string) $data['package_manifest_digest'] ) ) : '';
		$blockers = array();
		if ( ! preg_match( '/^[a-f0-9]{40}$/', $source ) ) $blockers[] = 'build_provenance_source_invalid';
		if ( ! preg_match( '/^[a-f0-9]{64}$/', $fingerprint ) ) $blockers[] = 'build_provenance_fingerprint_invalid';
		if ( ! preg_match( '/^[a-f0-9]{64}$/', $manifest ) ) $blockers[] = 'build_provenance_manifest_invalid';
		$files = array();
		foreach ( isset( $data['package_files'] ) && is_array( $data['package_files'] ) ? $data['package_files'] : array() as $row ) {
			if ( ! is_array( $row ) || empty( $row['path'] ) ) continue;
			$files[ str_replace( '\\', '/', ltrim( (string) $row['path'], '/' ) ) ] = $row;
		}
		$package_verification = self::verify_build_provenance_package( $data );
		if ( empty( $package_verification['valid'] ) ) $blockers = array_merge( $blockers, isset( $package_verification['blockers'] ) ? (array) $package_verification['blockers'] : array( 'build_provenance_package_verification_failed' ) );
		$blockers = array_values( array_unique( array_filter( array_map( 'sanitize_key', $blockers ) ) ) );
		return array(
			'valid' => empty( $blockers ),
			'source_commit_sha' => $source,
			'build_fingerprint' => $fingerprint,
			'package_manifest_digest' => $manifest,
			'package_files' => $files,
			'package_verification' => $package_verification,
			'blockers' => $blockers,
		);
	}

	private static function repository_evidence() {
		$path = MAD4B_SCP_DIR . self::REPOSITORY_FILE;
		if ( ! is_file( $path ) || ! is_readable( $path ) ) {
			return array(
				'present' => false,
				'valid' => false,
				'contract' => '',
				'source_commit_sha' => '',
				'families' => array(),
				'blockers' => array( 'repository_evidence_missing' ),
			);
		}
		$raw = file_get_contents( $path );
		$data = false === $raw ? null : json_decode( $raw, true );
		$evidence_sha256 = false === $raw ? '' : hash( 'sha256', $raw );
		$evidence_bytes = false === $raw ? 0 : strlen( $raw );
		if ( ! is_array( $data ) || self::REPOSITORY_CONTRACT !== ( isset( $data['contract'] ) ? (string) $data['contract'] : '' ) ) {
			return array(
				'present' => true,
				'valid' => false,
				'contract' => is_array( $data ) && isset( $data['contract'] ) ? (string) $data['contract'] : '',
				'source_commit_sha' => '',
				'families' => array(),
				'blockers' => array( 'repository_evidence_invalid' ),
			);
		}

		$blockers = array();
		$source = isset( $data['source_commit_sha'] ) ? strtolower( trim( (string) $data['source_commit_sha'] ) ) : '';
		$policy = self::policy();
		$provenance = self::build_provenance();
		$build_source = ! empty( $provenance['source_commit_sha'] ) ? (string) $provenance['source_commit_sha'] : self::build_source_commit_sha();
		if ( '' === $source || ! preg_match( '/^[a-f0-9]{40}$/', $source ) ) $blockers[] = 'repository_evidence_source_missing';
		if ( empty( $policy['valid'] ) ) $blockers = array_merge( $blockers, isset( $policy['blockers'] ) ? (array) $policy['blockers'] : array( 'functional_gap_policy_invalid' ) );
		if ( self::POLICY_CONTRACT !== ( isset( $data['policy_contract'] ) ? (string) $data['policy_contract'] : '' ) ) $blockers[] = 'repository_evidence_policy_contract_mismatch';
		$embedded_policy_sha = isset( $data['policy_sha256'] ) ? strtolower( trim( (string) $data['policy_sha256'] ) ) : '';
		if ( ! preg_match( '/^[a-f0-9]{64}$/', $embedded_policy_sha ) || empty( $policy['sha256'] ) || ! hash_equals( (string) $policy['sha256'], $embedded_policy_sha ) ) $blockers[] = 'repository_evidence_policy_sha256_mismatch';
		if ( empty( $provenance['valid'] ) ) $blockers = array_merge( $blockers, isset( $provenance['blockers'] ) ? (array) $provenance['blockers'] : array( 'build_provenance_invalid' ) );
		if ( '' !== $build_source && '' !== $source && ! hash_equals( $build_source, $source ) ) $blockers[] = 'repository_evidence_build_source_mismatch';
		$provenance_row = isset( $provenance['package_files'][ self::REPOSITORY_FILE ] ) && is_array( $provenance['package_files'][ self::REPOSITORY_FILE ] ) ? $provenance['package_files'][ self::REPOSITORY_FILE ] : null;
		if ( ! is_array( $provenance_row ) ) {
			$blockers[] = 'repository_evidence_not_bound_in_build_provenance';
		} else {
			$expected_sha = isset( $provenance_row['sha256'] ) ? strtolower( trim( (string) $provenance_row['sha256'] ) ) : '';
			$expected_bytes = isset( $provenance_row['bytes'] ) ? (int) $provenance_row['bytes'] : -1;
			if ( ! preg_match( '/^[a-f0-9]{64}$/', $expected_sha ) || ! hash_equals( $expected_sha, $evidence_sha256 ) ) $blockers[] = 'repository_evidence_sha256_mismatch';
			if ( $expected_bytes < 0 || $expected_bytes !== $evidence_bytes ) $blockers[] = 'repository_evidence_bytes_mismatch';
		}
		$policy_provenance_row = isset( $provenance['package_files'][ self::POLICY_FILE ] ) && is_array( $provenance['package_files'][ self::POLICY_FILE ] ) ? $provenance['package_files'][ self::POLICY_FILE ] : null;
		if ( ! is_array( $policy_provenance_row ) ) {
			$blockers[] = 'functional_gap_policy_not_bound_in_build_provenance';
		} else {
			$expected_policy_sha = isset( $policy_provenance_row['sha256'] ) ? strtolower( trim( (string) $policy_provenance_row['sha256'] ) ) : '';
			$expected_policy_bytes = isset( $policy_provenance_row['bytes'] ) ? (int) $policy_provenance_row['bytes'] : -1;
			if ( ! preg_match( '/^[a-f0-9]{64}$/', $expected_policy_sha ) || empty( $policy['sha256'] ) || ! hash_equals( $expected_policy_sha, (string) $policy['sha256'] ) ) $blockers[] = 'functional_gap_policy_sha256_mismatch';
			if ( $expected_policy_bytes < 0 || $expected_policy_bytes !== (int) ( isset( $policy['bytes'] ) ? $policy['bytes'] : 0 ) ) $blockers[] = 'functional_gap_policy_bytes_mismatch';
		}
		$blockers = array_values( array_unique( array_filter( array_map( 'sanitize_key', $blockers ) ) ) );

		return array(
			'present' => true,
			'valid' => empty( $blockers ),
			'contract' => (string) $data['contract'],
			'source_commit_sha' => $source,
			'evidence_sha256' => $evidence_sha256,
			'evidence_bytes' => $evidence_bytes,
			'policy_contract' => isset( $policy['contract'] ) ? (string) $policy['contract'] : '',
			'policy_sha256' => isset( $policy['sha256'] ) ? (string) $policy['sha256'] : '',
			'policy_bytes' => isset( $policy['bytes'] ) ? (int) $policy['bytes'] : 0,
			'build_fingerprint' => isset( $provenance['build_fingerprint'] ) ? (string) $provenance['build_fingerprint'] : '',
			'package_manifest_digest' => isset( $provenance['package_manifest_digest'] ) ? (string) $provenance['package_manifest_digest'] : '',
			'package_integrity' => isset( $provenance['package_verification'] ) && is_array( $provenance['package_verification'] ) ? $provenance['package_verification'] : array(),
			'families' => isset( $data['families'] ) && is_array( $data['families'] ) ? $data['families'] : array(),
			'blockers' => $blockers,
		);
	}

	private static function build_source_commit_sha() {
		$path = MAD4B_SCP_DIR . 'MAD4B-BUILD-PROVENANCE.json';
		if ( ! is_file( $path ) || ! is_readable( $path ) ) return '';
		$raw = file_get_contents( $path );
		$data = false === $raw ? null : json_decode( $raw, true );
		$sha = is_array( $data ) && isset( $data['source_commit_sha'] ) ? strtolower( trim( (string) $data['source_commit_sha'] ) ) : '';
		return preg_match( '/^[a-f0-9]{40}$/', $sha ) ? $sha : '';
	}

	private static function runtime_evidence( array $repository = array() ) {
		if ( ! function_exists( 'get_plugins' ) ) require_once ABSPATH . 'wp-admin/includes/plugin.php';
		$policy = self::policy();
		$probes = isset( $policy['data']['probes'] ) && is_array( $policy['data']['probes'] ) ? $policy['data']['probes'] : array();
		$make_pattern = static function ( $value ) {
			$value = trim( (string) $value );
			if ( '' === $value ) return '';
			$pattern = '~' . str_replace( '~', '\\~', $value ) . '~i';
			return false === @preg_match( $pattern, '' ) ? '' : $pattern;
		};
		$rest_pattern = $make_pattern( isset( $probes['rest_route_regex'] ) ? $probes['rest_route_regex'] : '' );
		$ajax_pattern = $make_pattern( isset( $probes['ajax_hook_regex'] ) ? $probes['ajax_hook_regex'] : '' );
		$cron_pattern = $make_pattern( isset( $probes['cron_hook_regex'] ) ? $probes['cron_hook_regex'] : '' );
		$secret_pattern = $make_pattern( isset( $probes['secret_key_regex'] ) ? $probes['secret_key_regex'] : '' );
		$option_candidates = isset( $probes['option_keys'] ) && is_array( $probes['option_keys'] ) ? array_values( array_filter( array_map( 'sanitize_text_field', $probes['option_keys'] ) ) ) : array();
		$constant_candidates = isset( $probes['constants'] ) && is_array( $probes['constants'] ) ? array_values( array_filter( array_map( 'sanitize_text_field', $probes['constants'] ) ) ) : array();

		$deep_scan = ! empty( $repository['valid'] );
		$plugin_map = get_plugins();
		$active = (array) get_option( 'active_plugins', array() );
		$network_active = is_multisite() ? array_keys( (array) get_site_option( 'active_sitewide_plugins', array() ) ) : array();
		$active_set = array();
		foreach ( array_merge( $active, $network_active ) as $plugin_file ) $active_set[ self::normalize_plugin_file( $plugin_file ) ] = true;

		$families = array();
		foreach ( self::targets() as $family => $rule ) {
			$families[ $family ] = array();
			foreach ( $plugin_map as $plugin_file => $headers ) {
				$normalized = self::normalize_plugin_file( $plugin_file );
				if ( ! is_array( $rule ) || ! self::plugin_matches_policy_family( $normalized, $rule ) ) continue;
				$is_active = isset( $active_set[ $normalized ] );
				$families[ $family ][] = array(
					'plugin_file' => (string) $plugin_file,
					'name' => isset( $headers['Name'] ) ? sanitize_text_field( (string) $headers['Name'] ) : '',
					'version' => isset( $headers['Version'] ) ? sanitize_text_field( (string) $headers['Version'] ) : '',
					'active' => $is_active,
					'plugin_tree' => ! $is_active ? array( 'file_count'=>0, 'total_bytes'=>0, 'tree_sha256'=>'', 'scan_stable'=>false, 'scan_attempts'=>0, 'comparison'=>'inactive_not_scanned' ) : ( $deep_scan ? self::plugin_tree( $plugin_file, self::repository_tree_hashes( $repository, $family ) ) : array( 'file_count'=>0, 'total_bytes'=>0, 'tree_sha256'=>'', 'scan_stable'=>false, 'scan_attempts'=>0, 'comparison'=>'repository_evidence_invalid_not_scanned' ) ),
				);
			}
			usort( $families[ $family ], static function ( $a, $b ) { return strcmp( $a['plugin_file'], $b['plugin_file'] ); } );
		}

		$routes = array();
		if ( function_exists( 'rest_get_server' ) ) {
			$server = rest_get_server();
			if ( is_object( $server ) && method_exists( $server, 'get_routes' ) ) {
				foreach ( $server->get_routes() as $route => $handlers ) {
					if ( '' === $rest_pattern || 1 !== preg_match( $rest_pattern, (string) $route ) ) continue;
					$methods = array();
					foreach ( (array) $handlers as $handler ) {
						if ( ! is_array( $handler ) || empty( $handler['methods'] ) ) continue;
						foreach ( (array) $handler['methods'] as $method => $enabled ) {
							if ( is_int( $method ) ) $method = $enabled;
							if ( $enabled ) $methods[] = strtoupper( (string) $method );
						}
					}
					$methods = array_values( array_unique( $methods ) );
					sort( $methods, SORT_STRING );
					$routes[] = array( 'route' => (string) $route, 'methods' => $methods );
				}
			}
		}
		usort( $routes, static function ( $a, $b ) { return strcmp( $a['route'], $b['route'] ); } );

		$ajax = array();
		global $wp_filter;
		foreach ( (array) $wp_filter as $hook => $hook_obj ) {
			if ( 0 !== strpos( (string) $hook, 'wp_ajax_' ) && 0 !== strpos( (string) $hook, 'wp_ajax_nopriv_' ) ) continue;
			if ( '' === $ajax_pattern || 1 !== preg_match( $ajax_pattern, (string) $hook ) ) continue;
			$ajax[] = (string) $hook;
		}
		$ajax = array_values( array_unique( $ajax ) );
		sort( $ajax, SORT_STRING );

		$options = array();
		foreach ( $option_candidates as $key ) {
			$value = get_option( $key, null );
			$row = array( 'exists' => null !== $value );
			if ( '' !== $secret_pattern && 1 === preg_match( $secret_pattern, $key ) ) {
				$row['redacted'] = true;
				$row['configured'] = null !== $value && '' !== (string) $value;
			} else {
				$row['redacted'] = false;
				$row['type'] = gettype( $value );
				if ( is_array( $value ) ) $row['item_count'] = count( $value );
				elseif ( is_scalar( $value ) || null === $value ) $row['empty'] = '' === (string) $value;
			}
			$options[ $key ] = $row;
		}

		$cron = array();
		if ( function_exists( '_get_cron_array' ) ) {
			foreach ( (array) _get_cron_array() as $timestamp => $hooks ) {
				foreach ( (array) $hooks as $hook => $events ) {
					if ( '' === $cron_pattern || 1 !== preg_match( $cron_pattern, (string) $hook ) ) continue;
					$cron[] = array( 'hook' => (string) $hook, 'timestamp' => (int) $timestamp, 'event_count' => is_array( $events ) ? count( $events ) : 0 );
				}
			}
		}
		usort( $cron, static function ( $a, $b ) { return strcmp( $a['hook'], $b['hook'] ) ?: ( $a['timestamp'] <=> $b['timestamp'] ); } );

		$constants = array();
		foreach ( $constant_candidates as $name ) {
			$constants[ $name ] = defined( $name ) ? sanitize_text_field( (string) constant( $name ) ) : null;
		}

		return array(
			'contract' => self::RUNTIME_CONTRACT,
			'generated_at' => gmdate( 'c' ),
			'deep_scan_performed' => $deep_scan,
			'scan_budget' => array(
				'files_hashed' => self::$scan_files,
				'bytes_hashed' => self::$scan_bytes,
				'elapsed_ms' => self::$scan_started_at > 0 ? (int) round( ( microtime( true ) - self::$scan_started_at ) * 1000 ) : 0,
				'max_files' => self::MAX_SNAPSHOT_TREE_FILES,
				'max_bytes' => self::MAX_SNAPSHOT_TREE_BYTES,
				'max_seconds' => self::MAX_SNAPSHOT_SCAN_SECONDS,
			),
			'families' => $families,
			'constants' => $constants,
			'rest_routes' => $routes,
			'ajax_hooks' => $ajax,
			'option_presence' => $options,
			'cron_hooks' => $cron,
			'safety' => array(
				'mutation_performed' => false,
				'remote_request_performed' => false,
				'secret_values_returned' => false,
				'raw_sql_performed' => false,
			),
		);
	}

	private static function active_plugins( array $runtime, $family ) {
		$rows = isset( $runtime['families'][ $family ] ) && is_array( $runtime['families'][ $family ] ) ? $runtime['families'][ $family ] : array();
		return array_values( array_filter( $rows, static function ( $row ) { return is_array( $row ) && ! empty( $row['active'] ); } ) );
	}

	private static function runtime_rows_stable( array $rows ) {
		if ( empty( $rows ) ) return false;
		foreach ( $rows as $row ) {
			if ( ! is_array( $row ) || empty( $row['plugin_tree']['scan_stable'] ) ) return false;
		}
		return true;
	}

	private static function plugin_versions( array $runtime, $family ) {
		$versions = array();
		foreach ( self::active_plugins( $runtime, $family ) as $row ) {
			$version = isset( $row['version'] ) ? (string) $row['version'] : '';
			if ( '' !== $version ) $versions[ $version ] = true;
		}
		$versions = array_keys( $versions );
		sort( $versions, SORT_STRING );
		return $versions;
	}

	private static function tree_matches( array $repo_family, array $runtime_rows ) {
		$trees = array();
		foreach ( isset( $repo_family['artifacts'] ) && is_array( $repo_family['artifacts'] ) ? $repo_family['artifacts'] : array() as $artifact ) {
			$digest = isset( $artifact['package_tree']['tree_sha256'] ) ? strtolower( (string) $artifact['package_tree']['tree_sha256'] ) : '';
			if ( ! preg_match( '/^[a-f0-9]{64}$/', $digest ) ) continue;
			$version = '';
			foreach ( isset( $artifact['plugin_headers'] ) && is_array( $artifact['plugin_headers'] ) ? $artifact['plugin_headers'] : array() as $header ) {
				if ( ! empty( $header['version'] ) ) { $version = (string) $header['version']; break; }
			}
			$trees[ $digest ] = array( 'archive' => isset( $artifact['archive'] ) ? (string) $artifact['archive'] : '', 'version' => $version );
		}
		$matches = array();
		foreach ( $runtime_rows as $plugin ) {
			if ( empty( $plugin['plugin_tree']['scan_stable'] ) ) continue;
			$digest = isset( $plugin['plugin_tree']['tree_sha256'] ) ? strtolower( (string) $plugin['plugin_tree']['tree_sha256'] ) : '';
			if ( ! isset( $trees[ $digest ] ) ) continue;
			$matches[] = array(
				'plugin_file' => isset( $plugin['plugin_file'] ) ? (string) $plugin['plugin_file'] : '',
				'version' => isset( $plugin['version'] ) ? (string) $plugin['version'] : '',
				'tree_sha256' => $digest,
				'repository_archive' => $trees[ $digest ]['archive'],
				'repository_version' => $trees[ $digest ]['version'],
			);
		}
		return $matches;
	}

	private static function route_methods( array $runtime ) {
		$out = array();
		foreach ( isset( $runtime['rest_routes'] ) && is_array( $runtime['rest_routes'] ) ? $runtime['rest_routes'] : array() as $row ) {
			if ( ! is_array( $row ) || empty( $row['route'] ) ) continue;
			$out[ (string) $row['route'] ] = isset( $row['methods'] ) && is_array( $row['methods'] ) ? $row['methods'] : array();
		}
		return $out;
	}

	private static function decision( $family, $state, $reason, array $extra = array() ) {
		return array_merge( array( 'family' => $family, 'state' => $state, 'reason' => $reason ), $extra );
	}

	private static function canonicalize( $value ) {
		if ( ! is_array( $value ) ) return $value;
		$keys = array_keys( $value );
		$is_list = empty( $keys ) || $keys === range( 0, count( $keys ) - 1 );
		if ( $is_list ) {
			$out = array();
			foreach ( $value as $item ) $out[] = self::canonicalize( $item );
			return $out;
		}
		ksort( $value, SORT_STRING );
		foreach ( $value as $key => $item ) $value[ $key ] = self::canonicalize( $item );
		return $value;
	}

	private static function decision_fingerprint( array $repository, array $policy, array $decisions ) {
		$payload = self::canonicalize( array(
			'contract' => self::EVALUATION_CONTRACT,
			'policy_sha256' => isset( $policy['sha256'] ) ? (string) $policy['sha256'] : '',
			'repository_evidence_sha256' => isset( $repository['evidence_sha256'] ) ? (string) $repository['evidence_sha256'] : '',
			'repository_source_commit_sha' => isset( $repository['source_commit_sha'] ) ? (string) $repository['source_commit_sha'] : '',
			'decisions' => $decisions,
		) );
		$json = wp_json_encode( $payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
		return false === $json ? '' : hash( 'sha256', $json );
	}

	private static function evaluate( array $repository, array $runtime ) {
		$decisions = array();
		$evaluation_blockers = array();
		$repo_families = isset( $repository['families'] ) && is_array( $repository['families'] ) ? $repository['families'] : array();
		$policy = self::policy();
		$policy_families = isset( $policy['data']['families'] ) && is_array( $policy['data']['families'] ) ? $policy['data']['families'] : array();

		if ( empty( $repository['valid'] ) || empty( $policy['valid'] ) ) {
			foreach ( array_keys( $policy_families ) as $family ) {
				$decisions[] = self::decision( sanitize_key( (string) $family ), 'evidence_unavailable', 'repository_evidence_or_policy_missing_or_stale' );
			}
			$blockers = array_merge(
				isset( $repository['blockers'] ) ? (array) $repository['blockers'] : array(),
				isset( $policy['blockers'] ) ? (array) $policy['blockers'] : array()
			);
			$blockers = array_values( array_unique( array_filter( array_map( 'sanitize_key', $blockers ) ) ) );
			usort( $decisions, static function ( $a, $b ) { return strcmp( isset( $a['family'] ) ? (string) $a['family'] : '', isset( $b['family'] ) ? (string) $b['family'] : '' ); } );
			$decision_fingerprint = self::decision_fingerprint( $repository, $policy, $decisions );
			return array(
				'contract' => self::EVALUATION_CONTRACT,
				'ready' => false,
				'promotion_authorized' => false,
				'production_mutation' => false,
				'policy_contract' => isset( $policy['contract'] ) ? $policy['contract'] : '',
				'policy_sha256' => isset( $policy['sha256'] ) ? $policy['sha256'] : '',
				'decision_fingerprint' => $decision_fingerprint,
				'decisions' => $decisions,
				'blockers' => $blockers,
			);
		}

		$routes = self::route_methods( $runtime );
		$options = isset( $runtime['option_presence'] ) && is_array( $runtime['option_presence'] ) ? $runtime['option_presence'] : array();

		foreach ( $policy_families as $family_id => $rule ) {
			$family = sanitize_key( (string) $family_id );
			if ( '' === $family || ! is_array( $rule ) ) continue;
			$mode = isset( $rule['evaluation_mode'] ) ? sanitize_key( (string) $rule['evaluation_mode'] ) : '';
			$rows = self::active_plugins( $runtime, $family );
			$versions = self::plugin_versions( $runtime, $family );
			$matches = self::tree_matches( isset( $repo_families[ $family ] ) ? $repo_families[ $family ] : array(), $rows );
			$base_extra = array( 'evaluation_mode'=>$mode, 'runtime_versions'=>$versions, 'exact_tree_matches'=>$matches );

			if ( empty( $rows ) ) {
				$decisions[] = self::decision( $family, 'not_active', 'provider_not_active', $base_extra );
				continue;
			}
			if ( ! self::runtime_rows_stable( $rows ) ) {
				$decisions[] = self::decision( $family, 'runtime_evidence_unstable', 'runtime_tree_changed_or_scan_failed', $base_extra );
				continue;
			}

			switch ( $mode ) {
				case 'bounded_read_routes':
					$required = isset( $rule['required_get_routes'] ) && is_array( $rule['required_get_routes'] ) ? array_values( array_filter( array_map( 'sanitize_text_field', $rule['required_get_routes'] ) ) ) : array();
					$missing = array();
					foreach ( $required as $route ) if ( ! isset( $routes[ $route ] ) || ! in_array( 'GET', $routes[ $route ], true ) ) $missing[] = $route;
					$extra = array_merge( $base_extra, array(
						'missing_get_routes'=>$missing,
						'safe_now'=>isset( $rule['safe_now'] ) && is_array( $rule['safe_now'] ) ? array_values( $rule['safe_now'] ) : array(),
						'blocked'=>isset( $rule['blocked'] ) && is_array( $rule['blocked'] ) ? array_values( $rule['blocked'] ) : array(),
					) );
					if ( count( $matches ) === count( $rows ) && empty( $missing ) ) $decisions[] = self::decision( $family, 'read_contract_candidate', 'exact_runtime_tree_and_required_get_routes_verified', $extra );
					else $decisions[] = self::decision( $family, 'contract_discovery_required', 'exact_runtime_tree_or_required_get_routes_unverified', $extra );
					break;

				case 'redacted_status':
					$secret_keys = isset( $rule['redacted_secret_option_keys'] ) && is_array( $rule['redacted_secret_option_keys'] ) ? array_values( array_filter( array_map( 'sanitize_text_field', $rule['redacted_secret_option_keys'] ) ) ) : array();
					$status_keys = isset( $rule['required_status_option_keys'] ) && is_array( $rule['required_status_option_keys'] ) ? array_values( array_filter( array_map( 'sanitize_text_field', $rule['required_status_option_keys'] ) ) ) : array();
					$secret_ok = ! empty( $secret_keys );
					foreach ( $secret_keys as $key ) if ( ! isset( $options[ $key ]['redacted'] ) || true !== $options[ $key ]['redacted'] ) $secret_ok = false;
					$status_model = ! empty( $status_keys );
					foreach ( $status_keys as $key ) if ( ! array_key_exists( $key, $options ) ) $status_model = false;
					$extra = array_merge( $base_extra, array(
						'secret_redaction_verified'=>$secret_ok,
						'status_model_verified'=>$status_model,
						'safe_now'=>isset( $rule['safe_now'] ) && is_array( $rule['safe_now'] ) ? array_values( $rule['safe_now'] ) : array(),
						'blocked'=>isset( $rule['blocked'] ) && is_array( $rule['blocked'] ) ? array_values( $rule['blocked'] ) : array(),
					) );
					if ( count( $matches ) === count( $rows ) && $secret_ok && $status_model ) $decisions[] = self::decision( $family, 'redacted_read_contract_candidate', 'exact_runtime_tree_and_secret_redaction_verified', $extra );
					else $decisions[] = self::decision( $family, 'contract_discovery_required', 'exact_runtime_tree_or_redacted_status_model_unverified', $extra );
					break;

				case 'exact_tree_review':
					if ( count( $matches ) === count( $rows ) ) $decisions[] = self::decision( $family, 'contract_evidence_review', 'exact_runtime_tree_verified_but_semantic_contract_not_yet_promoted', $base_extra );
					else $decisions[] = self::decision( $family, 'runtime_alignment_required', 'live_runtime_tree_does_not_match_repository_evidence', $base_extra );
					break;

				case 'runtime_only':
					$plugin_files = array();
					$tree_hashes = array();
					foreach ( $rows as $row ) {
						$plugin_files[] = isset( $row['plugin_file'] ) ? (string) $row['plugin_file'] : '';
						$tree_hashes[] = isset( $row['plugin_tree']['tree_sha256'] ) ? (string) $row['plugin_tree']['tree_sha256'] : '';
					}
					$decisions[] = self::decision( $family, 'runtime_contract_evidence_captured', 'runtime_only_provider_requires_semantic_contract_before_specialized_surface', array_merge( $base_extra, array( 'plugin_files'=>$plugin_files, 'tree_sha256'=>$tree_hashes ) ) );
					break;

				case 'premium_semantic':
					$decisions[] = self::decision( $family, 'semantic_attestation_required', 'premium_provider_exact_runtime_and_semantic_review_gate_remains_authoritative', $base_extra );
					break;

				case 'composite_behavioral':
					$decisions[] = self::decision( $family, 'runtime_alignment_or_behavioral_recertification_required', 'composite_provider_requires_exact_component_versions_and_behavioral_execution_contract', $base_extra );
					break;

				default:
					$evaluation_blockers[] = 'unsupported_evaluation_mode_' . ( '' !== $mode ? $mode : 'missing' );
					$decisions[] = self::decision( $family, 'evidence_unavailable', 'functional_gap_policy_evaluation_mode_unsupported', $base_extra );
					break;
			}
		}

		usort( $decisions, static function ( $a, $b ) { return strcmp( isset( $a['family'] ) ? (string) $a['family'] : '', isset( $b['family'] ) ? (string) $b['family'] : '' ); } );
		$decision_fingerprint = self::decision_fingerprint( $repository, $policy, $decisions );
		if ( ! preg_match( '/^[a-f0-9]{64}$/', $decision_fingerprint ) ) $evaluation_blockers[] = 'decision_fingerprint_unavailable';

		$counts = array();
		foreach ( $decisions as $row ) {
			$state = isset( $row['state'] ) ? (string) $row['state'] : 'unknown';
			$counts[ $state ] = isset( $counts[ $state ] ) ? $counts[ $state ] + 1 : 1;
		}
		ksort( $counts, SORT_STRING );
		$evaluation_blockers = array_values( array_unique( array_filter( array_map( 'sanitize_key', $evaluation_blockers ) ) ) );

		return array(
			'contract' => self::EVALUATION_CONTRACT,
			'ready' => empty( $evaluation_blockers ),
			'promotion_authorized' => false,
			'production_mutation' => false,
			'policy_contract' => isset( $policy['contract'] ) ? $policy['contract'] : '',
			'policy_sha256' => isset( $policy['sha256'] ) ? $policy['sha256'] : '',
			'decision_fingerprint' => $decision_fingerprint,
			'repository_source_commit_sha' => isset( $repository['source_commit_sha'] ) ? $repository['source_commit_sha'] : '',
			'counts' => $counts,
			'decisions' => $decisions,
			'blockers' => $evaluation_blockers,
		);
	}

	public static function package_integrity_status() {
		$provenance = self::build_provenance();
		$verification = isset( $provenance['package_verification'] ) && is_array( $provenance['package_verification'] ) ? $provenance['package_verification'] : array();
		return array(
			'contract' => 'mad4b.functional-gap-package-integrity.v1',
			'valid' => ! empty( $provenance['valid'] ) && ! empty( $verification['valid'] ),
			'source_commit_sha' => isset( $provenance['source_commit_sha'] ) ? (string) $provenance['source_commit_sha'] : '',
			'build_fingerprint' => isset( $provenance['build_fingerprint'] ) ? (string) $provenance['build_fingerprint'] : '',
			'package_manifest_digest' => isset( $provenance['package_manifest_digest'] ) ? (string) $provenance['package_manifest_digest'] : '',
			'integrity_level' => isset( $verification['integrity_level'] ) ? (string) $verification['integrity_level'] : 'unknown',
			'verified_file_count' => isset( $verification['verified_file_count'] ) ? (int) $verification['verified_file_count'] : 0,
			'verified_bytes' => isset( $verification['verified_bytes'] ) ? (int) $verification['verified_bytes'] : 0,
			'actual_file_count' => isset( $verification['actual_file_count'] ) ? (int) $verification['actual_file_count'] : 0,
			'elapsed_ms' => isset( $verification['elapsed_ms'] ) ? (int) $verification['elapsed_ms'] : 0,
			'external_cryptographic_attestation' => false,
			'blockers' => isset( $provenance['blockers'] ) ? array_values( (array) $provenance['blockers'] ) : array(),
		);
	}

	public static function snapshot() {
		$key = self::runtime_identity_key();
		if ( null !== self::$snapshot && '' !== self::$snapshot_key && hash_equals( self::$snapshot_key, $key ) ) return self::$snapshot;
		$repository = self::repository_evidence();
		self::$scan_files = 0;
		self::$scan_bytes = 0;
		self::$scan_started_at = microtime( true );
		$runtime = self::runtime_evidence( $repository );
		$evaluation = self::evaluate( $repository, $runtime );
		self::$snapshot_key = $key;
		self::$snapshot = array(
			'contract' => self::CONTRACT,
			'snapshot_identity_sha256' => $key,
			'read_only' => true,
			'authority_created' => false,
			'mutation_performed' => false,
			'remote_request_performed' => false,
			'secret_values_returned' => false,
			'build_source_commit_sha' => self::build_source_commit_sha(),
			'repository_evidence' => array(
				'present' => ! empty( $repository['present'] ),
				'valid' => ! empty( $repository['valid'] ),
				'contract' => isset( $repository['contract'] ) ? $repository['contract'] : '',
				'source_commit_sha' => isset( $repository['source_commit_sha'] ) ? $repository['source_commit_sha'] : '',
				'evidence_sha256' => isset( $repository['evidence_sha256'] ) ? $repository['evidence_sha256'] : '',
				'evidence_bytes' => isset( $repository['evidence_bytes'] ) ? (int) $repository['evidence_bytes'] : 0,
				'policy_contract' => isset( $repository['policy_contract'] ) ? $repository['policy_contract'] : '',
				'policy_sha256' => isset( $repository['policy_sha256'] ) ? $repository['policy_sha256'] : '',
				'policy_bytes' => isset( $repository['policy_bytes'] ) ? (int) $repository['policy_bytes'] : 0,
				'build_fingerprint' => isset( $repository['build_fingerprint'] ) ? $repository['build_fingerprint'] : '',
				'package_manifest_digest' => isset( $repository['package_manifest_digest'] ) ? $repository['package_manifest_digest'] : '',
				'package_integrity' => isset( $repository['package_integrity'] ) && is_array( $repository['package_integrity'] ) ? $repository['package_integrity'] : array(),
				'family_count' => isset( $repository['families'] ) && is_array( $repository['families'] ) ? count( $repository['families'] ) : 0,
				'blockers' => isset( $repository['blockers'] ) ? $repository['blockers'] : array(),
			),
			'runtime' => $runtime,
			'evaluation' => $evaluation,
		);
		return self::$snapshot;
	}

	public static function decision_map() {
		$snapshot = self::snapshot();
		$evaluation = isset( $snapshot['evaluation'] ) && is_array( $snapshot['evaluation'] ) ? $snapshot['evaluation'] : array();
		$map = array();
		foreach ( isset( $evaluation['decisions'] ) && is_array( $evaluation['decisions'] ) ? $evaluation['decisions'] : array() as $row ) {
			if ( ! is_array( $row ) || empty( $row['family'] ) ) continue;
			$map[ sanitize_key( (string) $row['family'] ) ] = $row;
		}
		ksort( $map, SORT_STRING );
		return $map;
	}

	public static function summary() {
		$snapshot = self::snapshot();
		$evaluation = isset( $snapshot['evaluation'] ) && is_array( $snapshot['evaluation'] ) ? $snapshot['evaluation'] : array();
		$repository = isset( $snapshot['repository_evidence'] ) && is_array( $snapshot['repository_evidence'] ) ? $snapshot['repository_evidence'] : array();
		$counts = isset( $evaluation['counts'] ) && is_array( $evaluation['counts'] ) ? $evaluation['counts'] : array();
		$package_integrity = isset( $repository['package_integrity'] ) && is_array( $repository['package_integrity'] ) ? $repository['package_integrity'] : array();
		$runtime_budget = isset( $snapshot['runtime']['scan_budget'] ) && is_array( $snapshot['runtime']['scan_budget'] ) ? $snapshot['runtime']['scan_budget'] : array();
		return array(
			'contract' => self::CONTRACT,
			'snapshot_identity_sha256' => isset( $snapshot['snapshot_identity_sha256'] ) ? $snapshot['snapshot_identity_sha256'] : '',
			'ready' => ! empty( $evaluation['ready'] ),
			'repository_evidence_valid' => ! empty( $repository['valid'] ),
			'evidence_integrity_bound' => ! empty( $repository['valid'] ) && ! empty( $repository['evidence_sha256'] ) && ! empty( $repository['policy_sha256'] ) && ! empty( $repository['build_fingerprint'] ) && ! empty( $repository['package_manifest_digest'] ),
			'package_self_consistent' => ! empty( $repository['package_integrity']['valid'] ),
			'package_integrity_level' => isset( $repository['package_integrity']['integrity_level'] ) ? $repository['package_integrity']['integrity_level'] : 'unknown',
			'package_integrity_elapsed_ms' => isset( $package_integrity['elapsed_ms'] ) ? (int) $package_integrity['elapsed_ms'] : 0,
			'package_verified_file_count' => isset( $package_integrity['verified_file_count'] ) ? (int) $package_integrity['verified_file_count'] : 0,
			'package_verified_bytes' => isset( $package_integrity['verified_bytes'] ) ? (int) $package_integrity['verified_bytes'] : 0,
			'runtime_scan_elapsed_ms' => isset( $runtime_budget['elapsed_ms'] ) ? (int) $runtime_budget['elapsed_ms'] : 0,
			'runtime_scan_files_hashed' => isset( $runtime_budget['files_hashed'] ) ? (int) $runtime_budget['files_hashed'] : 0,
			'runtime_scan_bytes_hashed' => isset( $runtime_budget['bytes_hashed'] ) ? (int) $runtime_budget['bytes_hashed'] : 0,
			'external_cryptographic_attestation' => false,
			'policy_sha256' => isset( $repository['policy_sha256'] ) ? $repository['policy_sha256'] : '',
			'evidence_sha256' => isset( $repository['evidence_sha256'] ) ? $repository['evidence_sha256'] : '',
			'build_fingerprint' => isset( $repository['build_fingerprint'] ) ? $repository['build_fingerprint'] : '',
			'package_manifest_digest' => isset( $repository['package_manifest_digest'] ) ? $repository['package_manifest_digest'] : '',
			'decision_fingerprint' => isset( $evaluation['decision_fingerprint'] ) ? $evaluation['decision_fingerprint'] : '',
			'promotion_authorized' => false,
			'counts' => $counts,
			'unstable_family_count' => isset( $counts['runtime_evidence_unstable'] ) ? (int) $counts['runtime_evidence_unstable'] : 0,
			'blockers' => isset( $evaluation['blockers'] ) ? $evaluation['blockers'] : array(),
		);
	}
}
