#!/usr/bin/env python3
from pathlib import Path
import re
import sys

ROOT=Path(__file__).resolve().parents[1]
catalog=(ROOT/"includes/class-mad4b-scp-ability-catalog-transport.php").read_text(encoding="utf-8")
schema=(ROOT/"includes/class-mad4b-scp-schema.php").read_text(encoding="utf-8")
journal=(ROOT/"includes/class-mad4b-scp-operation-journal.php").read_text(encoding="utf-8")
guard=(ROOT/"includes/class-mad4b-scp-database-transaction-guard.php").read_text(encoding="utf-8")
database_topology=(ROOT/"includes/class-mad4b-scp-database-topology.php").read_text(encoding="utf-8")
database_failures=(ROOT/"includes/class-mad4b-scp-database-failure-semantics.php").read_text(encoding="utf-8")
approvals=(ROOT/"includes/class-mad4b-scp-approval-tickets.php").read_text(encoding="utf-8")
operation_journal=(ROOT/"includes/class-mad4b-scp-operation-journal.php").read_text(encoding="utf-8")
commit_guard=(ROOT/"includes/class-mad4b-scp-execution-commit-guard.php").read_text(encoding="utf-8")
authorization=(ROOT/"includes/class-mad4b-scp-authorization.php").read_text(encoding="utf-8")
runtime_compatibility=(ROOT/"includes/class-mad4b-scp-runtime-compatibility-profile.php").read_text(encoding="utf-8")
persisted_contracts=(ROOT/"includes/class-mad4b-scp-persisted-contract-compatibility.php").read_text(encoding="utf-8")
runtime_generation=(ROOT/"includes/class-mad4b-scp-runtime-generation-fence.php").read_text(encoding="utf-8")
execution_evidence_policy=(ROOT/"includes/class-mad4b-scp-execution-evidence-policy.php").read_text(encoding="utf-8")
audit=(ROOT/"includes/class-mad4b-scp-audit.php").read_text(encoding="utf-8")
main=(ROOT/"mad4b-site-control-plane.php").read_text(encoding="utf-8")
request_generation=(ROOT/"includes/class-mad4b-scp-request-generation.php").read_text(encoding="utf-8")
restore_epoch=(ROOT/"includes/class-mad4b-scp-restore-epoch.php").read_text(encoding="utf-8")
execution_fence=(ROOT/"includes/class-mad4b-scp-execution-fence.php").read_text(encoding="utf-8")
projection=(ROOT/"includes/class-mad4b-scp-chatgpt-tool-projection.php").read_text(encoding="utf-8")
transport_context=(ROOT/"includes/class-mad4b-scp-transport-context.php").read_text(encoding="utf-8")
identity=(ROOT/"includes/class-mad4b-scp-identity-context.php").read_text(encoding="utf-8")
abilities=(ROOT/"includes/class-mad4b-scp-abilities.php").read_text(encoding="utf-8")
mcp_scope=(ROOT/"includes/class-mad4b-scp-mcp-request-scope.php").read_text(encoding="utf-8")
remote_work_queue=(ROOT/"includes/class-mad4b-scp-remote-work-queue.php").read_text(encoding="utf-8")
remote_operation_parity=(ROOT/"includes/class-mad4b-scp-remote-operation-parity.php").read_text(encoding="utf-8")
descriptor_registry=(ROOT/"includes/class-mad4b-scp-capability-descriptor-registry.php").read_text(encoding="utf-8")
operation_registry=(ROOT/"includes/class-mad4b-scp-operation-registry.php").read_text(encoding="utf-8")
authorization=(ROOT/"includes/class-mad4b-scp-authorization.php").read_text(encoding="utf-8")
commit_guard=(ROOT/"includes/class-mad4b-scp-execution-commit-guard.php").read_text(encoding="utf-8")

def need(cond,msg):
    if not cond:
        raise AssertionError(msg)

need("serialize( $definition )" not in catalog, "security-sensitive catalog fingerprint still has PHP serialize fallback")
need("mad4b.catalog-definition-unavailable.v1" in catalog and "$definition_failures" in catalog, "catalog canonical failure marker missing")
need("mad4b.catalog-object-envelope.v1" in catalog and "OBJECT_VERSION = 1" in catalog, "catalog persisted object envelope missing")
need("wire_generation()" in catalog and "mad4b_scp_catalog_wire_generation" in catalog, "catalog wire generation contract missing")
need("unwrap_object" in catalog and "mad4b_catalog_object_generation_mismatch" in catalog, "catalog does not reject unknown/future persisted object generations")
need("object_envelope( 'current'" in catalog and "object_envelope( 'snapshot'" in catalog and "object_envelope( 'schema'" in catalog, "catalog current/snapshot/schema objects are not versioned")
need("public static function transactional_storage_status" in schema, "transactional storage readiness contract missing")
need("'innodb' !== $engine" in schema, "transactional storage does not fail closed on non-InnoDB engine")
need("identity_comparison_policy" in schema, "database identity comparison policy missing")
need("SAVEPOINT " in guard and "RELEASE SAVEPOINT " in guard, "portable savepoint transaction-state probe missing")
need("savepoint.+does not exist" in guard, "savepoint no-transaction discriminator missing")
need("performance_schema.events_transactions_current" not in guard, "transaction ownership must not depend on Performance Schema privileges")
need("@@session.in_transaction" not in guard, "transaction ownership must not depend on MariaDB-only session variables")
need("mad4b_database_nested_transaction_denied" in guard, "nested transaction denial missing")
need("mad4b_database_transaction_commit_uncertain" in guard, "uncertain commit state is not explicit")
need("MAD4B_SCP_Database_Transaction_Guard::begin" in journal, "operation journal still owns raw transaction begin")
need("MAD4B_SCP_Database_Transaction_Guard::commit" in journal, "operation journal still owns raw transaction commit")
need("WHERE BINARY operation_id=BINARY %s" in journal, "operation journal identity lookup is not binary-exact")
need("'database_storage' => $database_storage" in commit_guard, "commit guard does not bind transactional storage")
revalidation_match=re.search(r"foreach\s*\(\s*array\((.*?)\)\s*as\s*\$dependency", commit_guard, re.S)
need(revalidation_match is not None, "commit revalidation dependency loop missing")
revalidation_dependencies=revalidation_match.group(1)
need("'database_storage'" in revalidation_dependencies, "commit revalidation does not recheck database storage")
need("'runtime_compatibility'" in revalidation_dependencies, "commit revalidation does not recheck runtime compatibility")
need("class-mad4b-scp-database-transaction-guard.php" in main, "transaction guard is not loaded by plugin bootstrap")
need("class-mad4b-scp-database-topology.php" in main, "database topology is not loaded by plugin bootstrap")
need("mad4b.database-topology.v1" in database_topology, "database topology contract missing")
need("uncertified_database_router_dropin" in database_topology, "uncertified db.php router does not fail closed")
need("CONNECTION_ID()" in database_topology and "@@read_only" in database_topology, "writer connection/read-only probes missing")
need("read_your_writes" in database_topology and "assert_same_writer" in database_topology, "read-your-writes/same-writer contract missing")
need("mad4b.database-failure-semantics.v1" in database_failures, "database failure semantics contract missing")
need("deadlock" in database_failures and "lock_wait_timeout" in database_failures and "connection_loss" in database_failures, "database failure classes incomplete")
need("blind_retry_allowed" in database_failures, "database failure semantics do not prohibit blind retry")
need("MAD4B_SCP_Database_Topology::assert_write_ready" in approvals, "approval claims/finalization are not topology-fenced")
need("MAD4B_SCP_Database_Failure_Semantics" in approvals, "approval persistence failures are not normalized")
need("MAD4B_SCP_Database_Failure_Semantics" in operation_journal, "operation journal failures are not normalized")
need("class-mad4b-scp-request-generation.php" in main, "request-generation fence is not loaded by plugin bootstrap")
need("mad4b.request-scope-generation.v1" in request_generation, "request-generation contract missing")
need("mad4b_request_scope_context_drift" in request_generation, "same-request context drift does not fail closed")
need("presentation_snapshot" in request_generation and "presentation_authority_effect" in request_generation, "non-authorizing presentation generation is not separated from authority context")
need("'projection_sha256'" in request_generation and "'projection_sha256' => self::digest( $projection )" in request_generation, "projection generation is not tracked")
need("'projection_sha256' => self::digest( $projection )" not in request_generation.split("private static function context_snapshot()",1)[1].split("private static function presentation_snapshot()",1)[0], "projection identity leaked back into authoritative request context")
need("mad4b_request_scope_worker_recycle_required" in request_generation, "site/runtime generation change does not require worker recycle")
need("MAD4B_SCP_Database_Transaction_Guard::transaction_state" in request_generation, "request boundary ignores active database transactions")
need("reset_owners" in request_generation and "MAD4B_SCP_Agent_Registry" in request_generation and "MAD4B_SCP_Servers" in request_generation, "request-local cache ownership registry is incomplete")
need("request_scope_state" in identity and "reset_request_cache" in identity, "identity request-local reset contract missing")
need("request_scope_state" in abilities and "reset_request_cache" in abilities, "dispatcher governance-envelope reset contract missing")
need("request_scope_transition_safe" in mcp_scope, "MCP hook-lifecycle transition safety contract missing")
need("public static function cancel(" in remote_work_queue and "'cancelled_no_effect'" in remote_work_queue and "'reconciling'" in remote_work_queue, "remote work cancellation state machine missing")
need("mad4b_remote_work_reconciliation_required" in remote_work_queue and "reconcile_provider_state_before_any_retry" in remote_work_queue, "claimed cancellation/lease expiry does not reconcile first")
need("reconciliation_completion_valid" in remote_work_queue and "postcondition_verified" in remote_work_queue, "reconciling work can terminalize without provider postcondition proof")
need("WORK_CANCEL_ABILITY" in remote_operation_parity and "cancel_remote_work" in remote_operation_parity, "governed remote cancellation ability missing")
need("mad4b.final-execution-admission.v1" in execution_fence, "final execution admission wrapper contract missing")
need("PHP_INT_MAX" in execution_fence and "wrap_final_execution_admission" in execution_fence, "final ability wrapper is not registered at terminal priority")
need("mad4b.projected-call-seal.v1" in execution_fence and "consume_projected_call" in execution_fence, "projected call one-time seal missing")
need("projected_call_requirements" in execution_fence and "require_projected_call_seal" in execution_fence and "projected_call_requirement_pending" in execution_fence, "denied projected calls do not leave a final-admission tombstone")
need("require_projected_call_seal" in projection, "pre-tool guard does not mark projected execution seal requirement before deny paths")
need("final_execution_wrapper_verified" in execution_fence and "final_execution_admission_required" in projection, "projection does not require final callback provenance")
need("private static function planning_row" in projection, "final admission policy is not separated from structural ability classification")
ability_row_body=projection.split("private static function ability_row",1)[1].split("private static function planning_row",1)[0]
need("final_execution_wrapper_verified" not in ability_row_body, "registration-time structural classifier evaluates final live callback provenance")
need("mad4b.governed-child-operation.v1" in execution_fence and "with_governed_child" in execution_fence, "explicit governed child operation contract missing")
need("mad4b_recursive_dispatch_child_operation_required" in execution_fence, "unexpected recursive mutation is not denied")
need("child_input_sha256" in execution_fence and "child_evidence_sha256" in execution_fence, "child permit is not bound to exact input/evidence")
need("with_governed_child" in transport_context and "write_dispatch" in transport_context and "developer_dispatch" in transport_context, "bounded dispatchers do not issue governed child permits")
need("mad4b.runtime-compatibility-profile.v1" in runtime_compatibility, "runtime compatibility profile contract missing")
need("persistent_object_cache_contract_unverified" in runtime_compatibility, "persistent object-cache fail-closed reason missing")
need("database_router_uncertified" in runtime_compatibility, "uncertified database-router reason missing")
need("security_firewall_plugin_requires_certification" in runtime_compatibility, "security/firewall certification reason missing")
need("wordpress_maintenance_mode_active" in runtime_compatibility, "maintenance-mode blocker missing")
need("remote_transport_wp_cli_context_conflict" in runtime_compatibility and "remote_transport_cron_context_conflict" in runtime_compatibility, "WP-CLI/cron transport-conflict reasons missing")
need("'runtime_compatibility' => $runtime_compatibility" in commit_guard, "commit guard does not bind runtime compatibility profile")
need("'runtime_compatibility', 'kill_switch'" in commit_guard, "commit guard does not revalidate runtime compatibility profile")
need("mad4b.persisted-contract-compatibility.v1" in persisted_contracts, "persisted-contract compatibility contract missing")
need("future_schema_downgrade_forbidden" in persisted_contracts and "legacy_migration_required" in persisted_contracts, "persisted version policy is incomplete")
need("exact_version_only" in persisted_contracts and "downgrade_reinterpretation_allowed" in persisted_contracts, "persisted write compatibility is not exact/fail-closed")
need("mad4b.execution-evidence-policy.v1" in execution_evidence_policy, "execution evidence policy contract missing")
need("provider_entry_possible" in execution_evidence_policy and "durable_receipt_committed" in execution_evidence_policy, "execution crash-point table incomplete")
need("blind_retry_allowed" in execution_evidence_policy and "reconcile_provider_state_before_any_retry" in execution_evidence_policy, "crash points do not fail closed against blind retry")
need("_mandatory_paths" in execution_evidence_policy and "mandatory_exceeds_bound" in execution_evidence_policy, "bounded audit compaction can silently drop mandatory evidence")
need("MAD4B_SCP_Execution_Evidence_Policy::compact_audit_summary" in audit, "audit overflow does not preserve mandatory execution evidence")
need("mad4b.execution-terminal-evidence.v1" in execution_evidence_policy and "mad4b.execution-terminal-receipt.v1" in execution_evidence_policy, "terminal execution evidence/receipt contracts missing")
need("terminal_success_material" in execution_evidence_policy and "terminal_receipt" in execution_evidence_policy and "terminal_persistence_error" in execution_evidence_policy, "terminal evidence barrier primitives missing")
need("MAD4B_SCP_Execution_Evidence_Policy::terminal_success_material" in authorization, "authorization success is not bound to terminal evidence")
need("'completed'" in authorization and "terminal_receipt" in authorization, "authorization can return success without durable terminal audit receipt")
need("mad4b_execution_terminal_evidence_persist_failed" in execution_evidence_policy, "post-side-effect evidence failure does not suppress terminal success")
need("mad4b.runtime-generation-fence.v1" in runtime_generation, "runtime-generation fence contract missing")
need("boot_runtime_file_sha256" in runtime_generation and "disk_runtime_file_sha256" in runtime_generation, "boot-vs-disk runtime generation proof missing")
need("policy_config_sha256" in runtime_generation and "catalog_wire_generation" in runtime_generation, "policy/catalog generation is not fenced")
need("mad4b_runtime_worker_recycle_required" in runtime_generation and "mad4b_runtime_generation_changed" in runtime_generation, "stale/mixed worker failure modes missing")
need("'persisted_contracts'" in revalidation_dependencies and "'runtime_generation'" in revalidation_dependencies, "commit guard does not revalidate persisted/runtime generations")
need("MAD4B_SCP_Runtime_Generation_Fence::assert_current" in guard, "database transaction preflight does not fence stale workers")
need("future_schema_downgrade_forbidden" in schema and "schema_upgrade_required" in schema, "transactional storage does not bind exact schema generation")

print("mad4b.capability-fabric.bulk-hardening.contract.v1: PASS")

need("mad4b.restore-authority-epoch.v1" in restore_epoch, "restore/authority epoch contract missing")
need("restore_epoch_database_snapshot_detected" in restore_epoch, "database snapshot time-travel mismatch is not detected")
need("write_external" in restore_epoch and "write_binding" in restore_epoch and restore_epoch.index("write_external") < restore_epoch.index("write_binding"), "restore epoch does not persist external state before DB binding")
need("mad4b_restore_epoch_write_must_be_disabled" in restore_epoch, "restore acknowledgement does not require write-disabled quarantine")
need("'restore_epoch'" in commit_guard, "commit guard does not bind restore epoch")
need("MAD4B_SCP_Restore_Epoch::advance( 'governed_execution' )" in authorization, "provider entry does not advance restore epoch")


authorization=(ROOT/"includes/class-mad4b-scp-authorization.php").read_text(encoding="utf-8")
restore_epoch=(ROOT/"includes/class-mad4b-scp-restore-epoch.php").read_text(encoding="utf-8")
need("pre_restore_epoch_commit_guard_receipt" in authorization and "post_epoch_snapshot" in authorization and "post_epoch_guard" in authorization, "commit guard is not re-captured/revalidated after restore epoch advance")
need("restore_epoch_site_identity_mismatch" in restore_epoch, "restore epoch is not bound to the current Site UUID")
need("reconcile_restored_security_state" in restore_epoch and "status='revoked'" in restore_epoch and "status='pending'" in restore_epoch and "released_verified_no_effect" in restore_epoch, "restore acknowledgement does not quarantine stale approval/idempotency state")


need("MAD4B_SCP_Restore_Epoch::ensure_bound()" in authorization.split("public static function claim_mutation",1)[1].split("public static function wrap_execution_boundary",1)[0], "governed authorization claim does not preflight restore epoch before mutation admission")


# Canonical Capability Descriptor consumer ownership.
need("mad4b.capability-descriptor-consumer-binding.v1" in descriptor_registry and "public static function assert_binding(" in descriptor_registry, "canonical descriptor consumer binding primitive missing")
need("bind_operation_descriptors" in operation_registry and "capability_descriptor_bindings" in operation_registry, "Operation Registry is not bound to canonical descriptors")
need("MAD4B_SCP_Capability_Descriptor_Registry::binding( $ability_name, 'authorization' )" in authorization, "Authorization does not consume canonical descriptor identity")
need("MAD4B_SCP_Capability_Descriptor_Registry::assert_binding" in commit_guard and "'capability_descriptor'" in commit_guard, "Commit Guard does not revalidate descriptor identity")
need("capability_descriptor_authorizing' => false" in authorization, "descriptor binding accidentally became an authority grant")
