from pathlib import Path
import subprocess
import sys

root = Path(__file__).resolve().parents[1]
main = (root / "mad4b-site-control-plane.php").read_text(encoding="utf-8")
authority = (root / "includes/class-mad4b-scp-context-authority.php").read_text(encoding="utf-8")
abilities = (root / "includes/class-mad4b-scp-abilities.php").read_text(encoding="utf-8")
drive = (root / "includes/class-mad4b-scp-google-drive-context.php").read_text(encoding="utf-8")
admin = (root / "includes/class-mad4b-scp-context-admin-ui.php").read_text(encoding="utf-8")
skills_admin = (root / "includes/class-mad4b-scp-skills-admin-ui.php").read_text(encoding="utf-8")
adapter = (root / "includes/adapters/class-mad4b-scp-context-adapter.php").read_text(encoding="utf-8")
audit = (root / "includes/class-mad4b-scp-audit.php").read_text(encoding="utf-8")
registry = (root / "includes/class-mad4b-scp-adapter-registry.php").read_text(encoding="utf-8")
servers = (root / "includes/class-mad4b-scp-servers.php").read_text(encoding="utf-8")
preflight = (root / "includes/class-mad4b-scp-context-preflight.php").read_text(encoding="utf-8")
skill_registry = (root / "includes/class-mad4b-scp-skill-registry.php").read_text(encoding="utf-8")
skill_abilities = (root / "includes/class-mad4b-scp-skill-abilities.php").read_text(encoding="utf-8")
skill_snapshot = (root / "includes/class-mad4b-scp-skill-snapshot-identity.php").read_text(encoding="utf-8")
skill_exporter = (root / "includes/class-mad4b-scp-skill-exporter.php").read_text(encoding="utf-8")
authorization = (root / "includes/class-mad4b-scp-authorization.php").read_text(encoding="utf-8")
write_authority = (root / "includes/class-mad4b-scp-staging-write-authority.php").read_text(encoding="utf-8")
grant_reconcile = (root / "includes/class-mad4b-scp-staging-write-grant-reconciliation.php").read_text(encoding="utf-8")
planning_guard = (root / "includes/class-mad4b-scp-staging-write-planning-guard.php").read_text(encoding="utf-8")
workflow = (root.parents[2] / ".github/workflows/mad4b-context-authority.yml").read_text(encoding="utf-8")
package_workflow = (root.parents[2] / ".github/workflows/mad4b-control-plane-package.yml").read_text(encoding="utf-8")
staging_handoff = (root / "config/staging-deployment-handoff.json").read_text(encoding="utf-8")
oauth_runtime = (root / "tests/context-oauth-lifecycle-runtime.php").read_text(encoding="utf-8")
ai_review_runtime = (root / "tests/context-ai-agent-review-runtime.php").read_text(encoding="utf-8")

def require(text, needle, label):
    assert needle in text, f"missing {label}: {needle}"

# Lifecycle and adapter registration.
require(main, "class-mad4b-scp-context-authority.php", "context authority wiring")
require(main, "class-mad4b-scp-google-drive-context.php", "google drive wiring")
require(main, "class-mad4b-scp-context-preflight.php", "Context Preflight runtime wiring")
require(main, "class-mad4b-scp-context-adapter.php", "context adapter wiring")
require(main, "class-mad4b-scp-context-admin-ui.php", "context admin wiring")
require(main, "MAD4B_SCP_Context_Admin_UI::boot();", "context admin boot")
require(registry, "'MAD4B_SCP_Context_Adapter'", "context adapter registry registration")

# Context Authority semantics.
require(authority, "'governed'", "governed source mode")
require(authority, "'task_attachment'", "task-only source mode")
require(authority, "mad4b_context_source_root_forbidden", "My Drive root source denial")
require(authority, "context_fingerprint", "context fingerprint")
require(authority, "$site = self::site_binding();", "Context reads bind to current Site Profile")
require(authority, "hash_equals( (string) $site['site_uuid']", "exact Site UUID read isolation")
require(authority, "! isset( $sources[ $source_id ] )", "orphan asset source denial")
require(authority, "hash_equals( $source_mode, $asset_mode )", "asset/source mode binding")
require(authority, "raw_sources", "raw Context source storage view")
require(authority, "raw_assets", "raw Context asset storage view")
require(authority, "authorized_sources_from_records", "source-authorized read projection")
require(authority, "authorized_assets_from_records", "asset-authorized read projection")
require(authority, "self::raw_assets()", "mutation paths preserve raw asset siblings")
require(authority, "self::raw_sources()", "mutation paths preserve raw source siblings")
require(authority, "classification_confidence", "classification confidence")
require(authority, "authority_class", "authority class")
require(authority, "quality_score", "quality score")
require(authority, "mad4b.context-quality-score.v2", "quality scoring v2 contract")
require(authority, "quality_profile_for_category", "category-aware quality profiles")
require(authority, "market_research", "market research scoring profile")
require(authority, "writer_reference", "writer reference scoring profile")
require(authority, "language_quality", "language-quality scoring dimension")
require(authority, "retrieval_quality", "retrieval-quality scoring dimension")
require(authority, "metadata_provisional", "metadata-only provisional scoring")
require(authority, "review_asset", "human review contract")
require(authority, "mad4b.context-human-review.v2", "exact human review v2 contract")
require(authority, "expected_content_hash", "human review exact content binding")
require(authority, "expected_registry_revision", "human review registry revision binding")
require(authority, "expected_authority_manifest_fingerprint", "human review authority manifest binding")
require(authority, "mad4b_context_review_content_drift", "stale content review fail-closed")
require(authority, "mad4b_context_review_registry_drift", "stale registry review fail-closed")
require(authority, "mad4b_context_review_authority_drift", "stale authority review fail-closed")
require(authority, "reviewed_content_hash", "persisted exact reviewed content hash")
require(authority, "automatic_classification", "separate automatic classification provenance")
require(authority, "'actor_type' => 'wp_admin'", "human review audit actor type")
require(authority, "'wp_user_id' => get_current_user_id()", "human review audit WordPress user attribution")
require(authority, "mad4b_context_required_scope_confirmation_required", "site-wide required Context escalation confirmation")
require(authority, "required_scope_escalated", "required Context escalation audit evidence")

review_body = authority.split("public static function review_asset", 1)[1].split("public static function review_queue", 1)[0]
scope_guard = review_body.index("$required_scope_changed && empty( $input['required_scope_confirmed'] )")
category_mutation = review_body.index("$asset['category'] = $category;")
required_mutation = review_body.index("$asset['required'] = $requested_required;")
if not (scope_guard < category_mutation < required_mutation):
    raise AssertionError("required-scope confirmation must precede all effective governance mutation")

require(authority, "required_scope_shifted", "required Context category-shift evidence")
require(authority, "required_scope_reduced", "required Context reduction evidence")
require(authority, "required_scope_changed", "unified site-wide required scope guard")
require(authority, "mad4b_context_review_decision_invalid", "bounded human review decision enum")
require(authority, "const AI_REVIEW_CONTRACT = 'mad4b.context-ai-agent-review.v1'", "AI Agent review contract")
require(authority, "const REVIEW_POLICY_CONTRACT = 'mad4b.context-review-policy.v1'", "review policy contract")
require(authority, "const AI_REVIEW_ABILITY = 'mad4b/context-ai-review'", "dedicated AI review ability")
require(abilities, "'mad4b-admin'", "registered core admin Ability category")
require(authority, "'category' => 'mad4b-admin'", "AI review registered governance category")
require(authority, "'surface' => 'write'", "AI review dedicated write transport surface")
if "'category' => 'mad4b-write'" in authority:
    raise AssertionError("mad4b-write is an MCP server/transport ID, not a WordPress Ability category")
require(authority, "public static function review_asset_by_agent", "dedicated AI review callback")
require(authority, "private static function review_asset_with_actor", "shared actor-aware exact review primitive")
require(authority, "public static function set_review_policy", "explicit review policy mutation")
require(authority, "'human_only'", "human-only default review mode")
require(authority, "'human_and_ai'", "additive Human + AI review mode")
require(authority, "mad4b_context_ai_review_confirmation_required", "explicit AI review delegation confirmation")
require(authority, "mad4b_context_ai_review_governance_mutation_forbidden", "AI governance metadata mutation denial")
require(authority, "mad4b_context_ai_review_staging_only", "AI review Staging-only boundary")
require(authority, "mad4b_context_ai_review_agent_not_profile_owned", "AI review canonical Site Profile agent boundary")
require(authority, "MAD4B_SCP_Site_Profile::agent_slug()", "AI review canonical agent source")
require(authority, "method_exists( 'MAD4B_SCP_Site_Profile', 'current_environment' )", "AI review partial Site Profile environment guard")
require(authority, "method_exists( 'MAD4B_SCP_Site_Profile', 'agent_slug' )", "AI review partial Site Profile agent guard")
require(admin, "method_exists( 'MAD4B_SCP_Site_Profile', 'agent_slug' )", "AI selector partial Site Profile guard")
require(write_authority, "method_exists( 'MAD4B_SCP_Site_Profile', 'current_environment' )", "AI delegation partial Site Profile environment guard")
require(write_authority, "method_exists( 'MAD4B_SCP_Site_Profile', 'agent_slug' )", "AI delegation partial Site Profile agent guard")
require(authority, "MAD4B_SCP_Agent_Registry::resolve_agent", "AI review authenticated agent resolution")
require(authority, "MAD4B_SCP_Agent_Registry::exact_grant", "AI review exact grant check")
require(authority, "'quality_mode' => 'preserve'", "AI review immutable quality policy")
require(authority, "'mad4b/context-asset-ai-review'", "dedicated AI review audit event")
require(authority, "'review_actor_type'", "persisted review actor type")
require(authority, "'review_agent_public_id'", "persisted AI reviewer public ID")
require(authority, "mad4b_context_review_source_mode_forbidden", "Human Review governed-source-only backend guard")
require(authority, "Task attachments remain task-local and cannot become Brand Authority", "task-local promotion denial semantics")
require(authority, "mad4b_context_review_note_required", "review rationale required for non-default governance decisions")
require(authority, "review_decision", "persisted review decision semantics")
require(authority, "review_note", "persisted bounded reviewer rationale")
require(authority, "'needs_changes'", "needs-changes review state")
require(authority, "'rejected'", "rejected review state")
require(authority, "context-review-queue.v1", "read-only human review queue contract")
require(authority, "brand-core-context-coverage.v1", "Brand Core coverage diagnostic contract")
require(authority, "quality_mode", "explicit automatic/manual quality review mode")
require(authority, "mad4b_context_quality_score_required", "manual quality score fail-closed")
require(authority, "mad4b_context_automatic_quality_unavailable", "automatic score reset fail-closed")
require(authority, "needs_review_content_changed", "rescan review invalidation")
require(authority, "$prior_review_bound = $same_content", "human review decisions remain bound to exact same-hash content")
require(authority, "in_array( $prior_review_status, array( 'approved', 'needs_changes', 'rejected' ), true )", "same-hash rescan preserves only explicit exact human decision states")
require(authority, "hash_equals( $prior_reviewed_hash, (string) $normalized['content_hash'] )", "same-hash review preservation requires the exact reviewed content hash")
require(authority, "$normalized['reviewed_at'] = '';", "content change clears reviewer timestamp evidence")
require(authority, "status'] = 'unavailable'", "missing asset retention")
require(authority, "not_seen_in_complete_scan", "complete-scan missing asset reason")
require(authority, "last_complete_scan_generation", "complete scan generation evidence")
require(authority, "absence_scan_generation", "absence evidence binding")
require(authority, "partial_scan", "partial scan state")
require(authority, "asset_normalization_failed", "scan normalization loss downgrades completeness")
require(authority, "registry_asset_capacity_limit", "registry capacity loss downgrades completeness")
require(authority, "mad4b_context_source_registry_capacity_limit", "source creation capacity gate")
require(authority, "mad4b_context_asset_registry_capacity_limit", "asset creation capacity gate")
require(authority, "context_source_registry_capacity_exceeded", "raw source overflow readiness blocker")
require(authority, "context_asset_registry_capacity_exceeded", "raw asset overflow readiness blocker")
require(authority, "observed_asset_count", "scan observed asset evidence")
require(authority, "represented_asset_count", "scan represented asset evidence")
require(authority, "Only a fully observed + normalized + representable scan", "absence minted only after representability proof")
require(authority, "REGISTRY_REVISION_OPTION", "Context registry revision")
require(authority, "REGISTRY_LOCK_OPTION", "Context registry mutation lock")
require(authority, "authority_manifest_fingerprint", "authority manifest fingerprint")
require(authority, "commit_option_changes", "compensated multi-option registry commit")
require(authority, "registry_option_snapshot", "pre-mutation registry snapshot")
require(authority, "restore_registry_option_snapshot", "registry snapshot compensation")
require(authority, "audited_registry_result", "deferred governance audit result")
require(authority, "registry_snapshot_changed", "callback failure state-change detection")
require(authority, "compensate_registry_error", "callback/revision/audit compensation")
require(authority, "mad4b_context_registry_audit_commit_failed", "audit failure compensated error")
require(authority, "mad4b_context_registry_recovery_required", "failed compensation recovery-required state")
require(authority, "mad4b_context_registry_revision_write_failed", "revision persistence fail-closed")
require(authority, "mandatory_context_contains_unavailable_assets", "mandatory unavailable asset fail closed")
require(authority, "optional_context_contains_unavailable_assets", "optional unavailable asset warning")
require(authority, "ready_with_warnings", "optional Context degradation state")
require(authority, "upsert_asset_from_provider", "provider registry refresh")
require(authority, "register_recreated_asset", "atomic replacement registration")
require(authority, "mad4b_context_recreate_registry_commit_failed", "atomic replacement commit failure")
require(authority, "mark_asset_recreated", "legacy replacement lineage helper")
require(authority, "mad4b/context-source-scan", "source scan governance audit")
require(authority, "'observed_asset_count' => count( $normalized_assets )", "scan audit observed-count evidence")
require(authority, "$scan_complete ? 'ok' : 'partial'", "scan audit completeness status")
require(authority, "mad4b/context-profile-save", "Brand Context Profile save audit")
require(authority, "mad4b/context-source-upsert", "source binding upsert audit")
require(authority, "'created' => empty( $current )", "source upsert audit distinguishes create/update")
require(authority, "mad4b/context-asset-review", "asset review audit")
require(authority, "mad4b_context_audit_not_ready", "audit fail-closed preflight")

# First-party Context provider structural contract must cover every Authority helper
# used by update/recreate/undo paths, not only the happy-path restore methods.
require(
    adapter,
    "'MAD4B_SCP_Context_Authority' => array(\n\t\t\t\t'source',\n\t\t\t\t'asset',\n\t\t\t\t'source_allows_write',\n\t\t\t\t'upsert_asset_from_provider',\n\t\t\t\t'register_recreated_asset'",
    "complete Authority helper prefix in provider structural contract",
)
require(adapter, "'begin_recreated_asset_rollback'", "provider contract rollback intent")
require(adapter, "'cancel_recreated_asset_rollback'", "provider contract rollback intent cancellation")
require(adapter, "'rollback_recreated_asset'", "provider contract rollback finalization")

# Google OAuth supports explicit read-only and read+write, never implicit upgrade.
require(drive, "const READ_SCOPE = 'https://www.googleapis.com/auth/drive.readonly';", "Drive read-only scope")
require(drive, "const WRITE_SCOPE = 'https://www.googleapis.com/auth/drive';", "Drive read-write scope")
assert "https://www.googleapis.com/auth/drive.file" not in drive, "drive.file is not sufficient for governed existing-asset repair"
require(drive, "scope_is_allowed", "scope allowlist")
require(drive, "scope_allows_write", "write-scope detection")
require(drive, "scope_matches_requested_mode", "exact OAuth mode matching")
require(drive, "mad4b_google_drive_write_scope_missing", "explicit OAuth write grant")
require(drive, "REVOKE_ENDPOINT", "Google OAuth revoke endpoint")
require(drive, "mad4b_google_drive_readonly_downgrade_requires_revoke", "least-privilege downgrade guard")
require(drive, "remote_revocation_confirmed", "disconnect revocation evidence")
require(drive, "revocation_pending", "pending revocation state")
require(drive, "mad4b_google_drive_remote_revocation_unconfirmed", "unconfirmed remote revoke fail-closed")
require(drive, "mad4b_google_drive_revocation_pending", "Drive access disabled during revoke retry")
require(drive, "access_mode", "OAuth access mode binding")
require(drive, "requested_scope", "OAuth requested-scope binding")
require(drive, "'include_granted_scopes' => 'false'", "non-incremental OAuth scope contract")
require(drive, "mad4b_google_drive_granted_scope_missing", "initial OAuth granted-scope evidence")
require(drive, "mad4b_google_drive_readonly_scope_escalated", "read-only least-privilege enforcement")
require(drive, "mad4b_google_drive_oauth_site_binding_changed", "OAuth Site Profile binding")
require(drive, "mad4b_google_drive_oauth_redirect_binding_changed", "OAuth redirect binding")
require(drive, "aes-256-gcm", "encrypted token storage")
require(drive, "MAX_WRITE_BYTES", "bounded Drive write size")
require(drive, "MAX_REVERSIBLE_TEXT_BYTES", "bounded reversible snapshot size")
require(drive, "reversible_update_state", "Drive update rollback snapshot")
require(drive, "restore_update_state", "Drive update rollback restore")
require(drive, "reversible_recreate_state", "Drive recreate rollback snapshot")
require(drive, "restore_recreate_state", "Drive recreate rollback restore")
require(drive, "asset_write_capabilities", "per-asset Drive actionability")
require(drive, "google_docs_rich_rollback_not_certified", "rich Google Docs update fail-closed")
require(drive, "provider_observed_text", "provider readback canonicalization")
require(drive, "compensate_created_file_failure", "post-create compensation")
require(drive, "mad4b_google_drive_post_create_compensation_failed", "orphan-risk compensation failure")
require(drive, "mad4b_google_drive_rollback_delete_failed", "bounded internal replacement delete failure")
require(authority, "rollback_recreated_asset", "registry recreation rollback")
require(authority, "begin_recreated_asset_rollback", "persisted recreate rollback intent")
require(authority, "cancel_recreated_asset_rollback", "rollback intent cancellation")
require(drive, "mad4b_google_drive_recreate_rollback_recovery_required", "post-side-effect recovery-required state")
require(drive, "mad4b_google_drive_root_write_forbidden", "no broad My Drive root writes")
require(drive, "mad4b_google_drive_asset_outside_selected_source", "selected-source write boundary")
require(drive, "non_recursive_source_boundary", "non-recursive source write boundary")
require(drive, "0 === $depth && empty( $source['recursive'] )", "nested update denied for non-recursive source")
require(drive, "mad4b_google_drive_asset_remote_stale", "remote stale hash guard")
require(drive, "mad4b_google_drive_recreate_requires_unavailable_asset", "recreate only missing assets")
require(drive, "provider_absence_from_metadata_result", "provider absence classification")
require(drive, "last_complete_scan_generation", "recreate requires complete scan evidence")
require(drive, "absence_scan_generation", "recreate absence-generation binding")
require(drive, "mad4b_google_drive_recreate_duplicate_title_detected", "duplicate-safe recreation")
require(drive, "fetch_text_content_record", "explicit provider normalization completeness")
require(drive, "runtime_readiness", "safe Context runtime readiness diagnostic")
require(drive, "mad4b.google-drive-context-runtime-readiness.v1", "runtime readiness contract")
require(drive, "gemini_api_key_present", "Gemini secret presence-only diagnostic")
require(drive, "generic_extractor_token_present", "generic extractor secret presence-only diagnostic")
require(drive, "'secrets_exposed' => false", "runtime readiness explicitly denies secret exposure")
require(drive, "'pkce_s256' => true", "OAuth PKCE S256 readiness declaration")
require(drive, "AUTH_MODE_CONTRACT = 'mad4b.google-drive-auth-mode.v1'", "Google Drive auth-mode contract")
require(drive, "AUTH_MODE_CUSTOM = 'custom_credentials'", "Custom OAuth authentication mode")
require(drive, "AUTH_MODE_MANAGED = 'managed_google'", "Managed Google authentication mode")
require(drive, "AUTH_MODE_DEDICATED = 'dedicated_google'", "Dedicated Site Google authentication mode")
require(drive, "DEDICATED_CONFIG_OPTION", "Dedicated Site OAuth credentials use an isolated configuration record")
require(drive, "dedicated_redirect_uri", "Dedicated Site OAuth callback derives from Site Profile canonical origin")
require(drive, "MAD4B_SCP_Site_Profile::site_origin()", "Dedicated Site OAuth uses Site Profile primary domain")
require(drive, "MAD4B_SCP_Site_Profile::site_urls_match_enrollment()", "Dedicated Site OAuth requires exact Site Profile URL enrollment")
require(drive, "save_dedicated_credentials", "Dedicated Site OAuth encrypted credential setup")
require(drive, "dedicated_site_managed", "Dedicated Site OAuth custody declaration")
require(drive, "'central_mad4b_dependency' => false", "Dedicated Site OAuth has no central MAD4B dependency")
require(drive, "MAD4B_GOOGLE_MANAGED_OAUTH_BROKER_URL", "Managed OAuth broker configuration boundary")
require(drive, "mad4b.google-managed-oauth-session.v1", "Managed OAuth session contract")
require(drive, "mad4b.google-managed-oauth-redemption.v1", "Managed OAuth one-time redemption contract")
require(drive, "mad4b.google-managed-oauth-refresh.v1", "Managed OAuth refresh contract")
require(drive, "verifier_challenge", "Managed OAuth verifier challenge")
require(drive, "'verifier_method' => 'S256'", "Managed OAuth S256 handoff")
require(drive, "managed_redirect_uri", "Managed OAuth dedicated callback")
require(drive, "managed_broker_post", "Managed OAuth server-to-server broker exchange")
require(drive, "mad4b_google_drive_auth_mode_change_requires_disconnect", "Authentication mode switch requires disconnect")
require(drive, "wp_cache_delete( 'notoptions', 'options' )", "stale Options API negative-cache invalidation")
require(drive, "Some persistent-cache drop-ins can retain a stale negative index", "persistent option-cache false-negative repair")
require(drive, "'google_client_secret_on_site' => false", "Managed OAuth denies Google Client Secret custody on WordPress")
require(drive, "'credential_custody' => 'mad4b_managed_oauth'", "Managed OAuth custody declaration")
require(drive, "refresh_managed_access_token", "Managed OAuth broker refresh path")
require(drive, "MANAGED_SITE_AUTH_CONTRACT = 'mad4b.google-managed-oauth-site-request-auth.v1'", "Managed site request authentication contract")
require(drive, "MANAGED_SITE_AUTH_SCHEME = 'MAD4B-GOOGLE-OAUTH-SITE-V1'", "Managed site request signing scheme")
require(drive, "MAD4B_GOOGLE_MANAGED_OAUTH_SITE_KEY_ID", "Managed broker site key ID configuration")
require(drive, "MAD4B_GOOGLE_MANAGED_OAUTH_SITE_SECRET", "Managed broker site signing secret configuration")
require(drive, "managed_site_auth_status", "Managed broker site request authentication readiness")
require(drive, "managed_site_request_headers", "Managed broker signed request headers")
require(drive, "X-MAD4B-Site-Key-ID", "Managed broker key-id header")
require(drive, "X-MAD4B-Site-Timestamp", "Managed broker timestamp header")
require(drive, "X-MAD4B-Site-Nonce", "Managed broker nonce header")
require(drive, "X-MAD4B-Site-Signature", "Managed broker HMAC signature header")
require(drive, "hash_hmac( 'sha256'", "Managed broker HMAC-SHA256 signing")
require(drive, "'code_challenge_method' => 'S256'", "OAuth authorization uses PKCE S256")
require(drive, "'code_verifier' => $pkce_verifier", "OAuth token exchange binds PKCE verifier")
require(drive, "normalization_capabilities", "normalization capability manifest")
require(drive, "application/vnd.google-apps.presentation", "Google Slides plain-text normalization")
require(drive, "normalize_pdf", "bounded local PDF text normalization")
require(drive, "pdf_ocr_required", "scanned PDF OCR routing")
require(drive, "normalize_docx", "DOCX local normalization")
require(drive, "normalize_xlsx", "XLSX multi-sheet local normalization")
require(drive, "normalize_pptx", "PPTX slide and notes local normalization")
require(drive, "normalize_odf", "OpenDocument local normalization")
require(drive, "normalize_epub", "EPUB local normalization")
require(drive, "normalize_rtf", "RTF local normalization")
require(drive, "external_extractor_record", "governed media extractor fallback")
require(drive, "gemini_extractor_record", "Gemini multimodal extraction adapter")
require(drive, "MAD4B_CONTEXT_GEMINI_ENABLED", "explicit Gemini content-disclosure opt-in")
require(drive, "MAD4B_CONTEXT_GEMINI_API_KEY", "Gemini secret configuration boundary")
require(drive, "x-goog-api-key", "Gemini key stays in request header")
require(drive, "download_workspace_lro_bytes", "Drive long-running read for native Google file types")
require(drive, "application/vnd.google-apps.form", "Google Forms normalization route")
require(drive, "application/vnd.google-apps.site", "Google Sites normalization route")
require(drive, "application/vnd.google-apps.vid", "Google Vids normalization route")
require(drive, "normalize_native_download_bytes", "future Google-native content sniffing")
require(drive, "application/vnd.google-gemini.", "Google Gemini Drive MIME fallback")
require(drive, "google_drive_metadata_only_type", "folders and third-party shortcuts remain metadata-only")
require(drive, "normalize_generic_archive", "Google Forms and generic ZIP normalization")
require(drive, "MAD4B_CONTEXT_EXTRACTOR_URL", "explicit external extractor endpoint configuration")
require(drive, "MAD4B_CONTEXT_EXTRACTOR_TOKEN", "explicit external extractor credential configuration")
require(drive, "'limit_response_size' => (int) $max_bytes + 1", "generic bounded download sentinel byte")
require(drive, "mad4b_context_asset_content_incomplete", "incomplete Context fail-closed")
require(drive, "mad4b_google_drive_recreate_original_restored", "restored-original blocker")
require(drive, "mad4b_google_drive_recreate_absence_unverified", "unverified-absence blocker")
require(authority, "'parent_folder_id'", "asset parent-folder lineage")
require(drive, "recreate_parent_candidate", "recreate parent candidate")
require(drive, "resolve_recreate_target_folder", "exact recreate parent resolver")
require(drive, "mad4b_google_drive_recreate_parent_unavailable", "missing parent fail-closed")
require(drive, "mad4b_google_drive_recreate_parent_outside_source", "parent source-boundary fail-closed")
require(drive, "! $is_source_root && empty( $source['recursive'] )", "nested recreate denied for non-recursive source")
require(drive, "create_provider_file( $target_folder_id", "recreate writes to exact parent folder")
assert "create_provider_file( (string) $source['external_root_id'], $title" not in drive, "Recreate must never silently fall back to source root"
assert drive.count("self::assert_original_file_absent(") >= 2, "Recreate capture and execution must independently prove provider absence"
require(drive, "create_asset", "Drive asset create")
require(drive, "$target_folder_id = self::bounded_drive_id", "selected-folder create binding")
require(drive, "create_provider_file( $target_folder_id, $name", "create writes only to selected source folder")
require(drive, "verify_created_file_parent", "provider-confirmed created parent")
require(drive, "mad4b_google_drive_created_parent_mismatch", "created-parent mismatch fail-closed")
require(drive, "delete_provider_file_for_rollback( $file_id, $source, false )", "exact newly-created file compensation")
assert "'target_folder_id' => $target_folder_id" in drive, "create receipt must bind the exact selected folder"
require(drive, "update_asset", "Drive asset update")
require(drive, "recreate_asset", "Drive asset recreate")
assert "delete_asset(" not in drive, "Drive delete surface must remain absent"
assert "trash_asset(" not in drive, "Drive trash surface must remain absent"

status_body = drive.split("public static function connection_status()",1)[1].split("public static function public_connection_status",1)[0]
public_status_body = drive.split("public static function public_connection_status()",1)[1].split("public static function authorization_url",1)[0]
assert "'access_token' =>" not in status_body, "connection status must not expose access token"
assert "'refresh_token' =>" not in status_body, "connection status must not expose refresh token"
for sensitive in ("'scope' =>", "'account_email' =>", "'account_name' =>", "'permission_id' =>", "'access_token' =>", "'refresh_token' =>"):
    assert sensitive not in public_status_body, f"public Google Drive status leaked identity/credential field: {sensitive}"
require(adapter, "MAD4B_SCP_Google_Drive_Context::public_connection_status()", "remote Google Drive status uses privacy-bounded projection")
require(adapter, "MAD4B_SCP_Google_Drive_Context::runtime_readiness()", "remote readiness uses secret-safe provider projection")


# Governed adapter surfaces.
for ability in [
    "context/status",
    "context/assets",
    "context/google-drive-status",
    "context/runtime-readiness",
    "context/create-drive-asset",
    "context/update-drive-asset",
    "context/recreate-drive-asset",
]:
    require(adapter, ability, f"Context adapter ability {ability}")
require(adapter, "'contract' => 'mad4b.context-asset-list.v4'", "task-isolated Context asset list v4 contract")
require(adapter, "mad4b_context_task_scope_required", "explicit task-attachment listing requires exact task scope")
require(adapter, "hash_equals( $asset_scope, $task_scope )", "task attachment metadata exact-scope isolation")
require(adapter, "'task_scope' => array( 'type' => 'string', 'maxLength' => 160", "bounded task_scope asset-list input")
require(adapter, "'write' => array(", "dedicated write surface")
require(adapter, "mutation_ability_runtime_eligibility", "write runtime eligibility")
require(adapter, "mad4b.rollback.google-drive-context-update.v1", "Drive update reversible contract")
require(adapter, "mad4b.rollback.google-drive-context-recreate.v1", "Drive recreate reversible contract")
require(adapter, "capture_reversible_state", "Drive reversible capture")
require(adapter, "read_reversible_state", "Drive reversible readback")
require(adapter, "restore_reversible_state", "Drive reversible restore")
assert "context/create-drive-asset' => 'mad4b.rollback." not in adapter, "Drive create must not claim pre-target reversibility"
write_capability = drive.split("public static function write_capability_status()",1)[1].split("public static function asset_write_capabilities",1)[0]
require(write_capability, "'allowed_operations' => array( 'update', 'recreate' )", "only certified Drive operations are advertised")
require(write_capability, "'create' => 'mad4b_google_drive_create_rollback_not_certified'", "create capability advertises rollback blocker")
require(adapter, "mad4b_google_drive_create_rollback_not_certified", "arbitrary create denied until exact rollback certification")
require(grant_reconcile, "'context/update-drive-asset' => 'google_drive_context'", "Context update exact-grant reconciliation provider binding")
require(grant_reconcile, "'context/recreate-drive-asset' => 'google_drive_context'", "Context recreate exact-grant reconciliation provider binding")
allowlist = grant_reconcile.split('public static function allowed_ability_providers()', 1)[1].split('public static function boot()', 1)[0]
assert "'context/create-drive-asset'" not in allowlist, "Context create must remain outside exact-grant reconciliation until rollback is certified"
require(adapter, "google_drive_write_scope_required", "write mount requires OAuth write capability")
require(adapter, "source_required_for_write", "write mount requires selected Context source")
require(adapter, "context_provider_contract_status", "first-party Context provider certification")
require(adapter, "mad4b.google-drive-context-provider.v1", "first-party provider contract version")
require(adapter, "artifact_fingerprint", "critical runtime artifact fingerprint")
require(adapter, "control_plane_build_fingerprint", "Control Plane build-bound provider identity")
require(adapter, "runtime_structural_plus_build_bound_artifact_fingerprint", "build-bound first-party provider certification mode")
require(adapter, "MAD4B_SCP_External_Handshake_Evidence", "shared exact Control Plane build fingerprint source")
require(adapter, "mad4b_context_provider_contract_not_ready", "provider contract fail-closed write mount")
require(adapter, "return false;", "generic external-plugin certification engine remains explicitly bypassed only in favor of the dedicated first-party Context provider contract")
assert "'content' => array(\n\t\t\t'context/" not in adapter, "Context Drive mutations must not mount on content surface"

# Server mounting must stay structural: reads are projected from the read
# adapter surface; mutations are projected only through the dedicated write
# surface and are never hard-coded into content/admin core maps.
require(servers, "$registry->ability_names( 'read' )", "adapter read projection")
require(servers, "foreach ( array( 'content', 'admin', 'write' ) as $surface )", "dedicated adapter write projection")
require(servers, "if ( 'mad4b-write' === $server_id )", "dedicated write authority branch")
require(servers, "self::write_tools()", "runtime-gated write mount")
for ability in [
    "context/create-drive-asset",
    "context/update-drive-asset",
    "context/recreate-drive-asset",
]:
    assert ability not in servers, f"{ability} must be adapter-projected, never hard-coded into core server maps"

# Skill Context preflight is read-only, bounded and fail-closed.
require(preflight, "This service is read-only", "read-only Context preflight")
require(preflight, "MAX_CONTEXT_BYTES", "bounded Context envelope")
require(preflight, "required_context_asset_unreadable", "provider-read fail-closed")
require(preflight, "required_unavailable_asset_count", "mandatory-only unavailable authority gate")
require(preflight, "optional_context_asset_unreadable:", "optional read warning")
require(preflight, "required_context_sets_missing", "missing required category fail-closed")
require(preflight, "review_status", "human review carried into Context receipt")
require(preflight, "'approved' !== ( isset( $asset['review_status'] )", "mandatory governed assets require human approval")
require(preflight, "effective_required_context_sets", "Site plus Skill required Context union")
require(preflight, "site_required_context_sets", "Site mandatory Context projection")
require(preflight, "registry_revision", "Context receipt registry revision binding")
require(preflight, "authority_manifest_fingerprint", "Context receipt authority fingerprint binding")
require(preflight, "context_registry_changed_during_preflight", "preflight concurrent registry drift blocker")
require(preflight, "context_authority_changed_during_preflight", "preflight authority drift blocker")
require(preflight, "MAX_RECEIPT_AGE", "bounded Context receipt freshness")
require(preflight, "context_source_registry_capacity_exceeded", "source capacity overflow preflight blocker")
require(preflight, "context_asset_registry_capacity_exceeded", "asset capacity overflow preflight blocker")
require(preflight, "mutation_context_guard", "brand-bearing content mutation Context guard")
require(preflight, "validate_receipt_binding", "live Context receipt revalidation")
require(preflight, "commit_receipt_evidence", "durable append-only Context receipt evidence")
require(preflight, "mad4b/context-receipt-bound", "Context receipt audit binding")
require(preflight, "canonical_receipt_digest", "canonical Context receipt integrity digest")
require(preflight, "content_mutation_requirement", "central content-bearing mutation classifier")
require(preflight, "allowed_mutation_abilities", "Skill-scoped mutation allowlist")
require(preflight, "intended_ability", "exact Context Receipt mutation binding")
require(preflight, "mad4b_content_context_receipt_ability_binding_required", "unbound Brand Context receipt denied")
require(preflight, "mad4b_content_context_receipt_ability_mismatch", "horizontal Context receipt replay denied")
require(preflight, "mad4b_content_context_receipt_policy_not_authorizing", "no-context receipt cannot authorize Brand-bearing mutation")
require(preflight, "mad4b/content-create-post", "core post creation receipt enforcement")
require(preflight, "mad4b/taxonomy-create-term", "core taxonomy creation receipt enforcement")
require(preflight, "media/update-metadata", "media text metadata receipt enforcement")
require(preflight, "mad4b/content-import-bundle", "content bundle receipt enforcement")
require(preflight, "mad4b/taxonomy-update-term", "taxonomy copy receipt enforcement")
require(preflight, "seo/update-meta", "SEO copy receipt enforcement")
require(preflight, "woocommerce/update-product", "product copy receipt enforcement")
require(preflight, "elementor/update-widget-settings", "Elementor copy receipt enforcement")
require(preflight, "jetengine/update-post-meta", "JetEngine copy receipt enforcement")
require(preflight, "mad4b/content-set-meta", "post meta copy receipt enforcement")
require(preflight, "content_paths_in_value", "nested widget content detection")
require(preflight, "editor|html|wysiwyg", "rich-text field-name detection")
assert "'context_receipt' => $receipt" not in preflight, "Full Context receipt must not be duplicated into append-only audit payload"

# Skill exposure must be Context-bound; portable export may not bypass it.
require(skill_registry, "context_policy_sha256", "Skill Context policy digest")
require(skill_registry, "normalize_context_policy", "Skill Context policy normalization")
require(skill_abilities, "MAD4B_SCP_Context_Preflight::preflight_entry", "Skill get Context Preflight")
require(skill_abilities, "mad4b_required_brand_context_unavailable", "Skill fail-closed Context blocker")
require(skill_abilities, "mad4b.skill-get.v3", "Context-bound Skill get contract with exact intended-ability binding")
require(skill_abilities, "intended_ability", "Skill get intended mutation input")
require(skills_admin, "Allowed Brand-bearing write abilities", "Skill Context mutation allowlist UX")
require(skill_snapshot, "context_policy_sha256", "portable snapshot Context policy identity")
require(skill_exporter, "mad4b_context_required_skill_policy_identity_missing", "portable Context-required Skill requires exact policy identity")
require(skill_exporter, "mad4b_context_required_skill_preflight_unavailable", "portable Context-required Skill requires server preflight")
require(skill_exporter, "context_required_skills_require_policy_digest", "portable snapshot records Context policy enforcement")
require(skill_exporter, "brand_bearing_writes_require_exact_context_receipt", "portable snapshot records exact receipt enforcement")
require(skill_exporter, "portable_skill_does_not_grant_write_authority", "portable Context Skill cannot become write authority")

# Context receipt must remain governance evidence: included in planning/approval
# identity, revalidated before claim, persisted before side effects, then stripped
# before the provider callback.
require(write_authority, "CONTEXT_RECEIPT_INPUT_KEY", "Context receipt governance envelope key")
require(write_authority, "context_receipt_from_input", "Context receipt extraction")
require(write_authority, "provider_input", "provider-facing governance metadata stripping")
require(write_authority, "unset( $clean[ self::CONTEXT_RECEIPT_INPUT_KEY ] )", "Context receipt stripped before provider callback")
require(authorization, "mutation_context_guard", "central mutation Context guard")
require(authorization, "commit_receipt_evidence", "receipt evidence committed before execution")
require(authorization, "context_receipt_bound", "receipt execution binding state")
require(planning_guard, "mutation_context_guard", "approval planning Context guard")
require(planning_guard, "Brand-bearing content approval planning", "planning fail-closed when Context runtime is unavailable")

# Guided UX makes OAuth capability vs MAD4B authority explicit.
require(admin, "Sign in with Google — Recommended", "Managed Google Sign-In recommended UX")
require(admin, "Dedicated Google OAuth — Site Domain", "Dedicated Site OAuth UX")
require(admin, "Custom Google OAuth App — Advanced", "Custom OAuth advanced UX")
require(admin, "ACTION_GOOGLE_DEDICATED_CALLBACK", "Dedicated Site OAuth callback action")
require(admin, "handle_google_dedicated_callback", "Dedicated Site OAuth callback handler")
require(admin, "Save Dedicated OAuth Configuration", "Dedicated Site OAuth settings UX")
require(admin, "Changes save automatically when you choose a connection method.", "AJAX-only authentication mode selection UX")
require(admin, "Managed Google Sign-In", "Managed OAuth setup UX")
require(admin, "MAD4B Managed OAuth broker and per-site request signing are configured.", "Managed OAuth broker readiness UX")
require(admin, "handle_google_managed_callback", "Managed OAuth dedicated callback handler")
require(admin, "Sign in with Google", "primary managed Google connect UX")
require(admin, "Drive access:", "selected Drive grant visibility")
require(admin, "Advanced Google settings", "advanced OAuth disclosure UX")
require(admin, "Google Workspace grants", "Workspace grant catalog UX")
require(admin, "Select Full Apps Suite", "Full Apps Suite grant preset UX")
require(admin, "Save Grants", "AJAX Workspace grant save UX")
require(admin, "mad4b-context-ajax-form", "AJAX settings forms")
require(admin, "mad4b-context-auth-mode-form", "AJAX auth-mode auto-save form")
require(admin, 'data-mad4b-autosave="auth-mode"', "auth-mode form explicit auto-save marker")
assert "Save Connection Method" not in admin, "auth-mode selection must not expose a Save Connection Method control"
require(admin, "form.requestSubmit()", "auth-mode radio auto-submit over AJAX")
require(admin, "wp_ajax_", "WordPress AJAX action registration")
require(admin, "mad4bBusy", "AJAX duplicate-submit guard")
require(admin, "aria-busy", "AJAX busy-state accessibility")
require(admin, "await refreshPanels();}catch(refreshError){}", "AJAX failure restores authoritative server-rendered Google state")
require(admin, ".mad4b-context-page > .notice", "AJAX clears stale post-redirect page notice")
require(admin, "check_ajax_referer", "AJAX nonce enforcement")
require(admin, "window.ajaxurl", "WordPress admin AJAX transport")
require(admin, "require_admin_request", "AJAX capability and nonce guard")
require(admin, "Disconnect & Revoke Google Access", "least-privilege disconnect UX")
require(admin, "Google revocation is pending.", "pending revoke warning UX")
require(admin, "Retry revoke", "revocation retry UX")
require(admin, "one-time approval", "governed write UX")
require(admin, "Folder Picker", "folder picker")
require(admin, "My Drive is available for navigation only", "root folder browse-only UX")
require(admin, "Governed Library", "governed library UX")
require(admin, "Task-only Source", "task-only source UX")
require(authority, "mad4b_context_source_write_policy_confirmation_required", "explicit source write escalation confirmation")
require(authority, "write_policy_escalation_requires_confirmation", "server-side least-privilege transition guard")
require(authority, "mad4b_context_source_recursive_confirmation_required", "explicit recursive source-scope expansion confirmation")
require(authority, "recursive_scope_expansion_requires_confirmation", "server-side recursive source boundary transition guard")
require(authority, "recursive_scope_confirmed", "audited recursive source boundary confirmation")
require(admin, "Confirm any increase in Drive write authority for this source", "new-source write escalation confirmation UX")
require(admin, "Confirm if this change increases Drive write authority", "existing-source write escalation confirmation UX")
require(admin, "Quality and authority are separate", "quality/authority UX guidance")
require(admin, "Normalization support", "normalization support matrix UX")
require(admin, "Use automatic score", "automatic quality score review UX")
require(admin, "Manual override", "manual quality override UX")
require(admin, "Context Review Queue", "visible combined Context review queue UX")
require(admin, "Approval Mode", "Human and AI approval mode panel")
require(admin, "Human Approval", "Human approval mode remains visible")
require(admin, "AI Agent Approval", "AI Agent approval mode is visible beside Human")
require(admin, "ACTION_SAVE_REVIEW_POLICY", "review policy admin action")
require(admin, "confirm_ai_review_delegation", "explicit AI delegation confirmation UX")
require(admin, "ai_agent_public_id", "exact delegated AI Agent selector")
require(admin, "MAD4B_SCP_Governance_Abilities::agent_list", "bounded enabled-agent selector source")
require(admin, "mad4b-context-review-policy-form", "AJAX review policy form")
require(admin, "Exact write authority/grant reconciliation remains explicit.", "no automatic grant reconciliation UX")
require(admin, "Human Review is intentionally unavailable for task-only Context", "task-local Human Review hidden UX")
require(admin, "Review decision saved.", "decision-neutral AJAX fallback")
require(admin, "wp_nonce_field( self::ACTION_REVIEW_ASSET )", "Human Review form nonce")
require(admin, "check_ajax_referer( $action, '_wpnonce', false )", "Human Review AJAX nonce enforcement")
require(admin, "current_user_can( 'manage_options' )", "Human Review admin capability enforcement")
require(admin, "Human review is pending.", "Source Folders Human Review discovery CTA")
require(admin, "Quality evidence does not replace Human Review.", "Quality Human Review discovery CTA")
require(admin, "Open Human Review Queue", "cross-tab Human Review queue navigation")
require(admin, "Exact Context content marked as needing changes.", "decision-aware needs-changes AJAX response")
require(admin, "Exact Context content rejected.", "decision-aware rejection AJAX response")
require(admin, "review_status' => $review_state", "AJAX review state response")
require(admin, "in_array( $review, array( 'unreviewed', 'needs_review_content_changed', 'needs_changes', 'rejected' ), true )", "complete actionable Human Review filter")
require(admin, "'approved' === $review && ! $review_exact", "legacy unbound approval remains actionable in Human Review filter")
require(admin, "Review required assets", "Overview direct human review CTA")
require(admin, "Approve exact content", "explicit approval semantics")
require(admin, "Needs changes", "explicit needs-changes review decision UX")
require(admin, "Reject exact content", "explicit rejection review decision UX")
require(admin, "data-mad4b-review-decision", "explicit review decision button binding")
require(admin, 'name="review_note"', "bounded review rationale UX")
require(admin, "Automatic suggestion:", "automatic classifier evidence in review UX")
require(admin, "Effective decision:", "effective human governance decision in review UX")
require(admin, "expected_content_hash", "admin exact content review binding")
require(admin, "expected_registry_revision", "admin registry revision review binding")
require(admin, "expected_authority_manifest_fingerprint", "admin authority fingerprint review binding")
require(admin, "required_scope_confirmed", "admin required Context escalation confirmation")
require(admin, "may change site-wide Brand Context requirements", "required-set shift/reduction confirmation UX")
require(admin, "mad4b-context-review-cell", "sticky review action UX")
require(admin, "refreshReviewPanels", "AJAX review readback refresh")

review_submit = admin.split('var form=event.target.closest(".mad4b-context-review-form")', 1)[1].split('var form=event.target.closest(".mad4b-context-ajax-form")', 1)[0]
if review_submit.index("var body=new URLSearchParams(new FormData(form));") > review_submit.index("controls.forEach(function(control){control.disabled=true;});"):
    raise AssertionError("review AJAX serializes after controls are disabled; disabled exact-review evidence would be omitted")

review_table = admin.split("foreach ( $assets as $asset )", 1)[1].split("private static function render_repair_queue", 1)[0]
task_guard = review_table.index("if ( 'governed' !== ( isset( $asset['source_mode'] )")
review_form_nonce = review_table.index("wp_nonce_field( self::ACTION_REVIEW_ASSET )")
if task_guard > review_form_nonce:
    raise AssertionError("task-local Human Review guard must run before rendering the review form")

require(admin, "Actionability", "per-asset actionability UX")
require(admin, "Reversible text update", "reversible update UX")
require(admin, "Reversible missing-asset recreation", "reversible recreate UX")
require(admin, "Write Governance Readiness", "write governance readiness UX")
require(admin, "MAD4B_SCP_Live_Truth::current_authority_status()", "live authority truth in UX")
require(admin, "Context Authority never reconciles grants automatically", "no automatic grant reconciliation UX")
require(admin, "runtime_authority_not_reconciled", "runtime reconciliation blocker UX")

require(workflow, "context-oauth-lifecycle-runtime.php", "OAuth lifecycle runtime CI")
require(oauth_runtime, "mad4b.site-control-plane.context-oauth-lifecycle.runtime.v10: PASS", "Managed, Dedicated, Workspace grants, site-HMAC, and persistent-option-cache OAuth lifecycle runtime proof")
require(oauth_runtime, "mad4b_context_option_cache", "stale persistent option-cache runtime fixture")
require(oauth_runtime, "notoptions", "stale negative option-cache regression")
require(oauth_runtime, "mad4b_assert_managed_site_signature", "Managed broker site-HMAC runtime verification")
require(oauth_runtime, "MAD4B_GOOGLE_MANAGED_OAUTH_SITE_SECRET", "Managed broker signing secret runtime fixture")
require(oauth_runtime, "Managed session/redeem/refresh must each use a fresh request nonce.", "Managed broker fresh nonce runtime assertion")
require(oauth_runtime, "AUTH_MODE_DEDICATED", "Dedicated Site OAuth runtime mode test")
require(oauth_runtime, "dedicated-client.apps.googleusercontent.com", "Dedicated Site OAuth client isolation runtime test")
require(oauth_runtime, "central MAD4B OAuth dependency", "Dedicated Site OAuth central independence runtime assertion")
require(oauth_runtime, "Dedicated OAuth must not call the MAD4B managed OAuth broker.", "Dedicated Site OAuth no-broker runtime assertion")
require(oauth_runtime, "managed_authorization_url", "Managed OAuth session runtime test")
require(oauth_runtime, "complete_managed_oauth", "Managed OAuth redemption runtime test")
require(oauth_runtime, "mad4b_google_drive_auth_mode_change_requires_disconnect", "Connected auth mode change fail-closed runtime test")
require(oauth_runtime, "full_suite_grant_selection", "Full Apps Suite runtime grant test")
require(oauth_runtime, "GMAIL_FULL_SCOPE", "Gmail full grant runtime assertion")
require(oauth_runtime, "CALENDAR_FULL_SCOPE", "Calendar full grant runtime assertion")
require(drive, "WORKSPACE_GRANTS_CONTRACT", "machine-readable Google Workspace grant contract")
require(drive, "workspace_grant_catalog", "Google Workspace grant catalog")
require(drive, "mad4b_google_workspace_scope_set_not_exact", "exact returned scope-set enforcement")
require(drive, "generative-language.retriever", "Gemini OAuth grant")
require(drive, "gmail.settings.sharing", "Gmail settings grant")
require(drive, "script.projects", "Apps Script project grant")
require(drive, "wp_cache_delete( $name, 'options' )", "option persistence cache readback hardening")
require(drive, "wp_cache_flush_group( 'options' )", "persistent Options cache group fallback")
require(drive, "self::clear_option_read_cache( $name, true )", "pre-read Options cache invalidation")
require(workflow, "context-human-review-runtime.php", "human review persistence runtime CI")
require(workflow, "context-ai-agent-review-runtime.php", "AI Agent review runtime CI")
require(ai_review_runtime, "mad4b.site-control-plane.context-ai-agent-review.runtime.v1: PASS", "AI Agent review runtime proof")
require(ai_review_runtime, "mad4b_context_ai_review_governance_mutation_forbidden", "AI runtime governance mutation denial proof")
require(ai_review_runtime, "mad4b_context_ai_review_exact_grant_missing", "AI runtime exact grant denial proof")
require(ai_review_runtime, "mad4b_context_ai_review_agent_mismatch", "AI runtime exact agent denial proof")
require(ai_review_runtime, "mad4b_context_ai_review_staging_only", "AI runtime Production denial proof")
require(adapter, "'context/review-queue'", "read-only Context review queue ability")
require(adapter, "'context/review-audit'", "bounded read-only Context review audit ability")

if adapter.count("'context/review-audit'") != 2:
    raise AssertionError("Context review-audit must appear exactly once in ability_names and once in registration")
if adapter.count("public function context_review_audit(") != 1:
    raise AssertionError("Context review-audit handler must have exactly one definition")
if adapter.count("final class MAD4B_SCP_Context_Adapter") != 1:
    raise AssertionError("Context adapter source contains duplicated class content")
require(adapter, "'pattern' => '^[a-f0-9]{64}$', 'default' => ''", "bounded Human Review audit asset-id schema")
if "'pattern' => '^[a-f0-9]{64}\n" in adapter:
    raise AssertionError("Context review-audit asset-id pattern is truncated or source-corrupted")

for forbidden_review_ability in ("'context/review-asset'", "'context/approve-asset'", "'context/review'", "'context/approve'"):
    if forbidden_review_ability in adapter:
        raise AssertionError(f"Human Review must remain Admin-only; forbidden MCP mutation surface found: {forbidden_review_ability}")

if "'mad4b/context-ai-review'" in adapter:
    raise AssertionError("AI Agent review is internal governance and must not mount through the Google Drive Context adapter")
require(authority, "'mad4b/context-ai-review'", "direct core AI review ability registration")
require(servers, "'mad4b/context-ai-review'", "stable unified catalog entry for AI review")
require(servers, "MAD4B_SCP_Context_Authority::ai_review_catalog_eligible()", "AI review runtime inventory policy gate")
require(servers, "array_diff( $candidates, array( 'mad4b/context-ai-review' ) )", "AI review fail-closed runtime unmount")
blocked_write_body = servers.split("public static function blocked_write_tools()", 1)[1].split("public static function governance_gated_write_tools()", 1)[0]
if "ai_review_standing_delegation_not_eligible" in blocked_write_body:
    raise AssertionError("blocked_write_tools must remain provider/runtime-certification scoped; core AI standing-delegation gates belong to write_tools()/authority status")
require(write_authority, "mad4b.context-ai-review-standing-delegation.v1", "AI review standing delegation contract")
require(write_authority, "public static function ai_review_delegation_status", "AI review request-time delegation guard")
require(write_authority, "public static function ai_review_delegation_allowed", "AI review standing delegation predicate")
require(write_authority, "'ai_review_approval_ticket_not_allowed'", "AI review forbids ticket/delegation ambiguity")
require(write_authority, "'ai_review_agent_not_profile_owned'", "AI standing delegation requires canonical Site Profile agent")
require(grant_reconcile, "'mad4b/context-ai-review' => 'core'", "AI review exact-grant reconciliation allowlist")
require(write_authority, "'governance_metadata_mutation_allowed' => false", "AI review standing delegation cannot change governance metadata")
require(write_authority, "'production_authorized' => false", "AI review standing delegation remains non-production")

require(adapter, "MAD4B_SCP_Audit::context_review_events", "Context review audit adapter delegates to bounded audit lookup")
require(audit, "context_review_events", "bounded Context review audit lookup")
require(audit, "'mad4b/context-asset-review'", "Human Context review audit event-type bound")
require(audit, "'mad4b/context-asset-ai-review'", "AI Context review audit event-type bound")
require(audit, "'wp_admin', 'ai_agent'", "bounded review audit actor filter")
require(audit, "review_note_present", "Context review audit exposes rationale presence only")
require(audit, "review_note_sha256", "Context review audit exposes rationale hash only")
require(audit, "unset( $summary['review_note'] )", "Context review audit redacts raw review rationale")
require(audit, "mad4b.context-review-audit.v2", "combined Context review audit read contract")
require(audit, "'read_only' => true", "Context Human Review audit remains read-only")
require(audit, "'mutation_performed' => false", "Context Human Review audit performs no mutation")
require(adapter, "'context/brand-core-coverage'", "read-only Brand Core coverage ability")
require(staging_handoff, "context_human_review_admin_ui_visible_for_governed_assets", "post-deploy governed Human Review UI acceptance")
require(staging_handoff, "context_task_local_human_review_controls_absent", "post-deploy task-local Human Review denial acceptance")
require(staging_handoff, "context_review_queue_read_only_surface_available", "post-deploy Human Review queue acceptance")
require(staging_handoff, "context_review_audit_read_only_surface_available", "post-deploy Human Review audit acceptance")
require(staging_handoff, "context_brand_core_coverage_read_only_surface_available", "post-deploy Brand Core coverage acceptance")
require(staging_handoff, "context_human_review_mcp_mutation_surface_absent", "post-deploy Human Review MCP mutation absence acceptance")
require(staging_handoff, "context_review_default_mode_human_only_after_upgrade", "post-deploy human-only default acceptance")
require(staging_handoff, "context_ai_review_admin_confirmation_required", "post-deploy explicit AI delegation acceptance")
require(staging_handoff, "context_ai_review_exact_agent_and_exact_grant_required", "post-deploy exact AI identity/grant acceptance")
require(staging_handoff, "context_ai_review_policy_change_does_not_auto_reconcile_grants", "post-deploy no automatic grant reconciliation acceptance")
require(staging_handoff, "context_ai_review_exact_bound_stale_evidence_rejected", "post-deploy stale AI evidence denial acceptance")
require(staging_handoff, "context_ai_review_governance_metadata_and_quality_immutable", "post-deploy AI governance immutability acceptance")
require(staging_handoff, "context_human_review_remains_available_after_ai_enablement", "post-deploy Human fallback acceptance")
require(staging_handoff, "context_ai_review_production_remains_unauthorized", "post-deploy Production denial acceptance")

require(package_workflow, "'normal_remote_writes_require_exact_one_time_approval': True", "package invariant for normal one-time approvals")
require(package_workflow, "'context_ai_review_may_use_explicit_standing_delegation': True", "package invariant for bounded AI review standing delegation")
require(package_workflow, "'context_ai_review_standing_delegation_staging_only': True", "package invariant for Staging-only AI review standing delegation")
require(package_workflow, "'context_ai_review_standing_delegation_exact_agent_grant_budget_audit_required': True", "package invariant for AI review governance requirements")
require(package_workflow, "'context_ai_review_standing_delegation_production_authorized': False", "package invariant denying Production AI review")
if "'remote_writes_require_exact_one_time_approval': True" in package_workflow:
    raise AssertionError("package manifest must not claim universal one-time approval after the bounded AI review standing-delegation exception")
require(adapter, "mad4b.context-asset-list.v4", "Context asset observability v4")
require(adapter, "review_actor_type", "Context asset review actor observability")
require(adapter, "review_agent_public_id", "Context asset AI reviewer observability")
require(adapter, "reviewed_content_hash", "Context asset exact review observability")
require(adapter, "review_binding_exact", "Context asset exact review binding observability")
require(adapter, "review_decision", "Context asset review decision observability")
require(adapter, "review_note", "Context asset reviewer rationale observability")
require(authority, "legacy_unbound", "legacy approval binding backlog observability")
require(adapter, "classification_source", "Context asset classification provenance observability")
require(adapter, "automatic_classification", "automatic classification evidence observability")

brand_contract = root / "tests/brand-context-builder-contract.py"
subprocess.run([sys.executable, str(brand_contract)], check=True)
brand_runtime = root / "tests/brand-context-builder-runtime.php"
subprocess.run(["php", str(brand_runtime)], check=True)

print("mad4b.site-control-plane.context-authority-contract.v73: PASS")
