from pathlib import Path

root = Path(__file__).resolve().parents[1]
main = (root / "mad4b-site-control-plane.php").read_text(encoding="utf-8")
authority = (root / "includes/class-mad4b-scp-context-authority.php").read_text(encoding="utf-8")
drive = (root / "includes/class-mad4b-scp-google-drive-context.php").read_text(encoding="utf-8")
admin = (root / "includes/class-mad4b-scp-context-admin-ui.php").read_text(encoding="utf-8")
adapter = (root / "includes/adapters/class-mad4b-scp-context-adapter.php").read_text(encoding="utf-8")
registry = (root / "includes/class-mad4b-scp-adapter-registry.php").read_text(encoding="utf-8")
servers = (root / "includes/class-mad4b-scp-servers.php").read_text(encoding="utf-8")
preflight = (root / "includes/class-mad4b-scp-context-preflight.php").read_text(encoding="utf-8")
skill_registry = (root / "includes/class-mad4b-scp-skill-registry.php").read_text(encoding="utf-8")
skill_abilities = (root / "includes/class-mad4b-scp-skill-abilities.php").read_text(encoding="utf-8")
skill_snapshot = (root / "includes/class-mad4b-scp-skill-snapshot-identity.php").read_text(encoding="utf-8")
skill_exporter = (root / "includes/class-mad4b-scp-skill-exporter.php").read_text(encoding="utf-8")
authorization = (root / "includes/class-mad4b-scp-authorization.php").read_text(encoding="utf-8")
write_authority = (root / "includes/class-mad4b-scp-staging-write-authority.php").read_text(encoding="utf-8")
planning_guard = (root / "includes/class-mad4b-scp-staging-write-planning-guard.php").read_text(encoding="utf-8")
workflow = (root.parents[2] / ".github/workflows/mad4b-context-authority.yml").read_text(encoding="utf-8")

def require(text, needle, label):
    assert needle in text, f"missing {label}: {needle}"

# Lifecycle and adapter registration.
require(main, "class-mad4b-scp-context-authority.php", "context authority wiring")
require(main, "class-mad4b-scp-google-drive-context.php", "google drive wiring")
require(main, "class-mad4b-scp-context-preflight.php", "Context Preflight runtime wiring")
require(main, "class-mad4b-scp-context-adapter.php", "context adapter wiring")
require(main, "class-mad4b-scp-context-admin-ui.php", "context admin wiring")
require(main, "MAD4B_SCP_Context_Admin_UI::boot();", "context admin boot")
require(registry, "'MAD4B_SCP_Context_Adapter'", "context adapter registry registration")

# Context Authority semantics.
require(authority, "'governed'", "governed source mode")
require(authority, "'task_attachment'", "task-only source mode")
require(authority, "mad4b_context_source_root_forbidden", "My Drive root source denial")
require(authority, "context_fingerprint", "context fingerprint")
require(authority, "$site = self::site_binding();", "Context reads bind to current Site Profile")
require(authority, "hash_equals( (string) $site['site_uuid']", "exact Site UUID read isolation")
require(authority, "! isset( $sources[ $source_id ] )", "orphan asset source denial")
require(authority, "hash_equals( $source_mode, $asset_mode )", "asset/source mode binding")
require(authority, "raw_sources", "raw Context source storage view")
require(authority, "raw_assets", "raw Context asset storage view")
require(authority, "authorized_sources_from_records", "source-authorized read projection")
require(authority, "authorized_assets_from_records", "asset-authorized read projection")
require(authority, "self::raw_assets()", "mutation paths preserve raw asset siblings")
require(authority, "self::raw_sources()", "mutation paths preserve raw source siblings")
require(authority, "classification_confidence", "classification confidence")
require(authority, "authority_class", "authority class")
require(authority, "quality_score", "quality score")
require(authority, "mad4b.context-quality-score.v2", "quality scoring v2 contract")
require(authority, "quality_profile_for_category", "category-aware quality profiles")
require(authority, "market_research", "market research scoring profile")
require(authority, "writer_reference", "writer reference scoring profile")
require(authority, "language_quality", "language-quality scoring dimension")
require(authority, "retrieval_quality", "retrieval-quality scoring dimension")
require(authority, "metadata_provisional", "metadata-only provisional scoring")
require(authority, "review_asset", "human review contract")
require(authority, "quality_mode", "explicit automatic/manual quality review mode")
require(authority, "mad4b_context_quality_score_required", "manual quality score fail-closed")
require(authority, "mad4b_context_automatic_quality_unavailable", "automatic score reset fail-closed")
require(authority, "needs_review_content_changed", "rescan review invalidation")
require(authority, "$prior_approved = $same_content", "approval remains bound to exact content hash")
require(authority, "&& 'approved' === ( isset( $prior['review_status'] )", "rescan may preserve only an already-approved exact hash")
require(authority, "$normalized['reviewed_at'] = '';", "content change clears reviewer timestamp evidence")
require(authority, "status'] = 'unavailable'", "missing asset retention")
require(authority, "not_seen_in_complete_scan", "complete-scan missing asset reason")
require(authority, "last_complete_scan_generation", "complete scan generation evidence")
require(authority, "absence_scan_generation", "absence evidence binding")
require(authority, "partial_scan", "partial scan state")
require(authority, "asset_normalization_failed", "scan normalization loss downgrades completeness")
require(authority, "registry_asset_capacity_limit", "registry capacity loss downgrades completeness")
require(authority, "mad4b_context_source_registry_capacity_limit", "source creation capacity gate")
require(authority, "mad4b_context_asset_registry_capacity_limit", "asset creation capacity gate")
require(authority, "context_source_registry_capacity_exceeded", "raw source overflow readiness blocker")
require(authority, "context_asset_registry_capacity_exceeded", "raw asset overflow readiness blocker")
require(authority, "observed_asset_count", "scan observed asset evidence")
require(authority, "represented_asset_count", "scan represented asset evidence")
require(authority, "Only a fully observed + normalized + representable scan", "absence minted only after representability proof")
require(authority, "REGISTRY_REVISION_OPTION", "Context registry revision")
require(authority, "REGISTRY_LOCK_OPTION", "Context registry mutation lock")
require(authority, "authority_manifest_fingerprint", "authority manifest fingerprint")
require(authority, "commit_option_changes", "compensated multi-option registry commit")
require(authority, "registry_option_snapshot", "pre-mutation registry snapshot")
require(authority, "restore_registry_option_snapshot", "registry snapshot compensation")
require(authority, "audited_registry_result", "deferred governance audit result")
require(authority, "registry_snapshot_changed", "callback failure state-change detection")
require(authority, "compensate_registry_error", "callback/revision/audit compensation")
require(authority, "mad4b_context_registry_audit_commit_failed", "audit failure compensated error")
require(authority, "mad4b_context_registry_recovery_required", "failed compensation recovery-required state")
require(authority, "mad4b_context_registry_revision_write_failed", "revision persistence fail-closed")
require(authority, "mad4b_context_registry_revision_recovery_required", "revision compensation recovery-required state")
require(authority, "mandatory_context_contains_unavailable_assets", "mandatory unavailable asset fail closed")
require(authority, "optional_context_contains_unavailable_assets", "optional unavailable asset warning")
require(authority, "ready_with_warnings", "optional Context degradation state")
require(authority, "upsert_asset_from_provider", "provider registry refresh")
require(authority, "register_recreated_asset", "atomic replacement registration")
require(authority, "mad4b_context_recreate_registry_commit_failed", "atomic replacement commit failure")
require(authority, "mark_asset_recreated", "legacy replacement lineage helper")
require(authority, "mad4b/context-asset-review", "asset review audit")
require(authority, "mad4b_context_audit_not_ready", "audit fail-closed preflight")

# Google OAuth supports explicit read-only and read+write, never implicit upgrade.
require(drive, "const READ_SCOPE = 'https://www.googleapis.com/auth/drive.readonly';", "Drive read-only scope")
require(drive, "const WRITE_SCOPE = 'https://www.googleapis.com/auth/drive';", "Drive read-write scope")
assert "https://www.googleapis.com/auth/drive.file" not in drive, "drive.file is not sufficient for governed existing-asset repair"
require(drive, "scope_is_allowed", "scope allowlist")
require(drive, "scope_allows_write", "write-scope detection")
require(drive, "scope_matches_requested_mode", "exact OAuth mode matching")
require(drive, "mad4b_google_drive_write_scope_missing", "explicit OAuth write grant")
require(drive, "REVOKE_ENDPOINT", "Google OAuth revoke endpoint")
require(drive, "mad4b_google_drive_readonly_downgrade_requires_revoke", "least-privilege downgrade guard")
require(drive, "remote_revocation_confirmed", "disconnect revocation evidence")
require(drive, "revocation_pending", "pending revocation state")
require(drive, "mad4b_google_drive_remote_revocation_unconfirmed", "unconfirmed remote revoke fail-closed")
require(drive, "mad4b_google_drive_revocation_pending", "Drive access disabled during revoke retry")
require(drive, "access_mode", "OAuth access mode binding")
require(drive, "requested_scope", "OAuth requested-scope binding")
require(drive, "'include_granted_scopes' => 'false'", "non-incremental OAuth scope contract")
require(drive, "mad4b_google_drive_granted_scope_missing", "initial OAuth granted-scope evidence")
require(drive, "mad4b_google_drive_readonly_scope_escalated", "read-only least-privilege enforcement")
require(drive, "mad4b_google_drive_oauth_site_binding_changed", "OAuth Site Profile binding")
require(drive, "mad4b_google_drive_oauth_redirect_binding_changed", "OAuth redirect binding")
require(drive, "aes-256-gcm", "encrypted token storage")
require(drive, "MAX_WRITE_BYTES", "bounded Drive write size")
require(drive, "MAX_REVERSIBLE_TEXT_BYTES", "bounded reversible snapshot size")
require(drive, "reversible_update_state", "Drive update rollback snapshot")
require(drive, "restore_update_state", "Drive update rollback restore")
require(drive, "reversible_recreate_state", "Drive recreate rollback snapshot")
require(drive, "restore_recreate_state", "Drive recreate rollback restore")
require(drive, "asset_write_capabilities", "per-asset Drive actionability")
require(drive, "google_docs_rich_rollback_not_certified", "rich Google Docs update fail-closed")
require(drive, "provider_observed_text", "provider readback canonicalization")
require(drive, "compensate_created_file_failure", "post-create compensation")
require(drive, "mad4b_google_drive_post_create_compensation_failed", "orphan-risk compensation failure")
require(drive, "mad4b_google_drive_rollback_delete_failed", "bounded internal replacement delete failure")
require(authority, "rollback_recreated_asset", "registry recreation rollback")
require(authority, "begin_recreated_asset_rollback", "persisted recreate rollback intent")
require(authority, "cancel_recreated_asset_rollback", "rollback intent cancellation")
require(drive, "mad4b_google_drive_recreate_rollback_recovery_required", "post-side-effect recovery-required state")
require(drive, "mad4b_google_drive_root_write_forbidden", "no broad My Drive root writes")
require(drive, "mad4b_google_drive_asset_outside_selected_source", "selected-source write boundary")
require(drive, "mad4b_google_drive_asset_remote_stale", "remote stale hash guard")
require(drive, "mad4b_google_drive_recreate_requires_unavailable_asset", "recreate only missing assets")
require(drive, "provider_absence_from_metadata_result", "provider absence classification")
require(drive, "last_complete_scan_generation", "recreate requires complete scan evidence")
require(drive, "absence_scan_generation", "recreate absence-generation binding")
require(drive, "mad4b_google_drive_recreate_duplicate_title_detected", "duplicate-safe recreation")
require(drive, "fetch_text_content_record", "explicit provider normalization completeness")
require(drive, "normalization_capabilities", "normalization capability manifest")
require(drive, "application/vnd.google-apps.presentation", "Google Slides plain-text normalization")
require(drive, "pdf_text_extractor_not_certified", "PDF provisional normalization evidence")
require(drive, "docx_text_extractor_not_certified", "DOCX provisional normalization evidence")
require(drive, "'limit_response_size' => self::MAX_TEXT_BYTES + 1", "truncation sentinel byte")
require(drive, "mad4b_context_asset_content_incomplete", "incomplete Context fail-closed")
require(drive, "mad4b_google_drive_recreate_original_restored", "restored-original blocker")
require(drive, "mad4b_google_drive_recreate_absence_unverified", "unverified-absence blocker")
require(authority, "'parent_folder_id'", "asset parent-folder lineage")
require(drive, "recreate_parent_candidate", "recreate parent candidate")
require(drive, "resolve_recreate_target_folder", "exact recreate parent resolver")
require(drive, "mad4b_google_drive_recreate_parent_unavailable", "missing parent fail-closed")
require(drive, "mad4b_google_drive_recreate_parent_outside_source", "parent source-boundary fail-closed")
require(drive, "create_provider_file( $target_folder_id", "recreate writes to exact parent folder")
assert "create_provider_file( (string) $source['external_root_id'], $title" not in drive, "Recreate must never silently fall back to source root"
assert drive.count("self::assert_original_file_absent(") >= 2, "Recreate capture and execution must independently prove provider absence"
require(drive, "create_asset", "Drive asset create")
require(drive, "$target_folder_id = self::bounded_drive_id", "selected-folder create binding")
require(drive, "create_provider_file( $target_folder_id, $name", "create writes only to selected source folder")
require(drive, "verify_created_file_parent", "provider-confirmed created parent")
require(drive, "mad4b_google_drive_created_parent_mismatch", "created-parent mismatch fail-closed")
require(drive, "delete_provider_file_for_rollback( $file_id, $source, false )", "exact newly-created file compensation")
assert "'target_folder_id' => $target_folder_id" in drive, "create receipt must bind the exact selected folder"
require(drive, "update_asset", "Drive asset update")
require(drive, "recreate_asset", "Drive asset recreate")
assert "delete_asset(" not in drive, "Drive delete surface must remain absent"
assert "trash_asset(" not in drive, "Drive trash surface must remain absent"

status_body = drive.split("public static function connection_status()",1)[1].split("public static function public_connection_status",1)[0]
public_status_body = drive.split("public static function public_connection_status()",1)[1].split("public static function authorization_url",1)[0]
assert "'access_token' =>" not in status_body, "connection status must not expose access token"
assert "'refresh_token' =>" not in status_body, "connection status must not expose refresh token"
for sensitive in ("'scope' =>", "'account_email' =>", "'account_name' =>", "'permission_id' =>", "'access_token' =>", "'refresh_token' =>"):
    assert sensitive not in public_status_body, f"public Google Drive status leaked identity/credential field: {sensitive}"
require(adapter, "MAD4B_SCP_Google_Drive_Context::public_connection_status()", "remote Google Drive status uses privacy-bounded projection")

# Governed adapter surfaces.
for ability in [
    "context/status",
    "context/assets",
    "context/google-drive-status",
    "context/create-drive-asset",
    "context/update-drive-asset",
    "context/recreate-drive-asset",
]:
    require(adapter, ability, f"Context adapter ability {ability}")
require(adapter, "'contract' => 'mad4b.context-asset-list.v2'", "task-isolated Context asset list contract")
require(adapter, "mad4b_context_task_scope_required", "explicit task-attachment listing requires exact task scope")
require(adapter, "hash_equals( $asset_scope, $task_scope )", "task attachment metadata exact-scope isolation")
require(adapter, "'task_scope' => array( 'type' => 'string', 'maxLength' => 160", "bounded task_scope asset-list input")
require(adapter, "'write' => array(", "dedicated write surface")
require(adapter, "mutation_ability_runtime_eligibility", "write runtime eligibility")
require(adapter, "mad4b.rollback.google-drive-context-update.v1", "Drive update reversible contract")
require(adapter, "mad4b.rollback.google-drive-context-recreate.v1", "Drive recreate reversible contract")
require(adapter, "capture_reversible_state", "Drive reversible capture")
require(adapter, "read_reversible_state", "Drive reversible readback")
require(adapter, "restore_reversible_state", "Drive reversible restore")
assert "context/create-drive-asset' => 'mad4b.rollback." not in adapter, "Drive create must not claim pre-target reversibility"
write_capability = drive.split("public static function write_capability_status()",1)[1].split("public static function asset_write_capabilities",1)[0]
require(write_capability, "'allowed_operations' => array( 'update', 'recreate' )", "only certified Drive operations are advertised")
require(write_capability, "'create' => 'mad4b_google_drive_create_rollback_not_certified'", "create capability advertises rollback blocker")
require(adapter, "mad4b_google_drive_create_rollback_not_certified", "arbitrary create denied until exact rollback certification")
require(adapter, "google_drive_write_scope_required", "write mount requires OAuth write capability")
require(adapter, "source_required_for_write", "write mount requires selected Context source")
require(adapter, "context_provider_contract_status", "first-party Context provider certification")
require(adapter, "mad4b.google-drive-context-provider.v1", "first-party provider contract version")
require(adapter, "artifact_fingerprint", "critical runtime artifact fingerprint")
require(adapter, "control_plane_build_fingerprint", "Control Plane build-bound provider identity")
require(adapter, "runtime_structural_plus_build_bound_artifact_fingerprint", "build-bound first-party provider certification mode")
require(adapter, "MAD4B_SCP_External_Handshake_Evidence", "shared exact Control Plane build fingerprint source")
require(adapter, "mad4b_context_provider_contract_not_ready", "provider contract fail-closed write mount")
require(adapter, "return false;", "generic external-plugin certification engine remains explicitly bypassed only in favor of the dedicated first-party Context provider contract")
assert "'content' => array(\n\t\t\t'context/" not in adapter, "Context Drive mutations must not mount on content surface"

# Server mounting must stay structural: reads are projected from the read
# adapter surface; mutations are projected only through the dedicated write
# surface and are never hard-coded into content/admin core maps.
require(servers, "$registry->ability_names( 'read' )", "adapter read projection")
require(servers, "foreach ( array( 'content', 'admin', 'write' ) as $surface )", "dedicated adapter write projection")
require(servers, "if ( 'mad4b-write' === $server_id )", "dedicated write authority branch")
require(servers, "self::write_tools()", "runtime-gated write mount")
for ability in [
    "context/create-drive-asset",
    "context/update-drive-asset",
    "context/recreate-drive-asset",
]:
    assert ability not in servers, f"{ability} must be adapter-projected, never hard-coded into core server maps"

# Skill Context preflight is read-only, bounded and fail-closed.
require(preflight, "This service is read-only", "read-only Context preflight")
require(preflight, "MAX_CONTEXT_BYTES", "bounded Context envelope")
require(preflight, "required_context_asset_unreadable", "provider-read fail-closed")
require(preflight, "required_unavailable_asset_count", "mandatory-only unavailable authority gate")
require(preflight, "optional_context_asset_unreadable:", "optional read warning")
require(preflight, "required_context_sets_missing", "missing required category fail-closed")
require(preflight, "review_status", "human review carried into Context receipt")
require(preflight, "'approved' !== ( isset( $asset['review_status'] )", "mandatory governed assets require human approval")
require(preflight, "effective_required_context_sets", "Site plus Skill required Context union")
require(preflight, "site_required_context_sets", "Site mandatory Context projection")
require(preflight, "registry_revision", "Context receipt registry revision binding")
require(preflight, "authority_manifest_fingerprint", "Context receipt authority fingerprint binding")
require(preflight, "context_registry_changed_during_preflight", "preflight concurrent registry drift blocker")
require(preflight, "context_authority_changed_during_preflight", "preflight authority drift blocker")
require(preflight, "MAX_RECEIPT_AGE", "bounded Context receipt freshness")
require(preflight, "context_source_registry_capacity_exceeded", "source capacity overflow preflight blocker")
require(preflight, "context_asset_registry_capacity_exceeded", "asset capacity overflow preflight blocker")
require(preflight, "mutation_context_guard", "brand-bearing content mutation Context guard")
require(preflight, "validate_receipt_binding", "live Context receipt revalidation")
require(preflight, "commit_receipt_evidence", "durable append-only Context receipt evidence")
require(preflight, "mad4b/context-receipt-bound", "Context receipt audit binding")
require(preflight, "canonical_receipt_digest", "canonical Context receipt integrity digest")
require(preflight, "content_mutation_requirement", "central content-bearing mutation classifier")
require(preflight, "mad4b/content-import-bundle", "content bundle receipt enforcement")
require(preflight, "mad4b/taxonomy-update-term", "taxonomy copy receipt enforcement")
require(preflight, "seo/update-meta", "SEO copy receipt enforcement")
require(preflight, "woocommerce/update-product", "product copy receipt enforcement")
require(preflight, "elementor/update-widget-settings", "Elementor copy receipt enforcement")
require(preflight, "jetengine/update-post-meta", "JetEngine copy receipt enforcement")
require(preflight, "mad4b/content-set-meta", "post meta copy receipt enforcement")
require(preflight, "content_paths_in_value", "nested widget content detection")
require(preflight, "editor|html|wysiwyg", "rich-text field-name detection")
assert "'context_receipt' => $receipt" not in preflight, "Full Context receipt must not be duplicated into append-only audit payload"

# Skill exposure must be Context-bound; portable export may not bypass it.
require(skill_registry, "context_policy_sha256", "Skill Context policy digest")
require(skill_registry, "normalize_context_policy", "Skill Context policy normalization")
require(skill_abilities, "MAD4B_SCP_Context_Preflight::preflight_entry", "Skill get Context Preflight")
require(skill_abilities, "mad4b_required_brand_context_unavailable", "Skill fail-closed Context blocker")
require(skill_abilities, "mad4b.skill-get.v2", "Context-bound Skill get contract")
require(skill_snapshot, "context_policy_sha256", "portable snapshot Context policy identity")
require(skill_exporter, "mad4b_context_required_skill_portable_export_unsupported", "portable Context bypass denied")

# Context receipt must remain governance evidence: included in planning/approval
# identity, revalidated before claim, persisted before side effects, then stripped
# before the provider callback.
require(write_authority, "CONTEXT_RECEIPT_INPUT_KEY", "Context receipt governance envelope key")
require(write_authority, "context_receipt_from_input", "Context receipt extraction")
require(write_authority, "provider_input", "provider-facing governance metadata stripping")
require(write_authority, "unset( $clean[ self::CONTEXT_RECEIPT_INPUT_KEY ] )", "Context receipt stripped before provider callback")
require(authorization, "mutation_context_guard", "central mutation Context guard")
require(authorization, "commit_receipt_evidence", "receipt evidence committed before execution")
require(authorization, "context_receipt_bound", "receipt execution binding state")
require(planning_guard, "mutation_context_guard", "approval planning Context guard")
require(planning_guard, "Brand-bearing content approval planning", "planning fail-closed when Context runtime is unavailable")

# Guided UX makes OAuth capability vs MAD4B authority explicit.
require(admin, "Connect Read-only", "read-only connect UX")
require(admin, "Connect Read + Write", "read-write connect UX")
require(admin, "Upgrade to Read + Write", "explicit scope upgrade UX")
require(admin, "Disconnect & Revoke Google Access", "least-privilege disconnect UX")
require(admin, "Google revocation is pending.", "pending revoke warning UX")
require(admin, "Retry revoke", "revocation retry UX")
require(admin, "one-time approval", "governed write UX")
require(admin, "Folder Picker", "folder picker")
require(admin, "My Drive is available for navigation only", "root folder browse-only UX")
require(admin, "Governed Library", "governed library UX")
require(admin, "Task-only Source", "task-only source UX")
require(admin, "Quality and authority are separate", "quality/authority UX guidance")
require(admin, "Normalization support", "normalization support matrix UX")
require(admin, "Use automatic score", "automatic quality score review UX")
require(admin, "Manual override", "manual quality override UX")
require(admin, "Actionability", "per-asset actionability UX")
require(admin, "Reversible text update", "reversible update UX")
require(admin, "Reversible missing-asset recreation", "reversible recreate UX")
require(admin, "Write Governance Readiness", "write governance readiness UX")
require(admin, "MAD4B_SCP_Live_Truth::current_authority_status()", "live authority truth in UX")
require(admin, "Context Authority never reconciles grants automatically", "no automatic grant reconciliation UX")
require(admin, "runtime_authority_not_reconciled", "runtime reconciliation blocker UX")

require(workflow, "context-oauth-lifecycle-runtime.php", "OAuth lifecycle runtime CI")
require(workflow, "context-human-review-runtime.php", "human review persistence runtime CI")

print("mad4b.site-control-plane.context-authority-contract.v32: PASS")
