<?php
/** Production forms/drafts/templates with explicit deterministic WP/service doubles; no live acceptance. */
define( 'ABSPATH',__DIR__.'/' );
error_reporting( E_ALL );
set_error_handler( static function( $severity,$message,$file,$line ) { if ( error_reporting() & $severity ) throw new ErrorException( $message,0,$severity,$file,$line ); return false; } );
class WP_Error { private $code; private $data; public function __construct( $code,$message='',$data=array() ) { $this->code=$code; $this->data=$data; } public function get_error_code() { return $this->code; } public function get_error_data() { return $this->data; } }
function is_wp_error( $v ) { return $v instanceof WP_Error; }
function sanitize_key( $v ) { return preg_replace( '/[^a-z0-9_-]/','',strtolower( $v ) ); }
$GLOBALS['scope']=array( 'binding_sha256'=>str_repeat( '1',64 ),'site_uuid'=>'site-one-uuid','origin'=>'https://one.example','environment'=>'staging','source_sha'=>str_repeat( 'a',40 ),'package_sha256'=>str_repeat( 'b',64 ),'runtime_generation'=>str_repeat( 'c',64 ),'restore_epoch'=>1,'profile_sha256'=>str_repeat( 'd',64 ),'actor_sha256'=>str_repeat( 'e',64 ),'blog_id'=>1,'locale'=>'ar' );
$GLOBALS['enabled']=false; $GLOBALS['options']=array(); $GLOBALS['scheduled']=array(); $GLOBALS['schedule_ok']=true; $GLOBALS['read_calls']=0; $GLOBALS['object_reads']=array(); $GLOBALS['collision']=false;
class MAD4B_SCP_CSO_Scope {
	public static function enabled( $flag ) { return $GLOBALS['enabled']; }
	public static function current() { return $GLOBALS['scope']; }
	public static function assert_current( $scope ) { return self::digest( $scope )===self::digest( self::current() ) ? true : self::error( 'stale' ); }
	public static function digest( $v ) { return hash( 'sha256',serialize( $v ) ); }
	public static function error( $r ) { return new WP_Error( 'cso_'.$r,'Scoped request denied.' ); }
	public static function seal( array $m,$p ) { return array( 'material'=>$m,'purpose'=>$p,'mac'=>hash_hmac( 'sha256',serialize( $m ).$p,'fixture-only-key' ) ); }
	public static function unseal( array $s,$p ) { return isset( $s['material'],$s['purpose'],$s['mac'] ) && $s['purpose']===$p && hash_equals( $s['mac'],hash_hmac( 'sha256',serialize( $s['material'] ).$p,'fixture-only-key' ) ) ? $s['material'] : self::error( 'seal' ); }
	public static function safe_data( $v,$ordinary=true ) { if ( is_array( $v ) ) { foreach ( $v as $key=>$child ) { if ( is_string( $key ) && preg_match( '/api_key|password|secret|credential/i',$key ) ) return false; if ( ! self::safe_data( $child ) ) return false; } } elseif ( is_string( $v ) && false!==strpos( $v,'sk_test_plaintext' ) ) return false; return true; }
}
class MAD4B_SCP_CSO_Registry {
	public static $definitions=array(); public static $allowed=true; public static $rows=array(); public static $drift=false;
	public static function describe( $name,$target=array() ) { if ( ! self::$allowed || ! isset( self::$definitions[ $name ] ) ) return new WP_Error( 'unavailable' ); $r=self::$definitions[ $name ]; $r['ability_name']=$name; $r['scope']=MAD4B_SCP_CSO_Scope::current(); $r['schema_sha256']=MAD4B_SCP_CSO_Scope::digest( array( 'input_schema'=>$r['input_schema'],'output_schema'=>$r['output_schema'] ) ); return $r; }
	public static function read( $name,$args,$prepared ) { $GLOBALS['read_calls']++; if ( 'test/relations'!==$name || 20!==( $args['limit']??null ) || 'ar'!==( $args['locale']??null ) || ! $prepared ) return new WP_Error( 'read_denied' ); if ( self::$drift ) $GLOBALS['scope']['restore_epoch']++; return array( 'contract'=>'mad4b.cso01.native-read.v1','read_only'=>true,'mutation_performed'=>false,'result'=>array( 'items'=>self::$rows ) ); }
}
function add_action( $hook,$callback,$priority=10,$args=1 ) { $GLOBALS['hooks'][ $hook ]=$callback; }
function get_option( $key,$default=false ) { return array_key_exists( $key,$GLOBALS['options'] ) ? $GLOBALS['options'][ $key ] : $default; }
function add_option( $key,$v,$deprecated='',$autoload=true ) { if ( $GLOBALS['collision'] && '_2'===substr( $key,-2 ) ) { $GLOBALS['collision']=false; $v['material']['values']=array( 'title'=>'Concurrent winner' ); $GLOBALS['options'][ $key ]=MAD4B_SCP_CSO_Scope::seal( $v['material'],MAD4B_SCP_CSO_Drafts::PURPOSE ); } if ( array_key_exists( $key,$GLOBALS['options'] ) ) return false; $GLOBALS['options'][ $key ]=$v; return true; }
function delete_option( $key ) { unset( $GLOBALS['options'][ $key ] ); return true; }
function wp_schedule_single_event( $at,$hook,$args,$wp_error=false ) { if ( ! $GLOBALS['schedule_ok'] ) return false; $GLOBALS['scheduled'][]=array( $at,$hook,$args ); return true; }
function current_user_can( $cap,$id=null ) { if ( 'read_post'===$cap ) return in_array( $id,array( 9,13,14,20 ),true ); if ( 'edit_user'===$cap ) return 7===$id; return in_array( $cap,array( 'list_users','assign_terms' ),true ); }
function get_post( $id ) { $GLOBALS['object_reads'][]=$id; return in_array( $id,array( 9,14 ),true ) ? (object)array( 'post_type'=>'tour' ) : ( 20===$id ? (object)array( 'post_type'=>'attachment' ) : ( 13===$id ? (object)array( 'post_type'=>'page' ) : null ) ); }
function get_taxonomy( $name ) { return 'category'===$name ? (object)array( 'cap'=>(object)array( 'assign_terms'=>'assign_terms' ) ) : null; }
function get_term( $id,$tax ) { return 5===$id ? (object)array( 'taxonomy'=>'category' ) : new WP_Error( 'not_found' ); }
function get_userdata( $id ) { return 7===$id ? (object)array( 'ID'=>7 ) : null; }
function has_filter( $key ) { return 'wpml_element_language_code'===$key; }
function apply_filters( $key,$value,$args ) { return 14===$args['element_id'] ? 'en' : 'ar'; }
function wp_kses_post( $html ) { return strip_tags( $html,'<p><strong><em>' ); }
require_once __DIR__.'/../includes/class-mad4b-scp-canonicalization.php';
require_once __DIR__.'/../includes/class-mad4b-scp-cso-forms.php';
require_once __DIR__.'/../includes/class-mad4b-scp-cso-drafts.php';
require_once __DIR__.'/../includes/class-mad4b-scp-cso-templates.php';
$checks=0;
function check( $ok,$label ) { global $checks; $checks++; if ( ! $ok ) { fwrite( STDERR,"FAIL: $label\n" ); exit( 1 ); } }
function denied( $v,$label ) { check( is_wp_error( $v ),$label ); }
$schema=array( 'type'=>'object','additionalProperties'=>false,'required'=>array( 'title','mode' ),'properties'=>array(
	'title'=>array( 'type'=>'string','title'=>'عنوان الرحلة','minLength'=>1,'maxLength'=>128 ),'mode'=>array( 'type'=>'string','enum'=>array( 'plain','map' ) ),'map_url'=>array( 'type'=>'string','format'=>'uri' ),
	'enabled'=>array( 'type'=>'boolean' ),'quantity'=>array( 'type'=>'integer','minimum'=>0,'maximum'=>10 ),'price'=>array( 'type'=>'number','minimum'=>0,'maximum'=>100,'multipleOf'=>0.25 ),'date'=>array( 'type'=>'string','format'=>'date' ),'time'=>array( 'type'=>'string','format'=>'date-time' ),
	'tags'=>array( 'type'=>'array','maxItems'=>2,'uniqueItems'=>true,'items'=>array( 'type'=>'string','enum'=>array( 'a','b' ) ) ),'relation'=>array( 'type'=>'integer' ),'related'=>array( 'type'=>'array','maxItems'=>2,'items'=>array( 'type'=>'integer' ) ),'term'=>array( 'type'=>'integer' ),'user'=>array( 'type'=>'integer' ),'media'=>array( 'type'=>'integer' ),
	'group'=>array( 'type'=>'object','required'=>array( 'label' ),'properties'=>array( 'label'=>array( 'type'=>'string','maxLength'=>10 ),'contact'=>array( 'type'=>'string','format'=>'email' ) ) ),'rows'=>array( 'type'=>'array','maxItems'=>2,'items'=>array( 'type'=>'object','properties'=>array( 'label'=>array( 'type'=>'string','maxLength'=>5 ) ) ) ),
	'body'=>array( 'type'=>'string' ),'contact'=>array( 'type'=>'string','format'=>'email' ),'api_key'=>array( 'type'=>'string','writeOnly'=>true ),'locked'=>array( 'type'=>'string','readOnly'=>true ),'private_field'=>array( 'type'=>'string' ),'unknown'=>array( 'type'=>'alien' ),'one'=>array( 'type'=>'integer' ),'two'=>array( 'type'=>'integer' ),
) );
$condition=array( 'field'=>'mode','operator'=>'equals','value'=>'map' );
$meta=array( 'map_url'=>array( 'visible_when'=>$condition,'required_when'=>$condition,'allowed_hosts'=>array( 'safe.example' ),'storage_kind'=>'native_ability' ),'relation'=>array( 'resource_type'=>'post','post_type'=>'tour','suggestion'=>array( 'ability_name'=>'test/relations','resource_type'=>'post','post_type'=>'tour','items_path'=>'items','value_key'=>'id','label_key'=>'label' ) ),'related'=>array( 'resource_type'=>'post','post_type'=>'tour' ),'term'=>array( 'resource_type'=>'term','taxonomy'=>'category' ),'user'=>array( 'resource_type'=>'user' ),'media'=>array( 'resource_type'=>'media' ),'body'=>array( 'field_type'=>'rich_text' ),'contact'=>array( 'sensitivity'=>'PERSONAL' ),'group.contact'=>array( 'sensitivity'=>'PERSONAL' ),'private_field'=>array( 'visibility'=>'hidden' ),'one'=>array( 'exclusive_with'=>array( 'two' ) ) );
$native=array( 'input_schema'=>$schema,'output_schema'=>array( 'type'=>'object' ),'field_metadata'=>$meta,'metadata_trusted'=>true,'adapter_sha256'=>str_repeat( 'f',64 ),'capability_binding'=>array( 'binding'=>'current' ),'lane'=>'write','writable_by_adapter'=>true,'provider'=>array( 'id'=>'native-test' ),'storage_status'=>'WRITE_CANDIDATE','preparation'=>array( 'bound'=>true ) );
MAD4B_SCP_CSO_Registry::$definitions['test/save']=$native; MAD4B_SCP_CSO_Registry::$definitions['test/relations']=array_replace( $native,array( 'lane'=>'read' ) );
denied( MAD4B_SCP_CSO_Forms::schema( 'test/save' ),'default off' ); $GLOBALS['enabled']=true;
$long=str_repeat( 'a',96 ).'/'.str_repeat( 'b',96 ); MAD4B_SCP_CSO_Registry::$definitions[ $long ]=$native; check( strlen( $long )===193 && ! is_wp_error( MAD4B_SCP_CSO_Forms::schema( $long ) ),'canonical longest 193-byte Ability accepted' );
foreach ( array( $long.'b',' test/save','test/save ','Test/save','test/savе','test//save','test/save/child' ) as $name ) denied( MAD4B_SCP_CSO_Forms::schema( $name ),'Ability aliases/overlong names denied' );
$prepared=MAD4B_SCP_CSO_Forms::schema( 'test/save' ); check( ! is_wp_error( $prepared ),'current schema compiled' ); $sealed=$prepared['sealed_form']; $fields=array_column( $prepared['fields'],null,'field_id' );
check( false===$prepared['execution_allowed'] && true===$prepared['non_authorizing'],'schema inert' ); check( ! isset( $fields['private_field'] ),'hidden field label absent' );
check( 'secret_handoff'===$fields['api_key']['type'] && true===$fields['api_key']['readonly'] && 'external_handoff'===$fields['api_key']['control'],'secret handoff never ordinary control' ); check( true===$fields['unknown']['readonly'],'unknown typed field read-only' );
check( array( 'value'=>'plain','label'=>'plain' )===$fields['mode']['options'][0],'typed option presentation' ); check( 'عنوان الرحلة'===$fields['title']['label'],'RTL Unicode retained' ); check( true===$fields['relation']['autocomplete'] && false===$fields['title']['autocomplete'],'native autocomplete marker only' ); check( array( 'field_id'=>'mode','equals'=>'map' )===$fields['map_url']['visibility'],'conditional client alias' );
foreach ( array( null,'forged',true,(object)array() ) as $v ) denied( MAD4B_SCP_CSO_Forms::inspect( $v ),'malformed seal denied before typed helper' );
$good=array( 'title'=>str_repeat( '😀',128 ),'mode'=>'plain','enabled'=>true,'quantity'=>10,'price'=>1.25,'date'=>'2026-02-28','time'=>'2026-10-10T12:30:00Z','tags'=>array( 'a','b' ),'relation'=>9,'related'=>array( 9 ),'term'=>5,'user'=>7,'media'=>20,'group'=>array( 'label'=>'ok' ),'rows'=>array( array( 'label'=>'ok' ) ),'body'=>'<p>safe</p>' );
$valid=MAD4B_SCP_CSO_Forms::validate( $sealed,$good ); check( ! is_wp_error( $valid ) && $valid['input']===$good,'all supported typed values accepted' ); check( false===$valid['execution_allowed'],'validation remains non-authorizing' );
foreach ( array( null,true,'object',(object)array(),array( 'title' ) ) as $v ) denied( MAD4B_SCP_CSO_Forms::validate( $sealed,$v ),'strict root input type' );
$bad=array( array( 'title'=>str_repeat( '😀',129 ) ),array( 'title'=>"bad\xff" ),array( 'title'=>'' ),array( 'title'=>"bad\0" ),array( 'title'=>12 ),array( 'enabled'=>'true' ),array( 'enabled'=>1 ),array( 'quantity'=>1.0 ),array( 'quantity'=>'2' ),array( 'quantity'=>-1 ),array( 'quantity'=>11 ),array( 'price'=>INF ),array( 'price'=>NAN ),array( 'price'=>0.1 ),array( 'price'=>'1.25' ),array( 'price'=>-1 ),array( 'date'=>'2026-02-30' ),array( 'date'=>'28/02/2026' ),array( 'time'=>'2026-02-30T12:00:00Z' ),array( 'tags'=>array( 'a','a' ) ),array( 'tags'=>array( 'c' ) ),array( 'tags'=>array( 'a','b','a' ) ),array( 'tags'=>array( 'key'=>'a' ) ),array( 'relation'=>12 ),array( 'relation'=>13 ),array( 'relation'=>14 ),array( 'relation'=>'9' ),array( 'related'=>array( 9,12 ) ),array( 'term'=>6 ),array( 'user'=>8 ),array( 'media'=>9 ),array( 'group'=>array( 'label'=>str_repeat( 'x',11 ) ) ),array( 'group'=>array( 'extra'=>1 ) ),array( 'rows'=>array( array( 'label'=>'123456' ) ) ),array( 'body'=>'<script>alert(1)</script>' ),array( 'api_key'=>'sentinel-secret-value' ),array( 'locked'=>'override' ),array( 'private_field'=>'guess' ),array( 'unknown'=>'x' ),array( 'not_registered'=>'x' ),array( 'one'=>1,'two'=>2 ),array( 'map_url'=>'https://safe.example' ),array( 'title'=>'sk_test_plaintext_value' ) );
foreach ( $bad as $change ) denied( MAD4B_SCP_CSO_Forms::validate( $sealed,array_replace( $good,$change ) ),'adversarial type/bounds/visibility rejection '.$checks );
check( ! in_array( 12,$GLOBALS['object_reads'],true ),'private object not fetched for existence' ); denied( MAD4B_SCP_CSO_Forms::validate( $sealed,array( 'title'=>'x','mode'=>'map' ) ),'required-if server enforced' ); check( ! is_wp_error( MAD4B_SCP_CSO_Forms::validate( $sealed,array( 'title'=>'x','mode'=>'map','map_url'=>'https://safe.example/tour' ) ) ),'active conditional URL accepted' );
foreach ( array( 'http://safe.example','https://evil.example','https://user@safe.example','https://user:pass@safe.example','https://safe.example:444',"https://safe.example/\n" ) as $url ) denied( MAD4B_SCP_CSO_Forms::validate( $sealed,array( 'title'=>'x','mode'=>'map','map_url'=>$url ) ),'URL allowlist/credentials/transport guard' );
$fixed=MAD4B_SCP_CSO_Forms::schema( 'test/save',array( 'relation'=>9 ) ); check( ! is_wp_error( $fixed ),'scoped target accepted' ); denied( MAD4B_SCP_CSO_Forms::validate( $fixed['sealed_form'],array( 'title'=>'x','mode'=>'plain','relation'=>9 ) ),'locked target cannot be replaced' ); check( ! is_wp_error( MAD4B_SCP_CSO_Forms::validate( $fixed['sealed_form'],array( 'title'=>'x','mode'=>'plain' ) ) ),'locked selector merged on server' ); denied( MAD4B_SCP_CSO_Forms::schema( 'test/save',array( 'contact'=>'person@example.com' ) ),'personal selector never sealed' );
$scope_snapshot=$GLOBALS['scope']; foreach ( array_keys( $scope_snapshot ) as $key ) { $GLOBALS['scope'][ $key ]=is_int( $scope_snapshot[ $key ] ) ? $scope_snapshot[ $key ]+1 : $scope_snapshot[ $key ].'changed'; denied( MAD4B_SCP_CSO_Forms::validate( $sealed,$good ),'scope replay denied '.$key ); $GLOBALS['scope']=$scope_snapshot; }
$tampered=$sealed; $tampered['material']['target']=array( 'relation'=>9 ); denied( MAD4B_SCP_CSO_Forms::inspect( $tampered ),'target MAC tamper denied' ); $expired=$sealed['material']; $expired['expires_at']=time()-1; denied( MAD4B_SCP_CSO_Forms::inspect( MAD4B_SCP_CSO_Scope::seal( $expired,MAD4B_SCP_CSO_Forms::PURPOSE ) ),'expired form denied' );
MAD4B_SCP_CSO_Registry::$allowed=false; denied( MAD4B_SCP_CSO_Forms::inspect( $sealed ),'native permission revoked' ); MAD4B_SCP_CSO_Registry::$allowed=true;
MAD4B_SCP_CSO_Registry::$definitions['test/save']['input_schema']['properties']['title']['maxLength']=127; denied( MAD4B_SCP_CSO_Forms::validate( $sealed,$good ),'schema drift denied' ); MAD4B_SCP_CSO_Registry::$definitions['test/save']=$native;
MAD4B_SCP_CSO_Registry::$definitions['test/save']['field_metadata']['one']['visible_when']=array( 'field'=>'two','operator'=>'is_set' ); MAD4B_SCP_CSO_Registry::$definitions['test/save']['field_metadata']['two']['visible_when']=array( 'field'=>'one','operator'=>'is_set' ); denied( MAD4B_SCP_CSO_Forms::schema( 'test/save' ),'cycle denied' ); MAD4B_SCP_CSO_Registry::$definitions['test/save']=$native;
MAD4B_SCP_CSO_Registry::$definitions['test/save']['field_metadata']['map_url']['visible_when']='eval PHP'; denied( MAD4B_SCP_CSO_Forms::schema( 'test/save' ),'executable expressions denied' ); MAD4B_SCP_CSO_Registry::$definitions['test/save']=$native;
MAD4B_SCP_CSO_Registry::$definitions['test/save']['input_schema']['properties']['api_key']['default']='sentinel-secret-value'; denied( MAD4B_SCP_CSO_Forms::schema( 'test/save' ),'secret schema default rejected before digest' ); MAD4B_SCP_CSO_Registry::$definitions['test/save']=$native;
MAD4B_SCP_CSO_Registry::$definitions['test/save']['input_schema']['writeOnly']=true; denied( MAD4B_SCP_CSO_Forms::schema( 'test/save' ),'secret entire object denied' ); MAD4B_SCP_CSO_Registry::$definitions['test/save']=$native;
MAD4B_SCP_CSO_Registry::$definitions['test/save']['input_schema']['properties']['group']['properties']['key']=array( 'type'=>'string','x-cso'=>array( 'sensitivity'=>'SECRET' ) ); $secret_group=MAD4B_SCP_CSO_Forms::schema( 'test/save' ); check( 'secret_handoff'===array_column( $secret_group['fields'],null,'field_id' )['group']['type'],'nested secret group never editable JSON' ); denied( MAD4B_SCP_CSO_Forms::validate_draft( $secret_group['sealed_form'],array( 'group'=>array( 'key'=>'sentinel' ) ) ),'native schema nested secret denied' ); MAD4B_SCP_CSO_Registry::$definitions['test/save']=$native;
$suggest=MAD4B_SCP_CSO_Forms::suggest( $sealed,'mode','pl',0 ); check( ! is_wp_error( $suggest ),'enum suggestion admitted '.( is_wp_error( $suggest ) ? $suggest->get_error_code() : '' ) ); check( 1===count( $suggest['items'] ) && 'plain'===$suggest['items'][0]['value'],'safe enum autocomplete' );
MAD4B_SCP_CSO_Registry::$rows=array( array( 'id'=>9,'label'=>'<strong>رحلة</strong>' ),array( 'id'=>12,'label'=>'PRIVATE SENTINEL' ),array( 'id'=>13,'label'=>'WRONG TYPE' ),array( 'id'=>14,'label'=>'WRONG LOCALE' ),array( 'id'=>'9','label'=>'WRONG ID TYPE' ) ); $suggest=MAD4B_SCP_CSO_Forms::suggest( $sealed,'relation' ); check( ! is_wp_error( $suggest ) && array( array( 'value'=>9,'label'=>'رحلة' ) )===$suggest['items'],'native per-object permission/type/locale autocomplete' ); check( ! isset( $suggest['total'] ) && null===$suggest['next_offset'],'no private existence or totals' );
denied( MAD4B_SCP_CSO_Forms::suggest( $sealed,'api_key' ),'secret has no autocomplete' ); denied( MAD4B_SCP_CSO_Forms::suggest( $sealed,'relation','','0' ),'strict pagination type' ); denied( MAD4B_SCP_CSO_Forms::suggest( $sealed,'relation',str_repeat( '😀',129 ) ),'query bound' ); MAD4B_SCP_CSO_Registry::$drift=true; denied( MAD4B_SCP_CSO_Forms::suggest( $sealed,'relation' ),'read-time scope drift prevents disclosure' ); MAD4B_SCP_CSO_Registry::$drift=false; $GLOBALS['scope']=$scope_snapshot;
$help=MAD4B_SCP_CSO_Forms::explain( $sealed,'title' ); check( 'UNKNOWN'===$help['storage_kind'] && array( 'UNKNOWN' )===$help['side_effects'] && 'native-test'===$help['owner'],'unknown behavior honestly labeled' ); denied( MAD4B_SCP_CSO_Forms::explain( $sealed,'private_field' ),'hidden field help denied' );
$before=$GLOBALS['options']; denied( MAD4B_SCP_CSO_Drafts::create( $sealed,array( 'api_key'=>'sentinel' ) ),'draft secret denied before storage' ); check( $before===$GLOBALS['options'],'secret refusal performs no option write' );
$draft=MAD4B_SCP_CSO_Drafts::create( $sealed,array( 'title'=>'Draft','contact'=>'person@example.com','group'=>array( 'label'=>'ok','contact'=>'second@example.com' ) ) ); check( ! is_wp_error( $draft ) && 1===$draft['revision'],'unfinished native draft created' ); check( ! isset( $draft['values']['contact'],$draft['values']['group']['contact'] ) && in_array( 'contact',$draft['redacted_fields'],true ),'personal draft fields redacted' ); check( false===strpos( serialize( $GLOBALS['options'] ),'person@example.com' ) && false===strpos( serialize( $GLOBALS['options'] ),'second@example.com' ),'no personal values persisted or hashed into records' ); check( ! is_wp_error( MAD4B_SCP_CSO_Drafts::load( $draft['draft_id'] ) ),'draft resumes current scope' );
$updated=MAD4B_SCP_CSO_Drafts::save( $draft['draft_id'],1,$sealed,array( 'title'=>'Updated' ) ); check( ! is_wp_error( $updated ) && 2===$updated['revision'],'native immutable CAS append' ); denied( MAD4B_SCP_CSO_Drafts::save( $draft['draft_id'],1,$sealed,array( 'title'=>'Lost' ) ),'stale CAS refused' ); denied( MAD4B_SCP_CSO_Drafts::save( $draft['draft_id'],'2',$sealed,array() ),'no revision coercion' );
$GLOBALS['scope']['actor_sha256']=str_repeat( '7',64 ); denied( MAD4B_SCP_CSO_Drafts::load( $draft['draft_id'] ),'other actor cannot locate draft' ); $GLOBALS['scope']=$scope_snapshot; $GLOBALS['scope']['source_sha']=str_repeat( '8',40 ); denied( MAD4B_SCP_CSO_Drafts::load( $draft['draft_id'] ),'new source cannot replay old draft' ); $GLOBALS['scope']=$scope_snapshot;
$race=MAD4B_SCP_CSO_Drafts::create( $sealed,array( 'title'=>'Original' ) ); $GLOBALS['collision']=true; denied( MAD4B_SCP_CSO_Drafts::save( $race['draft_id'],1,$sealed,array( 'title'=>'Loser' ) ),'atomic insert collision refuses race' ); $winner=MAD4B_SCP_CSO_Drafts::load( $race['draft_id'] ); check( 'Concurrent winner'===$winner['values']['title'],'concurrent winner preserved' );
$deleted=MAD4B_SCP_CSO_Drafts::delete( $draft['draft_id'],2 ); check( ! is_wp_error( $deleted ) && 'DELETED'===$deleted['status'],'delete tombstone created' ); denied( MAD4B_SCP_CSO_Drafts::load( $draft['draft_id'] ),'tombstone blocks resume' ); denied( MAD4B_SCP_CSO_Drafts::save( $draft['draft_id'],2,$sealed,array() ),'deleted draft cannot resurrect' );
$GLOBALS['schedule_ok']=false; $before=$GLOBALS['options']; denied( MAD4B_SCP_CSO_Drafts::create( $sealed,array() ),'cleanup scheduling failure refuses storage' ); check( $before===$GLOBALS['options'],'failed schedule rolls back owned options' ); $GLOBALS['schedule_ok']=true;
$owner=MAD4B_SCP_CSO_Scope::digest( $scope_snapshot ); $first_key='_mad4b_cso_d_'.$owner.'_'.$race['draft_id'].'_1'; $first=$GLOBALS['options'][ $first_key ]['material']; $first['expires_at']=time()-1; $GLOBALS['options'][ $first_key ]=MAD4B_SCP_CSO_Scope::seal( $first,MAD4B_SCP_CSO_Drafts::PURPOSE ); $GLOBALS['options']['foreign_option']='retain'; MAD4B_SCP_CSO_Drafts::expire( $owner,$race['draft_id'],time()+100 ); check( isset( $GLOBALS['options'][ $first_key ] ),'future purge cannot erase draft' ); $GLOBALS['scope']['actor_sha256']=str_repeat( '9',64 ); MAD4B_SCP_CSO_Drafts::expire( $owner,$race['draft_id'],$first['expires_at'] ); $GLOBALS['scope']=$scope_snapshot; check( ! isset( $GLOBALS['options'][ $first_key ] ) && 'retain'===$GLOBALS['options']['foreign_option'],'detached expired purge affects only owned draft' );
$exp=MAD4B_SCP_CSO_Drafts::create( $sealed,array( 'title'=>'expires' ) ); $ek='_mad4b_cso_d_'.$owner.'_'.$exp['draft_id'].'_1'; $record=$GLOBALS['options'][ $ek ]['material']; $record['expires_at']=time()-1; $GLOBALS['options'][ $ek ]=MAD4B_SCP_CSO_Scope::seal( $record,MAD4B_SCP_CSO_Drafts::PURPOSE ); denied( MAD4B_SCP_CSO_Drafts::load( $exp['draft_id'] ),'expired draft denied' ); $GLOBALS['options'][ $ek ]['material']['values']['title']='tamper'; denied( MAD4B_SCP_CSO_Drafts::load( $exp['draft_id'] ),'record MAC tamper denied' );
$active=MAD4B_SCP_CSO_Drafts::create( $sealed,array( 'title'=>'Active' ) ); $new=MAD4B_SCP_CSO_Forms::schema( 'test/save' ); denied( MAD4B_SCP_CSO_Drafts::save( $active['draft_id'],1,$new['sealed_form'],array() ),'new form cannot refresh old draft TTL' ); for ( $attempt=0;$attempt<11;$attempt++ ) { $q=MAD4B_SCP_CSO_Drafts::create( $sealed,array() ); if ( is_wp_error( $q ) ) break; } check( is_wp_error( $q ) && 'cso_draft_quota'===$q->get_error_code(),'bounded per-scope quota' );
$template=MAD4B_SCP_CSO_Templates::create( $sealed,array( 'version'=>2,'fields'=>array( array( 'field_id'=>'title' ),array( 'field_id'=>'mode' ) ) ) ); check( ! is_wp_error( $template ) && false===$template['execution_allowed'],'signed inert template created' ); $apply=MAD4B_SCP_CSO_Templates::apply( $template['sealed_template'],$sealed ); check( ! is_wp_error( $apply ) && array()===$apply['values'] && 2===count( $apply['fields'] ),'compatible template carries no values' ); denied( MAD4B_SCP_CSO_Templates::apply( 'forged',$sealed ),'malformed template denied before typed helper' );
foreach ( array( array( 'grants'=>array( 'admin' ) ),array( 'defaults'=>array( 'title'=>'x' ) ),array( 'values'=>array( 'title'=>'x' ) ),array( 'fields'=>array( array( 'field_id'=>'api_key' ) ) ),array( 'fields'=>array( array( 'field_id'=>'contact' ) ) ),array( 'fields'=>array( array( 'field_id'=>'title','value'=>'hidden' ) ) ),array( 'fields'=>array( array( 'field_id'=>'title' ),array( 'field_id'=>'title' ) ) ) ) as $r ) denied( MAD4B_SCP_CSO_Templates::create( $sealed,$r ),'unsafe recipe rejected' );
MAD4B_SCP_CSO_Registry::$definitions['test/save']['input_schema']['properties']['title']['maxLength']=100; $new=MAD4B_SCP_CSO_Forms::schema( 'test/save' ); denied( MAD4B_SCP_CSO_Templates::apply( $template['sealed_template'],$new['sealed_form'] ),'template schema drift requires explicit rebuild' ); MAD4B_SCP_CSO_Registry::$definitions['test/save']=$native;
$GLOBALS['enabled']=false; denied( MAD4B_SCP_CSO_Forms::inspect( $sealed ),'flag revokes prepared form' ); denied( MAD4B_SCP_CSO_Drafts::load( $active['draft_id'] ),'flag revokes draft' ); check( 2===$GLOBALS['read_calls'],'only explicit suggestions invoke governed read boundary' );
echo json_encode( array( 'status'=>'PASS','checks'=>$checks,'live_wordpress_acceptance'=>false,'production_classes'=>array( 'Canonicalization','Forms','Drafts','Templates' ) ),JSON_UNESCAPED_SLASHES )."\n";
