<?php
/** Explicit fake WordPress, certificate, native executor, provider and DB. No live acceptance. */
define('ABSPATH',__DIR__.'/');
class WP_Error {private $code;public function __construct($code,$message='',$data=array()){$this->code=$code;}public function get_error_code(){return $this->code;}}
function is_wp_error($v){return $v instanceof WP_Error;}
$GLOBALS['enabled']=true;$GLOBALS['user']=7;$GLOBALS['cookie']=str_repeat('browser-fixture-',4);$GLOBALS['issuer']=str_repeat('1',64);$GLOBALS['auth_session']=str_repeat('2',64);
$GLOBALS['authority']=true;$GLOBALS['permission']=true;$GLOBALS['certified']=true;$GLOBALS['wrapper']=true;$GLOBALS['registered']=true;$GLOBALS['storage']='managed_encrypted';$GLOBALS['plaintext_options']=false;$GLOBALS['permission_probe']=false;$GLOBALS['permission_probe_denied']=false;
$GLOBALS['endpoint']='https://example.test/wp-admin/admin-post.php';$GLOBALS['https']=true;$GLOBALS['calls']=array();$GLOBALS['envelopes']=array();$GLOBALS['hooks']=array();
$GLOBALS['scope']=array('site_uuid'=>'fixture-site-uuid','origin'=>'https://example.test','environment'=>'staging','source_sha'=>str_repeat('a',40),'package_sha256'=>str_repeat('b',64),'runtime_generation'=>str_repeat('c',64),'restore_epoch'=>1,'profile_sha256'=>str_repeat('d',64),'actor_sha256'=>str_repeat('e',64),'blog_id'=>1,'locale'=>'en_US');
$GLOBALS['wp_environment']='staging';
function wp_get_environment_type(){return $GLOBALS['wp_environment'];}
function get_current_user_id(){return $GLOBALS['user'];}function current_user_can($cap){return $GLOBALS['authority'];}function is_user_logged_in(){return $GLOBALS['user']>0&&''!==$GLOBALS['cookie'];}function wp_get_session_token(){return $GLOBALS['cookie'];}
function wp_create_nonce($action){return hash_hmac('sha256',$action.'|'.$GLOBALS['cookie'],'nonce-fixture');}function wp_verify_nonce($v,$action){return is_string($v)&&hash_equals(wp_create_nonce($action),$v);}
function add_query_arg(array $args,$url){return $url.'?'.http_build_query($args);}function admin_url($path,$scheme=''){return $GLOBALS['endpoint'];}function wp_parse_url($url,$component=-1){return -1===$component?parse_url($url):parse_url($url,$component);}function is_ssl(){return $GLOBALS['https'];}function wp_unslash($v){return $v;}
function maybe_serialize($v){return serialize($v);}function maybe_unserialize($v){return unserialize($v);}function wp_cache_delete($key,$group){}function add_action($hook,$callback){$GLOBALS['hooks'][$hook]=$callback;}
function add_option($key,$value,$legacy='',$autoload=false){if(isset($GLOBALS['wpdb']->rows[$key]))return false;$GLOBALS['wpdb']->rows[$key]=serialize($value);return true;}
class FakeDB {
	public $options='fixture_options';public $rows=array();public $last_error='';public $fail_cas=false;
	public function prepare($sql,...$args){return array('sql'=>$sql,'args'=>$args);}public function get_var(array $q){return $this->rows[$q['args'][0]]??null;}
	public function query(array $q){if($this->fail_cas){$this->fail_cas=false;return 0;}list($new,$key,$old)=$q['args'];if(($this->rows[$key]??null)!==$old)return 0;$this->rows[$key]=$new;return 1;}
}
$GLOBALS['wpdb']=new FakeDB();
class MAD4B_SCP_CSO_Scope {
	public static function enabled($component=''){return $GLOBALS['enabled'];}public static function current(){$s=$GLOBALS['scope'];$s['binding_sha256']=hash('sha256',serialize($s));return $s;}
	public static function assert_current(array $s){return self::current()===$s?true:new WP_Error('scope_changed');}
	public static function digest($material){return hash('sha256',serialize($material));}
	public static function seal(array $material,$purpose){return array('material'=>$material,'proof'=>hash_hmac('sha256',$purpose.serialize($material),'deployment-fixture'));}
	public static function unseal(array $sealed,$purpose){return isset($sealed['material'],$sealed['proof'])&&hash_equals(self::seal($sealed['material'],$purpose)['proof'],$sealed['proof'])?$sealed['material']:new WP_Error('tampered');}
}
class MAD4B_SCP_Identity_Context {public static function current(){return array('issuer_fingerprint'=>$GLOBALS['issuer'],'session_fingerprint'=>$GLOBALS['auth_session'],'subject_fingerprint'=>str_repeat('3',64));}}
class MAD4B_SCP_Policy {public static function can_read(){return $GLOBALS['authority'];}public static function can_mutate(){return $GLOBALS['authority'];}}
require_once dirname(__DIR__).'/includes/class-mad4b-scp-cso-secrets.php';
class FakeNativeProvider implements MAD4B_SCP_CSO_Secret_Provider {
	public $revision=0;public $configured=false;public $candidate='';public $secret='';public $stored=false;public $verified=false;public $active=false;public $revoked=false;public $failure='';public $drift='';public $leak=false;public $lose_verified=false;public $unconsumed=false;
	public function provider_key(){return 'fixture-provider';}public function is_available(){return true;}
	public function secret_fields(){return array('api-key'=>array('storage_mode'=>$GLOBALS['storage'],'plaintext_options'=>$GLOBALS['plaintext_options'],'max_bytes'=>4096,'store_ability'=>'fixture/store','verify_ability'=>'fixture/verify','cutover_ability'=>'fixture/cutover','revoke_ability'=>'fixture/revoke','readback_ability'=>'fixture/readback'));}
	public function secret_stage($field,$plaintext,array $context){$GLOBALS['calls'][]='store';if($this->revision!==$context['expected_revision']||!preg_match('/^csoh\.[a-f0-9]{64}$/D',$context['idempotency_ref']))return new WP_Error('native_cas');if('exception'===$this->failure)throw new Exception('fixture-secret-value');if('echo_secret'===$this->failure)return $plaintext;$this->secret=$plaintext;$this->candidate='cso-secret.'.str_repeat('9',32);$this->stored=true;++$this->revision;return $this->candidate;}
	public function secret_transition($phase,$field,$candidate,array $context){$GLOBALS['calls'][]=$phase;if($this->revision!==$context['expected_revision'])return false;if($phase===$this->failure)return true;if($candidate!==$this->candidate)return false;if('verify'===$phase)$this->verified=true;if('cutover'===$phase){$this->active=true;$this->configured=true;if($this->lose_verified)$this->verified=false;}if('revoke'===$phase)$this->revoked=true;++$this->revision;if($phase===$this->drift)$GLOBALS['scope']['runtime_generation']=str_repeat('f',64);return true;}
	public function inspect(array $target){$GLOBALS['calls'][]='readback:'.$target['phase'];$v=array('configured'=>$this->configured,'candidate_stored'=>$this->stored,'verified'=>$this->verified,'active_new'=>$this->active,'old_revoked'=>$this->revoked,'candidate_ref'=>$target['candidate_ref'],'observed_at'=>time(),'revision'=>$this->revision);if($this->leak&&'current'!==$target['phase'])$v['secret']='fixture-secret-value';return $v;}
}
$GLOBALS['provider']=new FakeNativeProvider();
class MAD4B_SCP_Adapter_Registry {public static function instance(){return new self();}public function register_defaults(){}public function all(){return $GLOBALS['registered']?array($GLOBALS['provider']):array();}}
class MAD4B_SCP_Provider_Compatibility_Certification {
	public static function clear_request_cache(){}public static function certification_generation_sha256($provider){return str_repeat('6',64);}
	public static function ability_status($p,$name,$adapter){return array('read_eligible'=>$GLOBALS['certified'],'write_eligible'=>$GLOBALS['certified'],'artifact_authority_bound'=>true,'behavioral_evidence'=>array('behavioral_verified'=>$GLOBALS['certified'],'receipt_sha256'=>str_repeat('4',64)),'activation_stage'=>'active','certification_level'=>'FULLY_CERTIFIED','capability_contract_digest'=>str_repeat('5',64));}
}
class MAD4B_SCP_Authorization {public static $executing='';public static function begin_execution_callback_observation($name){self::$executing='';}public static function execution_boundary_verified($ability){return $GLOBALS['wrapper'];}public static function execution_callback_started($name){return self::$executing===$name;}}
class MAD4B_SCP_Execution_Fence {public static $depth=0;public static function has_active_frame(){return self::$depth>0;}public static function final_execution_wrapper_verified($name){return $GLOBALS['wrapper'];}public static function with_governed_child($name,$input,$callback,$reason){if(self::$depth<1)return new WP_Error('real_parent_required');return $callback();}}
class FakeAbility {
	private $name;public function __construct($name){$this->name=$name;}public function get_meta(){return array('public'=>false,'mcp'=>array('public'=>false),'annotations'=>array('readonly'=>'fixture/readback'===$this->name));}public function check_permissions(array $input){if($GLOBALS['permission_probe']&&'fixture/store'===$this->name){$v=MAD4B_SCP_CSO_Secrets::dispatch_native($GLOBALS['provider'],$input);$GLOBALS['permission_probe_denied']=is_wp_error($v);}return $GLOBALS['permission'];}
	public function execute(array $input){$GLOBALS['envelopes'][]=array($this->name,$input);if(!$this->check_permissions($input))return new WP_Error('native_permission');$previous=MAD4B_SCP_Authorization::$executing;MAD4B_SCP_Authorization::$executing=$this->name;++MAD4B_SCP_Execution_Fence::$depth;try{if('fixture/readback'===$this->name)return $GLOBALS['provider']->inspect($input);if($GLOBALS['provider']->unconsumed)return 'cso-secret.'.str_repeat('8',32);return MAD4B_SCP_CSO_Secrets::dispatch_native($GLOBALS['provider'],$input);}finally{--MAD4B_SCP_Execution_Fence::$depth;MAD4B_SCP_Authorization::$executing=$previous;}}
}
function wp_get_ability($name){return new FakeAbility($name);}
$checks=0;function check($condition,$label){global $checks;++$checks;if(!$condition){fwrite(STDERR,'FAIL: '.$label."\n");exit(1);}}
function private_call($name,...$args){$r=new ReflectionMethod('MAD4B_SCP_CSO_Secrets',$name);$r->setAccessible(true);return $r->invokeArgs(null,$args);}function error_is($v,$reason=''){return is_wp_error($v)&&(''===$reason||false!==strpos($v->get_error_code(),$reason));}
function prepare($mode='configure'){return MAD4B_SCP_CSO_Secrets::session(array('provider_id'=>'fixture-provider','field_ref'=>'api-key','consent'=>true,'mode'=>$mode));}
function server(){return array('HTTPS'=>'on','HTTP_HOST'=>'example.test','HTTP_ORIGIN'=>'https://example.test','HTTP_SEC_FETCH_SITE'=>'same-origin','CONTENT_LENGTH'=>'1024','CONTENT_TYPE'=>'application/x-www-form-urlencoded','QUERY_STRING'=>'');}
function open_session(array $s,$sv=null){parse_str(parse_url($s['handoff_url'],PHP_URL_QUERY),$input);return private_call('open',$input,null===$sv?server():$sv);}
function submit(array $opened,$secret='fixture-secret-value',$sv=null,$nonce=null,$cookie=null){$ref=$opened['record']['session_ref'];return private_call('consume',array('action'=>MAD4B_SCP_CSO_Secrets::ACTION,'session_ref'=>$ref,'_wpnonce'=>null===$nonce?wp_create_nonce(MAD4B_SCP_CSO_Secrets::ACTION.':submit:'.$ref):$nonce,'secret'=>$secret),array(private_call('cookie_name',$ref)=>null===$cookie?$opened['cookie']:$cookie),null===$sv?server():$sv);}
function reset_provider($configured=false){$GLOBALS['provider']=new FakeNativeProvider();$GLOBALS['provider']->configured=$configured;$GLOBALS['calls']=array();$GLOBALS['envelopes']=array();}

MAD4B_SCP_CSO_Secrets::boot();MAD4B_SCP_CSO_Secrets::boot();check(1===count($GLOBALS['hooks'])&&isset($GLOBALS['hooks']['admin_post_mad4b_cso_secret_handoff']),'authenticated one-use handler only');
foreach(array('secret','credentials','password','api_key','raw_token','notes')as$key){$v=array('provider_id'=>'fixture-provider','field_ref'=>'api-key','consent'=>true,$key=>'fixture-secret-value');check(error_is(MAD4B_SCP_CSO_Secrets::session($v),'metadata_only'),'session plaintext denied '.$key);check(error_is(MAD4B_SCP_CSO_Secrets::rotation_plan($v),'metadata_only'),'plan plaintext denied '.$key);check(error_is(MAD4B_SCP_CSO_Secrets::status(array('session_ref'=>'csoh.'.str_repeat('7',64),$key=>'fixture-secret-value')),'metadata_only'),'status plaintext denied '.$key);}
check(error_is(MAD4B_SCP_CSO_Secrets::session(array('provider_id'=>array(),'field_ref'=>'api-key','consent'=>true))),'nested metadata denied');
$GLOBALS['enabled']=false;check(error_is(prepare(),'secrets_disabled'),'default OFF');$GLOBALS['enabled']=true;
$GLOBALS['wp_environment']='production';check(error_is(prepare(),'wordpress_environment_mismatch'),'WP production rejects staging secret handoff');
$GLOBALS['wp_environment']='staging';
foreach(array(array('registered',false),array('certified',false),array('storage','plaintext_options'),array('plaintext_options',true),array('wrapper',false))as$c){$old=$GLOBALS[$c[0]];$GLOBALS[$c[0]]=$c[1];$v=prepare();check('UNSUPPORTED'===$v['state']&&false===$v['collection_allowed']&&!isset($v['handoff_url']),'unsupported storage/certificate/wrapper before collection');$GLOBALS[$c[0]]=$old;}
$GLOBALS['cookie']='';check(error_is(prepare(),'first_party_session_required'),'OAuth cannot invent first-party browser cookie');$GLOBALS['cookie']=str_repeat('browser-fixture-',4);
$GLOBALS['permission']=false;check(error_is(prepare(),'native_permission_denied'),'native permission remains authority');$GLOBALS['permission']=true;
$plan=MAD4B_SCP_CSO_Secrets::rotation_plan(array('provider_id'=>'fixture-provider','field_ref'=>'api-key'));check('PLANNED'===$plan['state']&&false===$plan['execution_allowed']&&false===$plan['collection_allowed']&&7===count($plan['steps']),'plan is nonexecuting');
check(error_is(MAD4B_SCP_CSO_Secrets::dispatch_native($GLOBALS['provider'],array('field_ref'=>'api-key','candidate_ref'=>'','phase'=>'store')),'private_callback_unavailable'),'ordinary native/MCP execution has no plaintext');
$GLOBALS['endpoint']='https://foreign.test/wp-admin/admin-post.php';check(error_is(prepare(),'endpoint_foreign'),'foreign endpoint denied');$GLOBALS['endpoint']='https://example.test/wp-admin/admin-post.php';
$s=prepare();check('PREPARED'===$s['state']&&false===$s['plaintext_in_chat'],'prepared');
foreach(array('actor_sha256','source_sha','package_sha256','runtime_generation','restore_epoch','profile_sha256','site_uuid','origin','environment','blog_id','locale')as$key){$old=$GLOBALS['scope'][$key];$GLOBALS['scope'][$key]=is_int($old)?$old+1:('environment'===$key?'development':('origin'===$key?'https://other.test':$old.'x'));check(error_is(MAD4B_SCP_CSO_Secrets::status(array('session_ref'=>$s['session_ref']))),'scope drift denied '.$key);$GLOBALS['scope'][$key]=$old;}
foreach(array('cookie','issuer','auth_session')as$key){$old=$GLOBALS[$key];$GLOBALS[$key]=str_repeat('f',64);check(error_is(open_session($s),'actor_issuer_or_browser'),'forwarded link denied '.$key);$GLOBALS[$key]=$old;}
$sv=server();$sv['HTTP_PURPOSE']='prefetch';check(error_is(open_session($s,$sv),'navigation'),'prefetch denied');
$o=open_session($s);check('OPENED'===$o['record']['state'],'deliberate one-use open');check(error_is(open_session($s),'replayed'),'open replay denied');
$sv=server();$sv['HTTP_ORIGIN']='https://attacker.test';check(error_is(submit($o,'fixture-secret-value',$sv),'cross_origin'),'cross origin denied');$sv=server();unset($sv['HTTP_ORIGIN']);check(error_is(submit($o,'fixture-secret-value',$sv),'cross_origin'),'missing Origin denied');
check(error_is(submit($o,'fixture-secret-value',null,'bad'),'nonce_or_cookie'),'CSRF denied');check(error_is(submit($o,'fixture-secret-value',null,null,str_repeat('f',64)),'nonce_or_cookie'),'forwarded Strict cookie denied');
$sv=server();$sv['HTTP_HOST']='attacker.test';check(error_is(submit($o,'fixture-secret-value',$sv),'host_origin'),'Host mismatch denied');$GLOBALS['https']=false;check(error_is(submit($o),'https_required'),'TLS required');$GLOBALS['https']=true;
$sv=server();$sv['CONTENT_LENGTH']='999999';check(error_is(submit($o,'fixture-secret-value',$sv),'size_or_type'),'body bounded');$sv=server();$sv['CONTENT_TYPE']='application/json';check(error_is(submit($o,'fixture-secret-value',$sv),'size_or_type'),'no JSON plaintext transport');$sv=server();$sv['QUERY_STRING']='secret=value';check(error_is(submit($o,'fixture-secret-value',$sv),'submit_input'),'no secret in private POST URL');
check(error_is(submit($o,array('value')),'secret_value_invalid'),'malformed plaintext denied');
$GLOBALS['calls']=array();$v=submit($o);check('VERIFIED'===$v['state']&&$v['configured']&&$v['verified'],'independent setup lifecycle');check(array('readback:current','store','readback:store','verify','readback:verify','cutover','readback:cutover')===$GLOBALS['calls'],'actual setup order without revoke');
check(error_is(submit($o),'replayed'),'POST replay denied');check('fixture-secret-value'===$GLOBALS['provider']->secret,'native private store receives plaintext');
$encoded=json_encode(array($s,$v,$GLOBALS['wpdb']->rows,$GLOBALS['envelopes']));check(false===strpos($encoded,'fixture-secret-value')&&false===strpos($encoded,hash('sha256','fixture-secret-value')),'no plaintext/hash in URL, envelope, state or receipt');check(!MAD4B_SCP_Execution_Fence::has_active_frame()&&''===MAD4B_SCP_Authorization::$executing,'actual native frame cleanup');
reset_provider(true);$v=submit(open_session(prepare('rotate')));check('VERIFIED'===$v['state']&&$GLOBALS['provider']->revoked,'two-stage rotation');check('readback:revoke'===end($GLOBALS['calls']),'independent revocation readback');
reset_provider(true);$GLOBALS['provider']->failure='verify';$v=submit(open_session(prepare('rotate')));check('UNCERTAIN'===$v['state']&&$v['owner_recovery_required']&&!in_array('cutover',$GLOBALS['calls'],true)&&!in_array('revoke',$GLOBALS['calls'],true),'callback success is not verification');
reset_provider(true);$GLOBALS['provider']->failure='revoke';$v=submit(open_session(prepare('rotate')));check('PARTIAL'===$v['state']&&$v['owner_recovery_required'],'revoke callback without readback stays PARTIAL');
reset_provider(true);$GLOBALS['provider']->lose_verified=true;$v=submit(open_session(prepare('rotate')));check(in_array($v['state'],array('PARTIAL','UNCERTAIN'),true)&&!in_array('revoke',$GLOBALS['calls'],true),'verification cannot regress before old revocation');
reset_provider();$o=open_session(prepare());++$GLOBALS['provider']->revision;$v=submit($o);check(error_is($v,'native_state_changed')&&!in_array('store',$GLOBALS['calls'],true),'native CAS drift before collection');
reset_provider();$o=open_session(prepare());$GLOBALS['wpdb']->fail_cas=true;$v=submit($o);check(error_is($v,'compare_exchange')&&!in_array('store',$GLOBALS['calls'],true),'handoff claim loser cannot store');
reset_provider();$GLOBALS['provider']->leak=true;$v=submit(open_session(prepare()));check('UNCERTAIN'===$v['state']&&false===strpos(json_encode($v),'fixture-secret-value'),'readback extra secret rejected');
reset_provider();$GLOBALS['provider']->failure='exception';$v=submit(open_session(prepare()));check('UNCERTAIN'===$v['state']&&false===strpos(json_encode($v),'fixture-secret-value'),'native exception never leaks');
reset_provider();$GLOBALS['provider']->failure='echo_secret';$v=submit(open_session(prepare()));check('UNCERTAIN'===$v['state']&&false===strpos(json_encode($v),'fixture-secret-value'),'native callback plaintext sanitized before wrapper receipt');
reset_provider();$GLOBALS['provider']->unconsumed=true;$v=submit(open_session(prepare()));check('UNCERTAIN'===$v['state']&&!in_array('store',$GLOBALS['calls'],true),'native callback cannot fake private handoff consumption');
reset_provider();$o=open_session(prepare());MAD4B_SCP_Authorization::$executing='fixture/store';$GLOBALS['permission_probe']=true;$v=submit($o);check('VERIFIED'===$v['state']&&$GLOBALS['permission_probe_denied']&&1===count(array_keys($GLOBALS['calls'],'store',true)),'permission-time callback cannot consume private value');$GLOBALS['permission_probe']=false;
reset_provider();$GLOBALS['provider']->drift='verify';$v=submit(open_session(prepare()));check(error_is($v,'owner_recovery')&&!in_array('cutover',$GLOBALS['calls'],true),'runtime drift halts before cutover');$GLOBALS['scope']['runtime_generation']=str_repeat('c',64);
reset_provider();$s=prepare();$key=private_call('key',$s['session_ref']);$sealed=unserialize($GLOBALS['wpdb']->rows[$key]);$sealed['material']['expires_at']=time()-1;$GLOBALS['wpdb']->rows[$key]=serialize(MAD4B_SCP_CSO_Scope::seal($sealed['material'],MAD4B_SCP_CSO_Secrets::PURPOSE));check(error_is(open_session($s),'expired'),'TTL denied');$expiry_record_before=$GLOBALS['wpdb']->rows[$key];$v=MAD4B_SCP_CSO_Secrets::status(array('session_ref'=>$s['session_ref']));check('EXPIRED'===$v['state'],'expiry truthful');check($expiry_record_before===$GLOBALS['wpdb']->rows[$key],'status read must not mutate expired credential journal');
reset_provider();$s=prepare();$key=private_call('key',$s['session_ref']);$sealed=unserialize($GLOBALS['wpdb']->rows[$key]);$sealed['material']['field_ref']='other-key';$GLOBALS['wpdb']->rows[$key]=serialize($sealed);check(error_is(open_session($s),'record_invalid'),'field tampering denied');
fwrite(STDOUT,'PASS cso-secrets-runtime: '.$checks.' checks; explicit fake native executor, certificate, provider and DB; no live acceptance'."\n");
