<?php
if ( ! defined( 'ABSPATH' ) ) define( 'ABSPATH', __DIR__ . '/' );
$GLOBALS['opts']=array(); $GLOBALS['env']='staging'; $GLOBALS['home']='https://staging.client.test'; $GLOBALS['site']='https://staging.client.test'; $GLOBALS['uid']=7; $GLOBALS['admin']=true; $GLOBALS['bearer']=true; $GLOBALS['audit_ready']=true; $GLOBALS['audit_fail']=false; $GLOBALS['events']=array(); $GLOBALS['registered']=array();
$GLOBALS['prov']=array('manifest_present'=>true,'manifest_valid'=>true,'runtime_manifest_match'=>true,'stale'=>false,'provenance_mismatch'=>array(),'source_commit_sha'=>'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','build_fingerprint'=>'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb');
class WP_Error { private $c,$m,$d; function __construct($c,$m='',$d=null){$this->c=$c;$this->m=$m;$this->d=$d;} function get_error_code(){return $this->c;} function get_error_message(){return $this->m;} function get_error_data(){return $this->d;} }
function is_wp_error($v){return $v instanceof WP_Error;} function sanitize_key($v){return strtolower(preg_replace('/[^a-z0-9_\-]/','',(string)$v));} function sanitize_text_field($v){return trim(strip_tags((string)$v));} function absint($v){return abs((int)$v);} function wp_parse_url($u,$c=-1){return parse_url($u,$c);} function wp_json_encode($v,$f=0){return json_encode($v,$f);} function home_url($p=''){return rtrim($GLOBALS['home'],'/').(''===$p?'':'/'.ltrim($p,'/'));} function site_url($p=''){return rtrim($GLOBALS['site'],'/').(''===$p?'':'/'.ltrim($p,'/'));} function wp_get_environment_type(){return $GLOBALS['env'];} function current_user_can($c){return 'manage_options'===$c && !empty($GLOBALS['admin']);} function get_current_user_id(){return (int)$GLOBALS['uid'];} function get_option($k,$d=false){return array_key_exists($k,$GLOBALS['opts'])?$GLOBALS['opts'][$k]:$d;} function update_option($k,$v,$a=null){$GLOBALS['opts'][$k]=$v;return true;} function delete_option($k){unset($GLOBALS['opts'][$k]);return true;} function wp_generate_uuid4(){return '123e4567-e89b-42d3-a456-426614174000';} function get_userdata($id){return absint($id)>0?(object)array('ID'=>absint($id)):false;} function user_can($u,$c){return is_object($u)&&'manage_options'===$c;} function get_bloginfo($k){return 'Client Test';} function apply_filters($h,$v){return $v;} function add_filter(){} function add_action(){} function remove_filter(){return true;} function has_filter(){return false;} function wp_register_ability($n,$a){$GLOBALS['registered'][$n]=$a;} function wp_has_ability(){return false;}
final class MAD4B_SCP_Audit { static function storage_status(){return array('ready'=>!empty($GLOBALS['audit_ready']));} static function record($a,$s,$st=''){if(!empty($GLOBALS['audit_fail']))return new WP_Error('audit_failed','forced');$GLOBALS['events'][]=array($a,$s,$st);return true;} }
final class MAD4B_SCP_OAuth_Resource_Bridge { static function verified_bearer_active(){return !empty($GLOBALS['bearer']);} }
final class MAD4B_SCP_Live_Acceptance_Observer { static function build_provenance_status(){return $GLOBALS['prov'];} }
require_once dirname(__DIR__).'/includes/class-mad4b-scp-site-profile.php';
require_once dirname(__DIR__).'/includes/class-mad4b-scp-site-profile-write-enablement.php';
function ok($c,$m){if(!$c){fwrite(STDERR,"FAIL: $m\n");exit(1);}} function err($r,$c,$m){ok(is_wp_error($r)&&$c===$r->get_error_code(),$m.' got='.(is_wp_error($r)?$r->get_error_code():'success'));}
function seed_profile($env='staging',$origin='https://staging.client.test'){$GLOBALS['env']=$env;$GLOBALS['home']=$origin;$GLOBALS['site']=$origin;$GLOBALS['uid']=7;$GLOBALS['admin']=true;$GLOBALS['bearer']=true;$GLOBALS['audit_ready']=true;$GLOBALS['audit_fail']=false;$GLOBALS['events']=array();$GLOBALS['opts']=array();$GLOBALS['opts'][MAD4B_SCP_Site_Profile::OPTION]=array('contract'=>MAD4B_SCP_Site_Profile::CONTRACT,'version'=>MAD4B_SCP_Site_Profile::VERSION,'site_uuid'=>'123e4567-e89b-42d3-a456-426614174000','revision'=>4,'environment'=>$env,'canonical_origin'=>$origin,'display_name'=>'Preserve Me','chatgpt_app_id'=>'plugin_asdk_app_test123','oauth_user_ids'=>array(7),'related_origins'=>array('development'=>'https://dev.client.test','staging'=>'https://staging.client.test','production'=>'https://client.test'),'features'=>array('oauth'=>true,'skills'=>true,'write'=>false,'production_write_confirmed'=>false,'provider_isolation'=>true,'managed_runtime'=>true,'acceptance'=>true),'legacy_agent_slug'=>'','legacy_zero_touch'=>false,'created_at'=>'2026-01-01T00:00:00Z','updated_at'=>'2026-01-01T00:00:00Z');MAD4B_SCP_Site_Profile::reset_cache();return $GLOBALS['opts'][MAD4B_SCP_Site_Profile::OPTION];}
function input_now(){return array('expected_revision'=>MAD4B_SCP_Site_Profile::revision(),'expected_profile_digest'=>MAD4B_SCP_Site_Profile::profile_digest(),'expected_source_commit_sha'=>$GLOBALS['prov']['source_commit_sha'],'expected_build_fingerprint'=>$GLOBALS['prov']['build_fingerprint'],'confirmation'=>MAD4B_SCP_Site_Profile_Write_Enablement::CONFIRMATION);}

MAD4B_SCP_Site_Profile_Write_Enablement::register_ability();
$ability=$GLOBALS['registered'][MAD4B_SCP_Site_Profile_Write_Enablement::ABILITY];$schema=$ability['input_schema'];
ok(false===$schema['additionalProperties'],'schema denies additional properties');
ok(5===count($schema['properties']),'schema has exactly five inputs');
ok(array('expected_revision','expected_profile_digest','expected_source_commit_sha','expected_build_fingerprint','confirmation')===$schema['required'],'all five inputs are required');
ok(!array_key_exists('write_enabled',$schema['properties']),'generic write_enabled input is not exposed');
ok(array(MAD4B_SCP_Site_Profile_Write_Enablement::CONFIRMATION)===$schema['properties']['confirmation']['enum'],'schema pins exact governed Staging write confirmation');

$before=seed_profile();$in=input_now();$r=MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in);ok(!is_wp_error($r),'bounded Staging write enablement succeeds');$after=get_option(MAD4B_SCP_Site_Profile::OPTION,array());ok(5===(int)$after['revision'],'write enablement increments revision once');ok(!empty($after['features']['write'])&&empty($after['features']['production_write_confirmed']),'write enabled while Production confirmation remains false');$expected=$before;$expected['revision']=5;$expected['features']['write']=true;$expected['features']['production_write_confirmed']=false;unset($expected['updated_at'],$after['updated_at']);ok($expected===$after,'all non-write Site Profile fields are preserved exactly');ok(1===count($GLOBALS['events'])&&'mad4b/site-profile-write-enabled'===$GLOBALS['events'][0][0],'bounded write enablement audit recorded');ok(!empty($r['authority_reconciliation_deferred'])&&false===$r['same_invocation_nhi_created']&&0===$r['same_invocation_grants_created']&&false===$r['same_invocation_mutation_gate_enabled'],'same invocation creates no NHI grants or mutation gate');

seed_profile('production','https://client.test');$in=input_now();err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_staging_only','Production write enablement denied');
seed_profile();$in=input_now();$in['confirmation']='ENABLE WRITE';err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_confirmation_required','non-exact confirmation denied');
seed_profile();$in=input_now();$in['expected_revision']=3;err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_revision_stale','stale revision denied');
seed_profile();$in=input_now();$in['expected_profile_digest']=str_repeat('c',64);err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_digest_stale','stale digest denied');
seed_profile();$in=input_now();$in['expected_source_commit_sha']=str_repeat('c',40);err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_candidate_mismatch','candidate mismatch denied');
seed_profile();$in=input_now();$in['expected_build_fingerprint']=str_repeat('c',64);err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_fingerprint_mismatch','fingerprint mismatch denied');
$before=seed_profile();$GLOBALS['audit_fail']=true;$in=input_now();err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_audit_failed','audit failure is fail-closed');ok($before===get_option(MAD4B_SCP_Site_Profile::OPTION,array()),'audit failure restores exact previous profile');
$before=seed_profile();$GLOBALS['opts'][MAD4B_SCP_Site_Profile::OPTION]['features']['skills']=false;MAD4B_SCP_Site_Profile::reset_cache();$in=input_now();err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_phase_a_required','Phase A completion required');

echo "mad4b.site-profile-write-enablement.runtime.v1: PASS\n";
