<?php
if ( ! defined( 'ABSPATH' ) ) define( 'ABSPATH', __DIR__ . '/' );
if ( ! defined( 'ARRAY_A' ) ) define( 'ARRAY_A', 'ARRAY_A' );
$GLOBALS['opts']=array(); $GLOBALS['env']='staging'; $GLOBALS['home']='https://staging.client.test'; $GLOBALS['site']='https://staging.client.test'; $GLOBALS['uid']=7; $GLOBALS['admin']=true; $GLOBALS['bearer']=true; $GLOBALS['audit_ready']=true; $GLOBALS['audit_fail']=false; $GLOBALS['events']=array(); $GLOBALS['registered']=array();
$GLOBALS['agents']=array(); $GLOBALS['subjects']=array(); $GLOBALS['grants']=array(); $GLOBALS['tx_snapshot']=null; $GLOBALS['force_reconcile_fail']=false;
$GLOBALS['prov']=array('manifest_present'=>true,'manifest_valid'=>true,'runtime_manifest_match'=>true,'stale'=>false,'provenance_mismatch'=>array(),'source_commit_sha'=>'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','build_fingerprint'=>'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb');
class WP_Error { private $c,$m,$d; function __construct($c,$m='',$d=null){$this->c=$c;$this->m=$m;$this->d=$d;} function get_error_code(){return $this->c;} function get_error_message(){return $this->m;} function get_error_data(){return $this->d;} }
function is_wp_error($v){return $v instanceof WP_Error;} function sanitize_key($v){return strtolower(preg_replace('/[^a-z0-9_\-]/','',(string)$v));} function sanitize_text_field($v){return trim(strip_tags((string)$v));} function absint($v){return abs((int)$v);} function wp_parse_url($u,$c=-1){return parse_url($u,$c);} function wp_json_encode($v,$f=0){return json_encode($v,$f);} function home_url($p=''){return rtrim($GLOBALS['home'],'/').(''===$p?'':'/'.ltrim($p,'/'));} function site_url($p=''){return rtrim($GLOBALS['site'],'/').(''===$p?'':'/'.ltrim($p,'/'));} function wp_get_environment_type(){return $GLOBALS['env'];} function current_user_can($c){return 'manage_options'===$c && !empty($GLOBALS['admin']);} function get_current_user_id(){return (int)$GLOBALS['uid'];} function get_option($k,$d=false){return array_key_exists($k,$GLOBALS['opts'])?$GLOBALS['opts'][$k]:$d;} function update_option($k,$v,$a=null){$GLOBALS['opts'][$k]=$v;return true;} function delete_option($k){unset($GLOBALS['opts'][$k]);return true;} function wp_generate_uuid4(){return '123e4567-e89b-42d3-a456-426614174000';} function get_userdata($id){return absint($id)>0?(object)array('ID'=>absint($id)):false;} function user_can($u,$c){return is_object($u)&&'manage_options'===$c;} function get_bloginfo($k){return 'Client Test';} function apply_filters($h,$v){return $v;} function add_filter(){} function add_action(){} function remove_filter(){return true;} function has_filter(){return false;} function wp_register_ability($n,$a){$GLOBALS['registered'][$n]=$a;} function wp_has_ability(){return false;}
final class FakeWpdb {
    public $last_error='';
    function prepare($query,...$args){return array('query'=>$query,'args'=>$args);}
    function get_row($prepared,$format=null){if(is_array($prepared)&&false!==strpos($prepared['query'],'agents')&&false!==strpos($prepared['query'],'slug=')){$slug=(string)$prepared['args'][0];foreach($GLOBALS['agents'] as $row)if($row['slug']===$slug)return $row;return null;}return null;}
    function get_results($prepared,$format=null){if(is_array($prepared)&&false!==strpos($prepared['query'],'subjects')){$type=(string)$prepared['args'][0];$fp=(string)$prepared['args'][1];$rows=array();foreach($GLOBALS['subjects'] as $row)if($row['subject_type']===$type&&$row['subject_fingerprint']===$fp)$rows[]=$row;usort($rows,function($a,$b){return $a['id']<=>$b['id'];});return $rows;}return array();}
    function update($table,$data,$where,$formats=array(),$where_formats=array()){if('subjects'!==$table)return false;foreach($GLOBALS['subjects'] as $i=>$row){$match=true;foreach($where as $k=>$v)if(!array_key_exists($k,$row)||(string)$row[$k] !== (string)$v){$match=false;break;}if(!$match)continue;$GLOBALS['subjects'][$i]=array_merge($row,$data);return 1;}return 0;}
    function query($sql){$sql=strtoupper(trim((string)$sql));if('START TRANSACTION'===$sql){$GLOBALS['tx_snapshot']=array('subjects'=>$GLOBALS['subjects'],'opts'=>$GLOBALS['opts'],'events'=>$GLOBALS['events']);return 1;}if('ROLLBACK'===$sql){if(is_array($GLOBALS['tx_snapshot'])){$GLOBALS['subjects']=$GLOBALS['tx_snapshot']['subjects'];$GLOBALS['opts']=$GLOBALS['tx_snapshot']['opts'];$GLOBALS['events']=$GLOBALS['tx_snapshot']['events'];}$GLOBALS['tx_snapshot']=null;return 1;}if('COMMIT'===$sql){$GLOBALS['tx_snapshot']=null;return 1;}return false;}
}
$GLOBALS['wpdb']=new FakeWpdb();
final class MAD4B_SCP_Audit { static function storage_status(){return array('ready'=>!empty($GLOBALS['audit_ready']));} static function record($a,$s,$st=''){if(!empty($GLOBALS['audit_fail']))return new WP_Error('audit_failed','forced');$GLOBALS['events'][]=array($a,$s,$st);return true;} }
final class MAD4B_SCP_OAuth_Resource_Bridge { static function verified_bearer_active(){return !empty($GLOBALS['bearer']);} }
final class MAD4B_SCP_Live_Acceptance_Observer { static function build_provenance_status(){return $GLOBALS['prov'];} }
final class MAD4B_SCP_Local_OAuth_Server { static function issuer(){return 'https://staging.client.test/oauth/mcp';} }
final class MAD4B_SCP_Schema { static function critical_ready(){return true;} static function tables(){return array('agents'=>'agents','subjects'=>'subjects','grants'=>'grants');} }
final class MAD4B_SCP_Servers { static function provider_for_ability($server,$ability){$m=array('mad4b/content-update-post'=>'core','woocommerce/update-product'=>'woocommerce');return isset($m[$ability])?$m[$ability]:null;} }
final class MAD4B_SCP_Agent_Registry { static function get_agent_by_id($id){return isset($GLOBALS['agents'][(int)$id])?$GLOBALS['agents'][(int)$id]:null;} static function grants_for_agent($id,$server=''){return array_values(array_filter($GLOBALS['grants'],function($g)use($id,$server){return (int)$g['agent_id']===(int)$id&&(''===$server||$g['server_id']===$server);}));} static function exact_grant($id,$server,$ability,$provider='core'){foreach($GLOBALS['grants'] as $g){if((int)$g['agent_id']===(int)$id&&$g['server_id']===$server&&$g['ability_name']===$ability&&$g['provider']===$provider&&in_array($g['environment'],array('all',$GLOBALS['env']),true)){if('deny'===$g['effect'])return new WP_Error('mad4b_nhi_grant_denied');if('allow'===$g['effect'])return $g;}}return new WP_Error('mad4b_nhi_grant_missing');} }
final class MAD4B_SCP_Staging_Write_Authority { static function write_tools(){return array('mad4b/content-update-post','woocommerce/update-product');} static function reconcile(){$fp=hash('sha256','oauth'."\0".MAD4B_SCP_Local_OAuth_Server::issuer()."\0".'user:7');$bound=0;foreach($GLOBALS['subjects'] as $s)if($s['subject_type']==='oauth'&&$s['subject_fingerprint']===$fp&&$s['status']==='enabled')$bound=(int)$s['agent_id'];$ready=2===$bound&&empty($GLOBALS['force_reconcile_fail']);return array('ready'=>$ready,'agent_public_id'=>$ready?$GLOBALS['agents'][2]['public_id']:$GLOBALS['agents'][1]['public_id'],'breakglass_included'=>false,'grant_blockers'=>$ready?array():array('oauth_subject_bound_to_other_agent:user:7'));} }
require_once dirname(__DIR__).'/includes/class-mad4b-scp-site-profile.php';
require_once dirname(__DIR__).'/includes/class-mad4b-scp-site-profile-write-enablement.php';
function ok($c,$m){if(!$c){fwrite(STDERR,"FAIL: $m\n");exit(1);}} function err($r,$c,$m){ok(is_wp_error($r)&&$c===$r->get_error_code(),$m.' got='.(is_wp_error($r)?$r->get_error_code():'success'));}
function seed_profile($env='staging',$origin='https://staging.client.test',$write=false,$revision=4){$GLOBALS['env']=$env;$GLOBALS['home']=$origin;$GLOBALS['site']=$origin;$GLOBALS['uid']=7;$GLOBALS['admin']=true;$GLOBALS['bearer']=true;$GLOBALS['audit_ready']=true;$GLOBALS['audit_fail']=false;$GLOBALS['events']=array();$GLOBALS['opts']=array();$GLOBALS['force_reconcile_fail']=false;$GLOBALS['opts'][MAD4B_SCP_Site_Profile::OPTION]=array('contract'=>MAD4B_SCP_Site_Profile::CONTRACT,'version'=>MAD4B_SCP_Site_Profile::VERSION,'site_uuid'=>'123e4567-e89b-42d3-a456-426614174000','revision'=>$revision,'environment'=>$env,'canonical_origin'=>$origin,'display_name'=>'Preserve Me','chatgpt_app_id'=>'plugin_asdk_app_test123','oauth_user_ids'=>array(7),'related_origins'=>array('development'=>'https://dev.client.test','staging'=>'https://staging.client.test','production'=>'https://client.test'),'features'=>array('oauth'=>true,'skills'=>true,'write'=>$write,'production_write_confirmed'=>false,'provider_isolation'=>true,'managed_runtime'=>true,'acceptance'=>true),'legacy_agent_slug'=>'','legacy_zero_touch'=>false,'created_at'=>'2026-01-01T00:00:00Z','updated_at'=>'2026-01-01T00:00:00Z');MAD4B_SCP_Site_Profile::reset_cache();return $GLOBALS['opts'][MAD4B_SCP_Site_Profile::OPTION];}
function seed_authority($target_complete=true){$GLOBALS['agents']=array(1=>array('id'=>1,'public_id'=>'87af0473-4555-448e-9921-f8ac77fcb6a0','slug'=>'chatgpt-staging-write','label'=>'Legacy','status'=>'enabled','wp_user_id'=>7,'environment'=>'staging','revision'=>1),2=>array('id'=>2,'public_id'=>'0b8f7c20-6f75-4401-b33e-a59a14c48895','slug'=>'chatgpt-governed-write','label'=>'Canonical','status'=>'enabled','wp_user_id'=>7,'environment'=>'staging','revision'=>1));$fp=hash('sha256','oauth'."\0".MAD4B_SCP_Local_OAuth_Server::issuer()."\0".'user:7');$GLOBALS['subjects']=array(array('id'=>10,'agent_id'=>1,'subject_type'=>'oauth','subject_fingerprint'=>$fp,'label'=>'Local OAuth user:7','status'=>'enabled'));$GLOBALS['grants']=array(array('id'=>1,'agent_id'=>1,'effect'=>'allow','server_id'=>'mad4b-write','ability_name'=>'mad4b/content-update-post','provider'=>'core','environment'=>'staging'),array('id'=>2,'agent_id'=>1,'effect'=>'allow','server_id'=>'mad4b-write','ability_name'=>'woocommerce/update-product','provider'=>'woocommerce','environment'=>'staging'),array('id'=>3,'agent_id'=>1,'effect'=>'allow','server_id'=>'mad4b-write','ability_name'=>'jetengine/update-post-meta','provider'=>'jetengine','environment'=>'staging'),array('id'=>11,'agent_id'=>2,'effect'=>'allow','server_id'=>'mad4b-write','ability_name'=>'mad4b/content-update-post','provider'=>'core','environment'=>'staging'));if($target_complete)$GLOBALS['grants'][]=array('id'=>12,'agent_id'=>2,'effect'=>'allow','server_id'=>'mad4b-write','ability_name'=>'woocommerce/update-product','provider'=>'woocommerce','environment'=>'staging');}
function input_now(){return array('expected_revision'=>MAD4B_SCP_Site_Profile::revision(),'expected_profile_digest'=>MAD4B_SCP_Site_Profile::profile_digest(),'expected_source_commit_sha'=>$GLOBALS['prov']['source_commit_sha'],'expected_build_fingerprint'=>$GLOBALS['prov']['build_fingerprint'],'confirmation'=>MAD4B_SCP_Site_Profile_Write_Enablement::CONFIRMATION);}
MAD4B_SCP_Site_Profile_Write_Enablement::register_ability();
$ability=$GLOBALS['registered'][MAD4B_SCP_Site_Profile_Write_Enablement::ABILITY];$schema=$ability['input_schema'];ok(false===$schema['additionalProperties'],'schema denies additional properties');ok(5===count($schema['properties']),'schema has exactly five inputs');ok(array('expected_revision','expected_profile_digest','expected_source_commit_sha','expected_build_fingerprint','confirmation')===$schema['required'],'all five inputs are required');ok(!array_key_exists('write_enabled',$schema['properties']),'generic write_enabled input is not exposed');ok(array(MAD4B_SCP_Site_Profile_Write_Enablement::CONFIRMATION)===$schema['properties']['confirmation']['enum'],'schema pins exact governed Staging write confirmation');
$before=seed_profile();$in=input_now();$r=MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in);ok(!is_wp_error($r),'bounded Staging write enablement succeeds');$after=get_option(MAD4B_SCP_Site_Profile::OPTION,array());ok(5===(int)$after['revision'],'write enablement increments revision once');ok(!empty($after['features']['write'])&&empty($after['features']['production_write_confirmed']),'write enabled while Production confirmation remains false');$expected=$before;$expected['revision']=5;$expected['features']['write']=true;$expected['features']['production_write_confirmed']=false;unset($expected['updated_at'],$after['updated_at']);ok($expected===$after,'all non-write Site Profile fields are preserved exactly');ok(1===count($GLOBALS['events'])&&'mad4b/site-profile-write-enabled'===$GLOBALS['events'][0][0],'bounded write enablement audit recorded');ok(!empty($r['authority_reconciliation_deferred'])&&false===$r['same_invocation_nhi_created']&&0===$r['same_invocation_grants_created']&&false===$r['same_invocation_mutation_gate_enabled'],'initial invocation creates no NHI grants or mutation gate');
seed_profile('staging','https://staging.client.test',true,5);seed_authority(true);$before_profile=get_option(MAD4B_SCP_Site_Profile::OPTION,array());$before_grants=$GLOBALS['grants'];$in=input_now();$r=MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in);ok(!is_wp_error($r),'already-enabled exact profile performs bounded subject repair');ok('authority_reconciled'===$r['state']&&!empty($r['atomic_subject_move'])&&!empty($r['write_authority_ready']),'repair returns reconciled ready state');ok(2===(int)$GLOBALS['subjects'][0]['agent_id'],'exact OAuth subject moved atomically to canonical agent');ok($before_profile===get_option(MAD4B_SCP_Site_Profile::OPTION,array()),'repair does not mutate Site Profile revision or fields');ok($before_grants===$GLOBALS['grants'],'repair does not mutate legacy or canonical grant records');ok('enabled'===$GLOBALS['agents'][1]['status'],'repair does not disable legacy agent');ok(1===count($GLOBALS['events'])&&'mad4b/governed-write-subject-handoff'===$GLOBALS['events'][0][0],'repair audit recorded');$in=input_now();$r=MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in);ok(!is_wp_error($r)&&'authority_already_reconciled'===$r['state'],'repeat invocation is bounded and does not move subject twice');
seed_profile('staging','https://staging.client.test',true,5);seed_authority(false);$in=input_now();err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_repair_target_grants_incomplete','repair denied until canonical target has complete exact grant set');ok(1===(int)$GLOBALS['subjects'][0]['agent_id'],'grant preflight failure leaves legacy subject binding unchanged');
seed_profile('staging','https://staging.client.test',true,5);seed_authority(true);$GLOBALS['force_reconcile_fail']=true;$in=input_now();err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_repair_reconcile_failed','failed post-move reconciliation rolls back subject handoff');ok(1===(int)$GLOBALS['subjects'][0]['agent_id'],'reconciliation failure restores legacy subject binding');
seed_profile('staging','https://staging.client.test',true,5);seed_authority(true);$GLOBALS['audit_fail']=true;$in=input_now();err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_repair_audit_failed','handoff audit failure rolls back subject move');ok(1===(int)$GLOBALS['subjects'][0]['agent_id'],'audit failure restores legacy subject binding');
seed_profile('production','https://client.test');$in=input_now();err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_staging_only','Production write enablement denied');seed_profile();$in=input_now();$in['confirmation']='ENABLE WRITE';err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_confirmation_required','non-exact confirmation denied');seed_profile();$in=input_now();$in['expected_revision']=3;err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_revision_stale','stale revision denied');seed_profile();$in=input_now();$in['expected_profile_digest']=str_repeat('c',64);err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_digest_stale','stale digest denied');seed_profile();$in=input_now();$in['expected_source_commit_sha']=str_repeat('c',40);err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_candidate_mismatch','candidate mismatch denied');seed_profile();$in=input_now();$in['expected_build_fingerprint']=str_repeat('c',64);err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_fingerprint_mismatch','fingerprint mismatch denied');$before=seed_profile();$GLOBALS['audit_fail']=true;$in=input_now();err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_audit_failed','audit failure is fail-closed');ok($before===get_option(MAD4B_SCP_Site_Profile::OPTION,array()),'audit failure restores exact previous profile');$before=seed_profile();$GLOBALS['opts'][MAD4B_SCP_Site_Profile::OPTION]['features']['skills']=false;MAD4B_SCP_Site_Profile::reset_cache();$in=input_now();err(MAD4B_SCP_Site_Profile_Write_Enablement::enable_write($in),'mad4b_site_profile_write_enable_phase_a_required','Phase A completion required');
echo "mad4b.site-profile-write-enablement.runtime.v2: PASS\n";
