<?php
define('ABSPATH',__DIR__.'/');define('MAD4B_SCP_TEST_RUNTIME',true);define('MAD4B_SCP_DIR',dirname(__DIR__).'/');
class WP_Error{private $c;private $d;public function __construct($c='',$m='',$d=null){$this->c=(string)$c;$this->d=$d;}public function get_error_code(){return$this->c;}public function get_error_data(){return$this->d;}}
function is_wp_error($v){return$v instanceof WP_Error;} function sanitize_key($v){return strtolower(preg_replace('/[^a-z0-9_\-]/i','',(string)$v));} function wp_json_encode($v,$f=0){return json_encode($v,$f);}
require dirname(__DIR__).'/includes/class-mad4b-scp-time-policy.php';
$fail=static function($m,$v=null){fwrite(STDERR,'FAIL time-policy-runtime: '.$m.(null===$v?'':' '.json_encode($v)).PHP_EOL);exit(1);};$check=static function($c,$m,$v=null)use($fail){if(!$c)$fail($m,$v);};$code=static function($v){return is_wp_error($v)?$v->get_error_code():'';};
$clock=MAD4B_SCP_Time_Policy::set_test_clock(2000000000,500000);$check(is_array($clock)&&2000000000===$clock['wall_epoch']&&500000===$clock['monotonic_ms'],'test clock injection failed',$clock);
$check(300===MAD4B_SCP_Time_Policy::bounded_ttl('preparation_receipt',0),'preparation receipt default TTL drifted');$check(60===MAD4B_SCP_Time_Policy::bounded_ttl('approval_ticket',1),'approval min TTL bound failed');$check(3600===MAD4B_SCP_Time_Policy::bounded_ttl('durable_lease',999999),'lease max TTL bound failed');
$check(is_array(MAD4B_SCP_Time_Policy::assert_timestamp('crypto_signature',2000000029)),'future clock-skew allowance rejected valid signature');$check('mad4b_time_future_skew_exceeded'===$code(MAD4B_SCP_Time_Policy::assert_timestamp('crypto_signature',2000000031)),'future clock-skew overflow did not fail closed');$check('mad4b_time_observation_stale'===$code(MAD4B_SCP_Time_Policy::assert_timestamp('reconciliation_observation',1999999600,300)),'stale reconciliation observation was accepted');
$low=MAD4B_SCP_Time_Policy::offline_window('low',array(array('age_seconds'=>120,'ttl_seconds'=>600),array('age_seconds'=>120,'ttl_seconds'=>180)));$check(!empty($low['allowed'])&&180===$low['effective_max_age_seconds'],'shorter dependency TTL did not dominate offline window',$low);
$expired=MAD4B_SCP_Time_Policy::offline_window('low',array(array('age_seconds'=>181,'ttl_seconds'=>180)));$check(empty($expired['allowed'])&&'dependency_ttl_expired'===$expired['reason_code'],'expired dependency did not block offline window',$expired);
$high=MAD4B_SCP_Time_Policy::offline_window('high',array(array('age_seconds'=>0,'ttl_seconds'=>3600)));$check(empty($high['allowed'])&&!empty($high['online_required'])&&'online_validation_required'===$high['reason_code'],'high-risk offline authorization did not require online validation',$high);
$advanced=MAD4B_SCP_Time_Policy::advance_test_clock(-120,2500);$check(1999999880===$advanced['wall_epoch']&&502500===$advanced['monotonic_ms'],'wall rollback/monotonic advance fixture failed',$advanced);$check(MAD4B_SCP_Time_Policy::monotonic_ms()>500000,'monotonic clock did not remain forward-moving under wall rollback');
MAD4B_SCP_Time_Policy::reset_test_clock();echo "mad4b.time-policy.runtime.v1: PASS\n";
