<?php
namespace ETG\DynamicFilterSEOBridge\Diagnostics;

trait InventoryReconcilerDriftTrait {
    private function compareSnapshots(array $previous,array $current):array{
        if(!$previous||$this->validateSnapshot($previous)){return array('findings'=>array());}$out=array();$before=(array)$previous['inventory'];$after=(array)$current['inventory'];
        foreach(array('post_types','taxonomies') as $section){if(!$this->sectionComparable($before,$after,$section)){$out[]=$this->findingValue('warning','snapshot_'.$section.'_comparison_skipped_incomplete_inventory','snapshot:'.$section);continue;}$b=(array)($before[$section]??array());$a=(array)($after[$section]??array());foreach(array_diff(array_keys($a),array_keys($b)) as $key){$out[]=$this->findingValue('info','snapshot_'.$section.'_added',$section.':'.sanitize_key((string)$key),array('key'=>sanitize_key((string)$key)));}foreach(array_diff(array_keys($b),array_keys($a)) as $key){$out[]=$this->findingValue('warning','snapshot_'.$section.'_removed',$section.':'.sanitize_key((string)$key),array('key'=>sanitize_key((string)$key)));}foreach(array_intersect(array_keys($b),array_keys($a)) as $key){if($this->stableHash((array)$b[$key])!==$this->stableHash((array)$a[$key])){$out[]=$this->findingValue('warning','snapshot_'.$section.'_changed',$section.':'.sanitize_key((string)$key),array('key'=>sanitize_key((string)$key)));}}
        }
        if($this->sectionComparable($before,$after,'languages')){$b=$this->languageIndex((array)($before['languages']??array()));$a=$this->languageIndex((array)($after['languages']??array()));foreach(array_diff(array_keys($a),array_keys($b)) as $code){$out[]=$this->findingValue('info','snapshot_language_added','language:'.$code,array('code'=>$code));}foreach(array_diff(array_keys($b),array_keys($a)) as $code){$out[]=$this->findingValue('warning','snapshot_language_removed','language:'.$code,array('code'=>$code));}foreach(array_intersect(array_keys($b),array_keys($a)) as $code){if($this->stableHash($b[$code])!==$this->stableHash($a[$code])){$out[]=$this->findingValue('warning','snapshot_language_changed','language:'.$code,array('code'=>$code));}}}else{$out[]=$this->findingValue('warning','snapshot_languages_comparison_skipped_incomplete_inventory','snapshot:languages');}
        $bq=(array)($before['query_builder']??array());$aq=(array)($after['query_builder']??array());$comparable=$this->queryIdentityComplete($before)&&$this->queryIdentityComplete($after)&&!empty($bq['available'])&&!empty($aq['available'])&&0===(int)($bq['identity_conflict_count']??0)&&0===(int)($aq['identity_conflict_count']??0);
        if($comparable){$bi=$this->queryIndex($this->identityRecords($bq),array());$ai=$this->queryIndex($this->identityRecords($aq),array());foreach(array_diff(array_keys($ai),array_keys($bi)) as $id){$out[]=$this->findingValue('info','snapshot_query_added','query:'.$id,array('query_id'=>$id));}foreach(array_diff(array_keys($bi),array_keys($ai)) as $id){$out[]=$this->findingValue('warning','snapshot_query_removed','query:'.$id,array('query_id'=>$id));}foreach(array_intersect(array_keys($bi),array_keys($ai)) as $id){$b=(array)$bi[$id];$a=(array)$ai[$id];if(!empty($b['post_type_bounded'])&&empty($a['post_type_bounded'])){$out[]=$this->findingValue('blocking','snapshot_query_became_unbounded','query:'.$id,array('query_id'=>$id));continue;}if($this->stableHash($b)!==$this->stableHash($a)){$out[]=$this->findingValue('warning','snapshot_query_changed','query:'.$id,array('query_id'=>$id));}}}else{$out[]=$this->findingValue('warning','snapshot_query_comparison_skipped_incomplete_or_ambiguous_inventory','snapshot:query_builder');}
        return array('findings'=>array_slice($out,0,self::MAX_FINDINGS));
    }
}
