<?php
namespace ETG\DynamicFilterSEOBridge\Diagnostics;

use ETG\DynamicFilterSEOBridge\Config\Configuration;
use ETG\DynamicFilterSEOBridge\Context\FilterContextBuilder;
use ETG\DynamicFilterSEOBridge\SEO\IndexingPolicy;

final class LiveRuntimeProbe {
	private const ARM_KEY='etg_dfsb_live_probe_armed_until';
	private const SAMPLES_KEY='etg_dfsb_live_probe_samples';
	private $config; private $builder; private $policy; private $requestId=''; private $startedAt=0.0; private $bufferStarted=false;
	public function __construct(Configuration $config,FilterContextBuilder $builder,IndexingPolicy $policy){$this->config=$config;$this->builder=$builder;$this->policy=$policy;$this->startedAt=microtime(true);$this->requestId=substr(hash('sha256',$this->startedAt.'|'.(string)($_SERVER['REQUEST_URI']??'').'|'.wp_rand()),0,16);}
	public function register():void{
		add_action('admin_post_etg_dfsb_arm_live_probe',array($this,'armAction'));
		add_action('admin_post_etg_dfsb_clear_live_probe',array($this,'clearAction'));
		add_action('admin_post_etg_dfsb_export_live_probe',array($this,'exportAction'));
		add_action('wp',array($this,'captureWpEarly'),1);add_action('wp',array($this,'captureWpLate'),999);
		add_action('template_redirect',array($this,'startHtmlProbe'),0);add_action('template_redirect',array($this,'captureTemplateRedirect'),999);
		add_action('wp_head',array($this,'captureHeadEarly'),1);add_action('wp_head',array($this,'captureHeadLate'),999);
		add_action('shutdown',array($this,'captureShutdown'),999);
	}
	public function status():array{$until=$this->armedUntil();return array('contract'=>'etg.dfsb.live-runtime-probe-status.v1','armed'=>$until>time(),'armed_until_gmt'=>$until?gmdate('c',$until):'','seconds_remaining'=>$until>time()?$until-time():0,'sample_count'=>count($this->samples()),'authorizing'=>false);}
	public function samples():array{$value=function_exists('get_transient')?get_transient(self::SAMPLES_KEY):false;return is_array($value)?$value:array();}
	public function armAction():void{$this->requireAdmin('etg_dfsb_arm_live_probe');$minutes=isset($_POST['minutes'])?max(1,min(15,(int)$_POST['minutes'])):10;$ttl=$minutes*60;if(function_exists('set_transient')){set_transient(self::ARM_KEY,time()+$ttl,$ttl);} $this->redirect('probe_armed');}
	public function clearAction():void{$this->requireAdmin('etg_dfsb_clear_live_probe');if(function_exists('delete_transient')){delete_transient(self::SAMPLES_KEY);delete_transient(self::ARM_KEY);} $this->redirect('probe_cleared');}
	public function exportAction():void{$this->requireAdmin('etg_dfsb_export_live_probe');$payload=array('contract'=>'etg.dfsb.live-runtime-probe-export.v1','plugin_version'=>defined('ETG_DFSB_VERSION')?(string)ETG_DFSB_VERSION:'','generated_at_gmt'=>gmdate('c'),'authorizing'=>false,'global_enabled'=>$this->config->enabled(),'configuration_revision'=>$this->config->revision(),'samples'=>$this->samples());if(function_exists('nocache_headers')){nocache_headers();}header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename="etg-dfsb-live-runtime-probe.json"');echo wp_json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
	public function captureWpEarly():void{$this->capture('wp:1');} public function captureWpLate():void{$this->capture('wp:999');} public function captureTemplateRedirect():void{$this->capture('template_redirect:999');} public function captureHeadEarly():void{$this->capture('wp_head:1');} public function captureHeadLate():void{$this->capture('wp_head:999');} public function captureShutdown():void{$this->capture('shutdown:999');}
	public function startHtmlProbe():void{if(!$this->shouldProbe()||$this->bufferStarted||headers_sent()){return;}$context=$this->builder->buildEvidence();if(empty($context['active'])){return;}$this->bufferStarted=true;ob_start(array($this,'captureHtml'));}
	public function captureHtml(string $html):string{if(!$this->isArmed()){return $html;}$markers=array('etg_term_section'=>false!==strpos($html,'etg-filter-term-section'),'etg_sections'=>false!==strpos($html,'etg-filter-seo-section'),'etg_gallery'=>false!==strpos($html,'etg-filter-seo-gallery'),'html_h1'=>(bool)preg_match('/<h1\b[^>]*>.*?<\/h1>/isu',$html));$robots=$this->firstMeta($html,'robots');$canonical='';if(preg_match('/<link\b[^>]*rel=["\']canonical["\'][^>]*href=["\']([^"\']+)["\']/iu',$html,$m)||preg_match('/<link\b[^>]*href=["\']([^"\']+)["\'][^>]*rel=["\']canonical["\']/iu',$html,$m)){$canonical=(string)$m[1];}$record=array('contract'=>'etg.dfsb.server-html-evidence.v1','request_id'=>$this->requestId,'stage'=>'html_source','captured_at_gmt'=>gmdate('c'),'html_bytes'=>strlen($html),'html_sha256'=>hash('sha256',$html),'evidence_ref'=>'sha256:'.hash('sha256',$html),'markers'=>$markers,'robots'=>substr($robots,0,200),'canonical'=>substr($canonical,0,1000),'authorizing'=>false);$this->store($record);return $html;}
	private function capture(string $stage):void{if(!$this->shouldProbe()){return;}$context=$this->builder->buildEvidence();if(empty($context['active'])){return;}$decision=$this->policy->decide($context);$provider=(array)($context['jet_smart_filters_provider']??array());$record=array('contract'=>'etg.dfsb.live-runtime-stage.v1','request_id'=>$this->requestId,'stage'=>$stage,'captured_at_gmt'=>gmdate('c'),'elapsed_ms'=>(int)round((microtime(true)-$this->startedAt)*1000),'request_path'=>(string)($context['request_path']??''),'language'=>(string)($context['language']??''),'profile_id'=>(string)($context['profile_id']??''),'scope_valid'=>!empty($context['scope_valid']),'runtime_ready'=>!empty($context['runtime_ready']),'provider_observed'=>!empty($context['provider_observed']),'provider'=>(string)($provider['provider']??''),'query_id'=>(string)($provider['query_id']??''),'provider_observation_matches_url'=>!empty($context['provider_observation_matches_url']),'result_count'=>$context['result_count']??null,'result_count_source'=>(string)($context['result_count_source']??''),'result_count_authoritative'=>!empty($context['result_count_authoritative']),'result_count_detail'=>(string)($context['result_count_detail']??''),'missing_terms'=>array_keys((array)($context['missing_terms']??array())),'translation_fallback'=>!empty($context['translation_fallback']),'unicode_filters'=>(array)($context['unicode_filters']??array()),'runtime_stage'=>(array)($context['runtime_stage']??array()),'decision_reason'=>(string)($decision['reason']??''),'decision_index'=>$decision['index']??null,'query_count'=>function_exists('get_num_queries')?(int)get_num_queries():null,'memory_bytes'=>memory_get_usage(true),'peak_memory_bytes'=>memory_get_peak_usage(true),'global_enabled'=>$this->config->enabled(),'authorizing'=>false);$hashInput=$record;unset($hashInput['captured_at_gmt'],$hashInput['elapsed_ms'],$hashInput['memory_bytes'],$hashInput['peak_memory_bytes'],$hashInput['query_count']);$record['sample_sha256']=hash('sha256',$this->encode($hashInput));$record['evidence_ref']='sha256:'.$record['sample_sha256'];$this->store($record);}
	private function store(array $record):void{if(!function_exists('set_transient')){return;}$samples=$this->samples();$samples[]=$record;$limit=100;if(count($samples)>$limit){$samples=array_slice($samples,-$limit);}set_transient(self::SAMPLES_KEY,$samples,DAY_IN_SECONDS);}
	private function shouldProbe():bool{if(!$this->isArmed()){return false;}if(function_exists('is_admin')&&is_admin()){return false;}if(function_exists('wp_doing_ajax')&&wp_doing_ajax()){return false;}if(function_exists('wp_doing_cron')&&wp_doing_cron()){return false;}return true;}
	private function isArmed():bool{return $this->armedUntil()>time();} private function armedUntil():int{$v=function_exists('get_transient')?get_transient(self::ARM_KEY):false;return is_numeric($v)?(int)$v:0;}
	private function firstMeta(string $html,string $name):string{$q=preg_quote($name,'/');if(preg_match('/<meta\b[^>]*name=["\']'.$q.'["\'][^>]*content=["\']([^"\']*)["\']/iu',$html,$m)||preg_match('/<meta\b[^>]*content=["\']([^"\']*)["\'][^>]*name=["\']'.$q.'["\']/iu',$html,$m)){return (string)$m[1];}return '';}
	private function encode(array $value):string{$j=function_exists('wp_json_encode')?wp_json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):json_encode($value);return is_string($j)?$j:'{}';}
	private function requireAdmin(string $nonce):void{if(!current_user_can('manage_options')){wp_die('Forbidden','Forbidden',array('response'=>403));}check_admin_referer($nonce);}
	private function redirect(string $notice):void{$url=add_query_arg(array('page'=>'etg-filter-seo-publication','tab'=>'runtime','etg_notice'=>$notice),admin_url('options-general.php'));wp_safe_redirect($url);exit;}
}
