<?php
namespace ETG\DynamicFilterSEOBridge\Diagnostics;

use ETG\DynamicFilterSEOBridge\Config\Configuration;
use ETG\DynamicFilterSEOBridge\Config\ProfileRegistry;
use ETG\DynamicFilterSEOBridge\Runtime\Readiness;
use ETG\DynamicFilterSEOBridge\Runtime\ReleaseIdentity;
use ETG\DynamicFilterSEOBridge\SEO\PublicationRegistry;

final class PublicationEvidenceBundle {
	private $config;private $profiles;private $readiness;private $inventory;private $publication;private $release;private $probe;
	public function __construct(Configuration $config,ProfileRegistry $profiles,Readiness $readiness,RuntimeInventory $inventory,PublicationRegistry $publication,ReleaseIdentity $release=null,LiveRuntimeProbe $probe=null){$this->config=$config;$this->profiles=$profiles;$this->readiness=$readiness;$this->inventory=$inventory;$this->publication=$publication;$this->release=$release;$this->probe=$probe;}
	public function collect(int $previewLimit=50):array{
		$previewLimit=max(1,min(100,$previewLimit));$inventory=$this->inventory->collect();$readiness=$this->readiness->report();$summary=$this->publication->publicationSummary($previewLimit);$profileEvidence=array();$activationBlockers=array();
		if($this->config->enabled()){$activationBlockers[]='global_bridge_on_during_dark_validation_evidence';}
		if((string)($inventory['contract']??'')!==RuntimeInventory::CONTRACT||empty($inventory['evidence_complete'])){$activationBlockers[]='runtime_inventory_incomplete';}
		if(!empty($readiness['missing_dependencies'])){$activationBlockers[]='missing_dependencies';}if(!empty($readiness['missing_capabilities'])){$activationBlockers[]='missing_capabilities';}if(!empty($readiness['configuration_errors'])&&$this->config->enabled()){$activationBlockers[]='configuration_errors';}if(!empty($readiness['failed_runtime_checks'])){$activationBlockers[]='failed_runtime_checks';}
		$enabledProfiles=0;foreach($this->profiles->all() as $profileId=>$profile){$publication=(array)($profile['publication']??array());$blockers=array();if(empty($profile['enabled'])){$blockers[]='profile_disabled';}else{$enabledProfiles++;}if(!empty($profile['require_provider_observation_for_index'])){if(empty($publication['provider_observation_evidence_current'])){$blockers[]='provider_observation_not_verified_or_stale';}if(empty($publication['provider_observation_evidence_id'])){$blockers[]='provider_observation_evidence_missing';}}if(!empty($publication['require_elementor_content'])){if(empty($publication['elementor_evidence_current'])){$blockers[]='elementor_content_not_verified_or_stale';}if(empty($publication['elementor_verification_evidence_id'])){$blockers[]='elementor_verification_evidence_missing';}}if(!empty($publication['require_result_count_parity_for_publication'])){if(empty($publication['result_count_parity_evidence_current'])){$blockers[]='result_count_parity_not_verified_or_stale';}if(empty($publication['result_count_parity_evidence_id'])){$blockers[]='result_count_parity_evidence_missing';}}if(empty($profile['indexable_combinations'])){$blockers[]='approved_combinations_empty';}if(empty($profile['routes'])){$blockers[]='exact_route_missing';}if(empty($profile['allowed_taxonomy_sets'])){$blockers[]='allowed_taxonomy_sets_empty';}$profileEvidence[(string)$profileId]=array('enabled'=>!empty($profile['enabled']),'authority_fingerprint'=>(string)($profile['authority_fingerprint']??''),'route_count'=>count((array)($profile['routes']??array())),'approved_combination_count'=>count((array)($profile['indexable_combinations']??array())),'provider_observation_verified'=>!empty($publication['provider_observation_evidence_current']),'provider_observation_evidence_id'=>(string)($publication['provider_observation_evidence_id']??''),'elementor_content_verified'=>!empty($publication['elementor_evidence_current']),'elementor_verification_evidence_id'=>(string)($publication['elementor_verification_evidence_id']??''),'result_count_parity_verified'=>!empty($publication['result_count_parity_evidence_current']),'result_count_parity_evidence_id'=>(string)($publication['result_count_parity_evidence_id']??''),'max_preview_urls'=>(int)($publication['max_preview_urls']??25),'max_publication_urls'=>(int)($publication['max_publication_urls']??10),'blockers'=>array_values(array_unique($blockers)));}
		if(0===$enabledProfiles){$activationBlockers[]='no_enabled_profiles_for_activation';}foreach($profileEvidence as $row){if(!empty($row['enabled'])){foreach((array)$row['blockers'] as $blocker){$activationBlockers[]='profile_blocker:'.$blocker;}}}
		$probe=$this->probeSummary();$release=$this->release?$this->release->report():array();if($this->release&&empty($release['build_identity_available'])){$activationBlockers[]='runtime_release_identity_unavailable';}
		return array('contract'=>'etg.dfsb.publication-evidence-bundle.v2','plugin_version'=>defined('ETG_DFSB_VERSION')?(string)ETG_DFSB_VERSION:'','generated_at_gmt'=>gmdate('c'),'authorizing'=>false,'read_only'=>true,'profile_mutation'=>false,'merge_authorized'=>false,'production_activation_authorized'=>false,'global_enabled'=>$this->config->enabled(),'configuration_revision'=>$this->config->revision(),'evidence_complete'=>empty($activationBlockers),'activation_blockers'=>array_values(array_unique($activationBlockers)),'required_external_evidence'=>array('server_side_elementor_html_snapshot_sha256','frontend_vs_request_adapter_vs_background_count_parity_sha256','multilingual_hreflang_and_translated_slug_validation_sha256','global_off_empty_live_sitemap_validation','bounded_global_on_sitemap_validation','sitemap_ttfb_query_count_and_memory_baseline'),'live_runtime_probe'=>$probe,'release_identity'=>$release,'profile_evidence'=>$profileEvidence,'readiness'=>$readiness,'runtime_inventory'=>$inventory,'publication_preview'=>$summary);
	}
	private function probeSummary():array{if(!$this->probe){return array('available'=>false);}$samples=$this->probe->samples();$provider=false;$count=false;$html=false;$unicode=false;$refs=array();foreach($samples as $row){if(!empty($row['provider_observed'])&&!empty($row['provider_observation_matches_url'])){$provider=true;}if(!empty($row['result_count_authoritative'])){$count=true;}if('html_source'===(string)($row['stage']??'')&&(!empty($row['markers']['etg_term_section'])||!empty($row['markers']['etg_sections']))){$html=true;}if(!empty($row['unicode_filters'])&&empty($row['translation_fallback'])&&empty($row['missing_terms'])){$unicode=true;}if(!empty($row['evidence_ref'])){$refs[]=(string)$row['evidence_ref'];}}return array('available'=>true,'status'=>$this->probe->status(),'provider_observed_on_real_request'=>$provider,'authoritative_request_count_observed'=>$count,'server_rendered_etg_html_observed'=>$html,'unicode_translated_filter_observed_without_fallback'=>$unicode,'recent_evidence_refs'=>array_slice(array_values(array_unique($refs)),-20));}
}
