<?php
if ( ! defined( 'ABSPATH' ) ) {
    if ( function_exists( 'http_response_code' ) ) { http_response_code( 404 ); }
    exit;
}
/** Generated by competitive-evidence.py. Direct web execution returns HTTP 404 with no history. */
$payload = <<<'MAD4B_JSON'
{"acknowledgements":[],"alerts":[],"authorizing":false,"contract":"mad4b.competitive-evidence-history.v2","current_entry_sha256":"c64ae544b9e2dc0179f12ce68e5a8623bc100791592710232f39f0a94d5816a7","current_generation_sha256":"28fcd294965d402623daeb0ec8449df846525ce4a7eb5672d238b9c3a656467f","entries":[{"authorizing":false,"drift_flags":{"matrix":false,"packages":false,"source":false,"task":false},"entry_sha256":"c64ae544b9e2dc0179f12ce68e5a8623bc100791592710232f39f0a94d5816a7","generation_sha256":"28fcd294965d402623daeb0ec8449df846525ce4a7eb5672d238b9c3a656467f","matrix_source_sha":"32e32a94ddb1b7864f8924ad22cb0b03199856be","package_fingerprints":{"ai-engine":"ff14536aca8688ddf4631a87e1d33b9fdae983feab0b7c05f2d0cb524aa44ac0","easy-mcp-ai":"0cf4ab2d7d3e6de0d297ad59df68bdd60722de50e36bc8d792b9a585399be0bb","miniorange-secure-mcp-server":"baf0349514e92b59a57ee88bd5b3fd7095a6a5eec4de91a217f01cd6fee0e838","royal-mcp":"ccb8528552f804849726307fe6de1e28bada0404322f79ea5bfcb41edd3b8b70"},"previous_entry_sha256":"","previous_generation_sha256":"","revision":1,"source_generation":"fa615ba998fade31d180d10cb4d30472b38b7d8237349d8c3c21002e6e0128ba","state":"known_good","summary_sha256":"434604177eb02fbb6f7a590ecb1bc9d92a00ca767ce4d313fc195c70c3e79bc1","task_generation":"0042404f776e5299a386b5aa005dcff3f33568e6f42cb5f4757a8bf5b2501d94"}],"previous_known_good_generation_sha256":"","retention":{"max_entries":64,"policy":"append_only_fail_closed","silent_pruning":false}}
MAD4B_JSON;
return json_decode( $payload, true );
