<?php
if ( ! defined( 'ABSPATH' ) ) {
    if ( function_exists( 'http_response_code' ) ) { http_response_code( 404 ); }
    exit;
}
/** Generated by competitive-evidence.py. Direct web execution returns HTTP 404 with no history. */
$payload = <<<'MAD4B_JSON'
{"acknowledgements":[],"alerts":[],"authorizing":false,"contract":"mad4b.competitive-evidence-history.v2","current_entry_sha256":"6d0c13867616e659a6530556ad0de7b2d9936e13a2bb27c362778dea280790a6","current_generation_sha256":"385762c5d046ce9b47a72ebc53c5b626d546756486fd0ce193f94266a9e968d3","entries":[{"authorizing":false,"drift_flags":{"matrix":false,"packages":false,"source":false,"task":false},"entry_sha256":"6d0c13867616e659a6530556ad0de7b2d9936e13a2bb27c362778dea280790a6","generation_sha256":"385762c5d046ce9b47a72ebc53c5b626d546756486fd0ce193f94266a9e968d3","matrix_source_sha":"32e32a94ddb1b7864f8924ad22cb0b03199856be","package_fingerprints":{"ai-engine":"ff14536aca8688ddf4631a87e1d33b9fdae983feab0b7c05f2d0cb524aa44ac0","easy-mcp-ai":"0cf4ab2d7d3e6de0d297ad59df68bdd60722de50e36bc8d792b9a585399be0bb","miniorange-secure-mcp-server":"baf0349514e92b59a57ee88bd5b3fd7095a6a5eec4de91a217f01cd6fee0e838","royal-mcp":"ccb8528552f804849726307fe6de1e28bada0404322f79ea5bfcb41edd3b8b70"},"previous_entry_sha256":"","previous_generation_sha256":"","revision":1,"source_generation":"fa615ba998fade31d180d10cb4d30472b38b7d8237349d8c3c21002e6e0128ba","state":"known_good","summary_sha256":"702168233e50421fb27913c1b40e8c885013cab047a086b145f225efaa91bdd7","task_generation":"c13c54fb60dab82a470f685b2a0b95e1bf89494c3b5b7efae0fdc954f217438e"}],"previous_known_good_generation_sha256":"","retention":{"max_entries":64,"policy":"append_only_fail_closed","silent_pruning":false}}
MAD4B_JSON;
return json_decode( $payload, true );
