<?php
declare(strict_types=1);

function etg_expect($condition,$message){if(!$condition){fwrite(STDERR,"FAIL: $message\n");exit(1);}}
function etg_has($needle,$haystack,$message){etg_expect(false!==strpos($haystack,$needle),$message);}

$root=dirname(__DIR__);
$js=file_get_contents($root.'/assets/js/ajax-filter-state.js');$parser=file_get_contents($root.'/includes/JetSmartFilters/AjaxFilterStateParser.php');$live=file_get_contents($root.'/includes/Elementor/DynamicTags/LiveBindingTrait.php');$preview=file_get_contents($root.'/includes/Elementor/DynamicTags/PreviewContextTrait.php');$filter=file_get_contents($root.'/includes/Elementor/DynamicTags/FilterValueTag.php');$slot=file_get_contents($root.'/includes/Elementor/DynamicTags/ContentSlotTag.php');$inventory=file_get_contents($root.'/includes/Elementor/DynamicTags/InventoryValueTag.php');$term=file_get_contents($root.'/includes/Elementor/DynamicTags/TermFieldTag.php');$section=file_get_contents($root.'/includes/Elementor/DynamicTags/TermSectionTag.php');$shortcodes=file_get_contents($root.'/includes/Elementor/Shortcodes.php');$catalog=file_get_contents($root.'/includes/Presentation/InventoryContentCatalog.php');$builder=file_get_contents($root.'/includes/Context/FilterContextBuilder.php');$resolver=file_get_contents($root.'/includes/Presentation/PresentationResolver.php');$endpoint=file_get_contents($root.'/includes/Presentation/AjaxPresentationEndpoint.php');$sourceResolver=file_get_contents($root.'/includes/Presentation/ContentSourceResolver.php');$listingResolver=file_get_contents($root.'/includes/JetEngine/ListingContextResolver.php');$queryRunner=file_get_contents($root.'/includes/JetEngine/QueryRunner.php');$relationResolver=file_get_contents($root.'/includes/JetEngine/RelationResolver.php');$listingIntegration=file_get_contents($root.'/includes/JetEngine/ListingIntegration.php');$fieldKey=file_get_contents($root.'/includes/Identifiers/FieldKey.php');$presentationToken=file_get_contents($root.'/includes/Identifiers/PresentationToken.php');$fieldDiscovery=file_get_contents($root.'/includes/JetEngine/FieldDiscovery.php');
$endpointCompact=preg_replace('/\s+/','',$endpoint);$shortcodesCompact=preg_replace('/\s+/','',$shortcodes);

foreach(array('autoGroupKey','autoGroupResolution','activeGroupKeys','pathDeclaredGroupKey','prettyPathState','effectiveCurrentQuery','baseArchivePath','request_path','archive_path','data-etg-dfsb-fallback','ambiguous_auto_group','url_group_unavailable','pretty_url_group','eventSeenKeys','transport_error')as$needle){etg_has($needle,$js,'browser hardening: '.$needle);}etg_expect(false===strpos($js,'history.pushState')&&false===strpos($js,'history.replaceState'),'browser bridge cannot mutate history');etg_has("query['_tax_query_' + taxonomy] = value",$js,'pretty JSF URL can seed bounded initial tax state');etg_has("eventSeenKeys[key] = true",$js,'post-event currentQuery wins over stale pretty URL evidence');etg_expect(strpos($js,"if (pathState.group)")<strpos($js,'var active = activeGroupKeys()'),'pretty URL group is resolved before active/single-group fallbacks');
etg_has("strpos( \$path, '/jsf/' )",$parser,'parser strips JetSmartFilters pretty path suffix');etg_has("'request_path' => \$requestPath",$parser,'parser preserves request path evidence');etg_has("'archive_path' => \$archivePath",$parser,'parser exposes base archive scope');etg_has('AJAX Live Update',$live,'Elementor live toggle');etg_has('AJAX Group',$live,'Elementor provider/query group control');etg_has('URL group → active group → single group',$live,'Elementor Auto control documents deterministic group resolution');etg_has('data-etg-dfsb-group',$live,'live group attribute');etg_has('data-etg-dfsb-fallback',$live,'fallback transport attribute');etg_has('placeholder only and is not a saved value',$preview,'editor preview makes placeholder semantics explicit');etg_has('Live parity:',$preview,'Elementor editor exposes live parity warning');etg_has('Editor preview is synthetic',$preview,'Elementor warning distinguishes synthetic preview from live evidence');
etg_has("null === \$uri ? 'live_request' : 'synthetic_uri'",$builder,'server evidence distinguishes live request from synthetic editor URI');etg_has("'live_ajax'",$builder,'AJAX evidence is explicitly live');etg_has("'dark_presentation_allowed'=>\$darkPresentationAllowed",$builder,'context exports derived dark presentation decision');etg_has("'safe_live_evidence'",$builder,'safe live dark rendering has explicit decision source');etg_has("empty(\$profile['enabled'])",$builder,'automatic dark rendering requires the matched profile to remain disabled');etg_has("empty(\$scope['global_enabled'])",$builder,'automatic dark rendering requires Global bridge OFF');etg_has("!empty(\$publication['require_elementor_content'])",$builder,'automatic dark rendering is restricted to profiles that govern Elementor content');etg_has("empty(\$e['dark_presentation_allowed'])",$resolver,'live resolver consumes derived dark presentation policy');etg_has("empty(\$context['dark_presentation_allowed'])",$endpointCompact,'AJAX endpoint consumes same derived dark presentation policy');etg_has("'dark_presentation_source'",$endpoint,'AJAX diagnostics expose dark presentation policy source');
etg_has('etgValueOrFallback',$filter,'base text tags preserve Elementor fallback');foreach(array($slot,$inventory,$term,$section)as$source){etg_has('use LiveBindingTrait',$source,'dynamic content tag uses live binding trait');}etg_has("\$group='auto'",$shortcodesCompact,'empty shortcode group becomes fail-closed Auto');etg_has("'groups'=>\$groups",$catalog,'catalog exposes governed provider/query groups');etg_has("'authorizing'=>false",$catalog,'group catalog remains non-authorizing');foreach(array($live,$preview,$filter,$slot,$inventory,$term,$section,$catalog,$builder,$resolver,$endpoint,$sourceResolver,$listingResolver,$queryRunner,$relationResolver,$listingIntegration,$fieldDiscovery)as$source){etg_expect(false===strpos($source,'update_option('),'front-end hardening cannot write options');}

foreach(array("'listing_field'","'listing_meta'","'repeater'","'query'","'relation'","'relation_meta'",'MAX_SOURCES=24','mediaIds','rows','diagnose')as$needle){etg_has($needle,$sourceResolver,'advanced content source contract: '.$needle);}etg_has('FieldKey::normalize',$sourceResolver,'source meta identity is case-preserving');etg_has('MAX_LENGTH = 120',$fieldKey,'field identity has bounded contract');etg_has('termmeta:',$presentationToken,'presentation token supports exact term-meta suffix');etg_has('PresentationToken::normalize',$resolver,'presentation resolver uses canonical case-safe token identity');etg_has('PresentationToken::normalize',$endpoint,'AJAX endpoint preserves canonical case-safe token identity');etg_has('case_sensitive_field_tokens',$catalog,'catalog declares case-sensitive field tokens');
etg_has('get_current_object',$listingResolver,'JetEngine current listing object supported');etg_has('FieldKey::normalize',$listingResolver,'JetEngine listing meta preserves exact case');etg_has('get_query_by_id',$queryRunner,'Query Builder execution helper supported');etg_has('$this->active[$queryId]',$queryRunner,'Query Builder recursion guard supported');etg_has('get_parents',$relationResolver,'Relation parents supported');etg_has('get_children',$relationResolver,'Relation children supported');etg_has('metaValues',$relationResolver,'Relation edge meta supported');etg_has("'cct::'",$relationResolver,'CCT relation hydration supported');etg_has('jet-engine/listings/dynamic-repeater/pre-get-saved',$listingIntegration,'Dynamic Repeater bridge registered');etg_has('etg_content_slot',$listingIntegration,'JetEngine scalar slot macro registered');etg_has('etg_slot_rows',$listingIntegration,'JetEngine rows macro registered');etg_has('etg_filter_term_ids',$listingIntegration,'multi-value term IDs macro registered');etg_has('etg_filter_term_slugs',$listingIntegration,'multi-value term slugs macro registered');etg_has('etg_filter_term_meta_values',$listingIntegration,'multi-value term meta macro registered');etg_has('etg-filter-context',$listingIntegration,'JetEngine Filter Context registered');etg_has('activeSlots',$resolver,'content slot recursion guard enabled');etg_has('slotImage',$resolver,'native content-slot image resolution available');etg_has('slotGallery',$resolver,'native content-slot gallery resolution available');etg_has('get_fields_for_select',$fieldDiscovery,'JetEngine Meta Box field discovery supported');etg_has('get_content_types',$fieldDiscovery,'JetEngine CCT field discovery supported');

foreach(array('alpha13-jetengine-content-sources-smoke.php','alpha13-jetengine-deep-source-smoke.php','alpha13-presentation-token-case-smoke.php')as$child){$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg($root.'/tests/'.$child);passthru($cmd,$code);etg_expect(0===$code,$child.' passes');}
echo "Alpha13 front-end runtime hardening smoke tests passed.\n";
