<?php
declare(strict_types=1);
function sanitize_key($v){return preg_replace('/[^a-z0-9_\-]/','',strtolower((string)$v));}
function sanitize_text_field($v){return trim(strip_tags((string)$v));}
function absint($v){return abs((int)$v);}function wp_strip_all_tags($v){return strip_tags((string)$v);}function wp_kses_post($v){return(string)$v;}function esc_url_raw($v){return(string)$v;}function _n($s,$p,$n,$d=null){return 1===$n?$s:$p;}function apply_filters($tag,$value){return$value;}function home_url($p=''){return'https://example.test'.('/'===substr((string)$p,0,1)?$p:'/'.$p);}function wp_get_attachment_image_url($id,$size){return'https://example.test/media/'.(int)$id.'.jpg';}
$GLOBALS['etg_options']=array();function get_option($k,$d=array()){return$GLOBALS['etg_options'][$k]??$d;}function update_option($k,$v,$a=false){$GLOBALS['etg_options'][$k]=$v;return true;}
$GLOBALS['term_meta_case']=array(10=>array('HeroImage'=>'UPPER','heroimage'=>'lower'));function get_term_meta($id,$key,$single=true){return$GLOBALS['term_meta_case'][(int)$id][$key]??'';}
function expect_same($e,$a,$m){if($e!==$a){fwrite(STDERR,"FAIL: $m\nEXPECTED ".var_export($e,true)."\nACTUAL ".var_export($a,true)."\n");exit(1);}}
$root=dirname(__DIR__);require_once$root.'/includes/Identifiers/FieldKey.php';require_once$root.'/includes/Identifiers/PresentationToken.php';require_once$root.'/includes/Identifiers/QueryId.php';require_once$root.'/includes/Content/GalleryComposer.php';require_once$root.'/includes/Content/ContentComposer.php';require_once$root.'/includes/Presentation/ContentSlotRegistry.php';require_once$root.'/includes/Presentation/PresentationResolver.php';
use ETG\DynamicFilterSEOBridge\Identifiers\PresentationToken;use ETG\DynamicFilterSEOBridge\Content\GalleryComposer;use ETG\DynamicFilterSEOBridge\Content\ContentComposer;use ETG\DynamicFilterSEOBridge\Presentation\ContentSlotRegistry;use ETG\DynamicFilterSEOBridge\Presentation\PresentationResolver;
expect_same('termmeta:location:HeroImage',PresentationToken::normalize('TERMMETA:Location:HeroImage'),'term-meta suffix preserves exact case');expect_same('termmeta:location:heroimage',PresentationToken::normalize('termmeta:location:heroimage'),'case-only meta token remains distinct');
$context=array('active'=>true,'in_scope'=>true,'scope_valid'=>true,'runtime_ready'=>true,'filters'=>array('location_jet'=>'cairo'),'provider_observation_matches_url'=>true,'terms'=>array('location'=>array('term_id'=>10,'name'=>'Cairo','slug'=>'cairo')),'term_sets'=>array('location'=>array(array('term_id'=>10,'name'=>'Cairo','slug'=>'cairo'),array('term_id'=>11,'name'=>'Giza','slug'=>'giza'))),'profile'=>array('require_post_type_binding'=>false),'post_type_binding'=>array(),'unknown_filters'=>array(),'malformed'=>false,'missing_terms'=>array(),'translation_fallback'=>false);
$gallery=new GalleryComposer();$content=new ContentComposer($gallery);$slots=new ContentSlotRegistry();$resolver=new PresentationResolver(function()use($context){return$context;},$content,$gallery,$slots);
expect_same('UPPER',$resolver->value('termmeta:location:HeroImage',$context),'resolver reads exact-case term meta token');expect_same('lower',$resolver->value('termmeta:location:heroimage',$context),'resolver keeps case-only meta token distinct');expect_same('10, 11',$resolver->value('terms:location:ids',$context),'multi-term IDs token available');
echo "Alpha13 presentation token case contracts passed.\n";
