<?php
declare(strict_types=1);
function sanitize_key($key){return preg_replace('/[^a-z0-9_\-]/','',strtolower((string)$key));}
function expect_same($expected,$actual,string $message):void{if($expected!==$actual){fwrite(STDERR,"FAILED: {$message}\nExpected: ".var_export($expected,true)."\nActual: ".var_export($actual,true)."\n");exit(1);}}
function expect_true($actual,string $message):void{expect_same(true,(bool)$actual,$message);}
$base=dirname(__DIR__);require_once $base.'/includes/JetEngine/QueryIdentityResolver.php';
use ETG\DynamicFilterSEOBridge\JetEngine\QueryIdentityResolver;
$make=static function($id,$custom){$q=new stdClass();$q->id=$id;$q->query_id=$custom;return$q;};
$unique=new QueryIdentityResolver(static function()use($make){return array($make(42,'tours_archive'));});$result=$unique->resolve('tours_archive');expect_same(true,$result['resolved'],'unique custom Query ID resolves');expect_same('tours_archive',$result['custom_query_id'],'custom identity is preserved');expect_same('42',$result['internal_query_id'],'resolved internal ID is evidence only');expect_same(1,$result['match_count'],'unique mapping has one match');
$missing=new QueryIdentityResolver(static function()use($make){return array($make(42,'other'));});$result=$missing->resolve('tours_archive');expect_same(false,$result['resolved'],'missing custom Query ID fails closed');expect_same('query_identity_not_found',$result['reason'],'missing mapping reason is explicit');
$duplicate=new QueryIdentityResolver(static function()use($make){return array($make(1,'dup'),$make(70,'dup'));});$result=$duplicate->resolve('dup');expect_same(false,$result['resolved'],'duplicate custom Query ID fails closed');expect_same('query_identity_ambiguous',$result['reason'],'duplicate mapping reason is explicit');expect_same(2,$result['match_count'],'ambiguity reports all exact custom-ID matches');
$numeric=new QueryIdentityResolver(static function()use($make){return array($make(123,'other'),$make(999,'123'));});$result=$numeric->resolve('123');expect_same(true,$result['resolved'],'numeric-looking custom Query ID resolves only by custom namespace');expect_same('999',$result['internal_query_id'],'numeric-looking custom ID never falls back to internal ID');
$invalid=new QueryIdentityResolver(static function(){return'not-an-inventory';});$result=$invalid->resolve('x');expect_same(false,$result['resolved'],'invalid inventory fails closed');expect_same('query_identity_inventory_unavailable',$result['reason'],'invalid inventory reason is explicit');
foreach(array('Runtime/PostTypeObserver.php','SEO/JetEngineResultCountAdapter.php','SEO/PublicationResultCountProbe.php') as $relative){$source=file_get_contents($base.'/includes/'.$relative);expect_same(false,false!==strpos($source,'get_query_by_id'),'custom route identity consumer must not use get_query_by_id: '.$relative);expect_true(false!==strpos($source,'RuntimeQueryBindingResolver'),'Alpha11 consumer must resolve provider namespace through shared runtime binding resolver: '.$relative);expect_true(false!==strpos($source,'QueryIdentityResolver'),'Alpha10 exact custom-ID resolver remains the compatibility authority under the binding layer: '.$relative);}
$binding=file_get_contents($base.'/includes/Runtime/RuntimeQueryBindingResolver.php');expect_true(false!==strpos($binding,'QueryIdentityResolver'),'runtime binding delegates stable Query Builder identity to Alpha10 resolver');expect_true(false!==strpos($binding,'provider_query_id_equals_query_builder_custom_id'),'direct Alpha10 identity behavior remains supported');expect_true(false!==strpos($binding,'elementor_runtime_topology'),'Alpha11 topology can resolve a distinct provider namespace');
$bootstrap=file_get_contents($base.'/includes/Bootstrap.php');expect_true(false!==strpos($bootstrap,'$queryIdentityResolver=new QueryIdentityResolver()'),'Bootstrap creates one shared QueryIdentityResolver');expect_true(false!==strpos($bootstrap,'$queryBindingResolver=new RuntimeQueryBindingResolver($topology,$queryIdentityResolver)'),'Bootstrap layers one shared runtime binding resolver over Alpha10 identity authority');expect_true(false!==strpos($bootstrap,'new JetEngineResultCountAdapter($queryBindingResolver)'),'request-time result count receives shared binding resolver');expect_true(false!==strpos($bootstrap,'new PostTypeObserver($queryBindingResolver)'),'Post Type observer receives shared binding resolver');expect_true(false!==strpos($bootstrap,'new PublicationResultCountProbe($queryBindingResolver)'),'publication probe receives shared binding resolver');
fwrite(STDOUT,"Alpha10 Query Builder custom-ID guarantees retained under Alpha11 topology.\n");
