<?php
declare(strict_types=1);
function sanitize_key($key){return preg_replace('/[^a-z0-9_\-]/','',strtolower((string)$key));}
function esc_html($v){return (string)$v;} function esc_attr($v){return (string)$v;} function wp_strip_all_tags($v){return strip_tags((string)$v);} function wp_kses_post($v){return (string)$v;} function wpautop($v){return (string)$v;} function get_bloginfo($k){return 'Site';} function apply_filters($hook,$value){return $value;} function shortcode_atts($pairs,$atts,$shortcode=''){return array_merge($pairs,$atts);} function wp_get_attachment_image_url($id,$size){return 'https://example.com/'.$id.'.jpg';}
function expect_same($expected,$actual,string $message):void{if($expected!==$actual){fwrite(STDERR,"FAILED: {$message}\nExpected: ".var_export($expected,true)."\nActual: ".var_export($actual,true)."\n");exit(1);}}
$base=dirname(__DIR__);foreach(array('Content/GalleryComposer.php','Content/ContentComposer.php','SEO/IndexingPolicy.php','Config/Configuration.php','SEO/CanonicalBuilder.php','RankMath/MetadataAdapter.php','Elementor/Shortcodes.php') as $f){require_once $base.'/includes/'.$f;}
use ETG\DynamicFilterSEOBridge\Content\GalleryComposer;use ETG\DynamicFilterSEOBridge\Content\ContentComposer;use ETG\DynamicFilterSEOBridge\Config\Configuration;use ETG\DynamicFilterSEOBridge\SEO\IndexingPolicy;use ETG\DynamicFilterSEOBridge\SEO\CanonicalBuilder;use ETG\DynamicFilterSEOBridge\RankMath\MetadataAdapter;use ETG\DynamicFilterSEOBridge\Elementor\Shortcodes;
$gallery=new GalleryComposer();$content=new ContentComposer($gallery);$config=new Configuration();$policy=new IndexingPolicy($config);$canonical=new CanonicalBuilder($config);
$context=array('active'=>true,'in_scope'=>true,'scope_valid'=>true,'runtime_ready'=>true,'filters'=>array('property_city'=>'cairo','property_type'=>'apartment'),'unknown_filters'=>array(),'malformed'=>array(),'missing_terms'=>array(),'translation_fallback'=>false,'provider_observed'=>true,'provider_observation_matches_url'=>true,'profile'=>array('id'=>'properties','require_post_type_binding'=>true,'require_provider_observation_for_index'=>true,'taxonomy_rules'=>array('property_type'=>array('role'=>'type','priority'=>20),'property_city'=>array('role'=>'city','priority'=>10))),'post_type_binding'=>array('observed'=>true,'matches_profile'=>true),'terms'=>array('city'=>array('name'=>'Cairo','short_description'=>'City copy'),'type'=>array('name'=>'Apartment','short_description'=>'Type copy')),'language'=>'en');
$provider=function()use(&$context){return $context;};$metadata=new MetadataAdapter($provider,$content,$gallery,$policy,$canonical);$shortcodes=new Shortcodes($provider,$content,$gallery);
expect_same('Cairo — Apartment | Site',$metadata->title('vendor-title'),'generic metadata follows profile role priority');expect_same('Cairo &rsaquo; Apartment',$shortcodes->breadcrumb(),'generic breadcrumb follows profile role priority');$context['provider_observed']=false;$context['provider_observation_matches_url']=false;expect_same('vendor-title',$metadata->title('vendor-title'),'unobserved provider cannot mutate live metadata');$context['provider_observed']=true;$context['provider_observation_matches_url']=true;$context['post_type_binding']['matches_profile']=false;expect_same('vendor-title',$metadata->title('vendor-title'),'post type mismatch blocks metadata mutation');expect_same('',$shortcodes->h1(),'post type mismatch blocks shortcode presentation');$context['post_type_binding']['matches_profile']=true;$context['provider_observation_matches_url']=false;expect_same('vendor-title',$metadata->title('vendor-title'),'provider/query observation mismatch blocks metadata mutation');expect_same('',$shortcodes->breadcrumb(),'provider/query observation mismatch blocks breadcrumb presentation');$context['provider_observation_matches_url']=true;$context['translation_fallback']=true;expect_same('vendor-title',$metadata->title('vendor-title'),'translation fallback blocks metadata mutation');fwrite(STDOUT,"Presentation identity guard smoke tests passed.\n");
